### ISSUE TITLE
caed segfaults with MPG2 storage and JACK

### ISSUE THREAD

**Issue by hgshoggins** [ElvishArtisan/rivendell#112]
- have Rivendell wired with JACK as Card 0
- have a CART with a CUT stored in MPG2 format
- edit a CART in RDLibrary, click on "Edit Markers"
- RDLibrary freezes
- caed GDB output : 

[...]
CAE: connection 0 receiving OL 7 7 1600 
CAE: Connection 0 sending OL 7 7 1600 -!
CAE: connection 0 receiving IM 7 7 0 
CAE: Connection 0 sending IM 7 7 0 -!
CAE: connection 0 receiving LP 0 010001_001 

Program received signal SIGSEGV, Segmentation fault.
FillJackOutputStream (stream=0, this=0x7fc0643b7010) at /usr/include/x86_64-linux-gnu/bits/string3.h:85
85	  return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
(gdb) bt
#0  FillJackOutputStream (stream=0, this=0x7fc0643b7010) at /usr/include/x86_64-linux-gnu/bits/string3.h:85
#1  MainObject::FillJackOutputStream (this=0x7fc0643b7010, stream=0) at cae_jack.cpp:1458
#2  0x00000000004117c2 in MainObject::jackLoadPlayback (this=0x7fc0643b7010, card=0, wavename=..., stream=0x7ffdf9989100) at cae_jack.cpp:737
#3  0x0000000000409fe8 in MainObject::DispatchCommand (this=0x7fc0643b7010, ch=0) at cae.cpp:759
#4  0x000000000040d76b in MainObject::ParseCommand (this=0x7fc0643b7010, ch=0) at cae.cpp:628
#5  0x0000000000414acd in MainObject::qt_invoke (this=0x7fc0643b7010, _id=3, _o=0x7ffdf9989480) at moc_cae.cpp:142
#6  0x00007fc06de9eb6f in QObject::activate_signal(QConnectionList*, QUObject*) () from /usr/lib/libqt-mt.so.3
#7  0x00007fc06de9ed84 in QObject::activate_signal(int, int) () from /usr/lib/libqt-mt.so.3
#8  0x00007fc0700fe058 in RDSocket::qt_invoke (this=0x8863f0, _id=11, _o=0x7ffdf9989550) at moc_rdsocket.cpp:204
#9  0x00007fc06de9eb6f in QObject::activate_signal(QConnectionList*, QUObject*) () from /usr/lib/libqt-mt.so.3
#10 0x00007fc06de9ec47 in QObject::activate_signal(int) () from /usr/lib/libqt-mt.so.3
#11 0x00007fc06e036153 in QSocket::sn_read(bool) () from /usr/lib/libqt-mt.so.3
#12 0x00007fc06e16e3de in QSocket::qt_invoke(int, QUObject*) () from /usr/lib/libqt-mt.so.3
#13 0x00007fc06de9eb6f in QObject::activate_signal(QConnectionList*, QUObject*) () from /usr/lib/libqt-mt.so.3
#14 0x00007fc06de9ed84 in QObject::activate_signal(int, int) () from /usr/lib/libqt-mt.so.3
#15 0x00007fc06deb43bb in QSocketNotifier::event(QEvent*) () from /usr/lib/libqt-mt.so.3
#16 0x00007fc06de4d08d in QApplication::internalNotify(QObject*, QEvent*) () from /usr/lib/libqt-mt.so.3
#17 0x00007fc06de4d24e in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libqt-mt.so.3
#18 0x00007fc06de43c57 in QEventLoop::activateSocketNotifiers() () from /usr/lib/libqt-mt.so.3
#19 0x00007fc06de06dd6 in QEventLoop::processEvents(unsigned int) () from /usr/lib/libqt-mt.so.3
#20 0x00007fc06de5e7c9 in QEventLoop::enterLoop() () from /usr/lib/libqt-mt.so.3
#21 0x00007fc06de5e752 in QEventLoop::exec() () from /usr/lib/libqt-mt.so.3
#22 0x00000000004063b6 in main (argc=2, argv=<optimized out>) at cae.cpp:2304

... everything runs smoothly with WAV storage format.

**Comment by ElvishArtisan** [comment]
Unable to reproduce on CentOS7-x86_64.

What distro and version of TwoLAME are you using?  Is this a source build, or pre-packaged?

**Comment by hgshoggins** [comment]
It's a v2.12.0 source build on an Ubuntu 12.04, headless, virtual machine.
As you advised on the ML, I'll check the TwoLAME version ASAP.

**Comment by hgshoggins** [comment]
Ah ! Got it !

Does it sound right ?

Package: libtwolame-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 503
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: twolame
Version: 0.3.13-1build1
Replaces: libtwolame0-dev
Depends: libtwolame0 (= 0.3.13-1build1), libc6-dev, pkg-config
Conflicts: libtwolame0-dev

**Comment by ElvishArtisan** [comment]
Got it, thanks.  Can you also get the version of MAD being used?

**Comment by hgshoggins** [comment]
Here it is : 

Package: libmad0-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 235
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: libmad
Version: 0.15.1b-7ubuntu1
Depends: libmad0 (= 0.15.1b-7ubuntu1)

**Comment by ElvishArtisan** [comment]
'Kay. Looks normal.

What block size are you using for JACK.  In fact, what is the full JACK command line that you are using?

**Comment by hgshoggins** [comment]
The command : jackd -d dummy

**Comment by hgshoggins** [comment]
Tried with -p 2048, 4096, or 8192... It might not be the problem.
Also tried with jack1 and jack2, recompiling each time. No luck.

**Comment by ElvishArtisan** [comment]
Unable to reproduce.
