### ISSUE TITLE
Request: extend SongID field to a CHAR(36) in order to match MBrainz ID

### ISSUE THREAD

**Issue by elmuz** [ElvishArtisan/rivendell#120]
We would like to use that field to store MBID. At the moment it can host only 32 chars. By doing this we can easily request more metadata on the fly by querying MB database with the specific ID. Otherwise we would need a separate intermediate DB or we'd need to use other fields, which may be already filled.

**Comment by ElvishArtisan** [comment]
Rather than force the MBID into Song ID, I think it would be better to have a dedicated field for it.  Properly, this should be part of a full MBrainz integration.

**Comment by elmuz** [comment]
That would be awesome. For the moment we started using Cut Description to host MBID (which is our "foreign key" for other DBs). Btw what is SongID thought for?

**Comment by ElvishArtisan** [comment]
It is intentionally 'generic' --i.e. for use on a site-by-site basis.  MBIDs are ubiquitous and standardized enough that dedicating a field for them makes some sense (similar to what we already do for ISRC and ISCI).

**Comment by elmuz** [comment]
Ok, thank you.
