### ISSUE TITLE
Rivendell can't create users on MySQL v 5.7+

### ISSUE THREAD

**Issue by waynemerricks** [ElvishArtisan/rivendell#123]
MySQL has changed the format of the mysql->user table.

This is a problem for the opendb.cpp code called when rdadmin needs to create a new db from scratch.  This means that rdadmin fails with an "unable to access new database" error when it expects rduser to be available and it isn't (due to user table changes).

You can no longer do this:
`insert into user set Host=\"%s\", User=\"%s\",Password=PASSWORD(\"%s\")`

Password is now authentication_string as of MySQL v 5.7.  Instead of making users by directly manipulating the users table and creating problems with older MySQL versions, why not use the create user syntax?

`create user %s@'%s' identified by '%s'`

Similarly the grant tables although OK now can be more easily done with grant statements rather than setting the db table directly:

`grant all on %s.* to %s@'%s'`

I have a patch [here](http://thevoiceasia.com/rivendell/opendb.cpp.patch)

**Comment by ElvishArtisan** [comment]
<sigh>.  That whole OpenDB() method really needs to be thrown away and rewritten from scratch.  That said, what's the deal with MySQL breaking backward compatibility in this way?  It sounds plain Evil.

Can you formulate this as a pull request?  That way the proper attribution will be reflected in the git logs.

**Comment by waynemerricks** [comment]
Pull request added.  As an aside, I can probably knock up a rewrite of opendb to be a bit more sensible from a working with the db stand point.  I'm not great with QT/C++ but this kind of behind the scenes DB stuff seems straight forward enough.

**Comment by ElvishArtisan** [comment]
No worries, as the whole thing is about to be thrown away anyway.  I've come to the conclusion that putting all that stuff into Rivendell was really a mistake.  Provisioning and securing the DB is really a DBA responsibility, not the application's.  WordPress (for example) gets this right: it is the user's responsibility to create an (empty) database and secure it as appropriate for that user's environment.  All that WP does as part of its installation routine then is to create and populate the appropriate tables into the existing-but-empty DB.

**Comment by waynemerricks** [comment]
Fixed with merge so closing this.
