### ISSUE TITLE
Rivendell web components error 403 forbidden Apache 2.4+

### ISSUE THREAD

**Issue by waynemerricks** [ElvishArtisan/rivendell#124]
Apache has deprecated the access permissions in v 2.4 and above.

The old style:
`Order allow,deny
 Allow from all`

no longer works, you have to move to grants:

`Require all granted`

This affects rd-bin.conf that ships with Rivendell source. Patch [here](http://thevoiceasia.com/rivendell/rd-bin.conf.patch)

**Comment by ElvishArtisan** [comment]
Deprecated, or removed?  It's sounding like the later!

How well will this play on 2.2?

**Comment by waynemerricks** [comment]
Deprecated in Apache 2.3 and not quite removed in 2.4.  There is more info here:
https://httpd.apache.org/docs/current/mod/mod_access_compat.html
http://stackoverflow.com/questions/11992466/apache-permission-denied
https://httpd.apache.org/docs/2.4/howto/access.html

Basically the old module (mod_access_compat) that lets you use "allow from all" is superseded by the new one (mod_authz_host) with uses require granted. 

It was deprecated in Apache 2.3 and it seems that 2.4 now defaults to the new way of doing things.  You can faff with configs to get the old behaviour back but I guess it will be removed eventually.

Interestingly the Tryphon Rivendell repos have been using this require granted config since the Ubuntu 14.04 release (2014) but I didn't find this config change documented anywhere (I wish I had, it would have saved me some googling time).

**Comment by ElvishArtisan** [comment]
Ok.  Let's not fuss with it in 2.x then.  We will make the change as part of the transition to 3.x.
