### ISSUE TITLE
rdlibrary shows no carts with MySQL v5.7+

### ISSUE THREAD

**Issue by waynemerricks** [ElvishArtisan/rivendell#125]
Another one, rdlibrary returns no carts and errors in the console because of a new stricter group by mode enabled by default.

This needs to be run as db root before Rivendell will work:

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

This turns off the "only full group by" mode which is what causes problems.

**Comment by waynemerricks** [comment]
You could also patch opendb.cpp to set this mode when the DB is created.  Be aware this also affects rivendell if you've imported from an existing system rather than creating from scratch.

Opendb patch [available here](https://raw.githubusercontent.com/waynemerricks/rivendellubuntuxenial/master/install/rivendell/opendb.cpp.mysql-group.patch)

**Comment by ElvishArtisan** [comment]
This sounds like something that Downstream will need to deal with, as MySQL configuration is not directly within the scope of Rivendell.  We can revisit it when OpenDB() and friends get overhauled (hopefully later this summer).
