### ISSUE TITLE
Vanishing Text

### ISSUE THREAD

**Issue by TheOnlyAlPeterson** [ElvishArtisan/rivendell#127]
Running RD 2.12.0 on a networked QuadCore machine, Centos 6.7.

During a lengthy Import or Export of a long-form program in RDLIbrary: if the desktop is switched to another view, all the text and the progress bar disappears when switched back to view RDLibrary. It wont return until the Import or Export has completed.

Is this a bug, or just something that can be addressed by changing the priority of screen redraws?

**Comment by ElvishArtisan** [comment]
Fixed in v3.x.
