### ISSUE TITLE
rdairplay requires password, rdpanel segfault (instance column not removed)

### ISSUE THREAD

**Issue by waynemerricks** [ElvishArtisan/rivendell#129]
Apologies but it seems working with Ubuntu 16.04 is bringing out all the weirdness.  In the RDAIRPLAY and RDPANEL table there is an old INSTANCE column that was removed in schema v219 but if you create from scratch this doesn't happen.

When you load up RDAIRPLAY you get this error in the terminal:

invalid SQL or failed DB connection[Field 'INSTANCE' doesn't have a default value QMYSQL3: Unable to execute query]: insert into RDAIRPLAY set STATION="my_pc_name"

Nothing seems wrong until you try to quit and then you can't because you're asked for a password.

RDPANEL on the other hand crashes:
invalid SQL or failed DB connection[Field 'INSTANCE' doesn't have a default value QMYSQL3: Unable to execute query]: insert into RDPANEL set STATION="my_pc_name"
Database connection failed: insert into RDPANEL set STATION="my_pc_name"
Database conection restored
QSqlQuery::value: not positioned on a valid record
Segmentation fault (core dumped)

The problem seems to be that as part of the update DB scripts if your version is less than 219 you drop the INSTANCE columns (L7606, 7698 and 7722 in rdadmin/createdb.cpp) but as 2.13.0 is v255 and created from scratch, this never happens.

In production I've updated all the way from an early 2.x Riv, to 2.5 and more recently 2.10.3 so its not something I've noticed before.

As a work around dropping the columns works fine:
alter table RDAIRPLAY drop column INSTANCE;
alter table RDPANEL drop column INSTANCE;

But it really should be removed from the createdb.cpp file.  I'll create a pull request shortly.

**Comment by waynemerricks** [comment]
OK added to the same pull request for create user and grant fixes (it won't let me make a new one).

**Comment by ElvishArtisan** [comment]
So it appears that the version of MySQL that ships with 16.04 has implemented stricter ANSI SQL compliance.  Not a Bad Thing, but it does tend to flush out critters from odd corners!  We'll just swat 'em as they come.

**Comment by waynemerricks** [comment]
Closing as code has been merged and I've had no other reports of weirdness.
