### ISSUE TITLE
updated alsa  version breaks 2.13.0

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#131]
seems that they moved the asound.state to /var/lib/alsa/asound.state which doesn't exist...

alsamixer still works, but can't store setting...

[root@rdhost ~]# alsactl store 1
alsactl: save_state:1626: Cannot open /var/lib/alsa/asound.state for writing: No such file or directory
[root@rdhost ~]#

**Comment by waynemerricks** [comment]
Is it worth symlinking to wherever asound.state was?

**Comment by rlwoods** [comment]
Just create the /var/lib/alsa directory and you can then do a "alsactl
store" and save the config.

RW

**Comment by ElvishArtisan** [comment]
This has nothing to do with Rivendell <em>per se</em>.  We don't touch the ALSA mixer.
