### ISSUE TITLE
Port Qt3 to Qt4

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#140]
Primary focus on making compilation work, with little or no attention paid to runtime.

**Comment by ElvishArtisan** [comment]
Done in 'master'.

**Comment by Engineeringradio** [comment]
I'm getting a configure error: *** Qt toolkit not found, unable to continue *** on kubuntu 16.04. I'm wondering if the directories for QT4 are different or am I missing something?

**Comment by ElvishArtisan** [comment]
On Sep 12, 2016, at 05:15, Engineeringradio <notifications@github.com> wrote:

> I'm getting a configure error: *** Qt toolkit not found, unable to continue *** on kubuntu 16.04. I'm wondering if the directories for QT4 are different or am I missing something?

Qt3 and Qt4 are completely different animals, so it’s highly likely that they are installed in different locations on Ubuntu.  It tends to be highly distro-specific.  Try doing:

	pkg-config --flags QtCore

You should get back something like:

	-DQT_SHARED -I/usr/include/QtCore

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by Engineeringradio** [comment]
I think I've got the directories correct now but no luck.
I've had a look through the config.log and found this:

    QT_CXXFLAGS=-I/usr/include/qt4
    QT_DIR=
    QT_LIBS=-L/usr/lib/x86_64-linux-gnu -lqtcurve-utils   -lX11 -lXext -lXt 
    QT_BIN=/usr/lib/x86_64-linux-gnu/qt4/bin
    QT_UIC=/usr/lib/x86_64-linux-gnu/qt4/bin/uic
    QT_MOC=/usr/lib/x86_64-linux-gnu/qt4/bin/moc
configure:17215: checking correct functioning of Qt installation
configure:17249: /usr/lib/x86_64-linux-gnu/qt4/bin/moc bnv_qt_test.h -o moc_bnv_qt_test.cpp >/dev/null 2>/dev/null
configure:17252: $? = 0
configure:17260: g++ -I/usr/include/qt4 -c -g -O2 -o moc_bnv_qt_test.o moc_bnv_qt_test.cpp >/dev/null 2>/dev/null
configure:17263: $? = 1

configure: could not compile:
/****************************************************************************
** Meta object code from reading C++ file 'bnv_qt_test.h'
**
** Created by: The Qt Meta Object Compiler version 63 (Qt 4.8.7)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "bnv_qt_test.h"
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'bnv_qt_test.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 63
#error "This file was generated using the moc from 4.8.7. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
static const uint qt_meta_data_Test[] = {

 // content:
       6,       // revision
       0,       // classname
       0,    0, // classinfo
       2,   14, // methods
       0,    0, // properties
       0,    0, // enums/sets
       0,    0, // constructors
       0,       // flags
       1,       // signalCount

 // signals: signature, parameters, type, tag, flags
       6,    5,    5,    5, 0x05,

 // slots: signature, parameters, type, tag, flags
      13,    5,    5,    5, 0x0a,

       0        // eod
};

static const char qt_meta_stringdata_Test[] = {
    "Test\0\0send()\0receive()\0"
};

void Test::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
{
    if (_c == QMetaObject::InvokeMetaMethod) {
        Q_ASSERT(staticMetaObject.cast(_o));
        Test *_t = static_cast<Test *>(_o);
        switch (_id) {
        case 0: _t->send(); break;
        case 1: _t->receive(); break;
        default: ;
        }
    }
    Q_UNUSED(_a);
}

const QMetaObjectExtraData Test::staticMetaObjectExtraData = {
    0,  qt_static_metacall 
};

const QMetaObject Test::staticMetaObject = {
    { &QObject::staticMetaObject, qt_meta_stringdata_Test,
      qt_meta_data_Test, &staticMetaObjectExtraData }
};

#ifdef Q_NO_DATA_RELOCATION
const QMetaObject &Test::getStaticMetaObject() { return staticMetaObject; }
#endif //Q_NO_DATA_RELOCATION

const QMetaObject *Test::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->metaObject : &staticMetaObject;
}

void *Test::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_Test))
        return static_cast<void*>(const_cast< Test*>(this));
    return QObject::qt_metacast(_clname);
}

int Test::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
{
    _id = QObject::qt_metacall(_c, _id, _a);
    if (_id < 0)
        return _id;
    if (_c == QMetaObject::InvokeMetaMethod) {
        if (_id < 2)
            qt_static_metacall(this, _c, _id, _a);
        _id -= 2;
    }
    return _id;
}

// SIGNAL 0
void Test::send()
{
    QMetaObject::activate(this, &staticMetaObject, 0, 0);
}
QT_END_MOC_NAMESPACE
configure:17297: result: failure
configure:17300: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.

**Comment by ElvishArtisan** [comment]
On Sep 13, 2016, at 17:35, Engineeringradio <notifications@github.com> wrote:
> I think I've got the directories correct now but no luck.
> I've had a look through the config.log and found this:
> 
> 

Are you sure that you checked the code out of the ‘master’ branch on Git?  That’s the branch that has the Qt4 porting work going on in it.  It’s easy to get it wrong because, by default, you will get the ‘stable’ branch.

To check it out from the command-line, do:

	cd
	git clone http://git.com/ElvishArtisan/rivendell rivendell3
	cd rivendell3
	git checkout master

You should end up with a directory called ‘rivendell3’ in your home directory which will contain the code for the ‘master’ branch.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by Engineeringradio** [comment]
Thanks. I've bumped into another problem. It seems when run make, any headers beginning with q3 in the code wont work unless I put in the exact location they are on my hard disk. Is there an option I've missed out when running ./configure?

Pete

**Comment by Engineeringradio** [comment]
I've solved it by adding the qt3support folder in QT_CFLAGS.

Pete

**Comment by NBassan** [comment]
I was not able to have a functioning system because of DB changes. I tried a porting of the current stable branch in my fork. There is still some work to be done.

**Comment by cnighswonger** [comment]
I'm receiving the same error as the OP.

Context:

- Fresh install of CentOS 7: CentOS Linux release 7.6.1810 (Core)
- All deps installed per INSTALL file
- Qt Toolkit ver 4.8.7
- git clone of rivendell repo working with stable branch

Results of running `./configure --libexecdir=/var/www/rd-bin --sysconfdir=/etc/httpd/conf.d`

<snip>

```
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for Qt... no
configure: error: *** Qt toolkit not found, unable to continue ***
```
Output of `pkg-config --cflags QtCore`

`-DQT_SHARED -I/usr/include/QtCore`

Do I need to pass a configuration option to point to the Qt libs?

**Comment by ElvishArtisan** [comment]
You're on the wrong branch. The 'stable' branch contains the current v2.x line, which uses Qt3. Use 'master' for the v3.x development with Qt4.

**Comment by cnighswonger** [comment]
Ahh... makes sense. Master compiles fine.

Is master stable enough for production or should I roll back to Qt3 and use stable?

Thanks

**Comment by ElvishArtisan** [comment]
Just about to go beta. I would *not* be putting it on the air just yet (although I know of at least one person who as done just that).
