### ISSUE TITLE
Merge Python API

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#147]

**Comment by FireByTrial** [comment]
@ElvishArtisan I just noticed this, I am wondering if there is more information on this? would this open up Rivendell to be used/interfaced with python applications/scripts? or would it make use of python?
Basically I am wondering what this refers to and if Django could interface with Rivendell if were to be merged?

**Comment by toadybarker** [comment]
Hello there FireByTrial,
    This is currently a Work in Process, which is in the very beginning stages of design/analysis.  Another developer was interested in creating something to work with python and RIvendell, but how complete that will be, and what it is going to look like is still "to be determined".  With that in mind the only suggestion I can tell you is check back in a couple of months and maybe we will know more about this, and whether or not it's actually going to be something people would want to use or not.... Thanks
