### ISSUE TITLE
GPI Functions

### ISSUE THREAD

**Issue by dthertel** [ElvishArtisan/rivendell#153]
So I found another issue on my load...personal issue I am sure!

Running 2.13.1 on Mint 17

The RDGPIMON shows incoming GPIs and logs them, but the functions I have programmed under RD admin are not working.  I made a macro cart with a simple PP S1 1 1! and assigned that cart to GPI1 on my ACS8.2 switcher.  I can run the cart from RDLibrary and it works, but the GPI won't fire it.

Any ideas?

**Comment by ElvishArtisan** [comment]
Closed due to lack of activity.
