### ISSUE TITLE
2.15.1 dropbox imports

### ISSUE THREAD

**Issue by dthertel** [ElvishArtisan/rivendell#156]
Hello all.  I think I found a bug.  When importing files via a dropbox, 2.15.1 seems to drop the description in the file window.  Example.  Cut 100000 is being used as a rotator.  When dropbox imported the files with cart chunk info of artist title cart# and start kill dates, everything seems to have worked its way into the files, but the description of each cut is "Cut 001" "Cut 002" instead of the cut title.  I just used these same files on a 2.5.5 load and it is perfect, but the same cuts after updating to 2.15.1 is droping the title and putting in the generic "cut 001.... and so on"  Is there anyway to fix this?  If not I will need to reload machines with the older software.
![2151importbug](https://cloud.githubusercontent.com/assets/23169596/21408380/650eeb88-c79a-11e6-8fbb-fcd9dd4b17a4.png)

**Comment by ElvishArtisan** [comment]
This behavior was changed in v2.9.1.
