### ISSUE TITLE
*_STACK tables grow indefinitely

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#157]
In looking at my KDHE_STACK table. we've been running Rivendell since late December and there are now about 35,000 rows in the table after generating 2 weeks worth of logs. Looking at the source code, rows are inserted in the table but they are never deleted (unless the entire service is deleted).

I am new to Rivendell so I don't know if this is a bug or a feature, but it doesn't look right to me.

I also noticed that the SCHEDULED_AT field isn't being used.

I came across this when trying to understand how the log generation and scheduling works.

**Comment by waynemerricks** [comment]
_STACK is used to list all matching CARTS and check for rule breakages when generating a log.

From what I can see, rdevent_line.cpp is the main file that inserts and selects from the STACK table.  Looking through it there is definitely scope for some different usage of this table/queries to speed things up and cleanup.

For example in event line from 608 onto 841, Riv selects carts that are in a specific group and adds them to an array.  Then it queries the entire stack to find out what the next ID will be (e.g. rows + 1).  Then it queries the CARTS and ARTISTS in the STACK to get a list for title and artist separation, max in a row and do not schedule after checks.

Finally, it inserts effectively the whole log back into the STACK.

I can't find any other obvious usage of STACK (grep searches) so it seems like you don't really need more than your title separation/min wait number of rows to be in here.  Certainly not what appears to be all the rows from the beginning of time (my main Production service has over 1million rows in the STACK table).  Since I started using Riv my log generation has gone from around 2minutes to 10+ per day, I'm guessing STACK growth doesn't help.

**Comment by deltecent** [comment]
I agree. Every time it goes to add a line to the log, it reads the entire STACK and then gets the last record to determine the highest number. I modified mine to "ORDER BY x DESC LIMIT 1” to just grab the highest number that way. It still has to sort the list, but it doesn’t have to
process and return all the rows.

I am going to work on optimizing the STACK table and trimming it do the max of title/artist/min separation, or at least the 50,000
title limit set in software.

I’ll submit my changes once they’re done. That may speed up your log generation.

Patrick

**Comment by waynemerricks** [comment]
You can also query with count(*) or MAX(SCHED_STACK_ID) query times show little difference but posting here for reference (query / fetch in seconds averaged over 10 attempts):

SELECT *  : .00091 / 7.954
SELECT MAX(SCHED_STACK_ID) : .00044 / .000018
SELECT COUNT(*) : .187 / .000018
SELECT ... ORDER BY x DESC LIMIT 1 : .00048 / 0.000019

Also if you stay away from LIMIT you maintain compatibility with other databases as LIMIT seems to be a MySQL only command (and I assume Maria).  It can also help with table replication but as this is only for SELECT statements it doesn't really matter.

**Comment by deltecent** [comment]
Brilliant!  Your way is much better. 

Patrick

**Comment by deltecent** [comment]
I am working on adding a PurgeStacks() method to rdmaint.

**Comment by deltecent** [comment]
Here is my first attempt at purging the stacks. I'm new to programming Rivendell and C++, so your feedback is appreciated:

diff --git a/utils/rdmaint/rdmaint.cpp b/utils/rdmaint/rdmaint.cpp
index 1f907a3..0079e08 100644
--- a/utils/rdmaint/rdmaint.cpp
+++ b/utils/rdmaint/rdmaint.cpp
@@ -131,6 +131,7 @@ void MainObject::RunSystemMaintenance()
   PurgeLogs();
   PurgeElr();
   PurgeGpioEvents();
+  PurgeStacks();
   sql="update VERSION set LAST_MAINT_DATETIME=now()";
   q=new RDSqlQuery(sql);
   delete q;
@@ -280,6 +281,57 @@ void MainObject::PurgeGpioEvents()
   delete q;
 }
 
+void MainObject::PurgeStacks()
+{
+  QString sql;
+  RDSqlQuery *q;
+  RDSqlQuery *q1;
+  RDSqlQuery *q2;
+  int stackid;
+  int stacksize;
+  int artistsep=50000;
+  int titlesep=50000;
+
+  sql="select MAX(ARTISTSEP) from CLOCKS";
+  q=new RDSqlQuery(sql);
+  if(q->next()) {
+    artistsep=q->value(0).toInt();
+  }
+  delete q;
+
+  sql="select MAX(TITLE_SEP) from EVENTS";
+  q=new RDSqlQuery(sql);
+  if(q->next()) {
+    titlesep=q->value(0).toInt();
+  }
+  delete q;
+
+  stacksize=(artistsep<titlesep)?titlesep:artistsep;
+
+  sql="select NAME from SERVICES";
+  q=new RDSqlQuery(sql);
+  while(q->next()) {
+    QString tablename=q->value(0).toString()+"_STACK";
+    tablename.replace(" ","_");
+    sql=QString().sprintf("SELECT MAX(SCHED_STACK_ID) from %s",(const char*)tablename);
+    q1=new RDSqlQuery(sql);
+    if (q1->next())
+    { 
+      stackid=q1->value(0).toUInt();
+      if (stackid-stacksize > 0) {
+        sql=QString().sprintf("DELETE from `%s` where SCHED_STACK_ID <= %d", (const char*)tablename, stackid-stacksize);
+        q2=new RDSqlQuery(sql);
+        delete q2;
+      }
+
+      // Eventually, SCHED_STACK_ID is going to wrap back to 0.
+      // We may want to put something here to renumber the stack
+      // once it reaches a certain number.
+    }
+    delete q1;
+  }
+  delete q;
+}
   
 int main(int argc,char *argv[])
 {
diff --git a/utils/rdmaint/rdmaint.h b/utils/rdmaint/rdmaint.h
index 4cc8f3a..075a06b 100644
--- a/utils/rdmaint/rdmaint.h
+++ b/utils/rdmaint/rdmaint.h
@@ -44,6 +44,7 @@ class MainObject : public QObject
   void PurgeElr();
   void PurgeDropboxes();
   void PurgeGpioEvents();
+  void PurgeStacks();
   RDConfig *maint_config;
   bool maint_verbose;
   bool maint_system;

**Comment by deltecent** [comment]
Here is my first attempt and purging the stacks with rdmaint. I'm fairly new to Rivendell source and C++, so your feedback is appreciated:

diff --git a/utils/rdmaint/rdmaint.cpp b/utils/rdmaint/rdmaint.cpp
index 1f907a3..0079e08 100644
--- a/utils/rdmaint/rdmaint.cpp
+++ b/utils/rdmaint/rdmaint.cpp
@@ -131,6 +131,7 @@ void MainObject::RunSystemMaintenance()
   PurgeLogs();
   PurgeElr();
   PurgeGpioEvents();
+  PurgeStacks();
   sql="update VERSION set LAST_MAINT_DATETIME=now()";
   q=new RDSqlQuery(sql);
   delete q;
@@ -280,6 +281,57 @@ void MainObject::PurgeGpioEvents()
   delete q;
 }
 
+void MainObject::PurgeStacks()
+{
+  QString sql;
+  RDSqlQuery *q;
+  RDSqlQuery *q1;
+  RDSqlQuery *q2;
+  int stackid;
+  int stacksize;
+  int artistsep=50000;
+  int titlesep=50000;
+
+  sql="select MAX(ARTISTSEP) from CLOCKS";
+  q=new RDSqlQuery(sql);
+  if(q->next()) {
+    artistsep=q->value(0).toInt();
+  }
+  delete q;
+
+  sql="select MAX(TITLE_SEP) from EVENTS";
+  q=new RDSqlQuery(sql);
+  if(q->next()) {
+    titlesep=q->value(0).toInt();
+  }
+  delete q;
+
+  stacksize=(artistsep<titlesep)?titlesep:artistsep;
+
+  sql="select NAME from SERVICES";
+  q=new RDSqlQuery(sql);
+  while(q->next()) {
+    QString tablename=q->value(0).toString()+"_STACK";
+    tablename.replace(" ","_");
+    sql=QString().sprintf("SELECT MAX(SCHED_STACK_ID) from %s",(const char*)tablename);
+    q1=new RDSqlQuery(sql);
+    if (q1->next())
+    { 
+      stackid=q1->value(0).toUInt();
+      if (stackid-stacksize > 0) {
+        sql=QString().sprintf("DELETE from `%s` where SCHED_STACK_ID <= %d", (const char*)tablename, stackid-stacksize);
+        q2=new RDSqlQuery(sql);
+        delete q2;
+      }
+
+      // Eventually, SCHED_STACK_ID is going to wrap back to 0.
+      // We may want to put something here to renumber the stack
+      // once it reaches a certain number.
+    }
+    delete q1;
+  }
+  delete q;
+}
   
 int main(int argc,char *argv[])
 {
diff --git a/utils/rdmaint/rdmaint.h b/utils/rdmaint/rdmaint.h
index 4cc8f3a..075a06b 100644
--- a/utils/rdmaint/rdmaint.h
+++ b/utils/rdmaint/rdmaint.h
@@ -44,6 +44,7 @@ class MainObject : public QObject
   void PurgeElr();
   void PurgeDropboxes();
   void PurgeGpioEvents();
+  void PurgeStacks();
   RDConfig *maint_config;
   bool maint_verbose;
   bool maint_system;
