### ISSUE TITLE
Cart import doesn't reset time type to relative

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#165]
If an event is set to "Use hard start time", and the event has a pre-import cart, the time type is set to relative after pre-importing the cart, so the following import and post-import carts do not have hard time set to keep the following carts from removing the pre-import cart should carts need to be removed to meet the hard start time.

If the event has an import and a post-import, the import does not set the time type to relative, so both the import and the post-import carts have the same hard start time. If carts must be removed to meet the start time, the import cart is removed by the post-import cart.

If a cart is imported post-import or import, the time type should be set to relative.

**Comment by ElvishArtisan** [comment]
Appears to have been fixed in v3.x.
