### ISSUE TITLE
Delete event confirmation dialog ambiguous

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#167]
There is a confirmation dialog to ensure that the event being deleted from a clock is the one you really want. The current version of Rivendell displays, I believe, the length of the event, which makes the confirmation dialog ambiguous.

While I don't know if you need all the information (start time, end time, and description) in the dialog, the dialog should contain something that clearly identifies the actual event that is going to be deleted.

**Comment by deltecent** [comment]
Makes sense.  So how about we use just start time (MM:SS) and the Event Name?  That would permit unambiguous identification without overwhelming the user with unnecessary clutter.

**Comment by ElvishArtisan** [comment]
Reesolved in v2.16.0.
