### ISSUE TITLE
log saving issue...4Fred

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#171]
To User discussion about the Rivendell Radio Automation System
Mar 28 at 11:06 AM
On Mar 28, 2017, at 10:57, Ryan Williams <ryanmw@gmail.com> wrote:

> I'm having an regression with the most recent release. If I open RDLogEdit and try to add to a log's description it does not save. We use the field field to add "READY" to the end of the description when the log is cleared for air, so this one is going to sting a lot.

Partially confirmed here.  If you use the ‘Save’ button, the updated Description is indeed lost.  However, clicking ‘OK’ (without clicking ‘Save’ first) appears to work normally.

**Comment by validmirror** [comment]
also look at the scheduler codes disappearing, may or may not be related...ja

**Comment by ElvishArtisan** [comment]
Fixed in v2.160.
