### ISSUE TITLE
Bug: Cannot change RDAirPlay Startup Mode

### ISSUE THREAD

**Issue by ryanhagfors** [ElvishArtisan/rivendell#175]
Since upgrading to v2.15.3, we've noticed we can no longer change the Log Startup Mode under Log Mode Control in the RDAirPlay settings--it's stuck on Automatic.  If we change it to Manual or Previous, close out, then reopen the RDAirPlay config, it's back to Automatic.  I've tried this on other Rivendell hosts we have as well and get the same thing.  It appears to not update the MySQL table when changing the Startup Mode.  A "SELECT LOG0_START_MODE FROM RDAIRPLAY" returns all zeros.

**Comment by ElvishArtisan** [comment]
Confirmed in git 'stable'.

**Comment by ElvishArtisan** [comment]
Fixed in Git 'stable'.
