### ISSUE TITLE
 Can't import audio or delete audio

### ISSUE THREAD

**Issue by WDRCHD2** [ElvishArtisan/rivendell#178]
Can't import or delete audio files in rivendell 2.10.3 on Ubuntu 14.04.1. In RDLibrary import " unable to create destination file"
Also can not backup the database.
I updated Ubuntu from 12.04 to 14.04 LTS is when this issue started. Before this update everything work.

**Comment by ElvishArtisan** [comment]
Closed due to lack of activity.
