### ISSUE TITLE
DB Schema information needed for conversion

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#180]
Our current production version of Rivendell is 2.10.3 (db schema 242). We are setting up a pi for test and back up (so we can upgrade). It runs Rivendell version: 2.15.1 (db schema 259). Is there any documentation (or conversion scripts) to convert a 242 schema to a 259 schema? 

THank you

**Comment by waynemerricks** [comment]
All you have to do is run rdadmin.  If it detects an older version of the
database, it will update it automatically.

Regards,

Wayne
