### ISSUE TITLE
Schedule Rules in Rivendell 2.18.1

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#187]
In Rivendell 2.18.1, you cannot create scheduler rules with new clocks.  The table appears to not be created. To recreate:

First, make sure there are at least one scheduler code.

1. Create a new Rivendell installation (or use a current one)
2. Create a new clock
3. Edit Schedule rules -- notice the rules are cut off.

You can import, then save, and when you return the rules are missing.

**Comment by ElvishArtisan** [comment]
Confirmed in v2.18.1.

**Comment by ElvishArtisan** [comment]
Fixed in Git branch 'v2.18.1fixes'.
