### ISSUE TITLE
sql problem on fresh install

### ISSUE THREAD

**Issue by jeremielorente** [ElvishArtisan/rivendell#188]
Hi,
i've just intalled rivendell on a fresh centos 7 with rpm packages from paravel repo (2.18.1-1,  dec version, server standalone script).
Everything works (import/library etc) until rdlogmanager:
- event: creation of 1 ident event et 1 music event
- clock: ok but in scheduler rules, only one line appear...
- grid: ok, copy on the entire week ok too...
Then log creation fail: only idents, no music
Try with command line failed with this result:
`rdlogmanager` -g -d 0 -s HappyRadio
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
Database connection failed: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
rdlogmanager: invalid SQL or failed DB connection[Table 'Rivendell.BasicClock_RULES' doesn't exist QMYSQL3: Unable to execute query]: select CODE,MAX_ROW,MIN_WAIT,NOT_AFTER, OR_AFTER,OR_AFTER_II from BasicClock_RULES
`

**Comment by ElvishArtisan** [comment]
Already fixed in 'v2.18.1fixes'. See issue #187.
