### ISSUE TITLE
Add RDSimplePlayer buttons to RDLibrary Cart List

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#202]
It would be nice to have the ability to play carts from the ```RDLibrary``` Cart List.

**Comment by deltecent** [comment]
This was my idea of where to put the play/stop buttons:

![screen shot 2018-03-12 at 10 48 52 am](https://user-images.githubusercontent.com/24786756/37300509-602ce6a8-25e3-11e8-9fd8-e60fb81e3125.png)

**Comment by deltecent** [comment]
I understand the buttons do not take cuts into account and may give off a false impression. None of the modules within Rivendell, such as the play/stop buttons in RDAirPlay when adding a cart and the play/pause buttons in RDLogEdit do not support directly accessing individual cuts. The understanding of Rivendell and it's cart/cut concept is understood when using those applications and should be obvious when using the same type of buttons in RDLibrary.

Having those buttons is a significant time saver when wanting to speed through a lot of carts, especially when the database is on the other end of a VPN.

Would it be an option to only enable the buttons for carts that only contain a single cut?

**Comment by ElvishArtisan** [comment]
On May 29, 2018, at 18:11, Deltec Enterprises <notifications@github.com> wrote:
> I understand the buttons do not take cuts into account and may give off a false impression. None of the modules within Rivendell, such as the play/stop buttons in RDAirPlay when adding a cart and the play/pause buttons in RDLogEdit do not support directly accessing individual cuts. The understanding of Rivendell and it's cart/cut concept is understood when using those applications and should be obvious when using the same type of buttons in RDLibrary.
> 
RDAirPlay resolves the specific underlying cut to play on the basis of Rivendell’s built-in day-parting and rotation logic. As such, it properly does not present cut-level details to the user as they are not something that can be addressed in the context of a log.

As for RDLogEdit, yes, I totally get your point. It’s an architectural wart. Were I to receive a PR for that feature today, I would likely reject it for the same reason as for the RDLibrary case.

> Having those buttons is a significant time saver when wanting to speed through a lot of carts, especially when the database is on the other end of a VPN.
> 
> Would it be an option to only enable the buttons for carts that only contain a single cut?
> 


That would be a start, but what is really needed is to enable a ‘tree’ view of carts in RDLibrary —i.e. have each cart show its child cut(s) in additional rows below their parent cart. As each cut entry is selected (or its parent cart, if the cart contains only one), enable a ‘Play’ button for that cut. That would get us ‘one click play-out’ while still preserving a full-fidelity representation of what is actually in the Library.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by deltecent** [comment]
> On May 29, 2018, at 3:44 PM, Fred Gleason <notifications@github.com> wrote:
> 
> On May 29, 2018, at 18:11, Deltec Enterprises <notifications@github.com> wrote:
> > I understand the buttons do not take cuts into account and may give off a false impression. None of the modules within Rivendell, such as the play/stop buttons in RDAirPlay when adding a cart and the play/pause buttons in RDLogEdit do not support directly accessing individual cuts. The understanding of Rivendell and it's cart/cut concept is understood when using those applications and should be obvious when using the same type of buttons in RDLibrary.
> > 
> RDAirPlay resolves the specific underlying cut to play on the basis of Rivendell’s built-in day-parting and rotation logic. As such, it properly does not present cut-level details to the user as they are not something that can be addressed in the context of a log.
> 
> As for RDLogEdit, yes, I totally get your point. It’s an architectural wart. Were I to receive a PR for that feature today, I would likely reject it for the same reason as for the RDLibrary case.
> 
> > Having those buttons is a significant time saver when wanting to speed through a lot of carts, especially when the database is on the other end of a VPN.
> > 
> > Would it be an option to only enable the buttons for carts that only contain a single cut?
> > 
> 
> 
> That would be a start, but what is really needed is to enable a ‘tree’ view of carts in RDLibrary —i.e. have each cart show its child cut(s) in additional rows below their parent cart. As each cut entry is selected (or its parent cart, if the cart contains only one), enable a ‘Play’ button for that cut. That would get us ‘one click play-out’ while still preserving a full-fidelity representation of what is actually in the Library.
> 

Hmmm... that's currently beyond my QT skillset, but I say, challenge accepted.

Would you recommend a tree view option where all the carts show their cuts, or something to click on like a "+" on the cart line to reveal cuts only for that cart? Another question would be whether to load all the cuts at once when all the carts are loaded or fetch them from the database only when the cuts need to be displayed, like if a "+" is clicked?

Thank you for merging the other stuff.

Patrick

**Comment by druidlabs** [comment]
A double-click (or Edit button) on a cart line in RDLibrary opens the Edit
Cart dialog.  What will happen when you double-click on a cut line?  Play
the cut, open Cut Info, open Edit Markers, or something else?  I'd like to
see Edit Markers.
