### ISSUE TITLE
Now & Next stop sending titles after after a moment

### ISSUE THREAD

**Issue by jeremielorente** [ElvishArtisan/rivendell#204]
Hi,
Now & Next works only for a while, after 2 or 3 hours, it stop sending titles info.
In /var/log/messages ripcd stop doing rml command
in addition, it sometimes send the same titile twice after few seconds... or send nothing (no artist or title sent in %a and %t variables)

see attached file: my /var/log/message before ripcd stop sending rml command with now and next
[message.log](https://github.com/ElvishArtisan/rivendell/files/1804280/message.log)

**Comment by deltecent** [comment]
Does it always stop when there's no artist or title?
> ```echo " - "```

**Comment by jeremielorente** [comment]
I don't know if it's always in that case, but i've try to reload rdairplay yesterday and this is the last list with doubles and stop working after echo " - ":

`15/03/2018 22:02 -  - 
15/03/2018 22:00 - Femme Like U - K-Maro
15/03/2018 21:58 - Femme Like U - K-Maro
15/03/2018 21:54 - Toi et moi - Paradis
15/03/2018 21:50 - Stone Love - Kool  The Gang
15/03/2018 21:47 - Summer - Calvin Harris
15/03/2018 21:46 -  - 
15/03/2018 21:45 - Freedom - POSTAAL
15/03/2018 21:44 - Freedom - POSTAAL
15/03/2018 21:40 - Englishman in New York - Sting
15/03/2018 21:32 - Diego, libre dans sa tete (live) - Johnny Hallyday
15/03/2018 21:31 -  - 
15/03/2018 21:24 - African Reggae - Nina Hagen
15/03/2018 21:20 - Comanchero - Moon Ray
15/03/2018 21:16 - Caroline - Firewater
15/03/2018 21:16 -  - 
15/03/2018 21:15 - Love Is a Temple - Mario Biondi
15/03/2018 21:12 - Love Is a Temple - Mario Biondi
15/03/2018 21:05 - 24K Magic - Bruno Mars
15/03/2018 21:01 - Avant toi - Calogero
15/03/2018 21:01 -  - 
15/03/2018 21:00 - Lordly - Feder feat. Alex Aiono
15/03/2018 20:57 - Lordly - Feder feat. Alex Aiono
15/03/2018 20:53 - Cold Dresses - Al Corley
15/03/2018 20:47 -  - 
15/03/2018 20:45 - Jesus He Knows Me - Genesis
15/03/2018 20:43 - Jesus He Knows Me - Genesis
15/03/2018 20:37 - Mon bijou - Jul
15/03/2018 20:33 - Pink Medicine - Bearson
15/03/2018 20:33 -  - 
15/03/2018 20:26 - This Is What You Came For - Calvin Harris feat. Rihanna
15/03/2018 20:22 - Stone Love - Kool  The Gang
15/03/2018 20:19 - Me Too - Meghan Trainor
15/03/2018 20:15 - Family Affair - Mary J. Blige
15/03/2018 20:15 -  - 
15/03/2018 20:15 - 24K Magic - Bruno Mars
15/03/2018 20:11 - 24K Magic - Bruno Mars
15/03/2018 20:04 - History (Rutger Kroese 12_ version) - Mai Tai
15/03/2018 20:00 - Never Gonna Leave This Bed (acoustic) - Maroon 5
15/03/2018 20:00 -  - 
15/03/2018 20:00 - Caroline - Firewater
15/03/2018 19:56 - Caroline - Firewater
15/03/2018 19:54 - Come Again - Maddy Prior
15/03/2018 19:51 - Rupture - Laurie Darmon
15/03/2018 19:48 - Toi et moi - Paradis
15/03/2018 19:47 -  - 
15/03/2018 19:45 - You Gotta Be ('99 mix) - Des'ree
15/03/2018 19:43 - You Gotta Be ('99 mix) - Des'ree
15/03/2018 19:38 - Heat It Up (acid house remix) - The Wee Papa Girl Rappers
15/03/2018 19:32 - Belinda - M. Pokora
15/03/2018 19:31 -  - 
15/03/2018 19:30 - This Is What You Came For - Calvin Harris feat. Rihanna
15/03/2018 19:28 - This Is What You Came For - Calvin Harris feat. Rihanna
15/03/2018 19:24 - Saving All My Love for You - Whitney Houston
15/03/2018 19:21 - Manu - Renaud
15/03/2018 19:17 - Jesus He Knows Me - Genesis
15/03/2018 19:17 -  - 
15/03/2018 19:15 - Come back to me - Cunnie Williams
15/03/2018 19:13 - Come back to me - Cunnie Williams
15/03/2018 19:09 - Kiss Me - Ed Sheeran
15/03/2018 19:02 -  - 
15/03/2018 19:00 - Jesus He Knows Me - Genesis
15/03/2018 18:58 - Jesus He Knows Me - Genesis
15/03/2018 18:55 - Belinda - M. Pokora`

**Comment by jeremielorente** [comment]
after restarting rdaiplay, it didn't after echo " - " but after a full artist/title filled:

> 16/03/2018 22:58 - Counting Stars - OneRepublic
> 16/03/2018 22:54 - Part 011 - Dewey Lambdin read by John Lee
> 16/03/2018 22:50 - Burn - Ellie Goulding
> 16/03/2018 22:46 - Encore - Florent Pagny
> 16/03/2018 22:46 -  - 
> 16/03/2018 22:43 - Come back to me - Cunnie Williams
> 16/03/2018 22:34 - Chase - Giorgio Moroder
> 16/03/2018 22:30 - La Boum 2 - Your Eyes (Interpretee Par Cook Da Books) - Vladimir Cosma
> 16/03/2018 22:22 - What Do I Do (Carnival mix) - Phil Fearon  Galaxy
> 16/03/2018 22:22 -  - 
> 16/03/2018 22:18 - Jack to the Sound of the Underground - Hithouse
> 16/03/2018 22:12 - Self Control (extended version) - Infernal
> 16/03/2018 22:10 - Manu - Renaud
> 16/03/2018 22:02 - Music Sounds Better With You - Stardust
> 16/03/2018 22:02 -  - 
> 16/03/2018 21:58 - Pump Up the Volume - MARRS
> 16/03/2018 21:52 - Visitors - Koto
> 16/03/2018 21:47 - Calypso Crazy - Billy Ocean
> 16/03/2018 21:43 - Familiar - Agnes Obel
> 16/03/2018 21:41 - Come Again - Maddy Prior
> 16/03/2018 21:40 -  - 
> 16/03/2018 21:35 - Cha Cha Cha - Finzy Kontini
> 16/03/2018 21:31 - African Reggae - Nina Hagen
> 16/03/2018 21:28 - Mon bijou - Jul
> 16/03/2018 21:25 - Me Too - Meghan Trainor
> 16/03/2018 21:22 - Every Kiss - Mark Shreeve
> 16/03/2018 21:21 -  - 
> 16/03/2018 21:18 - Karma - Julian Perretta
> 16/03/2018 21:15 - This Is What You Came For - Calvin Harris feat. Rihanna
> 16/03/2018 21:11 - The Breaks - Kurtis Blow
> 16/03/2018 21:07 - Breathe - Blu Cantrell feat. Sean Paul
> 16/03/2018 21:00 - Street Dance (vocal) - Break Machine
> 16/03/2018 21:00 -  - 
> 16/03/2018 20:53 - Freedom - POSTAAL
> 16/03/2018 20:49 - Jesus He Knows Me - Genesis
> 16/03/2018 20:45 - Pink Medicine - Bearson
> 16/03/2018 20:45 -  - 
> 16/03/2018 20:45 - Say It Right - Nelly Furtado
> 16/03/2018 20:41 - Say It Right - Nelly Furtado
> 16/03/2018 20:37 - Part Time Lover - Stevie Wonder
> 16/03/2018 20:33 - African Reggae - Nina Hagen
> 16/03/2018 20:32 -  - 
> 16/03/2018 20:30 - Starboy - The Weeknd feat. Daft Punk
> 16/03/2018 20:28 - Starboy - The Weeknd feat. Daft Punk
> 16/03/2018 20:25 - You Belong - The Avener feat. Laura Gibson
> 16/03/2018 20:21 - Promiscuous (radio edit) - Nelly Furtado feat. Timbaland
> 16/03/2018 20:17 - Sweets for My Sweet - C.J. Lewis
> 16/03/2018 20:17 -  - 
> 16/03/2018 20:14 - Wesh Alors - Jul
> 16/03/2018 20:10 - This Is What You Came For - Calvin Harris feat. Rihanna
> 16/03/2018 20:06 - The Breaks - Kurtis Blow
> 16/03/2018 20:00 - Come Again - Maddy Prior
> 16/03/2018 20:00 -  - 
> 16/03/2018 20:00 - On dirait - Amir
> 16/03/2018 19:56 - On dirait - Amir
> 16/03/2018 19:53 - Castle in the Show - The Avener  Kadebostany feat. Vassy
> 16/03/2018 19:50 - Cosmo - Soprano
> 16/03/2018 19:47 -  - 
> 16/03/2018 19:45 - Pump Up the Volume - MARRS
> 16/03/2018 19:43 - Pump Up the Volume - MARRS
> 16/03/2018 19:38 -  - 
> 16/03/2018 19:30 - Chase - Giorgio Moroder
> 16/03/2018 19:29 - Chase - Giorgio Moroder
> 16/03/2018 19:24 - This Is My Life - Eartha Kitt
> 16/03/2018 19:20 - Set Me Free (extended version) - Jaki Graham
> 16/03/2018 19:17 - Faith - George Michael
> 16/03/2018 19:17 -  - 
> 16/03/2018 19:15 - This Is What You Came For - Calvin Harris feat. Rihanna
> 16/03/2018 19:13 - This Is What You Came For - Calvin Harris feat. Rihanna
> 16/03/2018 19:09 - Love Is a Temple - Mario Biondi
> 16/03/2018 19:05 - Music Sounds Better With You - Stardust
> 16/03/2018 19:02 - Karma - Julian Perretta
> 16/03/2018 19:02 -  - 
> 16/03/2018 19:00 - Cosmo - Soprano
> 16/03/2018 18:59 - Cosmo - Soprano
> 16/03/2018 18:57 - We Will Rock You - Queen
> 16/03/2018 18:49 - Breathe - Blu Cantrell feat. Sean Paul
> 16/03/2018 18:49 -  - 
> 16/03/2018 18:45 - Adventure of a Lifetime - Coldplay
> 16/03/2018 18:44 - Adventure of a Lifetime - Coldplay
> 16/03/2018 18:39 - Tous les cris les S.O.S. - Daniel Balavoine
> 16/03/2018 18:34 - Ouragan - Stephanie
> 16/03/2018 18:34 -  - 
> 16/03/2018 18:30 - Visitors - Koto
> 16/03/2018 18:28 - Visitors - Koto
> 16/03/2018 18:21 - Jack to the Sound of the Underground - Hithouse
> 16/03/2018 18:17 - Lonely - Akon
> 16/03/2018 18:16 -  - 
> 16/03/2018 18:15 - China Girl - David Bowie
> 16/03/2018 18:12 - China Girl - David Bowie
> 16/03/2018 18:09 - Die Walkure - 49ers
> 16/03/2018 18:06 - Les Yeux de la Mama - Kendji Girac
> 16/03/2018 18:00 - Heartache No. 9 - Delegation
> 16/03/2018 18:00 -  - 
> 16/03/2018 18:00 - I Need Your Love - Calvin Harris
> 16/03/2018 17:57 - I Need Your Love - Calvin Harris

**Comment by jeremielorente** [comment]
same kind of last text displayed by Now and Next today:

> 19/03/2018 23:35 - This Is My Life - Eartha Kitt
> 19/03/2018 23:30 -  - 
> 19/03/2018 23:30 - Get on Up - Jazzy Dee
> 19/03/2018 23:26 - Get on Up - Jazzy Dee
> 19/03/2018 23:23 - Love Is a Temple - Mario Biondi
> 19/03/2018 23:18 - Tous les cris les S.O.S. - Daniel Balavoine
> 19/03/2018 23:18 -  - 
> 19/03/2018 23:13 - Part Time Lover - Stevie Wonder
> 19/03/2018 23:11 - Paradise - Noa Moon
> 19/03/2018 23:07 - Encore - Florent Pagny
> 19/03/2018 23:03 - Sugar - Robin Schulz feat. Francesco Yates
> 19/03/2018 23:00 - This Is What You Came For - Calvin Harris feat. Rihanna
> 19/03/2018 23:00 -  - 
> 19/03/2018 23:00 - Someone Who Needs Me - Bob Sinclar
> 19/03/2018 22:57 - Someone Who Needs Me - Bob Sinclar
> 19/03/2018 22:50 - Me Too - Meghan Trainor
> 19/03/2018 22:46 - Saving All My Love for You - Whitney Houston
> 19/03/2018 22:46 -  - 
> 19/03/2018 22:45 - No Scrubs - TLC
> 19/03/2018 22:42 - No Scrubs - TLC
> 19/03/2018 22:32 - Street Dance (vocal) - Break Machine
> 19/03/2018 22:32 -  - 
> 19/03/2018 22:29 - Mon bijou - Jul
> 19/03/2018 22:24 - This Is My Life - Eartha Kitt
> 19/03/2018 22:21 - Sign of the Times - The Belle Stars
> 19/03/2018 22:18 - The Thrill Is Gone - MHE
> 19/03/2018 22:15 - Lovers2Lovers - Smash feat. Ridley
> 19/03/2018 22:15 -  - 
> 19/03/2018 22:15 - Gold - Andreya Triana
> 19/03/2018 22:11 - Gold - Andreya Triana
> 19/03/2018 22:08 - Never Gonna Leave This Bed (acoustic) - Maroon 5
> 19/03/2018 22:03 - Set Me Free (extended version) - Jaki Graham
> 19/03/2018 22:00 - Belinda - M. Pokora
> 19/03/2018 22:00 -  - 
> 19/03/2018 22:00 - Pump Up the Volume - MARRS
> 19/03/2018 21:56 - Pump Up the Volume - MARRS
> 19/03/2018 21:53 - Someone Who Needs Me - Bob Sinclar
> 19/03/2018 21:49 -  - 
> 19/03/2018 21:45 - History (Rutger Kroese 12_ version) - Mai Tai
> 19/03/2018 21:42 - History (Rutger Kroese 12_ version) - Mai Tai
> 19/03/2018 21:38 - I Need Your Love - Calvin Harris
> 19/03/2018 21:34 -  - 
> 19/03/2018 21:20 - What Do I Do (Carnival mix) - Phil Fearon  Galaxy
> 19/03/2018 21:17 - Help - Bananarama  Lananeeneenoonoo
> 19/03/2018 21:17 -  - 
> 19/03/2018 21:15 - Caroline - Firewater
> 19/03/2018 21:13 - Caroline - Firewater
> 19/03/2018 21:10 - Karma - Julian Perretta
> 19/03/2018 21:03 -  - 
> 19/03/2018 21:00 - No Favors - Temper
> 19/03/2018 20:56 - No Favors - Temper
> 19/03/2018 20:53 - Castle in the Show - The Avener  Kadebostany feat. Vassy
> 19/03/2018 20:49 - Love Is a Temple - Mario Biondi
> 19/03/2018 20:45 - Die Walkure - 49ers
> 19/03/2018 20:45 -  -

**Comment by jeremielorente** [comment]
Same problem on last version 2.29.1

**Comment by julienweiss** [comment]
Hi everyone ! 

I own a rivendell prepared by tryphon on debian distro. 

I am looking for a way to send NOW and Next directly on remote
webserver. 

Can someone help me to do that ? 

---
Julien WEISS 

Responsable technique et pédagogique 

Radiocampus Orléans 

4 rue de Tours 

"le Cône" 

45100 Orleans 

0238691742 

Le 2018-04-09 00:52, jeremielorente a écrit :

> Same problem on last version 2.29.1 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/ElvishArtisan/rivendell/issues/204#issuecomment-379589348
[2]

**Comment by jeremielorente** [comment]
Ok, fixed! (well... got around..)
Instead of using RN command line, i've used rlm_filewrite.rlm module to update my website and rlm_icecast2.rlm to add metadata to webradio stream

These modules work great! Thx :)
