### ISSUE TITLE
Log generation with CHAIN TO fails

### ISSUE THREAD

**Issue by jplojohn** [ElvishArtisan/rivendell#207]
When generating a log using `rdlogmanager`, either in GUI or CLI mode (-g), the generation fails at the final step - adding the `CHAIN TO` for the following day's log.

The reason given for this is as follows:

`invalid SQL or failed DB connection[Field 'TIME_TYPE' doesn't have a default value QMYSQL3: Unable to execute query]: insert into `2018_04_29_LOG` set ID=672,COUNT=672,TYPE=5,SOURCE=3,TRANS_TYPE=1,LABEL="2018-04-30"`

I believe that either the particular SQL statement should also have `TIME_TYPE=0` in it, or when `rdlogmanager` performs `CREATE TABLE`, it should set a default value of 0.

Unfortunately, I cannot rectify this in our database directly, as the table schema is defined by `rdlogmanager` and cannot be changed by me later (as I've had to do as a workaround for a couple of other tables for similar issues).

In GUI mode, this fails silently with no warning, and in CLI mode (or GUI mode with stdout going to an open terminal), the above error is displayed.

**Comment by jplojohn** [comment]
Yum tells me I'm running 2.19.2, from the Paravel repo

**Comment by ae6ch** [comment]
One of these in your mysql.cnf should fix it, I can't remember which anymore..
innodb_strict_mode             = 0
sql_mode=""

**Comment by jplojohn** [comment]
Setting sql_mode to no modes solves it as a workaround. Our tables are MyISAM, so no innodb options will affect them.

**Comment by ElvishArtisan** [comment]
Fixed in 'master'.
