### ISSUE TITLE
Rdlibrary keeps playing music after cut window closed

### ISSUE THREAD

**Issue by jplojohn** [ElvishArtisan/rivendell#208]
When closing the cut window with the use of the Escape key, rather than through the window manager or within the GUI, if sound is playing in that window, it will continue to play until it is finished or until rdlibrary is fully exited. Running 2.19.2 on CentOS 7 with the Paravel repo packages.

Expected behaviour: audio should stop when the cut window is exited by means of the Escape key.

**Comment by ElvishArtisan** [comment]
Unable to reproduce.
