### ISSUE TITLE
gcc-c++ v8.0.1 : pow10 was not declared in this scope

### ISSUE THREAD

**Issue by hgshoggins** [ElvishArtisan/rivendell#210]
When trying to compile Rivendell 2.19.0 with a new compiler from Fedora 28 (gcc version 8.0.1, I assume this is the actual problem), it fails complaining that the **pow10** function was not declared in the current scope.
It is used in `cae_jack.cpp` and `cae_alsa.cpp`.

The compiler suggests that the **powl** function could be used instead of **pow10**, and it seems the syntax is ```powl(base, exponent)``` whereas **pow10**'s already has `10` as the exponent.
So I went into changing the occurrences of **pow10** into **powl** having e.g `pow10((double)level/2000.0)` replaced with `powl((double)level/2000.0,10.0)`.

Is it the correct way to deal with the issue, does it look like it's the right replacement function, or is there a way to force the compiler to be compatible with "old" versions ?

**Comment by ElvishArtisan** [comment]
On May 8, 2018, at 15:09, hgshoggins <notifications@github.com> wrote:
> When trying to compile Rivendell 2.19.0 with a new compiler from Fedora 28 (gcc version 8.0.1, I assume this is the actual problem), it fails complaining that the pow10 function was not declared in the current scope.
> It is used in cae_jack.cpp and cae_alsa.cpp.
> 
> The compiler suggests that the powl function could be used instead of pow10, and it seems the syntax is powl(base, exponent)whereas pow10's already has 10 as the exponent.
> So I went into changing the occurrences of pow10 into powl having e.g pow10((double)level/2000.0) replaced with powl((double)level/2000.0,10.0).
> 
> Is it the correct way to deal with the issue, does it look like it's the right replacement function, or is there a way to force the compiler to be compatible with "old" versions ?
> 

pow10() is not part of ANSI, but is a GNU extension. You can likely get it to build by inserting the line:

#define _GNU_SOURCE

near the top of the offending source files.

Long term, best would probably be to refactor the code to use pow(), which is ANSI standard (and hence more portable).

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by hgshoggins** [comment]
No luck with that, or putting `-D_GNU_SOURCE` in `CFLAGS` or `CXXFLAGS` either.
The only thing that succeeded was to replace `pow10()` with `pow()` as suggested.

**Comment by TheCodeMechanic616** [comment]
Do note that pow10 is something to the power of 10. So pow10(2) is 10^2. 
To get the same result with say powl, you need to write powl(10,2) and not the other way around.

**Comment by hgshoggins** [comment]
I'm editing my first comment to reflect @TheCodeMechanic616's remark.

**Comment by amel0** [comment]
You can also replace `pow10()` with `exp10()` as suggested on [pow10 man-page](http://man7.org/linux/man-pages/man3/pow10.3.html)
