### ISSUE TITLE
Add support for Spinitron v2's APIs (feature request)

### ISSUE THREAD

**Issue by spinitron** [ElvishArtisan/rivendell#211]
Spinitron v2 is a complete rewrite of Spinitron rolling out now. It provides

- a [new API](https://spinitron.github.io/v2api/) that conforms better to current practices. Automation may use its POST /spins endpoint
- a [supplemental endpoint](https://gist.github.com/spinitron/fec82a90f1ae97440bbe2cca011c9e2d)  for easier backwards compatibility that is similar to the automation API for v1, although not the same. The changes are
    - the base URL is now https://spinitron.com/api/spin/create-v1
    - authenticate with an API key instead of the `st`, `un`, and `pw` fields

I would offer a PR but, for shame, I haven't programmed in C in over 30 years.

**Comment by ElvishArtisan** [comment]
Added in eb4f2df.
