### ISSUE TITLE
SQL errors under Ubuntu 18.04

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#213]
There are about a half dozen mysql errors while running the various rivendell applications, rdadmin, rdcatch, rdlogedit, rdlogmanager, rdpanel:

rdadmin
invalid SQL or failed DB connection[Field 'INSTANCE' doesn't have a default value QMYSQL3: Unable to execute query]: insert into RDPANEL set STATION="Rivendell-VirtualBox"

Database connection failed: insert into RDPANEL set STATION="Rivendell-VirtualBox"
QSqlQuery::value: not positioned on a valid record

invalid SQL or failed DB connection[Field 'PORT_2' doesn't have a default value QMYSQL3: Unable to execute query]: insert into MATRICES set STATION_NAME="Rivendell-VirtualBox",NAME="New Switcher",GPIO_DEVICE="/dev/gpio0",MATRIX=0, PORT=0, TYPE=15, INPUTS=0, OUTPUTS=0, GPIS=0, GPOS=0, PORT_TYPE=0, PORT_TYPE_2=2

invalid SQL or failed DB connection[Field 'TYPE_ID' doesn't have a default value QMYSQL3: Unable to execute query]: insert into REPLICATORS set NAME="Test"

rdcatch
invalid SQL or failed DB connection[Field 'STATION_NAME' doesn't have a default value QMYSQL3: Unable to execute query]: insert into RECORDINGS set ID=1
Database connection failed: insert into RECORDINGS set ID=1
Segmentation fault (core dumped)

rdlogedit
invalid SQL or failed DB connection[Field 'MODIFIED_DATETIME' doesn't have a default value QMYSQL3: Unable to execute query]: insert into LOGS set NAME="MyTest",TYPE=0,DESCRIPTION="MyTest log ",ORIGIN_USER="user",ORIGIN_DATETIME=now(),LINK_DATETIME=now(),SERVICE="Production"
Database connection failed: insert into LOGS set NAME="MyTest",TYPE=0,DESCRIPTION="MyTest log",ORIGIN_USER="user",ORIGIN_DATETIME=now(),LINK_DATETIME=now(),SERVICE="Production"

rdlogmanager
Grabbing the mouse failed with "GrabInvalidTime"
invalid SQL or failed DB connection[Field 'MODIFIED_DATETIME' doesn't have a default value QMYSQL3: Unable to execute query]: insert into LOGS set NAME="Production-0425",TYPE=0,DESCRIPTION="Production-0425 log ",ORIGIN_USER="RDLogManager",ORIGIN_DATETIME=now(),LINK_DATETIME=now(),SERVICE="Production"
Database connection failed: insert into LOGS set NAME="Production-0425",TYPE=0,DESCRIPTION="Production-0425 log ",ORIGIN_USER="RDLogManager",ORIGIN_DATETIME=now(),LINK_DATETIME=now(),SERVICE="Production"

rdpanel
invalid SQL or failed DB connection[Field 'INSTANCE' doesn't have a default value QMYSQL3: Unable to execute query]: insert into RDPANEL set STATION="Kubuntu-VirtualBox"
Database connection failed: insert into RDPANEL set STATION="Kubuntu-VirtualBox"
QSqlQuery::value: not positioned on a valid record
Segmentation fault (core dumped)

rdselect
Segmentation fault (core dumped)

**Comment by ElvishArtisan** [comment]
SQL errors should now all be corrected in 'stable'. Please test!

I was unable to reproduce the 'GrabInvalidTime' mouse error. I strongly suspect that it is a local Ubuntu desktop issue.

Likewise the segfault in rdselect(8). Can you give some more detail about what provokes this? A backtrace would be ideal.

**Comment by danielbair** [comment]
**Wow, thank you! I will give it a test.**

BTW, I have been able to revive the debian/ubuntu packaging done by Alban Peignier from tryphon.eu (his last deb package was rivendell 2.10.3 back in 2015) by pulling his source and updating it for rivendell 2.19 from your server. I can put those deb packages in an apt repository for others if there is an interest.

Would you be interested in that debian directory (as it differs significantly from the main source one on github and in the zip archives)?

**Comment by ElvishArtisan** [comment]
On May 29, 2018, at 19:58, Daniel Bair <notifications@github.com> wrote:

> Would you be interested in that debian directory (as it differs significantly from the main source one on github and in the zip archives)?

Totally up to you, Daniel. Those files are used for nothing except generating DEB packages. If updating them would be helpful to that end, send me a PR and I’ll be glad to merge it.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|
