### ISSUE TITLE
Rdimport causes SQL error with --to-cart option

### ISSUE THREAD

**Issue by atgossard** [ElvishArtisan/rivendell#217]
Since 2.19.x if user tries to replace an existing cart using rdimport --to-cart= using an existing cart number (in my example cart #290044), causes the following SQL error: 

invalid SQL or failed DB connection[Duplicate entry '290044' for key 'PRIMARY' QMYSQL3: Unable to execute query]: insert into CART set NUMBER=290044,TYPE=1,GROUP_NAME="MISC",TITLE="\[cart\ 290044-1]"
Database connection failed: insert into CART set NUMBER=290044,TYPE=1,GROUP_NAME="MISC",TITLE="\[cart\ 290044-1]"

This worked in 2.18.x

**Comment by ElvishArtisan** [comment]
Fixed in branch 'stable'.
