### ISSUE TITLE
New functionality

### ISSUE THREAD

**Issue by wojcik13** [ElvishArtisan/rivendell#219]
Hi,
I've got a question: is there any possibility to export once a month a list of songs (with artist, composer and # of plays), that was played during last month? I mean a list with:
- title
- artist
- composer
- integer (how many times this song was played)
Is it doable without programming anything? I am newbie in Rivendell and I don't know how to add this function.
Regards

**Comment by julienweiss** [comment]
Hi everyone. 

I need a little help. 

I have three machines running on rivendell tryphon's version (it was a
french society that was selling computer for radio with rivendell
working on it) 

I would like to migrate this debian system (1 server and 2 clients) on a
centos system (1server 2, clients) 

I have many questions : 

will my hardware will be recognize after a fresh intall of cent os on
the 3 machines ? 

I would like to reuse my sound and my  database ? will it be possible to
migrate it from 2.13 to 2.19 ? If yes how can I do ? 

I have configured a test machine and on this machine when I import the
2.13 database I can't do anything after that  ? Should I upgrade the
database by steps ? 2.13 -> 2.14 ->2.15  until 2.19 ? 

Thanks for reading me.

---
Julien WEISS 

Responsable technique et pédagogique 

Radiocampus Orléans 

4 rue de Tours 

"le Cône" 

45100 Orleans 

0238691742 

Le 2018-07-19 13:28, W4RL0CK a écrit :

> Hi,
> I've got a question: is there any possibility to export once a month a list of songs (with artist, composer and # of plays), that was played during last month? I mean a list with: 
> 
> * title
> * artist
> * composer
> 
> * integer (how many times this song was played)
> Is it doable without programming anything? I am newbie in Rivendell and I don't know how to add this function.
> Regards 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/ElvishArtisan/rivendell/issues/219
[2]

**Comment by ltyndale** [comment]
Hi,

When you update to a new version, the first thing to do is run rdadmin. 
This will update the database to the new schema.

There should be no problem updating from 2.13.x to 2.19.x

Rather then going to a Debian system, you might be better to update to
CentOS.  With Debian you'll be pretty much on your own - you'll need to
compile from source (right now there is not anyone putting out current
Debian packages).  For CentOS - there are current packages provided by
Paravel.

Chances are your current hardware will be supported, but you might want
to check the CentOS website and compare with your hardware.


Lorne Tyndale

**Comment by ElvishArtisan** [comment]
Check out the 'spincount' report in rdadmin(1), which should do what you want.
