### ISSUE TITLE
QServerSocket calls backlog parameter

### ISSUE THREAD

**Issue by markmcconnell** [ElvishArtisan/rivendell#220]
Should not be set to 0.  On some systems this does request a "default" backlog,  on other systems it requests a literal 0 length backlog which prevents any connections from getting out of the SYN_SENT state.

After experiencing this issue,  I changed cae.cpp, rdcatchd.cpp and ripcd.cpp to all use 5 instead of 0 in the 'new {Cae,Rdcatch,Ripcd}Socket(*_TCP_PORT,0,this,"socket")' calls.  After a recompile,  finally all the client applications could connect to caed and friends and actually function.  Absent this fix,  several programs like RDLibrary and RDLogin either fail to function or segfault (in RDEscapeString or in libqt somewhere).

Please consider adjusting these parameters to any integer greater than 0.  Thanks!

**Comment by ElvishArtisan** [comment]
Which platforms experience this problem?
