### ISSUE TITLE
Music not importing from Dropboxes when Normalize option is Active (2.19.2 paravel)

### ISSUE THREAD

**Issue by djaaynik** [ElvishArtisan/rivendell#225]
I am trying to upgrade from 2.10.3 and i managed to install the cenOS 2.19.2 from paravel. I am having some issues with the Dropboxes, when i deactivate all the options it works fine (obviusly all the tracks are too loud).

**Comment by ElvishArtisan** [comment]
Works worrectly in 'master'.
