### ISSUE TITLE
REST service

### ISSUE THREAD

**Issue by betancour** [ElvishArtisan/rivendell#229]
Hi Fred, do you have plans for RESTFUL Services on Rivendell?
Possible to integrate with webapps for scheduling and billing... 

Regards

Yitzhak.

PD. I wrote on the maillist few days ago, but I don't know why my message is not on the list.

**Comment by ElvishArtisan** [comment]
On Sep 10, 2018, at 21:07, Yitzhak Solórzano <notifications@github.com> wrote:

> I wrote on the maillist few days ago, but I don't know why my message is not on the list.

What address did you subscribe from? I can check the subscription list here.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by betancour** [comment]
Fred. thanks for answering
it's the one on my profile...

**Comment by ElvishArtisan** [comment]
Closing. See discussion on 'rivendell-dev' for context.
