### ISSUE TITLE
Dropbox log (master)

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#234]
The dropbox log is no longer created. RDCatchd switched from launching RDImport with system() and redirecting the output to the log file to using QProcess.

**Comment by deltecent** [comment]
I'm thinking we change --log-mode to --log-path and change all occurrences if printf() to fprintf() and fopen() if a log path is specified.

**Comment by deltecent** [comment]
Submitted pull request.

**Comment by ElvishArtisan** [comment]
On Sep 17, 2018, at 15:11, Deltec Enterprises <notifications@github.com> wrote:
> I'm thinking we change --log-mode to --log-path and change all occurrences if printf() to fprintf() and fopen() if a log path is specified.
> 

Should we redesign this to use syslog(1)?

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by deltecent** [comment]
I had thought about that but was wondering about it being run for the command line. I submitted a pull request with fprintf as it retains the previous functionality. I’m not sure how much you want to deviate from version 2. I’m really enjoying roaming around Rivendell so I’ll code any way you suggest. 

Patrick
