### ISSUE TITLE
Macros - Play vs Segue

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#240]
I'm having a problem with macros. If I have the cart set to Play, when the macro runs, all carts playing before it stop. If I set it to Segue, the cart after the macro starts before the macro has run to completion. I am trying to find a way to run a macro that doesn't stop what's before it and what's after it doesn't start until the macro is done. Is this possible?

**Comment by ElvishArtisan** [comment]
On Sep 27, 2018, at 00:58, Deltec Enterprises <notifications@github.com> wrote:

> I'm having a problem with macros. If I have the cart set to Play, when the macro runs, all carts playing before it stop. If I set it to Segue, the cart after the macro starts before the macro has run to completion. I am trying to find a way to run a macro that doesn't stop what's before it and what's after it doesn't start until the macro is done. Is this possible?

Yes. Open the macro cart in rdlibrary and tick the ‘Execute Asynchronously’ check box.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by deltecent** [comment]
If it was a snake, it would have bit me.
