### ISSUE TITLE
(Master) RDLibrary "Remove Marker" does not remove the marker from the waveform

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#259]
When removing a marker using the "Remove Marker" button, the marker is not removed from the waveform.

**Comment by ElvishArtisan** [comment]
This going to involve a complete refactoring of the Edit Audio dialog. Scheduled for after the initial beta release.

**Comment by deltecent** [comment]
Uploaded PR to fix problem. #310

**Comment by ElvishArtisan** [comment]
Resolved in 1c424c6.
