### ISSUE TITLE
(Master/Stable) RDDBMgr Modify Failure from 275 to 297

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#261]
I have a 275 database that I'm upgrading to 297 with ```rddbmgr --modify``` in the current master branch.

I have a clock with 2 lines, both with a start time of 00:00. I'm not sure how that happened, but it is there.

```
MariaDB [Rivendell]> select * from MAVTRIKs_Test_Clock_CLK;
+----+------------+------------+--------+
| ID | EVENT_NAME | START_TIME | LENGTH |
+----+------------+------------+--------+
|  1 | GPower     |          0 |      0 |
|  2 | LEGAL ID   |          0 |      0 |
+----+------------+------------+--------+
2 rows in set (0.00 sec)
```

When RDDBMgr tries to convert this table to ```CLOCK_LINES```, it fails with:

```
rddbmgr: sql error: Duplicate entry 'MAVTRIKs Test Clock-0' for key 'CLOCK_NAME_START_TIME_IDX' QMYSQL: Unable to execute query query: insert into CLOCK_LINES set CLOCK_NAME="MAVTRIKs Test Clock",EVENT_NAME="LEGAL ID",START_TIME=0,LENGTH=0
```
This is due to the fact that ```CLOCK_LINES``` indexes off ```CLOCK_NAME_START_TIME_IDX (CLOCK_NAME,START_TIME)```

Since I have this condition, I'm wondering if others also have this condition and if RDDBMgr should check for this and somehow fix it so people don't end up with a partially-updated database?

**Comment by deltecent** [comment]
I'll also mess around with RDLogManager and insure that it doesn't allow more than one event with the same START_TIME.

**Comment by ElvishArtisan** [comment]
On Oct 17, 2018, at 02:27, Deltec Enterprises <notifications@github.com> wrote:
> Since I have this condition, I'm wondering if others also have this condition and if RDDBMgr should check for this and somehow fix it so people don't end up with a partially-updated database?
> 

I suspect that it came about while you were hacking Rivendell code. That’s an occupational hazard of being a Rivendell hacker; and a *big* reason not to do so on production systems!

We can certainly write a check for it, but what should we _do_ if we find this? Randomly pick a record to delete? Delete all but the record with the lowest ID value? Something else?

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by deltecent** [comment]
I don’t think that’s what happened. I exported a database from out 2.19.2 (or maybe it’s 2.19.1)  production systems and imported it directly into master. There wasn’t any manipulation on the database other than rddbmgr.

**Comment by ElvishArtisan** [comment]
*** HACK ALERT *** HACK ALERT ***
I've back ported a check into schema update 291 that looks for duplicate START_TIME values and **removes** all such except the one with the lowest ID value while writing an obnoxious warning to STDERR about the fact [master ebe2869, lines 7694 - 7734 of 'utils/rddbmgr/updateschema.cpp'].

Patrick: Do we need to add the ability for rddbconfig(8) to display such warnings when doing a schema update?

**Comment by deltecent** [comment]
What rddbconfig does is display stderr if the exit code != 0. I can change this to also show stderr as an informational message rather than an error if the exit code is 0.

**Comment by ElvishArtisan** [comment]
If it's just warnings, rddbmgr(8) will still return exit code '0', as the final result was 'successful' (a modified DB in this case). Regardless, anything written to STDERR should be displayed to the user. (See <a href="http://doc.qt.io/archives/qt-4.8/qprocess.html#readAllStandardError">```QProcess::readAllStandardError()```</a> for an easy way to do this).
