### ISSUE TITLE
(Master) Segue changes when dragging a cart from RDLibrary to RDAirplay

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#270]
When dragging a cart into RDAirplay from RDLibrary, it displays the segue as "Play". As soon as the log updates the segue of the drug cart changes from "Play" to "Segue". Rivendel 2.19 would set the segue to the default set it RDAdmin. Should the current 2.19 behavior be retained in 3.0?

**Comment by ElvishArtisan** [comment]
On Oct 22, 2018, at 15:38, Deltec Enterprises <notifications@github.com> wrote:

> When dragging a cart into RDAirplay from RDLibrary, it displays the segue as "Play". As soon as the log updates the segue of the drug cart changes from "Play" to "Segue". Rivendel 2.19 would set the segue to the default set it RDAdmin. Should the current 2.19 behavior be retained in 3.0?

Yes, it should. I swatted that in ‘stable’ [see commit ffcfd45]. I still need to forward-port it to ‘master’.

The joys of maintaining two branches in parallel…

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by ElvishArtisan** [comment]
Fixed in 'master'.
