### ISSUE TITLE
(Master Install) 999999_001.wav missing from /var/snd

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#271]
I just did an install of ```rivendell-3.0.0alpha00-1.x86_64.rpm``` using a modified ```install_rivendell.sh``` (basically calls ```yum localinstall /home/patrick/rivendell-3.0.0alpha00-1.x86_64.rpm```) and the ```999999_001.wav``` is not in ```/var/snd```. I don't know where that file comes from.

**Comment by ElvishArtisan** [comment]
See branch 'rd3' of repo 'rivendell-install'. This was fixed in commit 8e302eb, by adding the statment:
```
rddbmgr --create --generate-audio
```
