### ISSUE TITLE
RDAirplay Crashes After Move Cart To End Of Log

### ISSUE THREAD

**Issue by RichStivers** [ElvishArtisan/rivendell#287]
In the Main Log display of RDAirplay if a move cart to 'end of log' is attempted, RDAirplay crashes. This happens most of the time but not always.

**Comment by ElvishArtisan** [comment]
What version of Rivendell is this?

**Comment by RichStivers** [comment]
This behavior still happens in v2.19.3 but not as often.

**Comment by ElvishArtisan** [comment]
Fixed in [master 25d0f41].
