### ISSUE TITLE
Cannot upgrade database from version 283 (2.19.3) to 298 (3.0.0-a3)

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#309]
When working to perform an upgrade from Rivendell 2.19.3 database version 283 to Rivendell 3.0.0-a3 database version 298 the following errors are encountered:

invalid SQL or failed DB connection[Can't DROP 'CARD0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD0
invalid SQL or failed DB connection[Can't DROP 'PORT0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT0
invalid SQL or failed DB connection[Can't DROP 'START_RML0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML0
invalid SQL or failed DB connection[Can't DROP 'STOP_RML0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML0
invalid SQL or failed DB connection[Can't DROP 'CARD1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD1
invalid SQL or failed DB connection[Can't DROP 'PORT1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT1
invalid SQL or failed DB connection[Can't DROP 'START_RML1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML1
invalid SQL or failed DB connection[Can't DROP 'STOP_RML1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML1
invalid SQL or failed DB connection[Can't DROP 'CARD2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD2
invalid SQL or failed DB connection[Can't DROP 'PORT2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT2
invalid SQL or failed DB connection[Can't DROP 'START_RML2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML2
invalid SQL or failed DB connection[Can't DROP 'STOP_RML2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML2
invalid SQL or failed DB connection[Can't DROP 'CARD3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD3
invalid SQL or failed DB connection[Can't DROP 'PORT3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT3
invalid SQL or failed DB connection[Can't DROP 'START_RML3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML3
invalid SQL or failed DB connection[Can't DROP 'STOP_RML3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML3
invalid SQL or failed DB connection[Can't DROP 'CARD4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD4
invalid SQL or failed DB connection[Can't DROP 'PORT4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT4
invalid SQL or failed DB connection[Can't DROP 'START_RML4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML4
invalid SQL or failed DB connection[Can't DROP 'STOP_RML4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML4
invalid SQL or failed DB connection[Can't DROP 'CARD5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD5
invalid SQL or failed DB connection[Can't DROP 'PORT5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT5
invalid SQL or failed DB connection[Can't DROP 'START_RML5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML5
invalid SQL or failed DB connection[Can't DROP 'STOP_RML5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML5
invalid SQL or failed DB connection[Can't DROP 'CARD6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD6
invalid SQL or failed DB connection[Can't DROP 'PORT6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT6
invalid SQL or failed DB connection[Can't DROP 'START_RML6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML6
invalid SQL or failed DB connection[Can't DROP 'STOP_RML6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML6
invalid SQL or failed DB connection[Can't DROP 'CARD7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD7
invalid SQL or failed DB connection[Can't DROP 'PORT7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT7
invalid SQL or failed DB connection[Can't DROP 'START_RML7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML7
invalid SQL or failed DB connection[Can't DROP 'STOP_RML7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML7
invalid SQL or failed DB connection[Can't DROP 'CARD8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD8
invalid SQL or failed DB connection[Can't DROP 'PORT8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT8
invalid SQL or failed DB connection[Can't DROP 'START_RML8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML8
invalid SQL or failed DB connection[Can't DROP 'STOP_RML8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML8
invalid SQL or failed DB connection[Can't DROP 'CARD9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD9
invalid SQL or failed DB connection[Can't DROP 'PORT9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT9
invalid SQL or failed DB connection[Can't DROP 'START_RML9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML9
invalid SQL or failed DB connection[Can't DROP 'STOP_RML9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML9
DB connection re-established
invalid SQL or failed DB connection[Can't DROP 'OP_MODE'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column OP_MODE
rddbmgr: sql error: Can't DROP 'OP_MODE'; check that column/key exists QMYSQL: Unable to execute query query: alter table RDAIRPLAY drop column OP_MODE

The output is the result of rddbmgr --modify.

**Comment by ElvishArtisan** [comment]
Schema 283 is *not* correct for v2.19.x; it should be 275. 283 is an interrim schema, not tied to any public release number. See line 16887 of 'ChangeLog'.

What exactly is the provenance of this database? I suspect that the original schema is corrupt.

**Comment by WMTH** [comment]
Interestingly, on the source system running version 2.19.3 the database version is reported as 275 and is is clean according to rddbcheck on that system (and that system runs flawlessly).   That exact same database copied to the 3.0.0-a3 system claims to be version 283 according to the associated rddbmgr application.  Note that I have also tried an in-place upgrade on the 2.19.3 machine by simply compiling the new code and running rddbmgr --modify and see the same result (so I am not even copying the database to another system).  What am I missing?

**Comment by ElvishArtisan** [comment]
So something is going wrong with the backup/restore process then. Lets try again, using these command-line statements:

On the 'Source' system:
mysqldump -u rduser -pletmein Rivendell > rivendell_test.sql

Copy the file 'rivendell_test.sql' to the 'Test' system

On the 'Test' system:
echo drop\ database\ Rivendell\\; | mysql -u rduser -pletmein
echo create\ database\ Rivendell\\; | mysql -u rduser -pletmein
cat rivendell_test.sql | mysql -u rduser -pletmein Rivendell

Now do 'rddbadm'. What schema version does it report?

**Comment by WMTH** [comment]
It now reports version 275 however, I still cannot upgrade the database with the following output from rddbmgr --modify:

nvalid SQL or failed DB connection[Can't DROP 'CARD0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD0
invalid SQL or failed DB connection[Can't DROP 'PORT0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT0
invalid SQL or failed DB connection[Can't DROP 'START_RML0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML0
invalid SQL or failed DB connection[Can't DROP 'STOP_RML0'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML0
invalid SQL or failed DB connection[Can't DROP 'CARD1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD1
invalid SQL or failed DB connection[Can't DROP 'PORT1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT1
invalid SQL or failed DB connection[Can't DROP 'START_RML1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML1
invalid SQL or failed DB connection[Can't DROP 'STOP_RML1'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML1
invalid SQL or failed DB connection[Can't DROP 'CARD2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD2
invalid SQL or failed DB connection[Can't DROP 'PORT2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT2
invalid SQL or failed DB connection[Can't DROP 'START_RML2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML2
invalid SQL or failed DB connection[Can't DROP 'STOP_RML2'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML2
invalid SQL or failed DB connection[Can't DROP 'CARD3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD3
invalid SQL or failed DB connection[Can't DROP 'PORT3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT3
invalid SQL or failed DB connection[Can't DROP 'START_RML3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML3
invalid SQL or failed DB connection[Can't DROP 'STOP_RML3'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML3
invalid SQL or failed DB connection[Can't DROP 'CARD4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD4
invalid SQL or failed DB connection[Can't DROP 'PORT4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT4
invalid SQL or failed DB connection[Can't DROP 'START_RML4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML4
invalid SQL or failed DB connection[Can't DROP 'STOP_RML4'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML4
invalid SQL or failed DB connection[Can't DROP 'CARD5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD5
invalid SQL or failed DB connection[Can't DROP 'PORT5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT5
invalid SQL or failed DB connection[Can't DROP 'START_RML5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML5
invalid SQL or failed DB connection[Can't DROP 'STOP_RML5'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML5
invalid SQL or failed DB connection[Can't DROP 'CARD6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD6
invalid SQL or failed DB connection[Can't DROP 'PORT6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT6
invalid SQL or failed DB connection[Can't DROP 'START_RML6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML6
invalid SQL or failed DB connection[Can't DROP 'STOP_RML6'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML6
invalid SQL or failed DB connection[Can't DROP 'CARD7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD7
invalid SQL or failed DB connection[Can't DROP 'PORT7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT7
invalid SQL or failed DB connection[Can't DROP 'START_RML7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML7
invalid SQL or failed DB connection[Can't DROP 'STOP_RML7'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML7
invalid SQL or failed DB connection[Can't DROP 'CARD8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD8
invalid SQL or failed DB connection[Can't DROP 'PORT8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT8
invalid SQL or failed DB connection[Can't DROP 'START_RML8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML8
invalid SQL or failed DB connection[Can't DROP 'STOP_RML8'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML8
invalid SQL or failed DB connection[Can't DROP 'CARD9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column CARD9
invalid SQL or failed DB connection[Can't DROP 'PORT9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column PORT9
invalid SQL or failed DB connection[Can't DROP 'START_RML9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column START_RML9
invalid SQL or failed DB connection[Can't DROP 'STOP_RML9'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDAIRPLAY drop column STOP_RML9
DB connection re-established
invalid SQL or failed DB connection[Can't DROP 'INSTANCE'; check that column/key exists QMYSQL: Unable to execute query]: alter table RDPANEL drop column INSTANCE
rddbmgr: sql error: Can't DROP 'INSTANCE'; check that column/key exists QMYSQL: Unable to execute query query: alter table RDPANEL drop column INSTANCE

**Comment by ElvishArtisan** [comment]
Progress! So your previous backup/restore methodology *did* introduce corruption somehow!

WRT the SQL errors: I think we do in fact have a problem with the conversion code in rddbmgr(8). I'm working it right now. Stay tuned...

**Comment by WMTH** [comment]
More information:  I followed the set of procedures you provided and rddbmgr reported schema 275.  After running rddbmgr --modify or starting fresh and running rddbconfig the  result is schema version 283 with the errors I previously documented.  Also, I tried simply again copying the original source database from the 2.19.3 system without doing any conversion and it also reports schema 275 (I did not do that check prior to the original writing).  Again, once rddbmgr or rddbconfig is used to modify the database schema 283 is the result.

**Comment by ElvishArtisan** [comment]
I see what happened. If rddbmgr(8) exits with an error while doing a --modify, it will leave the schema of the DB schema version at that of the last successful change. Since the problem schema change was the one that implemented 283 => 284, that why you rddbmgr(8) reported 283.

I misunderstood your original report. I thought that rddbmgr(8) was reporting 283 after restoring the DB on the test system, but *before* rddbmgr(8) was run.

**Comment by ElvishArtisan** [comment]
I've just committed a change [master c1ba5c9] that should fix this. It will appear in the next alpha release.

**Comment by WMTH** [comment]
Thank you for the follow-up.
