### ISSUE TITLE
(3.1) RDAiplay config option to (not) show traffic import markers

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#321]
A user doesn't like seeing the cyan traffic import markers in the log and would like an option to enable or disable their display.

**Comment by deltecent** [comment]
I'm not clear if they dislike seeing the markers in general, or hate the Cyan color. Maybe as an alternative make their background white or a far less intrusive color.

**Comment by ElvishArtisan** [comment]
Oh, they hate the markers. I've been getting _lots_ of feedback about it from various channels. :)

I think that the correct path forward will be to add an option to disable generating them, which will also disable to the ability to relink music/traffic data. I'm working up a change to implement such right now.

**Comment by ElvishArtisan** [comment]
Implemented in [master a9a3f38].
