### ISSUE TITLE
RDAirplay and RDPanel clarification

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#327]
To me, the documentation implies that if you select "S-1" in RDAirplay you will see the same carts if you select "S-1" in RDPanel because RD:

> rdpanel(1) application is merely a larger version of the Sound Panel portion of rdairplay(1).

My 2.19.2 system seems to have two sets of panels, one for RDAirplay and one for RDPanel (selecting "S-1" on RDAirplay shows different carts than "S-1" on RDPanel).

Do RDAirplay and RDPanel each have their own System and User panels or are they supposed to be the same?

**Comment by ElvishArtisan** [comment]
They are different, and cannot be the same due to the fact that the panel dimensions are different [5x5 in rdairplay vs. 9x7 in rdpanel(1)].

**Comment by deltecent** [comment]
Fixed in PR #328
