### ISSUE TITLE
CentOS 7.6 breaks axiad service

### ISSUE THREAD

**Issue by atgossard** [ElvishArtisan/rivendell#331]
Running 2.19.3 system on CentOS 7.5. Did yum upgrade to CentOS 7.6 now axiad service fails. Here is relevant portion of /var/log/messages: 
Dec  4 23:03:34 rdhost axiad: external/ 
Dec  4 23:03:34 rdhost axiad: external/lwko/ 
Dec  4 23:03:34 rdhost axiad: external/lwko/axialivewire.c 
Dec  4 23:03:34 rdhost axiad: external/lwko/axialivewire.mod.c 
Dec  4 23:03:34 rdhost axiad: external/lwko/axia.h 
Dec  4 23:03:34 rdhost axiad: external/lwko/axia_net.h 
Dec  4 23:03:34 rdhost axiad: external/lwko/Makefile 
Dec  4 23:03:34 rdhost axiad: axia-alsa/ 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/ 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/axia.c 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/axia_net.c 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/snd-axia.mod.c 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/axia_frame.h 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/axia_net.h 
Dec  4 23:03:34 rdhost axiad: axia-alsa/drv/Makefile 
Dec  4 23:03:34 rdhost axiad: make -C /lib/modules/3.10.0-957.1.3.el7.x86_64/build SUBDIRS=/tmp/axia-alsa/axia-alsa/drv modules 
Dec  4 23:03:35 rdhost axiad: make[1]: Entering directory '/usr/src/kernels/3.10.0-957.1.3.el7.x86_64' 
Dec  4 23:03:35 rdhost axiad: CC [M]  /tmp/axia-alsa/axia-alsa/drv/axia.o 
Dec  4 23:03:36 rdhost axiad: In file included from include/linux/module.h:17:0, 
Dec  4 23:03:36 rdhost axiad: from /tmp/axia-alsa/axia-alsa/drv/axia.c:21: 
Dec  4 23:03:36 rdhost axiad: /tmp/axia-alsa/axia-alsa/drv/axia.c: In function ‘__check_enable’: 
Dec  4 23:03:36 rdhost axiad: include/linux/moduleparam.h:338:45: warning: return from incompatible pointer type [enabled by default] 
Dec  4 23:03:36 rdhost axiad: static inline type *__check_##name(void) { return(p); } 
Dec  4 23:03:36 rdhost axiad: ^ 
Dec  4 23:03:36 rdhost axiad: include/linux/moduleparam.h:389:35: note: in expansion of macro ‘__param_check’ 
Dec  4 23:03:36 rdhost axiad: #define param_check_bool(name, p) __param_check(name, p, bool) 
Dec  4 23:03:36 rdhost axiad: ^ 
Dec  4 23:03:36 rdhost axiad: include/linux/moduleparam.h:430:2: note: in expansion of macro ‘param_check_bool’ 
Dec  4 23:03:36 rdhost axiad: param_check_##type(name, &(array)[0]);    \ 
Dec  4 23:03:36 rdhost axiad: ^ 
Dec  4 23:03:36 rdhost axiad: include/linux/moduleparam.h:416:2: note: in expansion of macro ‘module_param_array_named’ 
Dec  4 23:03:36 rdhost axiad: module_param_array_named(name, name, type, nump, perm) 
Dec  4 23:03:36 rdhost axiad: ^ 
Dec  4 23:03:36 rdhost axiad: /tmp/axia-alsa/axia-alsa/drv/axia.c:174:1: note: in expansion of macro ‘module_param_array’ 
Dec  4 23:03:36 rdhost axiad: module_param_array(enable, bool, BOOT_DEVS, 0444); 
Dec  4 23:03:36 rdhost axiad: ^ 
Dec  4 23:03:36 rdhost axiad: /tmp/axia-alsa/axia-alsa/drv/axia.c: In function ‘snd_card_axia_probe’: 
Dec  4 23:03:36 rdhost axiad: /tmp/axia-alsa/axia-alsa/drv/axia.c:852:2: error: implicit declaration of function ‘snd_card_create’ [-Werror=implicit-function-declaration] 
Dec  4 23:03:36 rdhost axiad: err = snd_card_create(index[dev], id[dev], THIS_MODULE, sizeof(struct snd_card_axia), &card); 
Dec  4 23:03:36 rdhost axiad: ^ 
Dec  4 23:03:36 rdhost axiad: cc1: some warnings being treated as errors 
Dec  4 23:03:36 rdhost axiad: make[2]: *** [/tmp/axia-alsa/axia-alsa/drv/axia.o] Error 1 
Dec  4 23:03:36 rdhost axiad: make[1]: *** [_module_/tmp/axia-alsa/axia-alsa/drv] Error 2 
Dec  4 23:03:36 rdhost axiad: make[1]: Leaving directory '/usr/src/kernels/3.10.0-957.1.3.el7.x86_64' 
Dec  4 23:03:36 rdhost axiad: make: *** [all] Error 2 
Dec  4 23:03:36 rdhost axiad: mkdir -p /lib/modules/3.10.0-957.1.3.el7.x86_64/kernel/sound/drivers 
Dec  4 23:03:36 rdhost axiad: cp snd-axia.ko /lib/modules/3.10.0-957.1.3.el7.x86_64/kernel/sound/drivers/snd-axia.ko 
Dec  4 23:03:36 rdhost axiad: cp: cannot stat ‘snd-axia.ko’: No such file or directory 
Dec  4 23:03:36 rdhost axiad: make: *** [install] Error 1 
Dec  4 23:03:36 rdhost axiad: modprobe: FATAL: Module snd-axia not found. 
Dec  4 23:03:36 rdhost axiad: Starting LiveWire Audio Driver ... done. 
Dec  4 23:03:36 rdhost systemd: axiad.service: control process exited, code=exited status=1 
Dec  4 23:03:36 rdhost systemd: Unit axiad.service entered failed state. 
Dec  4 23:03:36 rdhost systemd: axiad.service failed.

**Comment by ElvishArtisan** [comment]
This has nothing to do with the Rivendell project. If you need help with the Livewire driver, please e-mail support@paravelsystems.com.
