### ISSUE TITLE
(Master) RDStereoMeter Input and Output Difference

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#338]
I have encountered an issue and I do not know if it is a problem or not.

If I record a test tone in the voice tracker, during recording, the RDStereoMeter shows a level of 0. When I play back what was just recorded, the meter shows -5. This happens on a system with a Delta 44 card and another with an ASI card.

Shouldn't the playback level match the recorded level?

**Comment by ElvishArtisan** [comment]
Fixed in [master d71a22b].
