### ISSUE TITLE
(3.x) Add Generic Configuration Table

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#339]
Add a generic configuration table to the Rivendell database to be used by third-party apps. Since the table is generic, developers could use it without requiring a database schema change. A ```RDAppConfig``` class could be made for manipulating the table.

FIELD NAME | TYPE | REMARKS
---------- | ---- | -------
ID | int(10) unsigned | Primary key
APP_NAME | varchar(30) | Name of the Application
CONFIG_NAME | varchar(30) | Stores the name of the configuration item
CONFIG_BOOL | tinyint(1) | Stores a Boolean
CONFIG_INT | int(11) | Stores an Integer
CONFIG_TEXT | varchar(1024) | Stores Text
CONFIG_DATE | date | Stores a Date
CONFIG_TIME | time | Stores a Time
CONFIG_DATETIME | datetime | Stores a Date/Time

**Comment by ElvishArtisan** [comment]
Wouldn't a better approach for most apps be to use a separate database? That would effectively give each apps its own private namespace which it could manage as it sees fit.

**Comment by deltecent** [comment]
I was leaning towards ease of installation where an app w/should "just work" on a running Rivendell system. The app writer would not have to create databases and/or tables or worry about SQL permissions and the like.

**Comment by ElvishArtisan** [comment]
I'm not sure that this generic table approach would be adequate for many situations. Suppose, for example, the app author needs _two_ string fields per record? How would multiple apps coexist on the same system?

**Comment by deltecent** [comment]
The idea is for basic configuration of an app, not for storing lots of information. Each record has an application name, so that keeps different apps from colliding with each other. If someone needs to store two strings, they store two records. Each record has a unique pair of application and name, so if your app is "myapp" you'd store your two strings as APP_NAME='myapp' and CONFIG_NAME='string1' and CONFIG_NAME='string2'.

I'm not a fan of an entire database schema update because 1 setting was added to app.

I'm throwing this out there as an idea and appreciate your feedback. If it doesn't fit the Rivendell way of doing things, that's fine too.

**Comment by ElvishArtisan** [comment]
I'm primarily concerned about orthogonality here. Ideally, _nothing_ should be interacting directly with a Rivendell DB except Rivendell itself. This is why we have public APIs. 

If a third-party application needs a  SQL database, it should manage that itself. That way, it has its own namespace.
