### ISSUE TITLE
(Master 3.0) Add error logging to RDAudioConvert

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#342]
I spent an hour tracking down an ```RDAudioConvert::ErrorInternal``` error while importing a large M4A file. ```RDAudioConvert::ErrorInternal``` is not very helpful.

The problem turned out to be not enough space on ```/tmp``` for the large file.

Logging of errors needs to be added to ```RDAudioCovert``` so when something fails the actual reason is placed in the log rather than "rdxport.cgi: something went wrong".

I will submit a PR for this shortly.

**Comment by ElvishArtisan** [comment]
That whole transcoder subsystem needs an overhaul. The biggest issue is that the pipelines are batch-based (as you discovered when /tmp filled up). Let's put it on the dance card for post 3.0 release!

**Comment by deltecent** [comment]
I have a PR almost ready to go.

**Comment by deltecent** [comment]
Fixed in PR #347
