### ISSUE TITLE
(3.x Feature) Ability to disable artist separation

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#349]
When wanting to run carts with the same artist it should be possible to disable artist separation in the scheduler.

**Comment by deltecent** [comment]
Does anyone know why title separation is set for a specific event, but artist separation is done on an entire clock?

**Comment by deltecent** [comment]
Submitted in PR #381

**Comment by ElvishArtisan** [comment]
Done in 33ecab7.
