### ISSUE TITLE
Incorrect path in rddbconfig-root and rdalsaconfig-root

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#351]
In version 3 alpha and beta00 versions, the configuration tools RDAlsaConfig and RDDBConfig will not function because the path in /etc/security/console.apps/rdalsaconfig-root and rddbconfig-root have an incorrect program path of /usr/bin/<executable>.  For the versions built from source utilizing the default installation prefix, the path should be /usr/local/bin/<executable>.

**Comment by ElvishArtisan** [comment]
Fixed in [master 6e45c0b]. Thanks.
