### ISSUE TITLE
(v3.0.0beta00) PyPAD %i not sending Cut Description

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#354]
The Rivendell documentation says ```%i``` should be the Cut Description. This doesn't seem to work.

**Comment by ElvishArtisan** [comment]
Not work where? Can you provide an example?

**Comment by deltecent** [comment]
I think I know what I was doing... sorry. I probably shouldn't open these until I'm 100% sure it's a problem. Sometimes when I "see something that doesn't look right" I open an issue because I don't have a local place to keep track of stuff but I don't want to forget about it. I was working on something and running through the PyPAD API source to figure out how to do something. I think I was confused by:

```FIELD_DESCRIPTION='description'```
```
    def serviceDescription(self):
        """
           Returns the description of the service associated with this update
           (string).
        """
        return self.__fields['padUpdate']['service']['description']
```
``` string=self.__replaceWildcardPair('i','description',string,esc)```
``` pad_field - The specific field. Valid values are:
pypad.FIELD_DESCRIPTION - The 'Description' field (string)
```

It was confusing which "description" everything was referring to, since there's a service and cut description.

I would recommend that we change ```FIELD_DESCRIPTION='description'``` to ```FIELD_CUT_DESCRIPTION='cutDescription'``` to match ```cutNumber```.

Or close this out an remind me to "try before you pry".

**Comment by ElvishArtisan** [comment]
In the interest of API compactness, let's leave ```pypad.FIELD_DESCRIPTION``` alone, as it's clear from the larger context that it applies to a ```.pypad.TYPE_NOW``` or ```pypad.TYPE_NEXT``` update structure. However, I've just updated the PyDOC strings for both ```pypad.Receiver::serviceName()``` and '''padpad.Receiver::padField()``` to caution against confusing the two [master 568fedd].
