### ISSUE TITLE
(3.x Feature) RML to send Now/Next based on cart number

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#356]
I created a group named "PYPAD" with update now/next checked and created some empty macro carts. The purpose of these carts is to update Now/Next PAD data with Artist and Title of the macro cart. I don't want any macros run.

When the macro is run the PAD data sent is not the PAD data of the macro cart. The PAD data of the running cart that segued into the macro is sent.

I tried setting the macro to asynchronous in which case no PAD data is sent.

![screen shot 2019-01-19 at 11 18 33 am](https://user-images.githubusercontent.com/24786756/51431314-06a8ed80-1bdc-11e9-8edd-2d2b0f11dc41.png)

I'm looking for a way to generate Now/Next PAD data (to be sent over RDS) without an audio cart.

**Comment by deltecent** [comment]
I think what is happening is the macro cart is firing and being removed from the event log prior to the PAD data being sent, so what gets sent is the current running event and then a "blank" now/next. I put a "SP 2000!" into the macro which caused the PAD data to be sent correctly, but it also pauses the event log for 2 seconds, which isn't what I want.

I'm not up to speed on how PAD data is generated in ```RDAirplay```, so this is based on observation of ```/var/log/messages```.

How about a ```PY``` macro to generate PyPAD data?

**Comment by ElvishArtisan** [comment]
I'm not seeing this behavior here. The update from the empty macro cart is generated as expected (although it is followed immediately by the update from the subsequent event, which may make the macro cart's data effectively invisible in many contexts).

As for the proposed 'PY' RML: I fear it would run into truncation problems due to the fact that RML uses UDP for transport, which imposes a 1500 byte/RML payload limit on most networks. We could extend the 'Set Default Now & Next Cart' ['SN'] RML concept by providing an RML that would send an update based on some specified cart, but I think your original approach is much cleaner, assuming that it can be made to work.

**Comment by deltecent** [comment]
I didn't think I was seeing the behavior you are seeing. There isn't much now/next logging. But, if it is working as you suggest, which is more than likely the case, then my problem is with my PyPAD script which needs to address back-to-back updates.

I do like the idea of an RML for sending Now & Next based on a cart number.

**Comment by deltecent** [comment]
Here's some log output of what I'm seeing with macros and now/next:
```
Jan 26 19:53:59 rdhost pypad_xcmd.py[21557]: Connecting to 192.168.99.3:8823
Jan 26 19:53:59 rdhost pypad_xcmd.py[21557]: XCMD=<rds><item><dest>7</dest><text><short>MY99.7</short> <artist>Bruno Mars</artist> <title>Count On Me</title></text></item></rds>
Jan 26 19:53:59 rdhost pypad_xcmd.py[21557]: Closing connection
Jan 26 19:53:59 rdhost pypad_tunein.py[8994]: Updating TuneIn: artist=Bruno Mars title=Count On Me album=
Jan 26 19:53:59 rdhost pypad_icecast2.py[9023]: Updating audio.deltecent.com: song=Bruno Mars - Count On Me
Jan 26 19:54:50 rdhost rdairplay: started macro cart: Line: 583  Cart: 50506
Jan 26 19:54:50 rdhost caed: LoadPlayback  Card: 0  Stream: 0  Name: /var/snd/010956_001.wav  Handle: 73
Jan 26 19:54:50 rdhost rdairplay: started audio cart: Line: 584  Cart: 10956  Cut: 1 Pos: 0  Card: 0  Stream: 0  Port: 1
Jan 26 19:54:50 rdhost caed: PlaybackPosition - Card: 0  Stream: 0  Pos: 240  Handle: 73
Jan 26 19:54:50 rdhost caed: Play - 1
Jan 26 19:54:50 rdhost caed: Play - Card: 0  Stream: 0  Handle: 73  Length: 202826  Speed: 100000  Pitch: 0
Jan 26 19:54:50 rdhost ripcd: received rml: 'LB Commercial Free Music!' from 192.168.99.30
Jan 26 19:54:50 rdhost pypad_icecast2.py[9023]: Updating audio.deltecent.com: song=Bruno Mars - Count On Me
Jan 26 19:54:50 rdhost pypad_tunein.py[8994]: Updating TuneIn: artist=Bruno Mars title=Count On Me album=
Jan 26 19:54:50 rdhost pypad_xcmd.py[21557]: Connecting to 192.168.99.3:8823
Jan 26 19:54:50 rdhost pypad_xcmd.py[21557]: XCMD=<rds><item><dest>7</dest><text><short>MY99.7</short> <artist>Bruno Mars</artist> <title>Count On Me</title></text></item></rds>
Jan 26 19:54:50 rdhost pypad_xcmd.py[21557]: Closing connection
Jan 26 19:54:50 rdhost pypad_icecast2.py[9023]: Updating audio.deltecent.com: song=Lovelytheband - Broken
Jan 26 19:54:50 rdhost pypad_tunein.py[8994]: Updating TuneIn: artist=Lovelytheband title=Broken album=
Jan 26 19:54:54 rdhost caed: StopPlayback - Card: 0  Stream: 1  Handle: 72
Jan 26 19:54:54 rdhost rdairplay: finished event: Line: 582  Cart: 11186  Cut: 1 Card: 0  Stream: 1  Port: 0
Jan 26 19:54:54 rdhost caed: StopPlayback - Card: 0  Stream: 1  Handle: 72
Jan 26 19:54:54 rdhost caed: UnloadPlayback - Card: 0  Stream: 1  Handle: 72
Jan 26 19:54:55 rdhost pypad_xcmd.py[21557]: Connecting to 192.168.99.3:8823
Jan 26 19:54:55 rdhost pypad_xcmd.py[21557]: XCMD=<rds><item><dest>7</dest><text><short>MY99.7</short> <artist>Lovelytheband</artist> <title>Broken</title></text></item></rds>
Jan 26 19:54:55 rdhost pypad_xcmd.py[21557]: Closing connection
```
The Event Log was:
```
Bruno Mars - Count on Me
Macro - LB Commercial Free Music!
Lovelytheband - Broken
```
The PyPAD data I received was:
```
Bruno Mars - Count on Me
Bruno Mars - Count on Me
Lovelytheband - Broken
```
The Macro cart never showed up.

**Comment by deltecent** [comment]
A macro length is generated based on the number of commands in the macro. If a macro has no commands, the length will be 0, and the macro's metadata won't be sent because the end time won't be ```>``` the current cart. And even for a length to work, the ```Use Event Length...``` checkbox needs to be set.

If Fred agrees with this, I'll update the documentation. I don't think the ```Use Event Length...``` option is documented at all.

**Comment by ElvishArtisan** [comment]
Not if that event is going to end before a previously playing event. Otherwise, you are going to wind up with a 'gap' in the PAD (each event can only originate a PAD update _once_, when it's started).

This is one of those 'three pounds of flax' situations where, whatever you do, there are times where it's not going to be optimum. In this case, we've plumped on the side of handling the more common scenario where it's the longer-form material (such as a song) whose PAD you want to persist for the duration, rather than that of the short stinger that you've dropped in on top of it.

**Comment by deltecent** [comment]
Yes, this is probably one of those "you can't please everyone" scenarios. I would prefer it the other way, where "now" means "what just fired off now" and "next" means "what will fire off next", not "you're getting new pad data because something in the event log changed, but we're not sending you the change."

I have not looked if the "next" data is what I'm expecting the "now" data to be or if the macro is skipped all together.

**Comment by deltecent** [comment]
I'm wondering, since the "Use Event Length for Now and Next Updates" doesn't seem to be used anywhere, change it to mean to send the macro's PAD data regardless of when the previous event(s) end (basically how I want the PAD data sent). Change it to something like "Always Send Now and Next".
