### ISSUE TITLE
3.0.0beta00 - PyPAD Config Dialog too tall

### ISSUE THREAD

**Issue by pabsungenis** [ElvishArtisan/rivendell#360]
![img_1515](https://user-images.githubusercontent.com/11683026/51689145-10f42e80-1fc4-11e9-81c4-0fde570a3c9d.JPG)
I'm using an older monitor, which fits the output from RDAirPlay perfectly at default resolution.

On this screen, the configuration dialog for PyPAD instances is too tall. The OK and Cancel buttons are below the bottom of the visible screen, and there is no way to resize the dialog to get access to them.

**Comment by deltecent** [comment]
Submitted with PR #362

**Comment by ElvishArtisan** [comment]
Fixed in 0b39a665.
