### ISSUE TITLE
(3.x Issue) Copying and Pasting cuts does not preserve "No Fade on Segue Out"

### ISSUE THREAD

**Issue by electricurrent** [ElvishArtisan/rivendell#366]
I noticed this when copying cuts from one cart to another, the segue markers all moved over ok but the checkbox for "No Fade on Segue Out" would return to the default of unchecked.

**Comment by deltecent** [comment]
Fixed in PR #367

**Comment by ElvishArtisan** [comment]
Fixed in [master 75bab16].
