### ISSUE TITLE
(v3.0.0beta00) Make PyPAD API database functions public?

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#369]
Thoughts of giving PyPAD scripts access to the following functions similar to RDApplication:
```
    def __getDbCredentials(self):
        config=configparser.ConfigParser()
        config.readfp(open('/etc/rd.conf'))
        return (config.get('mySQL','Loginname'),config.get('mySQL','Password'),
                config.get('mySQL','Hostname'),config.get('mySQL','Database'))

    def __openDb(self):
        creds=self.__getDbCredentials()
        return MySQLdb.connect(creds[2],creds[0],creds[1],creds[3])
```
If a PyPAD scripts wants to access the Rivendell database, it doesn't have to reinvent the wheel.

**Comment by ElvishArtisan** [comment]
I'm strongly disinclined to allow this. We really don't want third-party applications mucking around in the DB. Remember, the schema is _not_ stable across Rivendell versions, and a misbehaving application could fatally corrupt the whole thing. (This, BTW, is the major problem with having a central binary 'registry' in Windows; it's not uncommon for a single buggy or malicious application to corrupt that registry to the point where a complete re-install of the OS becomes necessary).

Thus, we have public APIs in Rivendell. These are carefully regulated 'gateways' for data into and out of the system, the terms of which are kept stable across Rivendell versions and which include error and sanity checks on all incoming data.

I'm curious: What are you wanting to do that would require DB access?

**Comment by deltecent** [comment]
It is possible to use the PyPAD interface for uses other than sending now/next data to a device or file. For example, Rivendell does not have a "talk" segue type that will find a cut that will fit over the talk time of the next event (like a voicetrack). When a PyPAD script is notified, it can look at the next event and determine if something should be played over the talk time. If so, locate a proper cut in the database and send a "play next" RML.

Based on now/next data a PyPAD script could scan through the next 5 log events and make decisions, whatever that may be.

Another idea I have is to see if a voice track was actually recorded, and if not, replace it with a bumper.

All of these require access to the database.

I understand your point about people directly accessing the database. I'm wondering if it would be worthwhile to create a python library that would provide this basic functionality. I do recall there being some RLM helper functions.

**Comment by ElvishArtisan** [comment]
Most of this can be done already via the web API --e.g. accessing Library and log data. It has been a major item on my ToDo list to do a Python binding for that for some time. However, I don't want to hold up the 3.0 release for it.

**Comment by deltecent** [comment]
>Most of this can be done already via the web API --e.g. accessing Library and log data.

I didn't think the web API provided notification of event changes in the log machines like PyPAD does. The way PyPAD distributes that information via UDP is brilliant. It got my mind thinking of a lot of applications or Rivendell extensions beyond now/next that could be done in PyPAD rather than an entirely new macro language that we've spoken about before. Maybe what we need is to add the ability to receive PAD updates and send RML to the web API and yes, a Python binding to the web API would be fantastic! I also agree that we should address this after the release of 3.0.

I also want to thank you for addressing issues here. I myself, and I'm sure others, appreciate being able to post issues here and get your feedback on how to best approach the issue or just put it in the trash bin.
