### ISSUE TITLE
(v3.0.0beta00) Field 'INSTANCE' doesn't have a default value

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#373]
> On new install Rivendell v3.0.0Beta
> 
> invalid SQL or failed DB connection[Field 'INSTANCE' doesn't have a default value QMYSQL: Unable to execute query]: insert into RDLIBRARY set STATION="ciampap"
> QSqlQuery::value: not positioned on a valid record
> 
> rdlibrary_conf.cpp fails on line 42 because Field 'INSTANCE' doesn't have a default value.
> 
> sql=QString("insert into RDLIBRARY set ")+"STATION=\""+RDEscapeString(lib_station)+"\"";
> 
> Also rdstation.cpp fails on line 975 because Field 'INSTANCE' doesn't have a default value.
>
> Platform is Ubuntu 18.04
> mysql  Ver 14.14 Distrib 5.7.25,
>
>I also needed to add ALTER privilege to my rduser mysql account to complete setup

I don't see that ```RDLIBRARY.INSTANCE``` is used anywhere. It probably should have a default or be removed.

**Comment by deltecent** [comment]
> Sorry my bad.   Mysql 5.7 uses Strict Mode.  Affects many parts of rivendell.
> 
> edited   /etc/mysql/mysql.conf.d/mysqld.cnf   and appended
> 
> sql-mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
> 
> Walter

**Comment by ElvishArtisan** [comment]
Resolved in [master 7ac41a0].
