### ISSUE TITLE
RDImport CartChunk CutID Question

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#378]
Not knowing exactly how CartChunk CutID works, would ```--title-from-cartchunk-cutid``` be mutually exclusive with ```--use-cartchunk-cutid```?

```
      --title-from-cartchunk-cutid
           Set the cart title from CartChunk CutID.
       --use-cartchunk-cutid
           Import the audio into the cart specified by the CartChunk CutID parameter associated with
           the file. If the cart does not exist, it will be created. Use of this option is mutually exclusive
           with --to-cart.
```

**Comment by ElvishArtisan** [comment]
The CutID is an arbitrary string in the CartChunk schema, the semantic content of which is not really spelled out in the standard. These options are envisioning two basic possible use cases: where a valid cart number can be presumed to exist, or some arbitrary string that would be more appropriate as a Title field than the native CartChunk Title. While it seems unlikely that one would want _both_ options active simultaneously, it's not patently invalid to do so. (Assuming that the CutID contained cart numbers, you'd wind up with a set of carts whose Title would be the cart number).
