### ISSUE TITLE
Problem builing QT MySQL driver

### ISSUE THREAD

**Issue by PeterPancorbo** [ElvishArtisan/rivendell#386]
Hi! 

I'm having some issues trying to build MySQL driver according to [this guide](http://wiki.rivendellaudio.org/index.php/UbuntuXenial#Test_thoroughly_before_use_in_Production) 

When I trigger "Make install" for:
`cd /usr/local/qt3/plugins/src/sqldrivers/mysql
qmake -o Makefile "INCLUDEPATH+=/usr/include/mysql" mysql.pro
`

Displayed error shows like: 

> root@xxxx:/usr/local/qt3/plugins/src/sqldrivers/mysql# make install
> cp -f "../../../sqldrivers/libqsqlmysql.so" "../../../sqldrivers/libqsqlmysql.so"
> cp: '../../../sqldrivers/libqsqlmysql.so' y '../../../sqldrivers/libqsqlmysql.so' son el mismo fichero
> Makefile:140: fallo en las instrucciones para el objetivo 'install_target'
> make: [install_target] Error 1 (no tiene efecto)
> strip --strip-unneeded "../../../sqldrivers/libqsqlmysql.so"

Thanks for your help!

PP

**Comment by ElvishArtisan** [comment]
Not (strictly speaking) a Rivendell issue. I'm afraid that I have virtually zero experience working with Ubuntu.

You may have better results asking on Rivendell-dev. I know several folks that run Rivendell on Ubuntu hang out there.
