### ISSUE TITLE
Remote Macro Execution (CC) Not Working in Beta

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#387]
I looks like parameters for a CC macro are not getting passed in the new 3.0 beta.  The receiving end gets the macro, but not any parameters with it.

Macro on Sending End:
CC 172.31.52.249 RN /usr/local/bin/testme.pl ARG1!

Receiving End:
09/03/2019 - 11:36:53.734 : received rml: 'CC !' from 172.31.4.84

**Comment by ElvishArtisan** [comment]
Fixed in [master 9dfdd87].
