### ISSUE TITLE
Update the Documentation (2.19.3 - RML Command PX)

### ISSUE THREAD

**Issue by djaaynik** [ElvishArtisan/rivendell#390]
The new PX "INSERT CART" rml command should look like this (figured it out by trying every combination):  PX 2 00000 0 segue! 
This sample should load the "00000" cart in aux immediately in first row in segue transition. I've used the PX command to load promo cart's in a certain hour by programming the macro on rdcatch. It would be easier if there was a command to load an entire log (so it would act like a logchain but without deleting everything that's after the same log, it would just fill the autogenerated log with manual edited logs). I hope I've explained myself, if you have any questions feel free to comment below!

**Comment by ElvishArtisan** [comment]
Already [documented as such](http://opsguide.rivendellaudio.org/html/sect.rml.commands.html#sect.rml.insert_cart__px_) in the v3.x Ops Guide.

> It would be easier if there was a command to load an entire log (so it would act like a logchain but 
> without deleting everything that's after the same log, it would just fill the autogenerated log with 
> manual edited logs).

There are the [Load Log](http://opsguide.rivendellaudio.org/html/sect.rml.commands.html#sect.rml.load_log__ll_) and [Append Log](http://opsguide.rivendellaudio.org/html/sect.rml.commands.html#sect.rml.append_log__al_) commands, although it sounds like what you're describing would be something like a (currently non-existent) &quot;Insert Log&quot; RML.

**Comment by djaaynik** [comment]
Thank you very much! I've been using rivendell for 5 years now and the guide i was referring was the "rog". There are some other common issues I've been encountering for a long time but I've never wrote here. When generating a log  from day to day I've seen that the artist separation doesn't affect different clocks so even if i have 100 tracks in my music collection, it often generates two same carts in consecutive clock's.

**Comment by deltecent** [comment]
I have not seen where/how artist separation wouldn't cross clock boundaries, though each clock has its own setting. The scheduler doesn't pay attention to clocks. It just sees a sequence of events. Rivendell 3 moves artist separation from clocks to events, the same as title separation. You will also have the ability to disable both artist and title separation for an event.

The only way I know to get a violation of artist/title separation is if there aren't enough carts left to choose from after excluding separation matches. I don't think there's any way of knowing this is happening when running the scheduler from cron.

I wonder if we should add a notification center to send important messages to that will appear on the screen.

Patrick

**Comment by djaaynik** [comment]
In my example: i have set a schedulare code ("hits") in my Music group and i have set an artist/title separation long enough to not repeat any song in a whole 24h grid. My event's pik a song from "music" with must have code "hits". I've encountered that usually I'll have the same song every monday morning at the same time (btw the song database has something around 10000 individual songs, so i have something Around 10000 carts in my music group). 
I'm willing to test the rivendell 3 but not on this database.
