### ISSUE TITLE
[v3.0.0rc00] rdservice does not start after upgrade from [v3.0.0beta]

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#391]
After upgrade from 3.00beta to 3.00 rc0 through source compilation, services don't start.  

rd@rdbeta5:/usr/local/sbin$ rdservice -d
rdservice: unable to open database [Rivendell service is not active.]

rddbmgr performed update and reports this version:
root@rdbeta5:/usr/local/src/rivendell-3.0.0beta00# rddbmgr 
Rivendell database, schema 307 [v3.0.x]

**Comment by ElvishArtisan** [comment]
Fixed in [master a7cfb26].
