### ISSUE TITLE
[v3.0.0beta] rdimport --set-daypart-times not working

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#392]
When attempting an import, the following error occurs:

rdimport: unknown command option "--set-daypart-times"

**Comment by bpm1992** [comment]
Problem identified at line 246 of utils/rdimport/rdimport.cpp

There is an extraneous \n in the command parse string.  

if(rda->cmdSwitch()->key(i)=="--set-daypart-times\n") {

**Comment by deltecent** [comment]
That was probably me. I'll have a PR uploaded shortly.

**Comment by deltecent** [comment]
Fixed in PR #393
