### ISSUE TITLE
V3.0 Install Problems

### ISSUE THREAD

**Issue by rewstuff** [ElvishArtisan/rivendell#404]
Hello,
I've followed the instructions very carefully and attempted the install on 3 different systems, all exceeding the minimal specs.
Centos 7 installs fine and Rivendell install appears to run (using the standalone) with lots of commands and no apparent errors, but after I am done, I cannot find Rivendell on the system anywhere. Daemons are not running and rdairplay, library, etc are not to be found.
import/export directories are created and the ROG and First steps are on the desktop.
Any suggestions?
Thanks,
Bert

**Comment by julienweiss** [comment]
I have a similar issue. 

I try to add a new client in an existing rivendell system. 

Everything is fine until iI try to run Rivendell on new client. 

He can't start daemons. 

I even try to install in stand alone and it doesn't work too. 

---
Julien WEISS 

Responsable technique et pédagogique 

Radiocampus Orléans 

4 rue de Tours 

"le Cône" 

45100 Orleans 

0238691742 

Le 2019-04-25 03:35, rewstuff a écrit :

> Hello,
> I've followed the instructions very carefully and attempted the install on 3 different systems, all exceeding the minimal specs.
> Centos 7 installs fine and Rivendell install appears to run (using the standalone) with lots of commands and no apparent errors, but after I am done, I cannot find Rivendell on the system anywhere. Daemons are not running and rdairplay, library, etc are not to be found.
> import/export directories are created and the ROG and First steps are on the desktop.
> Any suggestions?
> Thanks,
> Bert 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/ElvishArtisan/rivendell/issues/404
[2]

**Comment by ElvishArtisan** [comment]
Ok, let's tackle the standalone-install problem. Joining a workstation to an existing setup involves other steps that we will ignore for purposes of this discussion.

julienweiss, what do you get after entering the following commands at a shell prompt?

     cat /etc/redhat-release

     rpm -qa | grep rivendell

**Comment by rewstuff** [comment]
Hello,
This is what I get when I run the commands:

[root@rd3 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
[root@rd3 ~]# rpm -qa | grep rivendell
[root@rd3 ~]# 

I tried an install on yet another machine with the same result. Cannot find Rivendell program anywhere.
Any help would be great.
-Bert

**Comment by ElvishArtisan** [comment]
> This is what I get when I run the commands:
>
> [root@rd3 ~]# cat /etc/redhat-release
> CentOS Linux release 7.6.1810 (Core)
> [root@rd3 ~]# rpm -qa | grep rivendell
> [root@rd3 ~]#

Thanks.

Looks like you don't have the Rivendell RPM packages installed at all. Are you attempting an installation from source by any chance?

**Comment by rewstuff** [comment]
Hi,
I am following the exact directions found here:
http://static.paravelsystems.com/rivendell-install-rd3/rivendell-install-rhel7.html
-Bert

**Comment by ElvishArtisan** [comment]
'Kay, I see what's happened. A bunch of Python dependencies have vanished from EPEL.

Stand by...

**Comment by pulsemgm** [comment]
I followed the instructions from the paravel site and same as above, when i open yum extender and type in rivendell, it shows that it never installed the 3.0 rc because of of 2 errors

"Dependeny resolution errors:

Package: Rivendell-pyad 3.0 0rc00-1.x86_64 (paravel-rivendell3_test)
    requires: Python34-mysql
Package: Rivendell-pyad 3.0 0rc00-1.x86_64 (paravel-rivendell3_test)
    requires: Python34-curl"



> 'Kay, I see what's happened. A bunch of Python dependencies have vanished from EPEL.
> 
> Stand by...

**Comment by ElvishArtisan** [comment]
Updated the dependencies to use Python 3.6 and released v3.0.0rc01. Installations work again!

**Comment by rewstuff** [comment]
It is working for me also, THANKS!
-Bert

**Comment by RadioisLife** [comment]
I'm not having any success installing version 3 of Rivendell with CentOS7 on a new build. I get the following error message after typing in 
 yum -y install wget

wget http://download.paravelsystems.com/CentOS/7/Paravel-Broadcast.repo -P /etc/yum.repos.d/

wget http://download.paravelsystems.com/CentOS/7/RPM-GPG-KEY-Paravel-Broadcast -P /etc/pki/rpm-gpg

yum -y install rivendell-install 
Message comes back saying No http://download.paravelsystems.com/CentOS/7/Paravel-Broadcast.repo -P /etc/yum.repos.d/ package available.
- Vicky

**Comment by druidlabs** [comment]
The error message suggests that the first line (yum install) is
concatenated with the second line (wget http...).  So the "yum install"
command is trying to install wget, wget again, then the http string.

Each of the commands shown in the install guide needs to be done
individually.

Regards,
Mike

**Comment by RadioisLife** [comment]
Mike,
                Thank You so much. It doesn’t quite spell that out in the instructions but someone like me with minimal computer experience should have tripped over that branch. I really appreciate your time and feedback.
                Now that I have successfully installed Rivendell V3.0, Thanks to you, I’ve got clocks to make, carts to build and a library to fill 😊

Thank You, again, Vicky

Vicky Gill | Supervisor | Weiler Abrasives Group | P 570-595-7495 ext. 1489 | F 570-595-5965 | vgill@weilerabrasives.com<mailto:vgill@weilerabrasives.com> | weilerabrasives.com<http://www.weilerabrasives.com/>
[cid:image001.png@01D618DA.98B0D070]<https://www.weilerabrasives.com/tigerzirc>
[cid:image002.png@01D618DA.98B0D070]<https://www.weilerabrasives.com/coronavirus>

**Comment by druidlabs** [comment]
You're welcome, and glad you've got it running.  If you have a Facebook
presence you may find it useful to join the "Rivendell Open Source
Automation Users" group there.  They are focused more on how to use
Rivendell, whereas Github and the related mailing list is more about the
technical guts of the software.  It's a private group, so you'll need to
request membership.

https://www.facebook.com/groups/1739406449620107/

**Comment by RadioisLife** [comment]
Thank You  Mike, I'll join that group!
Really appreciate your help!

Vicky

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
