### ISSUE TITLE
RDLibrary(1) "Show Note Bubbles" doesn't work

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#406]
The "Show Note Bubbles" checkbox in rdlibrary(1) isn't implemented. It should be removed and replaced with a right-click menu that will show Notes, Scheduler Codes, and quick access to the change Scheduler Code dialog.

**Comment by ElvishArtisan** [comment]
The Right-Click menu sounds like a good idea. However, we have to be sure to maintain access to the notes in a touchscreen-friendly way as well.

**Comment by ElvishArtisan** [comment]
Unable to reproduce the problem in current 'master'.

**Comment by deltecent** [comment]
You're correct. I was looking at the the wrong thing.
