### ISSUE TITLE
Save log can be very slow

### ISSUE THREAD

**Issue by albanpeignier** [ElvishArtisan/rivendell#41]
With a large log and a network database, the `RDLogEvent::save()` method can take about one minute.

The `save` method inserts every log event with a dedicated SQL request (`SaveLine` method). Even if each request can be fast (about 30 / 60 ms), the whole operation can be (too) long.

Some benchmark with a log of 720 events (2 minutes per event on a day) : 
 
With a local mysql :

    720 SaveLine: 22604 ms

With a remote mysql : 

    720 SaveLine: 50162 ms
    ...
    720 SaveLine: 49580 ms

This slowness is very annoying in the VoiceTrack editor.

**Comment by ElvishArtisan** [comment]
Fixed in Github-stable.
