### ISSUE TITLE
RDadmin issue

### ISSUE THREAD

**Issue by pulsemgm** [ElvishArtisan/rivendell#411]
When starting rdadmin, i'm getting the following

"Database version mismatch, should be 308, is 0"

**Comment by ElvishArtisan** [comment]
We'll need a lot more information. At a minimum:

1) Distro name and version

2) Rivendell version

3) How Rivendell was install (from source, CentOS installation script, something else?)

4) Was this a new installation, or an upgrade?

**Comment by pulsemgm** [comment]
1. Centos 7

2. using the lastest Release candidate for 3.0

3. using both the script from the praravel site and a pdf file on setting up to stream online that was posted to the rivendell facebook group.

4. new install

**Comment by ElvishArtisan** [comment]
> using the lastest Release candidate for 3.0

Which 'lastest Release candidate for 3.0'? (They were *all* of them 'the latest' at some point in their lifecycle). You can get this information by doing ```rpm -q rivendell``` at a command line.

> using both the script from the praravel site and a pdf file on setting up to stream online that was posted to the rivendell facebook group.

Please try again, with time _without_ the steps from the 'pdf file'.

**Comment by pulsemgm** [comment]
the release candidate that fixed the mysql issue with the missing pythn files you uploaded yesterday.

tried to uninstall then re-install and same error, looks like i;m back to re-installing centos and starting from scratch

i;m trying to set up rivendell and jack to stream to a ince server, which is why i was goig by the odf file, which uses mint linux (probably well outdated i think.)
