### ISSUE TITLE
Matching Carts and Limit Search

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#420]
From the "_Be careful what you wish for_" department: with the recent addition of the most welcome "Matching Carts" in RDLibrary (Thanks Patrick!), "Show Only First 100 Matches" enabled, no filter constraints and all dropdown menus set to "ALL", I see only 97 carts. One of my low-numbered carts has four Cuts which _may_ account for the difference (the code is a bit too dense for me to unravel).

Entering a Filter string that includes that multi-cut cart as well as other carts (single-cut) or any other search constraint, the Matching Carts count is correct.

Any idea why **Matching Carts** is set to 97 on launching RDLibrary?

**Comment by ElvishArtisan** [comment]
> One of my low-numbered carts has four Cuts which may account for the difference (the code is a bit too dense for me to unravel).

Yes, that is exactly what is going on. The label on that checkbox is somewhat misleading; what is actually being limited is the size of the result set being returned by a SQL call. Since that call includes a JOIN to the 'CUTS' table, the result will include a row for each cut.

**Comment by deltecent** [comment]
Was the intent of the 100 cart limit to reduce the amount of rows returned from the query, reduce the number of rows displayed in RDLibrary, or both?

If it was just to reduce the number of displayed rows, we can query all matches and limit in RDLibrary rather than in the query.

**Comment by dklann** [comment]
As a user, my view of the 100 cart limit is to reduce the number of displayed rows in order for _Use Realtime Filtering_ to be as responsive as possible; typing text in the _Filter_ field in RDLibrary with _Show Only First 100 Matches_ checked improves the "refine as you type" search.

**Comment by ElvishArtisan** [comment]
Perhaps we should modify the label to make it clearly? Something like "Show No More than 100 Matches"?

**Comment by deltecent** [comment]
I think I can fix this so that 100 matches means 100 carts as the way it is now is probably broke.

Let's say you had 95 total carts, 94 with 1 cut each and the 95th with 20 cuts. If you selected to show no more than 100 matches it would only show 5 of the 20 cuts for the last cart. The left join, which messes up the intention of the "limit", is only used to validate cuts and set the proper background color. This was done before we listed cuts in a tree. I believe that the join can be removed from ```RefreshList()``` and do the validation colors in ```RefreshCuts()``` making the limit count always return the correct number of carts regardless of cuts.

I'll push a PR and see what everyone thinks.

**Comment by deltecent** [comment]
There's also another issue. Unlike cuts, a cart can only display a single color code. What color code should a cart display if each cut has a different playability status? Should it only display a color, such as red, if there aren't any playable cuts?

**Comment by deltecent** [comment]
@dklann Give PR #435 a shot.

**Comment by ElvishArtisan** [comment]
On Mon, 2019-05-27 at 14:36 -0700, Deltec Enterprises wrote:
> There's also another issue. Unlike cuts, a cart can only display a
> single color code. What color code should a cart display if each cut
> has a different playability status? Should it only display a color,
> such as red, if there aren't any playable cuts?

It should indicate the behavior that would result if it were played in
a log --e.g. if even one non-evergreen cut is playable, then so the
cart itself (white). If only the evergreen cut is playable, then
(green). If *nothing* is playable, then (red).

**Comment by ElvishArtisan** [comment]
Fixed in #435.
