### ISSUE TITLE
Scheduler Code dropdown blank/disabled after selecting any group other ALL

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#423]
In RDLogEdit, when selecting a cart for insertion into a log, if you select a Group other than ALL, then the Scheduler Code dropdown in subsequent insert requests is disabled and shows blanks.   You must restart RDLogEdit to get the Scheduler Code list back. Occurs in 3.0.0rc02 and in 2.19.3.

Here's the simplest way to demonstrate. 
1. Start RDLogEdit.
2. Add a log.
3. On Edit Log, insert Cart at end of log.
4. On Edit Log Entry, leave fields empty, click Select.
5. On Select Cart, change Group to anything other than ALL. Note the Scheduler Code is ALL.
6. Click Cancel, then Cancel again to return to the main Edit Log screen.
7. Repeat the insert/select steps. Note that the Scheduler Code is blank, and remains blank no matter what Group you select. 
8. Restart RDLogEdit and note the problem is cleared.

**Comment by deltecent** [comment]
Fixed in #424
