### ISSUE TITLE
Rivendell v3.0.0rc02 Shell Command in Macro

### ISSUE THREAD

**Issue by HughStolmer** [ElvishArtisan/rivendell#426]
Hi Folks,
I cannot get a shell command to work from a macro (i.e. to create a new log using rdlogmanager).
I have 2 Rivendell systems side-by-side, one v2.17, one v3.00. Same macro on both, v2.17 creates a log, v3.00 does not. RDCATCH running the same macro also fails.
However running the command (i.e. copy and paste the command part of the same macro) from the terminal (not even logged in as root), it successfully generates a log.
Did the RN command change in v3.00?
Thanks,
Hugh

**Comment by ElvishArtisan** [comment]
> Did the RN command change in v3.00?

It did! Specifically, it is now possible to specify the user/group under which ```RN``` will run commands.
From the sample rd.conf(5) file:
```
; These entries are used to define the system user and group that commands
; executed by the 'Run Shell Command' ['RN'] RML will run under.
RnRmlOwner=rivendell
RnRmlGroup=rivendell
```
