### ISSUE TITLE
RDSoftKeys window is tiny, contents not visible

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#427]
On a newly created 3.0.0rc02 system, the RDSoftKeys window shows as a tiny box. It can be moved around the desktop.  Although it shows resizing handles, they don't do anything. This happens whether RDSoftKeys is run from the Rivendell menu or from a command line, 

Our station doesn't use this. It's something I came across while kicking the tires of a 3.0.0rc02 appliance installation.

**Comment by druidlabs** [comment]
Forgot to mention this is an appliance installed system.

**Comment by deltecent** [comment]
```RDSoftKeys``` attempts to set the window size based on the number of SoftKeys defined in ```rd.conf``` or the specified map file. If there aren't any SoftKeys defined, the window size is small.

I'm going to submit a PR that specifies a minimum window size and a message that no SoftKeys have been defined.

**Comment by deltecent** [comment]
Fixed in PR #429
