### ISSUE TITLE
Issue with RMLSend font size?

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#430]
Edit: This is on an appliance install for 3.0.0rc02.

This might be by design. If not, it's definitely just a nitpick.  The RMLSend display uses a different font size for field labels (Helvetica, 10) than other commands such as RDLogin (Helvetica, 12). The values for the choice pull-down boxes are also different sizes (Username vs. Dest).

Perhaps a better fix is to abstract the font definitions by use ("label", "value", "choice") into a common function, header, etc. and use those when creating displays. That would be a long term project I imagine.

**Comment by deltecent** [comment]
Fixed in #432

**Comment by druidlabs** [comment]
> Fixed in #432

Dude! Kickin' 'em out big time.  Thanks.
