### ISSUE TITLE
RDGpiMon date selector doesn't increase/decrease date

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#431]
On a new system created from the 3.0.0rc02 appliance install, the RDGpiMon display has these problems:
* The Date: entry box overlaps the State: field label.
* The up/down arrows on the Date: entry box don't do anything.
* Clicking in the Date: entry box changes the displayed date to "019". You can enter digits, but only three are ever displayed at a time.

Possibly it's caused by there being no GPI definitions or events?

**Comment by deltecent** [comment]
Fixed in #433
