### ISSUE TITLE
--End of Clock-- hour marker appears at top of new clock listing

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#441]
does not allow events to be scheduled before the end of clock

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by deltecent** [comment]
I believe the macro editor had this same problem. If I recall, it has to do with a custom ListView class and sorting.

**Comment by ElvishArtisan** [comment]
Fixed in [master 65cf9d3].
