### ISSUE TITLE
Ripcd crashes minutes after startup (v3.xx)

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#444]
On rc02 and rc01 (not the alpha release), ripcd will crash upon startup of the daemons using rdservice.

When you run "ripcd -d" from a command line, all functions well.

**Comment by ElvishArtisan** [comment]
Unable to reproduce the problem here. System is RedSleeve 7.5 on a Raspberry Pi 3B+/

**Comment by bpm1992** [comment]
I am experiencing the same with Intel as well.  Centos 7 x64.  I'll watch the debug logs and see if anything sticks out.

**Comment by ElvishArtisan** [comment]
Thanks. We'll hold this open pending further feedback.

**Comment by bpm1992** [comment]
I've been able to recreate the issue on both Intel and on ARM.  The issue seems to be related to an RML macro when ripcd is started through rdservice vs. "ripcd -d".

Here is a dump of the log from the startup sequence that kills ripcd:
Sep 29 12:25:17 rdbeta5 rdairplay: user changed to 'bmcglynn'
Sep 29 12:25:24 rdbeta5 ripcd: received rml: "SR 2 1 1!" from 127.0.0.1

Here is a dump of the log from the startup sequence when it works from ripcd being run from the command line:
Sep 29 12:25:56 rdbeta5 rdairplay: user changed to 'bmcglynn'
Sep 29 12:26:03 rdbeta5 ripcd: received rml: "SR 2 1 1!" from 127.0.0.1
Sep 29 12:26:03 rdbeta5 ripcd: received rml: "LL 1 2019_09_29_LAC 496!" from 127.0.0.1
Sep 29 12:26:09 rdbeta5 rdairplay: loaded log '2019_09_29_LAC' in Main Log

The issue seems to be associated with the LL macro.

**Comment by bpm1992** [comment]
Resolved.  The issue is that the service for systemd needs to have some specific parameters.  There was a SEGV that was causing the daemons to crash.  This can be resolved by adding these to /etc/systemd/system/rivendell.service

```
LimitRTPRIO=99
LimitNOFILE=65536
LimitMEMLOCK=infinity
LimitNICE=-19
```
