### ISSUE TITLE
.wav derived cut playback

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#447]
After changes posted 06-05-19, certain cuts imported from .wav files now playback very hot.  Adjusting the cut gain (in either direction) has no effect on playback level.  This behaviour is not reflected in cuts imported from .mp3 files.

**Comment by ElvishArtisan** [comment]
Please post a sample WAV file, along with precise instructions on how to produce the problem.

**Comment by WMTH** [comment]
Process:
1. Load cut into RDairplay
2. Start cut
3. Observe VU meters peaking to the lower edge of the red area
4. Stop cut
5. Delete fro RDairplay
6. Edit cut in RDlibrary
7. Reduce cut gain by any amount i.e. -10dB
8. Save cut
9. Load and play cut in RDairplay
10. Note no effect in playback level

This behavior only occurs with certain cuts imported from .wav files; .mp3 imports function normally from a playback level and cut gain adjustment standpoint.  

The files are too large to upload even individually.

Note I tried re-importing with no change in bad behavior.  Again, this just behavior began after compiling the  06-05-2019 changes (rolled back to the 05-31-2019 code and the files play normally).

**Comment by ElvishArtisan** [comment]
Thanks.

Please test again, using current 'master' [5f32385].

**Comment by WMTH** [comment]
Current 'master' [5f32385] addresses the issue, the cuts now play at the expected level.
