### ISSUE TITLE
RDLog::linkStatus() return value

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#448]
When a log is linked but nothing in the log is actually linked (for example, there aren't any links in the log), ```LOG.MUSIC_LINK``` is set to 'Y' and ```LOG.MUSIC_LINKS``` is set to 0.

When ```RDLog::linkState()``` is called, it returns false if ```LOG.MUSIC_LINKS``` is 0 even if ```LOG.MUSIC_LINK is 'Y'```.

Should ```RDLog::linkState``` check the quantity or just ```LOG.MUSIC_LINK```, should ```LOG.MUSIC_LINK``` not be set to 'Y' if nothing was merged, or should it remain like it is? If nothing is linked, but a link was run, should ```RDLog::linkState``` return true?

I think ```RDLog::linkState()``` should return based on ```LOG.MUSIC_LINK``` regardless of how many lines were merged.

```
+-----------------+--------------+-------------+
| NAME            | MUSIC_LINKED | MUSIC_LINKS |
+-----------------+--------------+-------------+
| My997-0618      | Y            |           0 |
+-----------------+--------------+-------------+
```
The above will cause ```RDLog::linkState()``` to return false.

```
bool RDSvc::linkLog(RDSvc::ImportSource src,const QDate &date,
                    const QString &logname,QString *report,RDUser *user,
                    QString *err_msg)
{

  //
  // Update the Log Link Status
  //
  log->setLinkState(link_src,true);
  if(link_src==RDLog::SourceMusic) {
    log->updateLinkQuantity(RDLog::SourceTraffic);
  }
}
```
```
RDLog::LinkState RDLog::linkState(RDLog::Source src) const
{
  if(linkQuantity(src)==0) {
    return RDLog::LinkNotPresent;
  }
  switch(src) {
      case RDLog::SourceMusic:
        return (RDLog::LinkState)RDBool(GetStringValue("MUSIC_LINKED"));

      case RDLog::SourceTraffic:
        return (RDLog::LinkState)RDBool(GetStringValue("TRAFFIC_LINKED"));
  }
  return RDLog::LinkNotPresent;
}
```

**Comment by ElvishArtisan** [comment]
These semantics are used in rdlogmanager(1)'s 'Generate Log' dialog to determine the correct state of the 'indicator lights' (red, green or white) and should not be changed. See the ```GenerateLog::UpdateControls()``` method.

**Comment by deltecent** [comment]
I'm using the same thing for MusicMaster merging. I was confused by seeing MUSIC_LINKED=='Y' but a red indicator light. I will use the current methodology.
