### ISSUE TITLE
(3.0.0rc02) VoiceTracker won't save/stop

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#449]
Load the voice tracker. Press "Start", "Record", "Start", "Save". When pressing "Save" it appears to stop recording but doesn't stop the cursor.

This seems to have broke somewhere between May 30 and June 13.

Can someone else confirm?

**Comment by deltecent** [comment]
I've confirmed this on a second system. My poor wife can't voice track.

**Comment by ElvishArtisan** [comment]
Confirmed here. Likely something to do with the big CAE rewrite a few weeks ago...

**Comment by WMTH** [comment]
Confirmed here as well.  Also, it was functioning prior to May 30.

**Comment by ElvishArtisan** [comment]
Confirmed that it is definitely a problem in ```caed(8)```. Introduced in c7b6322.

**Comment by ElvishArtisan** [comment]
Fixed in [master 5d7957e].
