### ISSUE TITLE
RDLogManager generate fails with "invalid SQL" when service name contains a period

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#45]
RDLogManager doesn't generate logs correctly if a service name with a period is selected, such as `Mike C.`. The symptom I had is that the generated log contained only the first event for each hour. Running rdlogmanager from the command line shows many database errors like this:

```
rdlogmanager: invalid SQL or failed DB connection
[SELECT command denied to user 'rduser'@'localhost' for table '_STACK' QMYSQL3: Unable to execute query]: 
SELECT SCHED_STACK_ID from Mike_C._STACK order by SCHED_STACK_ID
```

There are also failures for inserts into the same table.

RDCreateStackTableSql in /lib/rdcreate_log.cpp is transforming blanks but not periods. This function is called by GenerateLog::CreateData in rdlogmanager/generate_log.cpp, which is also transforming blanks but not periods.

**Comment by ElvishArtisan** [comment]
Fixed in v3.x.
