### ISSUE TITLE
[3.0.1] Create man(1) page for rdlogmanager

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#455]
Since rdlogmanager can also be run from the command line, it would be helpful if there was a man page describing its options.

**Comment by ElvishArtisan** [comment]
Not six hours even, and already a bug report! &lt;sigh&gt;.  :)

Agreed. There are some other modules --e.g. rdairplay(1)-- that could also use man pages of their own.

**Comment by deltecent** [comment]
Not a bug... just an enhancement. Someone posted a question on Facebook so I did a quick "man rdlogmanager" and lo and behold, nothing there. I had to dig into the source.

**Comment by ElvishArtisan** [comment]
Done in ba501b0 and 0ecf53b.
