### ISSUE TITLE
Macro cart entries turn RED after viewing in rdlibrary(1)

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#458]
Steps to reproduce:

1) Open up rdlibrary(1), untick 'Show Audio Carts'. 
2) Select a macro cart, click 'Edit'.
3) In the resulting 'Edit Cart' dialog, click 'OK'.
4) Click a different cart in the cart list.

The macro cart just viewed has been turned RED on the cart list.

**Comment by deltecent** [comment]
I'm sure that's me. I'll fix it.

**Comment by deltecent** [comment]
Fixed in #463
