### ISSUE TITLE
Audio playback issues with 3.0.1

### ISSUE THREAD

**Issue by hgshoggins** [ElvishArtisan/rivendell#462]
Upgrading machines from `2.19.3` to `3.0.1` from source.

Apart from the Rivendell version, no changes occurred on the machines in between, their configuration (NFS client mounts, software installs, etc.) have stayed still.

Here are the symptoms I now have:
* `caed` is correctly connected to JACK and with other inputs/outputs (I have tested with and without `root` user, discussion on mailing-list eventually lead to #459)
* on `rdairplay`, launching the "TEST TONE" in the panel is OK, several times, and then the app freezes
* on `rdairplay`, listening to the cue of a CART (double click on track then play) freezes
* launching `caed` in debug mode gives very little information, not sure if it's relevant:
```
$ caed -d
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM rd0
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM rd0
```
I seemed to recall that `caed -d` produces a lot more logging, especially some communication with MySQL, showing what it actually does.
To be able to have `caed` in debug mode and still have the apps not complain about the Rivendell services not being started, I first `systemct start rivendell.service`, then kill `caed`, then launch `caed -d`.
* on `rdlibrary`, when editing markers, hitting play works, audio is coming out, but **seeking to a specific position will stop the audio**, it's still possible to exit the modal window, but trying to open again the "Edit Markers" modal window will freeze `rdlibrary`
* application freeze **is not** a segfault or so: nothing prints out when launched _via_ `gdb`
* launching `caed` produces this logging in syslog:
```
caed: cae starting
caed: connected to JACK server
caed: Found TwoLAME encoder library, MPEG L2 encoding supported
caed: Found MAD decoder library, MPEG L2 decoding supported
caed: cae started
```
* note that when launched _via_ the regular `systemctl` call, `caed` also outputs
```
caed: unable to set realtime scheduling: Invalid argument
```
... don't know if it's of any use. I think it has to do with the `rtprio` setting, which is put to `99` for this user.
* there is no issue with the NFS storage on which `/var/snd` is mounted on each machine, however `rdmonitor` complains that the audio storage has failed. The unprivileged user has read and write access to this directory.

_(I have a third machine on which install was very difficult because it's fairly old and the Python version was bad, but this station, which also acts as the NFS server so it has `/var/snd` locally mounted, is correctly playing audio through its JACK server without issue. However it took me long to decide whether or not I would mention it in this issue because it's about all the other machines that can't work properly)_

Where should I start looking for debugging?

**Comment by deltecent** [comment]
> 	• on rdairplay, launching the "TEST TONE" in the panel is OK, several times, and then the app freezes
> 	• on rdairplay, listening to the cue of a CART (double click on track then play) freezes
> 	• on rdlibrary, when editing markers, hitting play works, audio is coming out, but seeking to a specific position will stop the audio, it's still possible to exit the modal window, but trying to open again the "Edit Markers" modal window will freeze rdlibrary

I cannot reproduce these symptoms using AudioScience 5611 card.

Patrick

**Comment by hgshoggins** [comment]
I'm not using AudioScience cards, they're RME ADAT cards, supported by ALSA through JACK. It's always worked like a charm with older releases of Rivendell.

**Comment by ElvishArtisan** [comment]
For debugging information, you will need to enable DEBUG priority messages in your syslog setup. For an RPM-based setup, you can do that as follows:

1) Open ‘/etc/rsyslog.d/rivendell.conf’ in a text editor, uncomment the last line and the save it back

2) Restart the syslog service by doing:

	```systemctl restart syslog```

The log files will then appear in ‘/var/log/rivendell/‘ (alongside the usual ‘operations’ log data).

For a source-based setup, depending on your distro you’ll likely need some additional configuration. You can find the syslog configuration (‘syslog.conf-sample’) as well as a sample configuration for logrotate(8) ('logrotate-sample’) in the ‘conf/‘ directory in the source tree. These are what is used by the RPM packages.

**Comment by ElvishArtisan** [comment]
Oh, and you'll also need to add the line:

    SyslogFacility=23

to the ```[Identity]``` section of rd.conf(5). Be sure to restart the Rivendell service after making the change.

**Comment by hgshoggins** [comment]
Should I do something else to increase the logging level? Now I get nice and clean logging directly inside `/var/log/rivendell/operations` (no other file is created under `/var/log/rivendell/`), but it contains nothing more than what the general purpose `/var/log/messages` had before the `rsyslog` change.

**Comment by hgshoggins** [comment]
I believe the: `caed: unable to set realtime scheduling: Invalid argument` issue while running the service _via_ `systemctl` is related to this: https://www.freedesktop.org/wiki/Software/systemd/MyServiceCantGetRealtime/

I have the feeling that I don't have to worry about that for the moment, for one because either way of running `caed` does not affect the behavior I'm confronted with, and that the RT priorities will be the cherry on the cake when my problem is solved.

**Comment by ElvishArtisan** [comment]
Check that you have uncommented the last line of the syslog config

```LOCAL7.DEBUG /var/log/rivendell/debug```

 and restarted the 'rsyslog' service.

Also, you can suppress the (now redundant) Rivendell messages in the system-wide syslog by finding the line:

```*info;mail.none;authpriv.none;cron.none    /var/log/messages```

and changing it to:

```*info;mail.none;authpriv.none;cron.none;local7.none    /var/log/messages```

A restart of the 'rsyslog' service will be needed afterwards.

**Comment by hgshoggins** [comment]
I should pay more attention, it was written all along.
Now I have debugging enabled in `/var/log/rivendell/debug`, yay!

Unfortunately, I'm afraid I don't have much to share.
Just now, I opened `rdlibrary`, and `/var/log/rivendell/debug` now contains a bunch of
```
caed: added connection 23
caed: removed connection 23
caed: added connection 23
caed: removed connection 23
caed: added connection 23
caed: removed connection 23
```

But when I select a CART, and click on "Edit Markers", all I get is a frozen `rdlibrary`, and this in the debug log:
```
caed: LoadPlayback  Card: 0  Stream: 0  Name: /var/snd/010034_001.wav  Handle: 0
caed: removed connection 28
```
... and that's it. No error or warning explaining why something stopped working.

Just so you know, I also had completely (or so I think) cleaned up the binaries from version `2.19.3` because I had noticed that binaries like `caed` or `ripcd` were now installed in `/usr/local/sbin` instead of `/usr/local/bin`, and the new install would not replace the old binaries and they would be picked up by the system because both `/usr/local/bin` and `/usr/local/sbin` are in `$PATH`. At first I though that would be the problem because that had happened to me in the past, it was `ripcd` that was still running a previous version and causing the system to get lost.

Well, now I'm stuck again.

**Comment by hgshoggins** [comment]
Second attempt with `rdlibrary`, I just killed the previous instance and launched a new one, and now clicking on "Edit Markers" shows the modal window, but clicking on "play" **does not** freeze `rdlibrary`, there is simply no audio, like when the file to play does not exist. But it does, and it's accessible.

**Comment by ElvishArtisan** [comment]
Mixing up elements of two different installations can definitely make weird things happen. I'd recommend completely uninstalling Rivendell 3, as follows (from a root shell):

```
cd [path-to-your-rivendell-source-tree]
systemctl stop rivendell
make uninstall
```

Then, try the following find(1) command to look for remnant bits of previous installs:

```find / -mount -name rd\* -print 2> /dev/null```

This will print a list of all files on your root filesystem that begin with 'rd'. If a file is part of Rivendell, delete it. **WARNING**: some of the files in that list may *not* be part of Rivendell! Don't touch those!

Then, go reinstall Rivendell 3 as before and see if anything changes.

**Comment by hgshoggins** [comment]
I had to make an emergency revert to `2.19.3` and the `make uninstall` method with all subsequent services stopped works like a charm.

In the meantime, I can't work on this issue as our whole system is back on `2.19.3`. I'll have a test setup soon to get back on that.
