### ISSUE TITLE
auto rdlogmanager ignoring day markers in crons to create logs

### ISSUE THREAD

**Issue by rogerdavis198** [ElvishArtisan/rivendell#464]
/usr/bin/rdlogmanager -g -s Production -d 9!

running this cron on 21/7/2019

give me
(all is doing is creating tomorrows log all the time, as tomorrow log is already there it just errors out as below, totally ignoring **-d 9!** command )

v 3.0.1 master

DB connection re-established
rdlogmanager: DB connection re-established
invalid SQL or failed DB connection[Duplicate entry '2019_07_22-378' for key 'LOG_NAME_IDX' QMYSQL: Unable to execute query]: insert into LOG_LINES set LOG_NAME="2019_07_22",LINE_ID=378,COUNT=378,TYPE=0,SOURCE=2,START_TIME=124000,GRACE_TIME=0,CART_NUMBER=120320,TIME_TYPE=0,POST_POINT="N",TRANS_TYPE=1,EXT_START_TIME="00:02:04",EVENT_LENGTH=176000
rdlogmanager: invalid SQL or failed DB connection[Duplicate entry '2019_07_22-378' for key 'LOG_NAME_IDX' QMYSQL: Unable to execute query]: insert into LOG_LINES set LOG_NAME="2019_07_22",LINE_ID=378,COUNT=378,TYPE=0,SOURCE=2,START_TIME=124000,GRACE_TIME=0,CART_NUMBER=120320,TIME_TYPE=0,POST_POINT="N",TRANS_TYPE=1,EXT_START_TIME="00:02:04",EVENT_LENGTH=176000
DB connection re-established
rdlogmanager: DB connection re-established
invalid SQL or failed DB connection[Duplicate entry '2019_07_22-382' for key 'LOG_NAME_IDX' QMYSQL: Unable to execute query]: insert into LOG_LINES set LOG_NAME="2019_07_22",LINE_ID=382,COUNT=382,TYPE=0,SOURCE=2,START_TIME=360000,GRACE_TIME=0,CART_NUMBER=85485,TIME_TYPE=0,POST_POINT="N",TRANS_TYPE=1,EXT_START_TIME="00:06:00",EVENT_LENGTH=120000
rdlogmanager: invalid SQL or failed DB connection[Duplicate entry '2019_07_22-382' for key 'LOG_NAME_IDX' QMYSQL: Unable to execute query]: insert into LOG_LINES set LOG_NAME="2019_07_22",LINE_ID=382,COUNT=382,TYPE=0,SOURCE=2,START_TIME=360000,GRACE_TIME=0,CART_NUMBER=85485,TIME_TYPE=0,POST_POINT="N",TRANS_TYPE=1,EXT_START_TIME="00:06:00",EVENT_LENGTH=120000
DB connection re-established

**Comment by ElvishArtisan** [comment]
Unable to reproduce this here.

This is smelling like DB corruption. Does running:

```rddbmgr --check --no```

turn up anything interesting?

**Comment by rogerdavis198** [comment]
database seem fine Fred, just install master with updates tonight and i still get

/usr/bin/rdlogmanager -g -s Production -d 31! ..

generate
Rivendell Log Exception Report
Generated at: 07/25/2019 - 00:56:18
Log: 2019_07_26
Effective Airdate: 07/26/2019

**Comment by ElvishArtisan** [comment]
Have you tried doing this for just a regular shell --i.e. not in a cron job?

**Comment by rogerdavis198** [comment]
Hi Fred,
Yes have tried user and root and all it ever does is makes a new log for tomorrow regardless of the day marker.

It was doing this  in r01 but using a cron or in terminal it worked fine, I just checked my test r03 and it's not working anymore via the cron anymore too but as I say r01 was working fine with cron but not via rdlibrary/rdcatch anymore.

If it's not showing your end I will make a new system at some point and install and test on that one.

⁣Get BlueMail for Android ​
