### ISSUE TITLE
radairplay log already opened (on localhost stand alone test system) 

### ISSUE THREAD

**Issue by rogerdavis198** [ElvishArtisan/rivendell#465]
Edit live log in rdairplay and we get

radairplay log already opened (on localhost stand alone test system) 

so can not save (rdlogedit is not running)

now open rdlogedit and do the same and it works fine. (In rdlogedit only)

v 3.0.1 master

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in [master 70c88ec].
