### ISSUE TITLE
RDalsaconfig enhancement

### ISSUE THREAD

**Issue by rogerdavis198** [ElvishArtisan/rivendell#466]
rdalsconfig is there any chance Fred will can add rate to the setting as unless you are running pro cards the audio cards will not work without these setting being adjust manually on every system, i have found 99 percent of audio cards will work by adding

pcm.rd0 {
  type hw
  card 0
  device 0
rate 44100
}
ctl.rd0 {
  type hw
  card 0
rate44100
}

Obviously 48000 if you are running that rate.

so any chance of adding a extra edit button in rdalsaconfig to edit the rate setting please.

been doing this on systems for years but be nice to be able to automate the process.

ps its worked on all linux systems and pi Fine so far.

**Comment by ElvishArtisan** [comment]
Implemented in c2e410f.

**Comment by rogerdavis198** [comment]
Thank you Fred

⁣Get BlueMail for Android ​
