### ISSUE TITLE
Jack not responding to JC or JD RML commands

### ISSUE THREAD

**Issue by michichan** [ElvishArtisan/rivendell#470]
An essential part of our operation utilizes the JC and JD RML commands to build and tear down connections in Jack.  This functionality works well in R2, but in R3, the JC and JD commands are not working.   Other RML commands are working but JC and JD are not. 

EXAMPLE:
When attempting from command line rmlsend:
[root@rd3 rd]# rmlsend JC\ system:playback_8\ rivendell_0:playout_4R\!
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
[root@rd3 rd]# 

Edited to add:
I am getting the Qt: message even on RML commands that are working, such as "PB" so apparently, the problem is with how RD3 is talking to Jack.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
> Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
[root@rd3 rd]#
>
> I am getting the Qt: message even on RML commands that are working, such as "PB" so apparently, the problem is with how RD3 is talking to Jack.

Yes, the session management errors are harmless, and have nothing to do with the RML issue.

**Comment by ElvishArtisan** [comment]
Fixed in [master 1462e75].
