### ISSUE TITLE
JC/JD command not working with multiple Glasscoder instances

### ISSUE THREAD

**Issue by michichan** [ElvishArtisan/rivendell#472]
For an installation running multiple instances of Stereo Tool and multiple instances of Glasscoder, the JC and JD will only allow for connections and disconnections with the first instance of Glasscoder.  

To test this, we built up three stereo tool instances:
stereo_tool
stereo_too2
stereo_too3

and three Glasscoder instances:
j1hits
j1gold
j1xtra

JC j1hits:input_1 stereo_too3:fm_l!  - WORKS
JC j1gold:input_1 stereo_too3:fm_l!  - DOESN'T WORK
JC j1xtra:input_1 stereo_too3:fm_l!  - DOESN'T WORK
after manually building a connection from stereo_too3:fm_l to j1xtra:input_1... 
JD j1xtra:input_1 stereo_too3:fm_l!  - DOESN'T WORK

Same results when using stereo_too2 and stereo_tool instances...  

![image](https://user-images.githubusercontent.com/7353746/62503218-3d81d200-b7c1-11e9-9406-1d8ceaabddce.png)

**Comment by ElvishArtisan** [comment]
Fixed in f834a58 and 37da80e.
