### ISSUE TITLE
Rivendell 3.0.3 Rip CD will not update data

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#473]
for some reason, Version 3.0.3 is not reading cd data...one particular example read infomation and song data from cd i in a double set, but failed to get date from cd2 in the same set.  Version 2 rivendell read both cd's easily, along with other cds that version 3 could not read....

**Comment by deltecent** [comment]
This should be fixed by PR #484 ... needs to be tested by @validmirror.

**Comment by ElvishArtisan** [comment]
Tested and confirmed working.
