### ISSUE TITLE
v 3.0.3 RdLogedit Voice Tracker

### ISSUE THREAD

**Issue by rogerdavis198** [ElvishArtisan/rivendell#474]
V303 under VT log only

Hard clock markers showing as 2323:59:58.0

instead of H23:59:58.0

so each hard maker has double hour digits

1010:59:58.0

instead of H10:59:58.0

etc etc

Normal Edit log shows as

T23:59:58

T10:59:58

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in ffe986f.
