### ISSUE TITLE
[3.0.3] Problem with RDAlsaConfig

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#479]
There are three sound cards in this machine. If I use RDAlsaConfig to configure all three, after closing and reopening RDAlsaConfig, the selected sound cards are displayed wrong.

![before](https://user-images.githubusercontent.com/24786756/63277480-44e1ba80-c25a-11e9-87c6-ea842891aef0.png)
![after](https://user-images.githubusercontent.com/24786756/63277492-490dd800-c25a-11e9-9e23-f8102695da0b.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in [master f6d220c].

I ended up completely rewriting rdalsaconfig(8) so as to use absolute ALSA device IDs rather than the ordinal numbers from ```/proc/asound/cards``` (which have shown a nasty habit of changing between reboots on some setups). The new UI will hopefully be a bit clearer to use as well.
