### ISSUE TITLE
v303 dropbox logs not working since 2.19.3

### ISSUE THREAD

**Issue by rogerdavis198** [ElvishArtisan/rivendell#481]
Hi the the links of dropbox folders ie local log you have added the link too

such as
/home/rd/dropboxLIST

is blank so its like a needle in a haystack to see which carts the Imports went into, also if import
does not go into the library for any reason there is no listing of any problems.

Cheers

**Comment by ElvishArtisan** [comment]
In 3.x, dropbox logs get sent to the syslog by default ('/var/log/rivendell/operations' on the standard CentOS setup). This is a change from the v2.x behavior.

That said, I'm tagging this as a bug, as there should be controls in the 'Dropbox Configuration' dialog in rdadmin(1) indicating this, as well as the ability to specify a seperate log file if desired.

**Comment by rogerdavis198** [comment]
Hi Fred Thanks for the feedback, The file 'operations' in /var/log/rivendell/ did not exist.
So I have made it, but still no data writing to that file, I have even 777 it also rd::rd and the rivendell  log folder too, on two systems and nothing at all where logs are concerned.

**Comment by rogerdavis198** [comment]
I am getting the logs ok under the full message output via root /var/log/messages
but not really the best place as they are mixed up with the whole machine log but atleast I can find some info of inports

Cheers

**Comment by ElvishArtisan** [comment]
Sounds like you need to configure your syslog setup. The way we do this in the CentOS appliance is to use the ```LOCAL7``` syslog facility (see the 'SyslogFacility=' directive in rd.conf(5)) and then drop an additional routing rule into rsyslog (see the snippet in 'conf/syslog.conf-sample' in the Rivendell sources). The CentOS appliance installer does all of this automatically.

**Comment by ElvishArtisan** [comment]
Just pushed a bunch of logging changes with ```rdimport(1)``` that should address this [master b9722a3].
