### ISSUE TITLE
3.0.3 RDLIBRARY Rip Disk Artist Album not working

### ISSUE THREAD

**Issue by 1opeti** [ElvishArtisan/rivendell#482]
Importing audio from CD's which are not listed in the world database means keying Title data for each track. Simple enough if the Artist and Album data entered in the panels at the top are written to the Carts enabling a rapid search. This is not working in our appliance install of 3.0.3 on CentOS 7.

**Comment by deltecent** [comment]
This should be fixed by PR #485. Needs confirmation testing.

**Comment by ElvishArtisan** [comment]
Tested and confirmed working.
