### ISSUE TITLE
RDLogManager (Bug)

### ISSUE THREAD

**Issue by kinghamr** [ElvishArtisan/rivendell#483]
RDLogManager isn't straightening out when you click on any of the top row events When trying to click on a column to organize by start, length, event or count it won't sort, but when you insert an event, it will throw events randomly anywhere, however, it will still schedule them on time as I scheduled them into the clocks... I'm running 3.0.3 and was running into this same problem with Rivendell about the clock generator in 3.0.1 and 3.0.2.

**Comment by deltecent** [comment]
I think the problem here is the columns in the clock editor are not supposed to be able to be sorted, but they are, and some of the numeric columns are sorted alphabetically, so they don't sort properly.

Fred, is this the case? Should we disable the ability to sort the columns?

Patrick
