### ISSUE TITLE
Loading multiple logs from command line doesn't work

### ISSUE THREAD

**Issue by wilson500** [ElvishArtisan/rivendell#490]
Rivendell 3.03 - Ubuntu 18.04

Loading multiple logs into rdairplay from the command line results in only the first log in the command being loaded.

`rdairplay --log1=news_1 --log2=news_2 --log3=news_3`

results in only news_1 being loaded into the main log.

`rdairplay --log2=news_2`

Will result in news_2 being loaded into log2 proving the syntax of the command is correct.

**Comment by ElvishArtisan** [comment]
Known issue. Fixed in 7869c62.
