### ISSUE TITLE
Rivendell 3.0.1 = (int1), assorted quirks, and other stuff..

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#493]
sorry, in huge rush, will add more info later..

CentOS 7 does not allow RDAirplay to be set at autostart....message says "Rivendell Service Not Active", but if you close that window, and click rdairplay, runs fine...

RDAirplay Airplay top banner Line...(shows host, user Log and service)...Log indicated is not showing dates, as indicated by macro....so "CAM-%m%d" is produced as CAM- on that banner.  Log does appear to load correctly in Airplay!

Seeing unstable actions on overnight log loads though, also, timed starts don't seem to be happening as expected, although further inspection is necessary on my part...but with system in automatic, it seems that a hard start legal, should start at the next timed event (from a paused log)...

it sate for a least 8 hours...

**Comment by ElvishArtisan** [comment]
> Seeing unstable actions on overnight log loads though, also, timed starts don't seem to be happening as expected, although further inspection is necessary on my part...but with system in automatic, it seems that a hard start legal, should start at the next timed event (from a paused log)...

Known problem, likely fixed in 7b772ca.

**Comment by ElvishArtisan** [comment]
> RDAirplay Airplay top banner Line...(shows host, user Log and service)...Log indicated is not showing dates, as indicated by macro....so "CAM-%m%d" is produced as CAM- on that banner. Log does appear to load correctly in Airplay!

Confirmed here.

**Comment by ElvishArtisan** [comment]
> CentOS 7 does not allow RDAirplay to be set at autostart....message says "Rivendell Service Not Active", but if you close that window, and click rdairplay, runs fine...

Should be fixed in c057441. Please test!

**Comment by ElvishArtisan** [comment]
> RDAirplay Airplay top banner Line...(shows host, user Log and service)...Log indicated is not showing dates, as indicated by macro....so "CAM-%m%d" is produced as CAM- on that banner. 

Fixed in 446eabb.

**Comment by validmirror** [comment]
> > Seeing unstable actions on overnight log loads though, also, timed starts don't seem to be happening as expected, although further inspection is necessary on my part...but with system in automatic, it seems that a hard start legal, should start at the next timed event (from a paused log)...
> 
> Known problem, likely fixed in [7b772ca](https://github.com/ElvishArtisan/rivendell/commit/7b772ca1014077620e380572e072c3506c05ec7d).

Actually, this was TOTAL DUMBNESS on my part...my issue turned out to be caused by scheduling a Station ID, set with segue markers at :00 [forcing an immediate overlap], immediately prior to the next days log chain. This forces RDAirplay to fail, and immediately close.
 
While the "overlapped" ID is fine for most hours, forcing the ID, and the chain to event simultaneously is a very bad idea.  I simply eliminated the overlap, everything is fine.  (and I don't have to be up at midnight to restart stuff"

thanks
