### ISSUE TITLE
Dropbox not the same on 3.03

### ISSUE THREAD

**Issue by 1opeti** [ElvishArtisan/rivendell#497]
The Dropbox system in 3.0.3 is not working as it used to in 2.x 

The Metadata Pattern has some unwanted side effects
filename is news0x00.mp3
Setting the metadata pattern to ‘news%i.’ changes the cut ID as expected 
 but it also erases the cart name.
I don’t want to have to supply the cart name every time a file is loaded.
I do want to be able to identify individual cuts.

The log file does not work.
There is logging to /var/log/rivendell/operations but you have to grep to get the data.
Defining a log file does not function.
I like to have a log file to check for the odd file that fails usually because of network lag.
Something placed in a safe place you can tail -f from a remote terminal.
I tried defining a log and now there is no logging.

**Comment by ElvishArtisan** [comment]
> The log file does not work.
There is logging to /var/log/rivendell/operations but you have to grep to get the data.
Defining a log file does not function.
I like to have a log file to check for the odd file that fails usually because of network lag.
Something placed in a safe place you can tail -f from a remote terminal.
I tried defining a log and now there is no logging.

Known problem, fixed in b9722a3.

**Comment by ElvishArtisan** [comment]
> The Metadata Pattern has some unwanted side effects
filename is news0x00.mp3
Setting the metadata pattern to ‘news%i.’ changes the cut ID as expected
but it also erases the cart name.
I don’t want to have to supply the cart name every time a file is loaded.
I do want to be able to identify individual cuts.

Whereas other users *do* want **all** of a cart's metadata updated each time. No matter what we do, some subset of Rivendell users is going to be unhappy about it.

Thus, I think what is really needed is a new dropbox attribute that would allow one to specify the desired behavior --i.e. update **all** the metadata when importing to an existing cart, *or* just the bits that are explicitly set in the metadata pattern.
