### ISSUE TITLE
Bug: rdimport: Didn't setup umlaut strings correctly

### ISSUE THREAD

**Issue by prometoys** [ElvishArtisan/rivendell#50]
Hi,

if you call rdimport with e.g. `--set-string-title="fü bär"`, the umlauts are imported with a wrong encoding. 

The problem is briefly described here:
http://caspian.paravelsystems.com/pipermail/rivendell-dev/2014-December/022116.html

**Comment by ElvishArtisan** [comment]
Fixed in v3.x.
