### ISSUE TITLE
compile problem rivwebcapi

### ISSUE THREAD

**Issue by chmaculus** [ElvishArtisan/rivendell#501]
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: se sale del directorio '/mnt/sda6/descargas/radio software/rivendell-3.1.0/apis/rivwebcapi/rivwebcapi'
Making all in tests
make[1]: se entra en el directorio '/mnt/sda6/descargas/radio software/rivendell-3.1.0/apis/rivwebcapi/tests'
  CC       addcart_test.o
  CCLD     addcart_test
/usr/bin/ld: cannot find -lrivwebcapi
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:628: addcart_test] Error 1
make[1]: se sale del directorio '/mnt/sda6/descargas/radio software/rivendell-3.1.0/apis/rivwebcapi/tests'
make: *** [Makefile:469: all-recursive] Error 1

any idea?

**Comment by ElvishArtisan** [comment]
Please give us the following information:
1) Distro name and version
2) Rivendell version
3) The invocation used for './configure'.

**Comment by ElvishArtisan** [comment]
Closed due to non-response.
