### ISSUE TITLE
RDimport - %n in metadata causing SegFault

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#504]
This command is producing a segfault:
`
rd@rdschlep01:/home/rd$ /usr/local/bin/rdimport --persistent-dropbox-id=187 --drop-box --normalization-level=-13 --autotrim-level=0 --delete-cuts --metadata-pattern=%n.wav --delete-source --startdate-offset=0 --enddate-offset=0 --log-syslog Music /storage/netmusic/*.wav
*** %n in writable segment detected ***
`

By commenting out this in utils/rdimport/rdimport.cpp, the issue goes away. 
`
  if(!import_metadata_pattern.isEmpty()) {
    Log(LOG_INFO,QString().sprintf(" Using metadata pattern: %s\n",
				   (const char *)import_metadata_pattern));
  }
`
There appears to be an issue with the way sprintf handles the %n pattern.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in a6983df.
