### ISSUE TITLE
Delayed working voicetracker and markereditor after update from 3.03 to 3.1

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#506]
My mailinglist post:

Between two voice-track productions i updated my system via yum on centos 7 to the latest version 3.1. And i noticed, that the work with the voicetracker is from now on extremely lagging. The VU freezes for +-2 seconds, and most of the time one channel VU level will be visible after save for some seconds. Another example... Opening the Edit Marker dialog takes now 2-3 seconds what usually happens not.
These examples happens on my clients and on the server, so it should not network related...

**Comment by ElvishArtisan** [comment]
Fixed in 8a2dd87.
