### ISSUE TITLE
BUG: Now and Next Data sends the conductor, regardless of the pattern of UDP String

### ISSUE THREAD

**Issue by prometoys** [ElvishArtisan/rivendell#51]
Hi,

this is my UDP String for Now+Next-Data in RDAirplay: `%g|%a|%i|%h %r`
This is, what is sent: `MUSIK|Radiohead|These Are My Twisted Words|325476 meineschoenenacht`

pattern: `%g|%a|%i|%h %r`
result: `MUSIK|Radiohead|These Are My Twisted Words| meineschoenenacht`

The string "meineschoenenacht" is in the Conductor field of the song. (please don't ask why ;) )

Kind regards and Merry Christmas

Keywan

**Comment by ElvishArtisan** [comment]
'%r' is the wildcard for 'conductor', so this is the expected output.  See https://github.com/ElvishArtisan/rivendell/blob/master/docs/metadata_wildcards.txt.

**Comment by prometoys** [comment]
Ups, sorry. confused %r with \r. Really sorry... Thanks for the hint.
