### ISSUE TITLE
Any macro fired from Soundpanel doesn't work

### ISSUE THREAD

**Issue by wilson500** [ElvishArtisan/rivendell#510]
Rivendell 3.0.3
Ubuntu 18.04

Any marco fired from the Soundpanel doesn't work. It gets logged but the action doesn't happen.
Same macro placed within the LOG works fine.

The log shows:
Nov 18 16:37:03 riv-night ripcd: received rml: "EX 90002!" from 10.20.30.52

then nothing else.

**Comment by ElvishArtisan** [comment]
Unable to reproduce on v3.2.0.

**Comment by wilson500** [comment]
Checked again. It was caused by something else I was testing. Sorry about that.

**Comment by ElvishArtisan** [comment]
No worries! Glad we got to the bottom of it.
