### ISSUE TITLE
Log setting ignored so always logs to syslog

### ISSUE THREAD

**Issue by wilson500** [ElvishArtisan/rivendell#511]
Rivendell 3.03
Ubuntu 18.04

The setting in /etc/rd.conf to not use syslog is ignored.

Facility=File
LogDirectory=/home/studio/rdlogs

Despite this setting, Rivendell still logs to /var/log/syslog

**Comment by ElvishArtisan** [comment]
These settings have been removed and are no longer supported in Rivendell 3.x. All logging is now handled via syslog.
