### ISSUE TITLE
Feature Requests - Rdairplay Add Box

### ISSUE THREAD

**Issue by wilson500** [ElvishArtisan/rivendell#512]
In older versions of Rivendell, when Add was clicked in rdairplay, the focus was on the search box allowing something to be typed straight away.
In 3.03 it is necessary to click into the box before you can type.

If you then enter a cart number or any search that returns one result, it is now necessary to click and select the one item before you can click OK to enter it in the playlist. In older version this wasn't necessary.

Combined there are two extra clicks to adding a cart compared to the old version we are replacing.

Feature Request 1.
Text search box has cursor focus when Add box is opened.

Feature Request 2.
If search results in one result, it becomes selected and doesn't need clicking on.

Thank you.

**Comment by ElvishArtisan** [comment]
> In older versions of Rivendell, when Add was clicked in rdairplay, the focus was on the search box allowing something to be typed straight away.
In 3.03 it is necessary to click into the box before you can type.

Not seeing this in v3.2.0. There, it already works as you describe.

**Comment by wilson500** [comment]
Just rechecked. In 3.0.3, start rdairplay and the first time you click add it works as desired. On subsequent occasions, the search box doesn't have focus. Is this the case in 3.2.0?

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 9626035.
