### ISSUE TITLE
Looking for information on  Log generation speed

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#513]
We are running a 1.7 version of Rivendell with about 25K tunes. It takes about 10 minutes to generate a log. 

We built a new Rivendell server 2.1 and loaded about 47K tunes. It takes about 2 hours to build a play log.  

The database doesn't seem to the issue. Any ideas as to why it's 10x slower to generate a log when the data is not quite twice as big?

-Jan

**Comment by ElvishArtisan** [comment]
Those are both ancient versions of Rivendell. I would recommend trying one of the current versions (v2.19.3 or v3.2.0). See also #502 for benchmark info relevant to the v3.x versions.

**Comment by jangittelman** [comment]
The system with version 2.1 is actually 2.19 (sorry for misleading). It was built to allow us to upgrade our 1.7 system (which will get the latest version 3.2). 

-Jan


Jan Gittelman
(919) 740 - 5497

**Comment by jangittelman** [comment]
Installed Rivendell version 3.2. Log generation is back to about a 10 minutes even with 47K tunes.
