### ISSUE TITLE
Reports - Select Boxes Missing from Add/Edit report window (v3.2.0)

### ISSUE THREAD

**Issue by jasonmskidmore** [ElvishArtisan/rivendell#514]
When editing reports, unable to select services, hosts, groups (Empty space where the select boxes should appear).  This results in being unable to run reports from LogManager because the report is not associated with a service. I was able to work around this by adding a row in the REPORT_SERVICES table linking the report to the service.  | Issue was not present in v3.1.0. 

Screenshots below show 3.1.0 vs 3.2.0
![screenshot1](https://user-images.githubusercontent.com/2318864/69753362-0d1bc600-1119-11ea-9fe1-c9ac07e3c99d.png)
![Screen Shot 2019-11-27 at 1 24 30 PM](https://user-images.githubusercontent.com/2318864/69753460-47856300-1119-11ea-9b1c-11c5b7323dbe.png)

**Comment by ElvishArtisan** [comment]
Fixed in ac59b52.
