### ISSUE TITLE
M4A import

### ISSUE THREAD

**Issue by maxtimbo** [ElvishArtisan/rivendell#516]
I haven't tried to use the feature yet, but according to the wiki:

> Known Issues
> M4A format will not be imported, as libmp4v2-dev is no more available.

I've used ffmpeg in the past to quickly convert M4A's to mp3s or wav files. Perhaps using ffmpeg as an alternative to libmp4v2-dev?

ffmpeg is an extremely powerful tool that could be helpful for all kinds of audio manipulation. I have also written a python script that analyzes a directory with mixed 30sec and 60sec commercials and concatenates all 30sec bits to make 60sec commercials.

**Comment by ElvishArtisan** [comment]
The basic problem with any flavor of AAC encoding in a FOSS environment is that it is patent-encumbered. This makes it unlikely that binary packages for the relevant tools will be available in any major distro. If you need such capabilities, you will generally need to build the necesary tools from source yourself.
