### ISSUE TITLE
Unable to import files with non-english characters such as ç

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#518]
On Rivendell version 3.2.0 I am unable to import files with non-english (ex. a with an accent over it, c with a cedilla under it) characters. The import for files with those characters worked fine in version 2.19.3 and version 1.7.

I am using rdimport to do the import as I'm importing about 49,000 tunes and tagging them with schedule codes. It is only the files (or directories) with non-english characters that is failing. If I change the name to include only english characters, the files load.

Is there a language setting for Rivendell? Any suggestions as to how to address this, besides changing all the file and directory names?

Thanks,
Jan

**Comment by ElvishArtisan** [comment]
Could you send me a sample file that exhibits the problem?

**Comment by workino** [comment]
Hello Fred,
i solved the issue with this:

  for(int i=0;i<flist.length();i++) {    - entry+=flist.at(i);    +
QString str=flist.at(i);    + entry+=QString::fromUtf8(str);  }

changing the code present from line 902 to 905 in file
utils/rdimport/rdimport.cpp. In the console log there are still the
error with
characters but rdimport is able to import correctly the file with accents.

I don't know if it will be a real resolution but for the moment is working :D

I'll send u a file u can try in private way

Regards

Gabriele


Il giorno lun 16 dic 2019 alle ore 15:34 Fred Gleason <
notifications@github.com> ha scritto:

**Comment by ElvishArtisan** [comment]
Got it ... thanks!

That finally exhibited the problem here. Interestingly, my prior test case (a file named '文字化け.wav') did not goose this particular bug. I've added yours as a second test case.

**Comment by ElvishArtisan** [comment]
Fixed in 8ea0983 and 2b3b733.

>   for(int i=0;i<flist.length();i++) {    - entry+=flist.at(i);    +
QString str=flist.at(i);    + entry+=QString::fromUtf8(str);  }

> changing the code present from line 902 to 905 in file
utils/rdimport/rdimport.cpp. In the console log there are still the
error with
characters but rdimport is able to import correctly the file with accents.
>
> I don't know if it will be a real resolution but for the moment is working :D

I ended up completely removing that ```ProcessFileList()``` method, as all that the original was doing was (incorrectly) copying a ```QString``` into another ```QString``` and then calling ```ProcessFileEntry()``` with it. Now, we just call ```ProcessFileEntry()``` directly.

It's interesting that your original fix worked. The actual problem was in the ```glob()``` call in ```ProcessFileEntry()``` (line 888), which was converting the filename to Latin1 rather than UTF-8 (an invidiously easy error to make in Qt, as its default ```(const char *)``` conversion uses Latin1).

Please test!

**Comment by jangittelman** [comment]
Reading this, it sounds like you don't need my sample files. Although, I'm happy to send them (or just the file or directory names as that's all that is needed). For example, create this directory name: Bau-Inspiração  Add any valid importable files to it and they will fail to import, if  the directory name is included in the filename (ex: Bau-Inspiração/morena.wav) when passed to rdimport. 

Is it possible for me to get this version of rdimport to try?

-Jan

**Comment by jangittelman** [comment]
I’ve pulled the code down ( I installed via repository), so will try to compile rdimport tomorrow and let you know how it works.

THanks,
Jan

Jan Gittelman
(919) 740 - 5497

**Comment by jangittelman** [comment]
Tested rdimport with the changes specified above.  Worked like a charm. 574 tunes with accents, carons, umlauts, cedillas, and numerous other diacritical marks loaded. Thank you very much.

**Comment by ElvishArtisan** [comment]
Cool! Thank you for the feedback!

**Comment by workino** [comment]
Hello Fred,
Sorry for delay I confirm also all is ok now 😁
Regards
Gabriele
