### ISSUE TITLE
Feature Request: Advance to Next Timed Event in Live Assist

### ISSUE THREAD

**Issue by ChZeman** [ElvishArtisan/rivendell#522]
I would like to have RDAirPlay advance to the next timed event in Live Assist Mode, just as it would if operating in Automatic Mode.

Thank you,
Chris Zeman

**Comment by ElvishArtisan** [comment]
I like the idea, but this would be a major change that could affect many users adversely. I suggest floating it on Rivendell-dev to get some community feedback.

**Comment by ChZeman** [comment]
I presented the idea in the Rivendell Facebook group about 2 or 3 times over the past year, and was only met with some support for the idea this last time at least a few weeks ago. It sounded like John Anderson was going to discuss it with you.

I had suggested making it a configurable option per host, fully expecting that what I'm suggesting wouldn't work well for everyone. The problem with it not doing what I'm asking for it to do is that, for some reason, some of my producers struggle with cuing the breaks.

I had considered modifying the source code and compiling only RDAirPlay to run a custom version in our studios, but then I'd be unable to update to newer versions without going through the headache of editing newer versions of RDAirPlay and recompiling for each update.

I'll consider posting the idea in Rivendell-dev, but I tend not to join mailing lists anymore. They have just ended up being a pain for me in the past. :-) At this point, I'm probably going to just purchase a license for software that already does what I need. I love Rivendell, but really need to just get past operational issues in the studio so I can tend to more important items.

Thank you,
Chris

**Comment by ElvishArtisan** [comment]
> I'll consider posting the idea in Rivendell-dev, but I tend not to join mailing lists anymore. They have just ended up being a pain for me in the past. :-)

Which is likewise why I avoid Facebook like the plague. To each his own poison!  :)

> At this point, I'm probably going to just purchase a license for software that already does what I need. I love Rivendell, but really need to just get past operational issues in the studio so I can tend to more important items.

Fair enough.
