### ISSUE TITLE
Request: Add cut description to cart title in Now+Next

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#523]
When sending Now+Next data, I'd like to include the cut's description in the cart title, as a substitutable field.  An example, using %CD as the field marker:
````
Cart title: UnderCurrents - hour 1 (%CD)
Cut description: uc4599a
Now+Next: UnderCurrents - hour 1 (uc5499a)
````

We broadcast a music program whose playlist for each hour is published on the web. Each playlist has unique name, uc_nnnna_. We import the program's hour-long segments into a cart using the playlist name as the cut description. Occasionally a listener will ask us about a song that was played during the program, and we have to go to the system log to determine which cut was played to determine the program number for that hour.  If we can display the program number in Now+Next we can eliminate the need to look at system files, and we provide the listener with the ability to locate the information herself, rather than having to wait on us.

This should be optional, by cart, to prevent accidentally screwing up any existing cart whose title might contain the field marker (%CD in my example).

**Comment by ElvishArtisan** [comment]
This can already be done by using ```%i```/```%I``` from the [metadata wildcards](http://opsguide.rivendellaudio.org/html/appendix.metadata_wildcards.html#sect.metadata_wildcards).
