### ISSUE TITLE
RDADMIN missing missing database backup and restore buttons

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#527]
Rivendell version: 3.2.0 and version 3.2.1
Database schema 311

RDADMIN doesn't include the database BACKUP and RESTORE buttons.

**Comment by ElvishArtisan** [comment]
That's correct. Nor do any of the v3.x versions.
That functionality has been moved to rddbconfig(8).

**Comment by jangittelman** [comment]
thank you. sorry to bother you
Jan Gittelman
(919) 740 - 5497
