### ISSUE TITLE
Blank Year Released field displays -4713

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#528]
When the Year Released variable (%y) is used to display date in RDAirplay, RDCardSlots, etc. and the Year Released is left blank when creating the cart, the year released is shown as -4713.  A normal date in this field yields the expected display.  The behavior is seen in v3.2.1int2.

**Comment by WMTH** [comment]
Verified this issue is not seen in v3.2.1.

**Comment by ElvishArtisan** [comment]
Confirmed.

**Comment by ElvishArtisan** [comment]
Fixed in 1a88bcb. Please test!

**Comment by WMTH** [comment]
Testing complete, the %y functions as intended; a blank Year Released results in a blank field in RDAirplay, etc.

**Comment by ElvishArtisan** [comment]
Thank you.
