### ISSUE TITLE
Bug: RDLogManager:Clock: Clone Event weird behaviour 

### ISSUE THREAD

**Issue by prometoys** [ElvishArtisan/rivendell#53]
Hi,

I like Albans clone event feature, but it needs a bit more love:

1. Select Event
2. Click on "Clone"
3. Push "Esc" (not Cancel)
Expected outcome: no change
Observed outcome: an event is added with no respect to overlapping. you can't fix the times of this event later, you must delete it and start again.

**Comment by ElvishArtisan** [comment]
Fixed in origin master.
