### ISSUE TITLE
Audio Import Progress Bar Missing in 3.2

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#531]
RDLibrary used to present the user with a progress bar when performing an audio import. I still see the code in lib/rdaudioimport.cpp and other source files, but it is not clear to me how the progress bar is built and presented to the user.

I have run rdlibrary with strace(1) to see if I can discern where the progress bar gets called, but that did not reveal anything helpful (to me).

Steps to reproduce:

1. Install Rivendell 3.2.x
2. Launch RDLibrary
3. Add a new (audio) Cart
4. Import/Export Audio (especially a long-ish piece of audio)
5. Expect to see a progress bar...

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in fef77fa.

The problem turned out to be that the themeing engine in XFCE was overriding the palette selections set in ```RDBusyBar```. We kept those, but added a call to ```QWidget::setStyleSheet()``` with the same color values. *Voila* -- the themeing engine now sees them!
