### ISSUE TITLE
Cannot pass parameters to shell script from RN line in macro

### ISSUE THREAD

**Issue by zotz** [ElvishArtisan/rivendell#532]
Old system:
Linux riv3 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u1 i686
Rivendell 2.10.2 Database Schema 242

cart 700011
Macro Line: 001
Command: RN /home/rduser/playvid.sh 700011!
Macro Line: 002
Command: SP 236960!

$ cat /home/rduser/playvid.sh
#! /bin/bash
echo $1 > /tmp/playvid
echo "add /var/vid/$1.mp4" | nc 192.168.86.145 4212

Parameters get passed as expected:

$ tail -f /tmp/playvid 
700007
tail: /tmp/playvid: file truncated
700014
tail: /tmp/playvid: file truncated
700008

New System:
Centos 7
Rivendell 3.2.1 Database Schema 311

cart 700011
Macro Line: 001
Command: RN /home/rd/playvid.sh 700011!
Macro Line: 002
Command: SP 236960!

playvid.sh does not seem to run: (no change to /tmp/playvid)

$ cat playvid.sh
#! /bin/bash

echo "this is playvid.sh" > /tmp/playvid
echo "genericplayvid" >> /tmp/playvid
echo `/bin/whoami` >> /tmp/playvid
echo $1 >> /tmp/playvid
sudo -i -u rd /home/rd/playvidrun.sh $1

I have a workaround but it is painful. It involves a bash script for each macro cart rather than a single bash script that gets passed a parameter from each macro cart...

**Comment by zotz** [comment]
Did some more digging.

rmlsend RN\ /home/pypad/playvidpywp1.sh\ ponea\ ptwoa\ pthreea\ pfoura\ pfiva\ psixa\ psevena\ peighta\ pninea\ ptena\!

$ sudo cat /tmp/passedparamspywp1.txtAll the command-line parameters are: ptena ptena ptena ptena ptena ptena ptena ptena ptena ptena

$ sudo cat /home/pypad/playvidpywp1.sh 
#!/bin/bash
echo
echo "All the command-line parameters are: "$*"" >> /tmp/passedparamspywp1.txt
echo
exit 0


Seems parameters get passed... $0 seems fine. Every other parameter seems to get passed as the last parameter.

$ rmlsend RN\ /home/pypad/playvidpywp1.sh\ ponea\ ptwoa\ pthreea\ pfoura\ pfiva\!

$ sudo cat /tmp/passedparamspywp1.txtAll the command-line parameters are: pfiva pfiva pfiva pfiva pfiva

This obviously seems to be a bug in the code...

drew

**Comment by zotz** [comment]
Tried something equivalent on my old 2.x box:

rmlsend RN\ /home/rduser/playvidpywp1.sh\ ponea\ ptwoa\ pthreea\ pfoura\ pfiva\!

$ cat /tmp/passedparamspywp1.txtAll the command-line parameters are: ponea ptwoa pthreea pfoura pfiva

2.x passes the parameters correctly.

drew

**Comment by zotz** [comment]
More digging on my 3.x system:

in the graphical rmlsend:

RN /home/pypad/playvidpywp1.sh ponea ptwoa pthreea pfoura pfiva!

1st try:

All the command-line parameters are: ponea pfiva pfiva pfiva pfiva

2nd try:

All the command-line parameters are: pfiva pfiva pfiva pfiva pfiva

Where did that ponea come from and then go to?

drew

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in a955fee. Please test!

**Comment by zotz** [comment]
I have to learn how to do that... Soon hopefully...

drew

**Comment by zotz** [comment]
OK, I have set up a virtual machine, pulled down the git repo, got the devel setup working enough to test.

Looks like parameter passing is good see sample:

All the command-line parameters are: 700020 "Fixing My Brain" "Brad Sucks"
All the command-line parameters are: 700011 "Gasoline" "Brad Sucks" sat
All the command-line parameters are: 700001 "California Lullabye" "Josh Woodward"
All the command-line parameters are: 700015 "Fake It" "Brad Sucks" sat mar
All the command-line parameters are: 700009 "The Dreamers" sat mar
All the command-line parameters are: 700020 "Fixing My Brain" "Brad Sucks"
All the command-line parameters are: 700011 "Gasoline" "Brad Sucks" sat
All the command-line parameters are: 700001 "California Lullabye" "Josh Woodward"
All the command-line parameters are: 700015 "Fake It" "Brad Sucks" sat mar
All the command-line parameters are: 700009 "The Dreamers" sat mar
All the command-line parameters are: 700020 "Fixing My Brain" "Brad Sucks"
All the command-line parameters are: 700011 "Gasoline" "Brad Sucks" sat
All the command-line parameters are: 700001 "California Lullabye" "Josh Woodward"
All the command-line parameters are: 700015 "Fake It" "Brad Sucks" sat mar
All the command-line parameters are: 700009 "The Dreamers" sat mar
All the command-line parameters are: 700020 "Fixing My Brain" "Brad Sucks"

That is what is being logged...

RN lines vary somewhat by cart for testing purposes right now. That said the first parameter is the cart number, the next is the "cart title", the next is the "cart artist", things like sat and mar are macro/metadata expansions of %a and %b just to illustrate what is getting expanded.

A sample RN line producing one of the lines you are seeing:

RN /home/pypad/playvidpywp1.sh 700015 "Fake It" "Brad Sucks" %a %b!

I have made a directory for pypad, and changed pypad's line in /etc/passwd to this:
pypad:x:151:151:Rivendell PyPAD scripts:/dev/null:/bin/false

Oops, looks like I forgot to make the change but it is still working for this bit.

I intended to change it to this:

pypad:x:151:151:Rivendell PyPAD scripts:/home/pypad:/bin/false

and I may still have to to get the pypad script option to work. We shall see.

Thanks for the parameter passing bug fix.

Can anyone think of a way to script the addition of "macro lines" to a macro cart from the command line?

Thinking it might be nice to have a script that creates a new macro cart, get's told the cart number, adds the song title and artist (and anything else) to the cart.

Adds an RN line to the cart and fills it out with the cart's particulars. Adds an SP line to the cart with a passed in duration. (In my case, I would pull this amount from the video length that matched the card.)

**Comment by ElvishArtisan** [comment]
> Looks like parameter passing is good see sample:

So the original bug ("Cannot pass parameters to shell script from RN line in macro") can be considered fixed? If so, let's close this issue and continue the video server discussion elsewhere, either in a dedicated issue or on Rivendell-prog. (I suspect we'd get a larger audience on the ML).
