### ISSUE TITLE
BUG: RDLogManager (Severe): Scheduler Rules damaged by save, when columns sorted. 

### ISSUE THREAD

**Issue by prometoys** [ElvishArtisan/rivendell#54]
Hi,

I found a severe Bug in RDLogmanager. If you open a clock and edit the scheduler rules and save them, rivendell doesn't take care about the sorting of the column.

Example: Set the Sched code like this:

SC   min   max
a     1    0
b     2    0
c     0   1

Sort it bei Min in a row

SC   min   max
c     0   1
a     1    0
b     2    0

Close the Rules with ok, Save and close the clock, open again, you will find these settings:

SC   min   max
a     0   1
b     1    0
c     2    0

I guess the list should be sorted back before saving or somehow else the consistency should be assured

Btw: I hope you consider my issue reporting as helpful and not as spam, In the later case please let me know :)

**Comment by ElvishArtisan** [comment]
Fixed in origin master.  Thank you for the report!
