### ISSUE TITLE
Cannot have timed events on log. Only if I add a marker and made timed.

### ISSUE THREAD

**Issue by radiocafero** [ElvishArtisan/rivendell#542]
If I made commercial break timed event, then first "generate log" & "import music" generate and populate the log, and "timed traffic inline events" appear as as timed events but after import the traffic log, all timed events lost this particularity and remain untimed.
If I put a marker on preimported carts then timed atribute will remain in log.

**Comment by ElvishArtisan** [comment]
Already fixed in e407d9e and released in v3.3.0.

**Comment by radiocafero** [comment]
I have tested in 3.3 and even If I have "hard start time" on make next, on commercial break, when I open the log in rdlogedit or load in rdairplay, no timed events loaded.

<img width="958" alt="06-rdlogedit" src="https://user-images.githubusercontent.com/60175920/77020147-63906700-698b-11ea-9b03-f5c594d1e66b.png">
<img width="1012" alt="01-grid" src="https://user-images.githubusercontent.com/60175920/77020150-668b5780-698b-11ea-963e-b8edc5b18972.png">
<img width="1026" alt="05-edit event PUB" src="https://user-images.githubusercontent.com/60175920/77020151-67bc8480-698b-11ea-8718-5741cf96c27b.png">
<img width="604" alt="04-event PUB" src="https://user-images.githubusercontent.com/60175920/77020152-68551b00-698b-11ea-82b0-d24b97624184.png">
<img width="1002" alt="03-clock pie" src="https://user-images.githubusercontent.com/60175920/77020153-68edb180-698b-11ea-9e10-868769bcfea2.png">
<img width="423" alt="02-clock number" src="https://user-images.githubusercontent.com/60175920/77020154-69864800-698b-11ea-8f4e-c09f9b005c45.png">
