### ISSUE TITLE
rdexport Output Filename Incorrect

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#548]
It seems as if rdexport(1) in Rivendell 3.3.0 is generating incorrect output filenames. When I run it with:
`rdexport --verbose --format=MP3 --carts=6:6 .`
(and with several other combinations of options) I get this:

    exporting cart/cut 000006/001 [Title]
    000006_-01.mp3
    exporting cart/cut 000006/002 [Title]
    000006_-01[1].mp3
    exporting cart/cut 000006/003 [Title]
    000006_-01[2].mp3
    exporting cart/cut 000006/004 [Title]
    000006_-01[3].mp3

I *think* the problem code is in lib/rdlog_line.cpp: RDLogLine::resolveWildcards(), specifically the line containing `pattern.replace("%j",QString().sprintf("%03d",cutNumber()));`. But I am not sure how it should be done differently. I'll keep banging on it to see if I can figure it out...

**Comment by dklann** [comment]
Running rdexport under gdb(1) (which is something I'm extremely rusty with), it appears that in `RDAudioExport::runExport()` (rdaudioexport.cpp:132), `conv_dst_filename` is empty:
`
conv_dst_filename = {static null = {<No data fields>}
`
Here is the output in gdb of _print *this_:
`
$24 = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x60e460 <QObject::staticMetaObject>, stringdata = 0x7ffff78f9cc0 <qt_meta_stringdata_RDAudioExport> "RDAudioExport", 
      data = 0x7ffff78f9d00 <qt_meta_data_RDAudioExport>, extradata = 0x7ffff7ba8660 <RDAudioExport::staticMetaObjectExtraData>}}, static staticMetaObjectExtraData = {objects = 0x0, 
    static_metacall = 0x7ffff78ca480 <RDAudioExport::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>}, conv_cart_number = 6, conv_cut_number = 1, conv_dst_filename = {static null = {<No data fields>}, 
    static shared_null = {ref = {_q_value = 115}, alloc = 0, size = 0, data = 0x60e51a <QString::shared_null+26>, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, 
    static shared_empty = {ref = {_q_value = 13}, alloc = 0, size = 0, data = 0x7ffff37178da <QString::shared_empty+26>, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, 
    d = 0x6c77d0, static codecForCStrings = 0x0}, conv_start_point = -1, conv_end_point = -1, conv_enable_metadata = true, conv_settings = 0x7fffffffc980, conv_aborting = false}
`
So, the cart number and the cut number are present, but the output filename is empty?

Still digging ...

**Comment by dklann** [comment]
I think I found the problem. I'll issue a pull request against a development branch.

**Comment by ElvishArtisan** [comment]
Confirmed here.
