### ISSUE TITLE
[3.3.0] RDLogManager dialog error

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#550]
When choosing to import from the scheduler by selecting `Select from:` in the `IMPORT` section, the timed start `Transition if previous event ends...` combobox is enabled. I don't believe it should as that value is only saved (or relevant) if `Use hard start time` is selected.

As a side note, I cannot find any combination of settings that enables the `First cart has a X transition`.

**Comment by deltecent** [comment]
I did a grep on `firstTransType` and this is all that comes up:
```
./lib/rdevent_line.cpp:RDLogLine::TransType RDEventLine::firstTransType() const
./lib/rdevent.cpp:RDLogLine::TransType RDEvent::firstTransType() const
./rdlogmanager/edit_event.cpp:    event_transtype_box->setCurrentItem(event_event->firstTransType());
./rdlogmanager/edit_event.cpp:  event_firsttrans_box->setCurrentItem(event_event->firstTransType());
```
Does anyone know what this is/was used for because it looks like it isn't used anywhere.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
You do need the ability to specify the transition type for what's coming from the music scheduler, and this provides that. The label is certainly a bit misleading in that context however. Perhaps change it to just say 'Transition Type' in that scenario?

**Comment by ElvishArtisan** [comment]
Ok, I finally decided to take no prisoners on this one. I've completely refactored the control layout in this dialog, in favor of something that is (hopefully!) clearer and more intuitive. Sanity check please!
