### ISSUE TITLE
Bug: RDLibrary changes group if case is different

### ISSUE THREAD

**Issue by FireByTrial** [ElvishArtisan/rivendell#56]
When editing a cart in RDLibrary if the case of the group does not match exactly the case of the group the group of the edited cart will be changed to the first alphabetic group.

Example:
We used rdimport to import our library into rivendell 2.10.2. our script used the group "music" and everything else works fine. however if we edit a individual cart the group will be changed to "BEDS" even though "MUSIC" is a valid group in our configuration. it will even show up in the list the same color as "MUSIC" (shows green). 

Could this be made case insensitive or might that cause problems. if it causes problems would there be a way to have rdimport verify the group exists exactly as entered?

**Comment by ElvishArtisan** [comment]
Fixed in [master 7f4e3a2].
