### ISSUE TITLE
Configure GPIs in Edit Switcher, only edit first GPI carts

### ISSUE THREAD

**Issue by olvaar** [ElvishArtisan/rivendell#560]
When I configure GPIs in the editswitcher, these carts only show up in the RDGpiMon for the FIRST input. All the rest is not configurable through the edit switcher menu.

If I use RMLsend to configure these GPI, It DOES work, and the carts are being called.

**Comment by ElvishArtisan** [comment]
I'm afraid that I'm not following your question. What is the 'edit switcher menu'? Could you post a screenshot?

It would also be very helpful if you could mention the version of Rivendell you're using, the distribution you're running it on and the type of GPIO device being used.

**Comment by olvaar** [comment]
Fred,

I am using rivendel 3.2.0 in centos7

The widget i al talking About is 
Rdadmin -> manage hosts -> host -> manage -> switcher gpio -> switcher -> configure gpis 
There where you can link a cart to An on- or off-transition of the gpi Lines.

You can enter Carts, but only the first Will be really assigned. (Checked with rdgpimon)



 




Verstuurd vanaf mijn iPhone

**Comment by ElvishArtisan** [comment]
Thanks. Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in f92e877.
