### ISSUE TITLE
[3.0.0] rdadmin(1) Edit Service dialog enhancements

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#562]
Add the ability to see the values of predefined import templates.

Add the ability to copy a predefined import template to the custom parser settings.

![rdadmin import_parser_fields](https://user-images.githubusercontent.com/24786756/78724565-95d61a00-78e2-11ea-91aa-1116bcd3556c.png)

**Comment by deltecent** [comment]
Added in PR #563

**Comment by deltecent** [comment]
I added a confirmation dialog.

**Comment by ElvishArtisan** [comment]
Merged #563 to 'master'. Thank you!
