### ISSUE TITLE
Garbeled Text in RDLogEdit Edit Log Entry

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#565]
If check box for Start Immediately is checked there is garbled text for checkbox below.
![Screenshot 2020-04-15 14 33 50](https://user-images.githubusercontent.com/63725659/79375788-318d0900-7f27-11ea-831b-3f59154ab296.png)
![Screenshot 2020-04-15 14 34 15](https://user-images.githubusercontent.com/63725659/79375792-3356cc80-7f27-11ea-9f70-e47c0457d560.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 1f6535f.
