### ISSUE TITLE
Rdlogedit show other services than I setup in rdadmin 

### ISSUE THREAD

**Issue by radiocafero** [ElvishArtisan/rivendell#566]
Hi,
I have set up a new service in rdadmin but I do not see it in rdlogedit. 
Instead, I see others that I deleted in the past.
In rdairplay I see them correctly as in rdlogmanager.

**Comment by ElvishArtisan** [comment]
Sounds like you need to configure your per-user service permissions.

**Comment by radiocafero** [comment]
indeed.I forgot about it ... thanks!
