### ISSUE TITLE
RN RML error when Rivendell runs as rd, not root.

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#568]
I have a script (Insert_Station_Legal_ID.sh) that works from the command
line. File is stored at /home/rd with permission 777 and executable.
----------------------------------
#!/bin/bash
rmlsend LB\ "Inserted Legal ID\!
rmlsend PX\ 001001\ play\!
sleep 10
rmlsend LB\ \!
----------------------------------

If I try to trigger it as a macro from a log it fails without error.
-----------------------------------------
001 SP 1000!
002 RN /home/rd/Insert_Station_Legal_ID.sh!
003 SP 1000!
----------------------------------------
I am running on centos 7 3.3.0 fully patched as user rd. Rivendell is set to run as rd with user=rd in rivendell.service, which allows me to run liquidsoap, icecast, etc.
rd.conf has AudioOwner and AudioGroup = rivendell, PaypadOwner and
group=pypad, and RnRmlOwner and Group = rd

IF i change rivendell.service back to where rivendell runs as root, the above macro's work correctly from the log. WHEN rivendell is running as rd, the macro RN .... will not work.

**Comment by Chester-Graham** [comment]
I am not sure that this can be fixed for running Rivendell.service with user=rd. I would propose leaving RN as is, and creating another macro command, for example RU, that would execute a shell script without using the runuser command which can only be run as root.

**Comment by ElvishArtisan** [comment]
What Rivendell version are you running? v2.x and v3.x have totally different behaviors here.

**Comment by Chester-Graham** [comment]
Version 3.3.0 running with rivendell.service option of user=rd. See above . . .

**Comment by Chester-Graham** [comment]
I have reinstalled with Rivendell running as root and to work around this issues.
