### ISSUE TITLE
Bug: RDAudioStore compilation error

### ISSUE THREAD

**Issue by olivierdutheil** [ElvishArtisan/rivendell#57]
Hi,
Here is a compilation error between rdlibrary/disk_gauge and lib/rdaudiostore

disk_gauge.o: In function `DiskGauge::update()':
/rivendell2.10.2/rdlibrary/disk_gauge.cpp:89: undefined reference to`RDAudioStore::RDAudioStore(RDStation_, RDConfig_, QObject_, char const_)'
/rivendell2.10.2/rdlibrary/disk_gauge.cpp:90: undefined reference to `RDAudioStore::runStore(QString const&, QString const&)'
/rivendell2.10.2/rdlibrary/disk_gauge.cpp:92: undefined reference to`RDAudioStore::freeBytes() const'
/rivendell2.10.2/rdlibrary/disk_gauge.cpp:93: undefined reference to `RDAudioStore::totalBytes() const'
collect2: ld returned 1 exit status
make[1]: **\* [rdlibrary] Erreur 1

Regards,
Olivier

**Comment by ElvishArtisan** [comment]
Fixed.
