### ISSUE TITLE
Rivendell 3.3.0 Dropbox issue

### ISSUE THREAD

**Issue by dancebeatfm** [ElvishArtisan/rivendell#576]
Hello.
Hardware:
Raspberry Pi4
Software:
OS: Raspbian Buster
Rivendell v3.3.0

I have a odd things with dropbox
**First**, RDImport won't import file with character = in name of the file

Importing file "DJ CARGO=Fly (DJ Cargo Vs. Kei Morton Pumping Mix).mp3" [Fly (DJ Cargo vs. Kei Morton Pumping Mix)] to cart 010802 ... May 03 18:01:00:  RDXport service returned an error, skipping /home/pi/Radio/Music/Techno-Trance/DJ CARGO=Fly (DJ Cargo Vs. Kei Morton Pumping Mix).mp3...
May 03 18:01:01:  Importing file "DJ CARGO=Reach Up (Locco Freakz Remix).mp3" [Reach Up (Locco Freakz Remix)] to cart 010802 ... May 03 18:01:01:  RDXport service returned an error, skipping /home/pi/Radio/Music/Techno-Trance/DJ CARGO=Reach Up (Locco Freakz Remix).mp3...

 **Second**, when i was importing audio files throw dropbox, i don't now why, but it stacks with 2 files and began to import them in a circle in different cart's

May 03 13:52:29:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012327 ... May 03 13:52:54: done.
May 03 13:52:54:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012328 ... May 03 13:53:19: done.
May 03 13:53:40:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012329 ... May 03 13:54:07: done.
May 03 13:54:07:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012330 ... May 03 13:54:33: done.
May 03 13:54:53:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012331 ... May 03 13:55:17: done.
May 03 13:55:17:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012332 ... May 03 13:55:42: done.
May 03 13:56:02:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012333 ... May 03 13:56:28: done.
May 03 13:56:28:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012334 ... May 03 13:56:53: done.
May 03 13:57:13:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012335 ... May 03 13:57:38: done.
May 03 13:57:38:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012336 ... May 03 13:58:03: done.
May 03 13:58:24:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012337 ... May 03 13:58:49: done.
May 03 13:58:49:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012338 ... May 03 13:59:16: done.
May 03 13:59:37:  Importing file "06 - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit) - DJ Manian Vs. Tune UP! - Rhythm & Drums (Rave Allstars RMX Edit).mp3" [Rhythm & Drums (Rave Allstars RMX Edit)] to cart 012339 ... May 03 14:00:02: done.
May 03 14:00:02:  Importing file "07 - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit) - Sven-R-G Vs. Bass-T - The Sign 2006 (Shibuya RMX Edit).mp3" [The Sign 2006 (Shibuya RMX Edit)] to cart 012340 ... May 03 14:00:27: done.

**Comment by ElvishArtisan** [comment]
<strong>First</strong>. Confirmed here.

<strong>Second</strong>. Absent the original files, there is no way to even begin to troubleshoot this.

**Comment by ElvishArtisan** [comment]
**First**. Fixed in 18dd093 and f3bd897.

**Comment by ElvishArtisan** [comment]
**Second**. If you have the data and can consistently reproduce this, feel free to open a separate issue for it and we'll have a go. In the meantime, I'm marking this issue as resolved.
