### ISSUE TITLE
RDLibrary Cuts Sorting issue

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#580]
In Rivendell 3.3.0 on Centos 7 default install when you have multiple cuts in a cart and choose the "schedule by order" option, clicking on the order colum heading "sorts" the colum but not correctly.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in f51f39b.
