### ISSUE TITLE
py-compile missing

### ISSUE THREAD

**Issue by tonsofpcs** [ElvishArtisan/rivendell#581]
Attempts to make install 3.3.0 on debian 10 result in a failure in installing the pypad api.  py-compile does not appear to be in any debian packages.  pycompile does but does not appear to be the necessary item. 

`make[1]: Entering directory '/home/administrator/rivendell/rivendell-3.3.0/apis'
Making install in pypad
make[2]: Entering directory '/home/administrator/rivendell/rivendell-3.3.0/apis/pypad'
Making install in api
make[3]: Entering directory '/home/administrator/rivendell/rivendell-3.3.0/apis/pypad/api'
make[4]: Entering directory '/home/administrator/rivendell/rivendell-3.3.0/apis/pypad/api'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/lib/python3.7/site-packages'
 /usr/bin/install -c -m 644 pypad.py '/usr/local/lib/python3.7/site-packages'
/bin/bash: ../../../py-compile: No such file or directory
make[4]: *** [Makefile:388: install-rivendellPYTHON] Error 127
make[4]: Leaving directory '/home/administrator/rivendell/rivendell-3.3.0/apis/pypad/api'
make[3]: *** [Makefile:482: install-am] Error 2
make[3]: Leaving directory '/home/administrator/rivendell/rivendell-3.3.0/apis/pypad/api'
make[2]: *** [Makefile:423: install-recursive] Error 1
make[2]: Leaving directory '/home/administrator/rivendell/rivendell-3.3.0/apis/pypad'
make[1]: *** [Makefile:422: install-recursive] Error 1
make[1]: Leaving directory '/home/administrator/rivendell/rivendell-3.3.0/apis'
make: *** [Makefile:518: install-recursive] Error 1`

**Comment by tonsofpcs** [comment]
apis/pypad/api/Makefile includes `py_compile = $(top_srcdir)/py-compile` and `am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/py-compile`

**Comment by tonsofpcs** [comment]
Looks like perhaps I was missing some packages that needed to be installed before configure or make despite them not throwing errors.  I re-ran through the package installation instructions and it found a few, make clean, configure, make, make install still didn't do it.  Removing the tree and downloading the release from git seems to have allowed it to build and install just fine.

**Comment by wpope** [comment]
py-compile is set up by ./autogen.sh
