### ISSUE TITLE
Musicbrainz support - can't compil since 3.3.0

### ISSUE THREAD

**Issue by boozaa** [ElvishArtisan/rivendell#583]
Hello and thank you for your work.
I'm trying to compile latest sources under Ubuntu and i am faced off error during compilation about the Musicbrainz support.

I installed this support of Musicbrainz using this command:
`sudo apt-get install libdiscid-dev libmusicbrainz5-2 libmusicbrainz5-dev libcoverart-dev libcoverartcc1v5 libcoverart1`

The configure pass without any errors and print me that Musicbrainz support is "yes".

I have a lot of fatal errors like this one during the make process:
`rivendell-3.4.0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::ArtistCredit() const'`

And a long list all about reference to MusicBrainz5 and CoverArtArchive.

Have you any idea about how i can fix those errors ?
Perhaps you can link me to the libraries sources you use ?

Regards,

[rivendell.make.errors.musicbrainz.txt](https://github.com/ElvishArtisan/rivendell/files/4653467/rivendell.make.errors.musicbrainz.txt)

**Comment by dancebeatfm** [comment]
Hello boozaa.
Please, check this.
https://github.com/ElvishArtisan/rivendell/issues/578

**Comment by boozaa** [comment]
Thank you for your answer dancebeatfm, i missed this post.
Installing from source:

[libmusicbrainz5-dev](https://github.com/metabrainz/libmusicbrainz/releases/download/release-5.1.0/libmusicbrainz-5.1.0.tar.gz)

[libdiscid](http://ftp.musicbrainz.org/pub/musicbrainz/libdiscid/libdiscid-0.6.2.tar.gz)

Seems to solve those fatal errors, my compilation continues for instance.
