### ISSUE TITLE
PyPad UDP crash when ProcessNullUpdates not '0'

### ISSUE THREAD

**Issue by olvaar** [ElvishArtisan/rivendell#587]
The Pypad UDP script crashes when ProcessNullupdate is set to 1,2 or 3. When cartname = NULL

**Comment by ElvishArtisan** [comment]
What exactly is 'cartname' in this context?

**Comment by ElvishArtisan** [comment]
Closed due to no response.

**Comment by olvaar** [comment]
I send %a and %t via the pypad udp script.
For the groups where I send 'send now next' to NO .. It will send 2 Empty strings for %a and %t id ProcessNullUpdates is zero.

with ProcessNullUpdates set to 1,2 or 3 the pypad udp script stops with an errorcode, it returns an error, about a variable not being defined in some module. (it has been a while, i took a look at the code and the was indeed a branch if ProcessNullupdate was not zero)
With ProcessNullUpdate set to '0' it works. but is will send out %a and %t with zero length to my RDS system

Regards
Peter
