### ISSUE TITLE
rdairplay edit event cueCard and cuePort not set

### ISSUE THREAD

**Issue by wpope** [ElvishArtisan/rivendell#588]
rd airplay cueCard and cuePort setting have been removed from rdadmin.  The airplay hangs if the play button is clicked in event edit.  The airplay shuts down if the dialogue is forced shut.
If the card and port are adjusted in STATIONS via mysql then station runs as intended.
I also miss having the preview in add cart, would also use the same card and port.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 6cd1b3b.
