### ISSUE TITLE
BUG: Segue Fade out broken in version 3.3

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#590]
My RDAirplay is configured to have a forced segue (set via RDAdmin) of 4000 msec. In version, 2.19 it worked perfectly.  A hard stop at the top of the hour, to broadcast our legal id had the previous hour fading out over the legal id.  I upgraded to version 3.3 and the fade out quit working.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in cb9ee9a. Please test!

**Comment by jangittelman** [comment]
WIll do. Thank you
Jan Gittelman
(919) 740 - 5497

**Comment by jangittelman** [comment]
Tested. Works as desired.  Running RDAirplay for a week with no issues.

Thank you.
