### ISSUE TITLE
log render ignore no fade on segue.

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#592]
Tried using the Log Render feature for the first time today, and immediately noticed something: it seems to ignore the "No Fade On Segue" setting where active.

Was able to reproduce this behavior on both 2.19.2 and 3.4, which makes me wonder: am I doing it wrong (don't know what I could have missed), or have I found a long-standing bug (not likely)?

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 4840b75.

**Comment by RudiOnTheAir** [comment]
Fixed?
I've tried to render a voicetracked log, and notice that my ramptalks (voice) are fading out at the moment when the next track is started..

Tested on V4 beta (Ubuntu Studio)

**Comment by CWJR** [comment]
As ancillary to this, it would be very useful if the default for a cart's "No fade on segue out" could be changed from the hard-coded always off to always on.  Having to change each and every VT and imported music cart in our library could be simpler, as it is rare that we want that option off--not the other way around.

--Chuck
