### ISSUE TITLE
JACKSINK module for pulseaudio - Centos7

### ISSUE THREAD

**Issue by djaaynik** [ElvishArtisan/rivendell#594]
I have a problem finding the jacksink module for jackd in Centos7. Does anybody have the same issue. I searched everywhere and i can't find a compiled one.

**Comment by ElvishArtisan** [comment]
Does not appear to be in the CentOs or EPEL repos. You may have to build it yourself.

**Comment by ElvishArtisan** [comment]
Not a Rivendell issue.
