### ISSUE TITLE
PyPAD: new "NOW" data not written until segue is complete

### ISSUE THREAD

**Issue by kthelen** [ElvishArtisan/rivendell#600]
Not sure if this is the right place for this - if not, my apologies!

Finally got to try PyPAD recently (on v3.4.0). I notice that, while one cart is segueing into another, an update is sent with new "next" data - but the "now" data continues to show the cart that is ending, not the cart that just fired. Once the segue ends, another update is sent, with the "now" data showing the cart that just fired.

I previously used RLM in v2.x. In such a situation there, I was used to it providing "now" data for the cart that had just fired. That would be the preferred behavior for my use case.

Is this configurable somewhere - or, is there some other way of getting it to do what I'm looking for?

**Comment by ElvishArtisan** [comment]
Hmm. I'm not seeing that behavior here. I'm testing as follows:

1) In rdlibrary(1), Create three carts, each containing a 10 second test tone (I just used copies of the test tone included with all new installs of Rivendell). Call them 'Tone Cart 1', 'Tone Cart 2' and Tone Cart 3'. In 'Tone Cart One', put a Segue Start marker at 0:00:05.0 and a SegueEnd marker at 0:00:10.0.

2) In rdlogedit(1), create a log, looking like:
        SEGUE  Tone Cart 1
        SEGUE  Tone Cart 2
        SEGUE  Tone Cart 3

3) Open a shell and run the 'now_and_next.py' test script included in the Rivendell source tree by running the following commands:

        cd <top-of-rivendell-source-tree>
        python3 apis/pypad/tests/now_and_next.py

4) Start up rdairplay(1), set it to automatic, then load and then run the log you just created in its entirety. You should see the following in the shell window running the PyPAD script:

*** snip snip ***
001:xxxx NOW: [none]
001:0000 NEXT:  - Tone Cart 1

001:0000 NOW:  - Tone Cart 1
001:0001 NEXT:  - Tone Cart 2

001:0001 NOW:  - Tone Cart 2
001:0002 NEXT:  - Tone Cart 3

001:0002 NOW:  - Tone Cart 3
001:xxxx NEXT: [none]

001:xxxx NOW: [none]
001:xxxx NEXT: [none]
*** snip snip ***

Do you see different results?

**Comment by kthelen** [comment]
Finally got a chance to get back to the site where I observed this issue. Noted that that the host in question had been upgraded to v3.4.1 since I last saw it.

And, try as I might, I can no longer reproduce the issue.

So I guess this is no longer a concern. Sorry for the wild goose chase!
