### ISSUE TITLE
Groups selection in RDlibrary 3.4.1

### ISSUE THREAD

**Issue by olvaar** [ElvishArtisan/rivendell#605]
Hi,

One of my team has noticed that the group selection in Rdlibrary is not 100% 'clickable' from left to right.
The side where the dropdown arrow is, misses some 'clickablitity'. if you press direct on the arrow it does not respond.

Regards,
Peter

**Comment by deltecent** [comment]
I just noticed the same thing today.

I'll push a PR to fix it today or tomorrow.

Patrick

**Comment by ElvishArtisan** [comment]
Fixed in #607.
