### ISSUE TITLE
Altering RDcatch on a Client

### ISSUE THREAD

**Issue by olvaar** [ElvishArtisan/rivendell#606]
Hi,

I opened RDcatch on a client, to change an start-time.
But the server kept performing the task on the old start-time.
I opened RDcatch on an other client, there the start time was the new start time, so it was stored in the DB.
When I opened RDcatch on the server, there was also the new start time also, but only after 'save' was clicked, the task was preformed correct. It took the new time from the DB

Regards
Peter

**Comment by ElvishArtisan** [comment]
This is most likely due to a mis-configuration. Check that the IP address of your host(s) are correct in RDAdmin->ManageHosts.

**Comment by olvaar** [comment]
Fred,

That will be the problem. I run my personal 2 hosts via vpn. without a
fixed ip address.
That will be something that I will have to learn to live with, probably.

Regards
Peter

Op ma 10 aug. 2020 om 19:30 schreef Fred Gleason <notifications@github.com>:

**Comment by ElvishArtisan** [comment]
> That will be the problem. I run my personal 2 hosts via vpn. without a
fixed ip address.
> That will be something that I will have to learn to live with, probably.

There's more to it than that. Rivendell 3.x does a significant amount of its inter-host signalling by means IGMP multicasting. Most VPNs don't foward that kind of traffic.

**Comment by olvaar** [comment]
Owkay, I was wondering why there is a Multicast address for notifications
in the system-wide settings in version 3.
My Router is quite sophisticated, renewed it recently, there might be an
option to setup a IGMP proxy, for use over VPN.
I Will have to look into that.
If i remember correctly, in the older versions of the manuals, there was a
chart, with all the building blocks of the system, and the communication
between those blocks. Is there still something available like this ?

Apart from that issue, most of my hosts work pretty well over VPN.
I had to improvise during the corona lockdown. Most people now work from
their homes, voice-tracking, maintaining the database,etc.
I am very grateful for this.

Regards,
Peter



Op ma 10 aug. 2020 om 22:15 schreef Fred Gleason <notifications@github.com>:

**Comment by ElvishArtisan** [comment]
'Kay, I'm closing this for now then,
