### ISSUE TITLE
Bug: Binary in SO RML being converted to date

### ISSUE THREAD

**Issue by AaronHorn** [ElvishArtisan/rivendell#609]
Hello, I think I have found a bug which has appeared either in 3.3 or 3.4.

I have an old BroadcastTools 2.1 switcher.  To control it you have to send a message of:

*201 (input 1)
*202 (input 2)
*20m (mute)

Via serial.

Previously, I had a macro with RML of: SO 0 %2a201! which accomplished this. It worked fine in 3.2 (I think it was this version).  In fact, if I sent this from the command line using rmlsend --from-file= this works fine.

However when I program this as a macro in rdlibrary in 3.4, it doesn't work.  Per the log, it appears %2a (eg binary for *) is being converted to a day (I assume with the new date delta feature) and I get this in the log:

Aug  8 04:00:00 rdairplay1 ripcd: received rml: "SO 0 sat202!" from 192.168.2.2

I believe this to be a bug.  How do I send binary data to the serial port?

P.s. I couldn't get the built in code for the switcher to work (I think mine might be an older version) so it was simpler just to send the commands via serial.

**Comment by ElvishArtisan** [comment]
Yes, RML statements in a macro cart are subject to to interpretation of [Metadata Wildcards](http://opsguide.rivendellaudio.org/html/appendix.metadata_wildcards.html#sect.metadata_wildcards). To pass a literal '%' to the actual RML engine, just double it --i.e. '%%'.

**Comment by AaronHorn** [comment]
So if I enter %%2a to the macro, it will pass %2a to the RML engine which will in turn pass 0x2a (*) to the serial port?

I’ll give it a go but assuming it works I’d suggest the documentation for Binary Data be updated and perhaps something added to the ChangeLog to reflect when this change of behaviour occurred.

**Comment by ElvishArtisan** [comment]
> So if I enter %%2a to the macro, it will pass %2a to the RML engine which will in turn pass 0x2a (*) to the serial port?

Correct.


I’ll give it a go but assuming it works I’d suggest the documentation for Binary Data be updated and perhaps something added to the ChangeLog to reflect when this change of behaviour occurred.

Already done in b2731d6.
