### ISSUE TITLE
BUG: RML LL has problems with case sensivity, loads only first cart

### ISSUE THREAD

**Issue by prometoys** [ElvishArtisan/rivendell#61]
#### How to reproduce:
1. Create a new log "Test" with multiple carts/lines.
2. Run: rmlsend "LL 1 TEST"!
#### Expected outcome:

RDAirplay load the log "Test" or load nothing.
#### Actual outcome:

RDAIirplay loads only the first cart/line from the log "Test".
#### Suggestion:

Save all log names uppercase by default. If user types lowercase table names, then convert them to upper case either during input  or when saving log to database.
#### System:

Debian Wheezy, MySQL 5.5.38-0+wheezy1, RD 2.10.2

**Comment by ElvishArtisan** [comment]
Fixed in [master c170dc3].
