### ISSUE TITLE
Strange behavior with multiple services on Events and Clocks

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#617]
This system has the following defined services: kfhl, Production, wgtt.
Hosts are defined as ffrnserver, kfhl, wgtt.
Enabled Hosts for each service are kfhl/kfhl, Production/ffrnserver, wgtt/wgtt

When adding a new event, or a new clock, If i choose "Production" for the service and close it, when I re-open it for editing I find that my enabled Services List is:     kfhl, Production, Production, wgtt.

Currently I only want "Production" to be chosen. Not sure if I have something mis-configured or if this is the desired behavior.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 7a48deb.
