### ISSUE TITLE
Macro cart binary being interpreted as date formatting?

### ISSUE THREAD

**Issue by kthelen** [ElvishArtisan/rivendell#623]
Fresh install of 3.4.1 on CentOS 7 (via rivendell-install).

"UO x.x.x.x yyyy TEST%0A!"

When I send this command using rmlsend, it works properly - the word "TEST" followed by a newline is received.

When I send this command from within a macro cart, different result - "TESTfriday", without a newline, is received.

For what it's worth, I double-checked the applicable row in CART, and the command appears exactly as I entered it.

It's as if the format sequences from date(1) are being applied to macro carts.

**Comment by AaronHorn** [comment]
I believe this is the same as 609 - you need to use a double % in RDLibrary to have a single % sent through to the rmlsend engine. 

Duplicate of #609

**Comment by kthelen** [comment]
Double percent solved it. Thanks!
