### ISSUE TITLE
RDAirplay not loading log on startup

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#626]
Version: 3.4
Schema: 317
OS: Centos 7.8

When the system reboots rdairplay is started and the current days log is loaded. Occasionally, this started failing leaving us with dead air. I changed the rdairplay configuration to load 'previous' and the reboot started failing regularly.  

On my development system,  load previous appears to work fine as does specifying the log (but of course, it's not monitored the way production is).  Other things of note: while the dev and production box are the same version, schema, and os, they are not the same hardware. AND, I noticed the rd-default.conf is not the same on the systems even tho' I just use the default config.  Note: matching the configs (Dev boxes config was 4 months older) didn't break dev, but it did turn on the dev's logging.

Anyone else having this issue?

**Comment by ElvishArtisan** [comment]
What part of it exactly is failing? The rdairplay(1) startup? The log loading? The play-out startup? Something else?

**Comment by jangittelman** [comment]
Sorry for not being clearer.  RDAirplay starts up just fine. The log doesn’t load. Sometimes, the log will partially load; sometime it doesn’t load at all. It never starts.

-jan

Jan Gittelman
(919) 740 - 5497

**Comment by jangittelman** [comment]
More Information: If the start up log is set to previous (via RDAirplay configuration in RDAdmin), it always fails. If the startup log is set to empty and a script loads teh current days log on boot up, sometimes it works sometimes it fails. Until this version, the script has worked.

**Comment by jangittelman** [comment]
The mysql database on production is corrupted. I'm guessing this problem will go away or change characteristics once the database is repaired.
