### ISSUE TITLE
Talk-up Time Always :00 if Dropped or Add until Event Is Played

### ISSUE THREAD

**Issue by CWJR** [ElvishArtisan/rivendell#630]
In RD AirPlay v3.4.1 when an event is either dragged and dropped or entered with the Add button, the Talk-up time appears as :00 regardless of what it actually is.  And that :00 continues as it makes its way up the cart slots until reaching the top and activated into play.

--Chuck Waggoner

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 'master' and 'qt5'.
