### ISSUE TITLE
Duplicate Cart Titles

### ISSUE THREAD

**Issue by wpope** [ElvishArtisan/rivendell#633]
will the depreciating of "disallow duplicate cart titles" cause issues if I have the same song from various artist in my database?  Ie. Silent Night 119 entries.  I really don't want an "title number" in my RDS playlist.
Walter

**Comment by ElvishArtisan** [comment]
No, it will have no effect on that at all. The default in Rivendell has always been to *allow* duplicates. The feature in question was developed for a very specific use case; one that requires that Rivendell be used in certain very stereotypical ways. AFAICT, it has only ever been used at a single site (where they are well aware of the limitations regarding its use).

**Comment by wpope** [comment]
Thanks Fred.   I misunderstood the direction of change.
