### ISSUE TITLE
Single Quote Not Accepted in RDAirplay "Add" Dialog

### ISSUE THREAD

**Issue by CWJR** [ElvishArtisan/rivendell#638]
A single quote--or apostrophe--is not accepted in the search field of the “Add” dialog in RDAirplay.  Makes entering contractions impossible.  This is not a problem in Library.

--Chuck Waggoner

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 'master'.
