### ISSUE TITLE
Rivendell 3.5 Log Auto Refresh issue + RML Trigger Macro Cart issue

### ISSUE THREAD

**Issue by woody0991** [ElvishArtisan/rivendell#639]
I am having 2 issues with Rivendell.

Firstly, for some reason the log files are not auto-refreshing. I have 2 separate machines, one performing voice tracks and the other playing out the shows. If I record a voice track on one machine, the log does not auto refresh on the other. The refresh button does seem to show, but when clicked this also does nothing. I have also tried to send an RML command to refresh the log and this also fails.

Secondly, There seems to be an issue triggering a macro cart that fades out the main log and starts another. I had this working on one Rivendell machine attached to a sound card, but the ones connected to JACK do not seem to work. I can see the command is received in the log but the cart is never triggered. (EX <CART NO>! RML command)

Let me know if you want any logs to investigate these issues.

**Comment by ElvishArtisan** [comment]
> Firstly, for some reason the log files are not auto-refreshing. I have 2 separate machines, one performing voice tracks and the other playing out the shows. If I record a voice track on one machine, the log does not auto refresh on the other. The refresh button does seem to show, but when clicked this also does nothing. I have also tried to send an RML command to refresh the log and this also fails.

This is almost certainly a local configuration problem, as this feature is known to be currently working at multiple sites with v3.5.0. The most common cause for these sorts of issues is specifying an incorrect/invalid IP address for the host(s) in RDAdmin->ManageHosts.


> Secondly, There seems to be an issue triggering a macro cart that fades out the main log and starts another. I had this working on one Rivendell machine attached to a sound card, but the ones connected to JACK do not seem to work. I can see the command is received in the log but the cart is never triggered. (EX ! RML command)

We're going to need a lot more information about what exactly it is you're trying to do. At a minimum, the precise RMLs that you're using.

Also, please open a separate issue in GitHub for each anomaly. This makes it *much* easier to track the progress of anomalies.
