### ISSUE TITLE
Bug: Exporting file will delete markers

### ISSUE THREAD

**Issue by elmuz** [ElvishArtisan/rivendell#64]
The guys found a bug using RDLibrary, which deletes talk/segue markers each time you export that cut.
In order to reproduce this bug simply:
- Take cart, choose one cut and set some markers.
- Try to export it and save it somewhere.
- Go back in Edit Markers.
- Magically Talk and Segue markers disappeared. Cut markers remeained.
Bug confirmed on both 2.9.2 and 2.10.3. Both stations are based on Debian 7 with Tryphon repositories.
Here's a link for a video showing the bug https://youtu.be/hW27OTHxJts

**Comment by ElvishArtisan** [comment]
Fixed in master.
