### ISSUE TITLE
Debian stable .deb Packages (10/Buster at this time)

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#644]
Hi community.... I'm very indeterted in this software...

I have managed to build in Debian10 / Buster following the instructions, but I would like to build a Debian package instead of installing a whole dev-environment on every machine and make install the built sources.

I'm failing to build deb packages (I've tried with dh-make/debuild and also gave chekinstall a try once I gave up... no success)

I've seen that time ago there were Ubuntu .deb packages for the v2 version of Rivendell.

Has anyone managed to create .deb packages for some 3.x version?

**Comment by edgeradio993fm** [comment]
I have pre-built Debian 10 packages here: https://github.com/edgeradio993fm/rivendell/releases/tag/3.5.0-1
Also have an automated installation script for Debian 10 here: https://github.com/edgeradio993fm/rivendell/wiki/Automated-Installation

**Comment by alexolivan** [comment]
Awesome.... Thank you very much!

Does your package include support of AudioScience HPI cards?
I have built AudioScience HPI (and also ALSA) .deb driver packages, (they build out-of-the-box now from official released Linux drivers, using pbuilder), including dev package.
I installed the hpi dev package, and .configure detected HPI support and make ran just fine.... so it is feasible. 

I wonder the sources would include necessary stuff to ease the creation of Debian packages.

Best regards

**Comment by alexolivan** [comment]
I'm making progress.... but I'm stuck as my build ends here:

rdadmin.cpp:74:72: error: format not a string literal and no format arguments [-Werror=format-security]
     fprintf(stderr,QString().sprintf("rdadmin: %s\n",(const char *)str));

I've tried the -Wno-format-security flag with no success, though...

**Comment by edgeradio993fm** [comment]
Oh what fun. A compilation error. I've never encountered that error before. Are you doing a fresh compile? Unfortunately since I mostly work on ARM devices there isn't much call for the HPI drivers. If you upload your compiled HPI deb files I can make a package with them if you like.

**Comment by alexolivan** [comment]
Sure I wish to share them! Thank you SO much! It would be great if you could add HPI support on your .debs :-D  ... My concern but is that I want to be strictly polite with licensing (and licensing is often quite confusing to me and makes me feel unsafe on what I can/can't do):  While AudioScience makes publicly available for download their Linux driver .tar.gz here https://www.audioscience.com/internet/download/linux_drivers.htm , which now includes noob-proof (Yay! :-) Debian .deb packaging/creating procedures , I'm not sure whether is fine if I upload and make publicly available the resulting .deb packages... What I'm going to do is to mail them and ask them whether I could share this .debs!!! if they approve I will upload them!!! 

Regarding your question: Are you doing a fresh compile? ... well, I think yes, I do (well, I apply the patch as pointed in the Debian 10 install guide), but, the key thing is that, when I just perform make from terminal, the sources do build... I mean, I could do make install thereafter.
The problem appears as I try to apply what I've learn (I'm still learning) to build my .debs... I do using dh_make and then calling debuild ... its then, when the building fails.

I have managed to bypass the format-security error, by adding in debian/control -Werror=0 as aditional CFLAGS , but then I struck another build error (It was too late yesterday night, I will retry and try to deal with it).
My guess is that debuild is creating a very different, more restrictive, build environment, than the usual terminal/shell one, which leads to warnings being treated as errors ... I have to try to learn how to handle that, but its hard for a noob :-P

Will update!
Best regards!

**Comment by alexolivan** [comment]
Got it to build and assemble the .deb packages.
I forget about ignoring errors and went the way of handling them one by one (bare minimum changes to avoid warn fail).
A summary of what I changed follows:

rdadmin/rdadmin.cpp:74:72
- fprintf(stderr,QString().sprintf("rdadmin: %s\n",(const char *)str));
+ fprintf(stderr,"%s",QString().sprintf("rdadmin: %s\n",(const char *)str));

tests/datedecode_test.cpp:88:31
- fprintf(stderr,err.ascii());
+ fprintf(stderr,"%s",err.ascii());

tests/reserve_carts_test.cpp:97:31
- fprintf(stderr,err.ascii());
+ fprintf(stderr,"%s",err.ascii());

tests/test_pam.cpp:56:12
- fgets(resp[i]->resp,256,stdin;
+ if (!fgets(resp[i]->resp,256,stdin)) {
+    continue;
+ }

tests/log_unlink_test.cpp:93:31
- fprintf(stderr,err.ascii());
+ fprintf(stderr,"%s",err.ascii());

/utils/rdalsaconfig/rdalsamodel.cpp:280:38
- fprintf(f,model_other_lines.at(i));
+ fprintf(f,"%s",model_other_lines.at(i));

/utils/rdalsaconfig/rdalsaconfig.cpp:47:13
- system("systemctl --quiet stop rivendell");
+ int sysRetCode = system("systemctl --quiet stop rivendell");
+      if( sysRetCode == -1) {
+        fprintf(stderr,"rivendell failed to stop?");
+      }

/utils/rdalsaconfig/rdalsaconfig.cpp:57:11
- system("systemctl --quiet start rivendell");
+ int sysRetCode = system("systemctl --quiet start rivendell");
+   if( sysRetCode == -1) {
+     fprintf(stderr,"rivendell failed to start?");
+   }
+ }

Now but, I want to re-do everything using quilt, including the patch at updateschema.cpp ... so I will have all that changes handled the right way... Still a olt to learn regarding packaging :-P

Regards!

**Comment by ElvishArtisan** [comment]
Not much point in including HPI support on ARM. AFAICT, it's not an AudioScience supported architecture.

**Comment by edgeradio993fm** [comment]
Yep. A few ARM boards have PCI-E support. Not a market AudioScience needs to worry about. Class Compliant USB interfaces are a safer bet in this department.
