### ISSUE TITLE
RDLibrary bug on multi cart edit

### ISSUE THREAD

**Issue by elmuz** [ElvishArtisan/rivendell#65]
A guy just found a bug on RDLibrary which I think it hasn't been reported yet. When you change GROUP to many carts at once using RDLibrary you will loose the year information on every cart.
In order to reproduce the bug you can simply do the folllowing:
- Open RDLibrary
- Select more than one cart
- Edit
- Change GROUP.

What happens:
- Group has changed, but Year field in every cart has been lost.

**Comment by ElvishArtisan** [comment]
Fixed in master.
