### ISSUE TITLE
dadpro-import.pl

### ISSUE THREAD

**Issue by egnarskit** [ElvishArtisan/rivendell#652]
We are only getting Title and Artist data while running this with .wav and .mp3

 files from our enco library. We get title and artist data only using the regular import. Not sure this importer works with the current enco systems. Test file attached.
[encodadwav.zip](https://github.com/ElvishArtisan/rivendell/files/6298203/encodadwav.zip)

**Comment by ElvishArtisan** [comment]
```dadpro-import.pl``` gets metadata from Enco's ```CUTS.DBF``` file, not the audio file. As for your sample file, it contains a Cart chunk with just the TITLE field populated with the string 'Collaborative Divorce', so I would not expect 

Include the ```CUTS.DBF``` file that goes with this file and me may be able to get more meaningful results.

**Comment by egnarskit** [comment]
Thanks for the prompt reply! I am one step closer it seems! Now when I put in the code in terminal each cut says "no audio, skipping..." This is the code I am inputting into Terminal:

dadpro-import.pl --dbf-file=CUTS.DBF --first-cut=7404 --last-cut=7405 --cart-offset=0 beds

Where do the cuts need to be placed for the script to see them? I think the one part of the code I am missing is the <cuts-dir> but no matter what I type there I get a invalid argument error or the same result with audio file missing. Right now, I have the Cuts I want to add, located in the same folder as the CUTS.DBF file on the Rivendell System. I am running Terminal from that directory as well.

**Comment by egnarskit** [comment]
*The one part of the code I am missing is "cuts-dir"

**Comment by druidlabs** [comment]
I think you need to explicitly code the cuts directory on the command
line.  I think just "." will work.

Looking at the script at
https://github.com/ElvishArtisan/rivendell-importers/blob/master/audio/dadpro-import.pl.
The script uses the directory as-is, there is no default.  So it ends up
looking for its import files in "/", not the current directory.

Mike

**Comment by egnarskit** [comment]
"." said no audio skipping. I also tried: dadpro-import.pl --dbf-file=CUTS.DBF --first-cut=7404 --last-cut=7405 --cart-offset=0 beds /home/rd/Downloads/test/

That also said no audio skipping. I see there is a .mp2 in the script. I don't know much about scripting. Do my files need to be .mp2? Mine are .WAV and .MP3.

**Comment by egnarskit** [comment]
I changed one file to .MP2 and that worked. How do I change the script to work with .WAV and .MP3 or is this not possible?

**Comment by druidlabs** [comment]
Sure, why not?  As we used to say at my old day job, "It's only code".
<smile>

You need to locate the script, then edit it.  (I don't have
rivendell-encoders installed, so these are generic instructions.)  Assuming
a CentOS 7 appliance install:

   1. Open a Terminal session.
   2. Locate the script with the "find" command: find / -name "
   dadpro-import.pl" 2>/dev/null
   3. I assume the scripts are installed into a "protected" directory such
   as /usr/local/bin, and will need superuser access to change them.  Enter
   the "su" command and reply with the root user's password.
   4. Edit the script using the "gedit" command.  You can also use "nano"
   or even (shudder) "vi".

Good luck!

Mike

**Comment by egnarskit** [comment]
What script am I locating? dadpro-import.pl? I am able to edit that script but changing .MP2 to .WAV does not fix the issue. I still get no audio skipping.

**Comment by druidlabs** [comment]
Yes, the find command is locating the dadpro script.  I don't know where
this script gets installed, and in case you didn't know either this command
tells you where it is.

The only thing I can think of is that perhaps the .wav file extension on
your files is a different case than what the script is looking for: WAV vs
wav for example.  You might change the "no audio" printf command to also
include the value of the $cutpath variable, which has the filename the
script is looking for.  That will give you some visual feedback on what the
script is doing.

Mike

**Comment by ElvishArtisan** [comment]
> I changed one file to .MP2 and that worked. How do I change the script to work with .WAV and .MP3 or is this not possible?

It's been a few years since I've had a real live Dad system to play with, but back in the day, all audio files used by Dad were BWF wavefiles, even though, on some systems, they could have unusal file extensions ('.FIL' is one I remember). The script is hard coded to use ".MP2", but this can easily be changed (see line 227).

**Comment by egnarskit** [comment]
I changed that line and it still could not recognize the files for some reason.  I ended up converting the files to .mp2 then using the Bulk Rename tool to switch their name to end in .MP2. This worked great. All the information we needed was inserted into the library. Thanks for the help!
