### ISSUE TITLE
Cannot compile rdxport.cpp in Rivendell 4 QT5 code base

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#655]
rdxport.rdd fails compilation:

rdxport.cpp: In member function ‘void Xport::XmlExit(const QString&, int, const QString&, int, RDAudioConvert::ErrorCode)’:
rdxport.cpp:468:27: error: cannot convert ‘const QString’ to ‘const char*’ for argument ‘1’ to ‘void RDXMLResult(const char*, int, RDAudioConvert::ErrorCode)’
   RDXMLResult(str,code,err);

**Comment by ElvishArtisan** [comment]
Ah, I see what happened. This gets goosed only if one doesn't give the ```--enable-rdxport-debug``` switch to ```./configure```.

Fixed in c5ab833. Please test!

**Comment by WMTH** [comment]
The fix works, rdxport and the balance of the code compiles successfully.

**Comment by ElvishArtisan** [comment]
Thanks.
