### ISSUE TITLE
Qt5 .deb packaging errors [Solved]

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#657]
Hi all.

Qt5 .deb packaging is almost out-of-the-box with the commits of the last week.
Still I needed to quilt/patch 4 files due to debuild compile options throwing [-Werror=format-security] errors in just 4 files... I just bypassed the warn/errors like this (probably not the best way):

```
rdadmin/rdadmin.cpp:63:27
   - fprintf(stderr,QString().sprintf("rdadmin: %s\n",(const char *)str));
   + fprintf(stderr,"%s",QString().sprintf("rdadmin: %s\n",(const char *)str));

tests/datedecode_test.cpp:88:31
   - fprintf(stderr,err.toUtf8());
   + fprintf(stderr,"%s",err.toUtf8());

tests/log_unlink_test.cpp:87.32
   - fprintf(stderr,err.toUtf8());
   + fprintf(stderr,"%s",err.toUtf8());

tests/reserve_carts_test.cpp:90:32
   - fprintf(stderr,err.toUtf8());
   + fprintf(stderr,"%s",err.toUtf8());
```

Hopefully those fprintfs could be updated in the future.

Best regards.

**Comment by ElvishArtisan** [comment]
Fixed in a217f43. Please test!

**Comment by alexolivan** [comment]
Didn't had the time to let debuild perform a clean / complete rebuild ... just poped out my patches, merged, and rebuild with not clean option (still, due to the many SQL commits it rebuild a lot of stuff) ...so far, so good!!!  I would say it's solved!

Thanks.
Regards.

**Comment by ElvishArtisan** [comment]
Thank you.
