### ISSUE TITLE
[Possible Bug + fix] RDLibrary window process External Editor 

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#659]
Hi... I've noticed that whenever an external editor is setup for a host (like this: audacity %f), if the feature is used (edit a cart , then the cut, then click the editor) the RDLibrary parent window cannot be closed anymore.

I've checked in console for rdlibrary processes and I've noticed that a second process is started upon editing, so my guess is that the parent window PID is somehow messed, so the taskbar close button fails to close the correct PID (just my guessing)
Killing the PID closes the window and no problems so far.

I have tried using some TTY detach tricks on the external editor command RDAdmin configuration field (like nohup, disown, ()$, etc) but they just prevent the editor to opening at all.

Regards.

**Comment by alexolivan** [comment]
Hi again.... 
I've being playing with this a while and I have found a workaround to make the external editor to work nicely with rdlibrary.

The trick was basically replacing fork() with vfork().
I've also tried to ensure a completely independent and immediate external editor spawning... I have just tried with audacity at the moment, I would try other editors to check for consistent results .... anyways here're my changes:

rdlibrary/audio_cart.cpp

  - if(fork()==0) {
  -  system(cmd+" &");
  -  exit(0);
  - }
  + if(vfork()==0) {
  + system("(setsid "+cmd+" >/dev/null 2>&1 &)");
  + }

Best regards.

**Comment by ElvishArtisan** [comment]
That's a ticking time bomb, on a couple of fronts. First, by removing the ```exit(0)```, you now have an additional process left around, one that will have inherited various things from its parent (see the ```fork(2)``` man page for the gory details). Second, ```vfork(2)``` is really just a performance hack on Linux; arguably, the only safe use for it is for immediately calling ```execve(2)``` afterwards (which might actually be a good way to properly fix this).

I agree that the current code is broken. If possible, I'd rather fix this using ```QProcess``` as that is the Qt-native way of doing this sort of thing, whereas as the ```exec()``` family of calls can be notoriously tricky to get right, with all sorts of fiddly edge cases.

**Comment by alexolivan** [comment]
Hi! .... I'm far from an experienced C++/Qt devel so can't help, sure you'll find the best way. 

Anyways, but, during my tests I was monitoring the rdadmin processes closely with 'ps auxf' (the child process spawned by fork was the problem... the QWidget close button killed the wrong pid, if I killed the child, everything went well) and I failed to see a rogue rdlibrary process around. 
When I read about vfork() I thought it would rather make things worse... but since other things I tried failed, I just gave it a shot. Upon trying, the first thing that happened is that the exit(0) caused the whole RDLirary to close (I guess, it killed the parent), although the editor managed to start...  I was cofused but, well, I'm just a noob... so I just removed it, tried, and, tada! it worked!
So, that's why I removed it...

I will try to purposelly create a rogue or zombie process, maybe passing wrong command to system(), opening the editor multiple times...will try... although, most of the stuff I found googling around the matter, as you stated, pointed to QProcess.

Anyways, thank you very much.
Best regards!

**Comment by alexolivan** [comment]
Have we some update on this? ... I think that, in the meantime (or even definitely) it would be better to just disable or remove the open external editor button, rather then having RDLibrary freezed.

In adition, whenever you edit directly an audio file on /var/snd with audacity (the one I tried) the cut gets screwed (I guess the hash doesn't longer match or something) so, unless an easy way to automatically re-import upon exiting the editor (I can't imagine how this could be possible) would exist, I don't really see this button being nothing but a potential source of problems.

Cheers.

**Comment by alexolivan** [comment]
Ok... saw a coomit that point to this old one!

My nightly builds should allow me to upgrade and test tomorrow... will close this issue ASAP.
