### ISSUE TITLE
[Possible Bug + fix] Unable to add any non-Serial/IP GPIO device

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#660]
I'm trying to setup a Local Audio Apdater switcher/GPIO, but this is impossible, since the form triggers a "primary serial device not active!".
Although both Primary and Secondary Connections sections are greyed out, the Primary Connection field 'Type' has value 'Serial', whereas secondary has type 'None'.

If not mistaken, this could be the reason why error is triggered as case (line 1194 of edit_matrix.cpp) is met for a TTY type matrix.

I don't understand the logic behind rdmatrix.cpp boolean matrices values, but, shouldn't __mx_primary_controls and __mx_backup_controls both match their values? Why I get type 'Serial' for primary and 'None' for secondary?

Best regards.

**Comment by alexolivan** [comment]
I have updated the issue .... Still not confirmed.
I have to test whether once workaround the problem the issue is gone, so the bug would be confirmed.

The problem is that, Local Audio Adapter (but in my tests I have noticed other GPIO such virtual and I think another) cannot, in any way be added to a host in RDAdmin... I'm not sure, because my bet is that others should have noticed about such problem.

By commenting out the following TTY check (very , very, ugly!) at edit_matrix.cpp, about line 1204

      QMessageBox::warning(this,"RDAdmin - "+tr("Invalid Address"),
                           tr("The primary IP address is invalid!"));
      return false;
    }
    break;
       
  case RDMatrix::TtyPort:
    //tty=new RDTty(rda->station()->name(),edit_port_box->currentIndex());
    //if(!tty->active()) {
    //  QMessageBox::information(this,"RDAdmin - "+tr("Error"),
                              // tr("The primary serial device is not active!"));
    //  delete tty;
    //  return false;
    //}
    //delete tty;
    //break;

  case RDMatrix::NoPort:
    break;
  }

It all works again.

I think the problem is that the last case, RDMatrix::NoPort: never matches, no matter what... because any non TCP/IP Type gpio matches the TTY... I have to check whether setting RDMatrix::NoPort case first would solve the issue

Best regards

**Comment by ElvishArtisan** [comment]
Confirmed here.

This is due to a (completely misguided) attempt of mine to deal with situations where a serial device is required for a working switcher --e.g. most Broadcast Tools switchers. At this point, I'm inclined to just rip out the entire thing.

**Comment by alexolivan** [comment]
Amazing!

Thank you very much.... will try for sure!
