### ISSUE TITLE
Feature Request - 'Auxiliary' VuMeters on RDAirplay

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#665]
Hi.
Since I'm seeing several suggestions here... well, here's one of mine:
I'm missing very much not being able to visually see actual sound metering on RDAirplay other than for the Main Log... It's kinda strange to me just 'believe' an Aux log is playing out.
Sure, we can send Jack outputs to some intermediate app to act as mixer, such as Ardour, JackMixer, etc... but I really miss that.
Curiously to me, the rest of the UI seems monitored as expected... RDCatch, RDCartSlots, RDPanel... you always have a matering on the output... but this is not that way for RDAirplay.

I feel the UI design of RDAirplay was ver deterministic and very 'Main Log' focused/centered .... but I very would like to have, even by using the only available Main-Log top VuMeters, an option to enslave them to the 'currently selected Log'.
So, If Main Log is selected, then VuMeters monitoring the Main Log as usual, and whenever another Log is selected, then VuMeters  switch to monitor the selected LogMachine output.

Ideally though, I think the UI should have two sets of VUMeters... the fixed,  'Main' VUMeters, as originally designed and are right now, along with another 'Auxiliary' set of VuMeters, over the log / button-panel widget, to monitor the output of currently selected Aux log / Button Panel

Regards!!!

**Comment by ElvishArtisan** [comment]
Ok, I've taken this idea and run with it a bit. Check out the "new" rdairplay(1): instead of a 'main' meter that reflects the sum of audio played from the Main Log, we now have a 'strip' of meters, one for each configured audio output. The label under each meter can be configured in RDAdmin->ManageHosts->AudioPorts.

**Comment by alexolivan** [comment]
What? WOW!!!! ... I mean WOW!!!

I'll check that as soon as I can (now I'm learning the pypad stuff...which is amazing!)

Best regards

**Comment by ElvishArtisan** [comment]
Yeah. Now that all the Qt5 porting and SQL remediation drudgery is done, we can finally start focussing on the ''fun stuff'.
:)

**Comment by alexolivan** [comment]
Really appreciate the implementation of the feature.

Thank you!
