### ISSUE TITLE
Dropbox 'crashes'

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#668]
Hi!
I'm testing performance on the dropbox system by making an old Athlon PC / 4GB Ram to 'ingest' around 900 files of music... and I'm overall very very impressed .... but the problem is that the dropbox 'crashes' and resetting it doesn't make any effect.

To debug it, I tailed to console the syslog and, upon resetting, I saw the cause being that the import segfaults as it reaches certain file that, for format reason, it can't import.

I don't know if this is the desired behaviour (the bulk import getting stuck in the offending file) or the segfault being some unhandled exception that could be avoided and prevent the process to die.... reporting just in case.

**Comment by alexolivan** [comment]
Sure you'll have .... I'm not right now home.... will do ASAP.

Best regards.

**Comment by ElvishArtisan** [comment]
Got the file .. thanks!

The file is (as suspected) corrupt. Specifically, it's got a bunch of 0xFF bytes, interpersed with blocks of seemingly random data, sandwiched between the end of the ID3 tag and the start of the MPEG frame data. Even file(1) is unable to identify it as an MPEG file.

However, I am unable to reproduce the segfault problem on v3.6.0. From syslog:

>May 27 10:00:21 elastigirl dropbox[16]: rdimport started
May 27 10:00:21 elastigirl dropbox[16]: RDImport v3.6.0
May 27 10:00:21 elastigirl dropbox[16]: Force to Mono is OFF
May 27 10:00:21 elastigirl dropbox[16]: Normalization is OFF
May 27 10:00:21 elastigirl dropbox[16]: AutoTrim is OFF
May 27 10:00:21 elastigirl dropbox[16]: Destination cart is AUTO
May 27 10:00:21 elastigirl dropbox[16]: Single cart mode is OFF
May 27 10:00:21 elastigirl dropbox[16]: Delete source mode is ON
May 27 10:00:21 elastigirl dropbox[16]: Delete cuts mode is OFF
May 27 10:00:21 elastigirl dropbox[16]: DropBox mode is ON
May 27 10:00:21 elastigirl dropbox[16]: Start Date Offset = 0 days
May 27 10:00:21 elastigirl dropbox[16]: End Date Offset = 0 days
May 27 10:00:21 elastigirl dropbox[16]: Broken format workarounds are DISABLED
May 27 10:00:21 elastigirl dropbox[16]: E-mail reporting is DISABLED
May 27 10:00:21 elastigirl dropbox[16]: Import Create Dates mode is OFF
May 27 10:00:21 elastigirl dropbox[16]: Persistent DropBox ID = 16
May 27 10:00:21 elastigirl dropbox[16]: Files to process:
May 27 10:00:21 elastigirl dropbox[16]: "/home/fredg/dropbox/*"
May 27 10:00:56 elastigirl dropbox[16]: File "Culture Beat - Mr. Vain 2003 (Starsplash Remix).mp3" is not readable or not a recognized format, skipping...

Which is the expected output, and behavior.

What dropbox settings are you using?

**Comment by ElvishArtisan** [comment]
That got it! Confirmed here,

**Comment by ElvishArtisan** [comment]
Fixed in 62a3075 and dd5eaa1. Please test!

**Comment by alexolivan** [comment]
Wow! ... thanks ... I will rebuild and test!!!

**Comment by alexolivan** [comment]
I have tested with exactly the same options and exactly same offending files:
This time 2 aout of the 4 files (malformed) where successfully imported.
No crash.

Confirmed fixed!
