### ISSUE TITLE
Consolehelper associated applications no longer working

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#677]
In Rivendell 4.0 beta 1, compiled in a CentOS 7 environment, applications dependent on Consolehelper fail with a message box stating "unknown error".  Further certain files such as rddbconfig-root are not installed in/etc/pam.d.  To solve on an interim basis, I have manually configured the required facility to mirror previous builds and the applications function correctly.  The issue was introduced in 4.0 beta 1, previous builds installed and functioned as designed.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 8a5080a. Please test!

**Comment by WMTH** [comment]
Confirmed working following fix.

**Comment by ElvishArtisan** [comment]
Thanks!
