### ISSUE TITLE
Carts don't show the "talk" time properly when dragged in or added via "Add" button

### ISSUE THREAD

**Issue by electricurrent** [ElvishArtisan/rivendell#681]
When going live and adding carts on the fly, the "talk" time will always show ":00" until the log refreshes by having the next cart play, then the talk time shows the proper time. I don't believe it used to be an issue? Or maybe I just never noticed it, but it's something I find mildly annoying.

**Comment by deltecent** [comment]
This was fixed in 3.6.0.

**Comment by CWJR** [comment]
Confirming that it is not a problem in 3.6.1.

**Comment by deltecent** [comment]
I updated @electricurrent to 3.6.1 and can confirm that this problem has been resolved. This issue can be closed.
