### ISSUE TITLE
Dark-Mode GUI issues

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#683]
Hi again.

I'd like to report on some minor issues to help polish the Dark-Mode experience (waaaay nicer it looks awesome! :-)

- RDLibrary: The 'lenght' field on single-cut carts seems to be hardcoded in black, making the reading difficult. Interestingly, the very same field is depicted white, reading perfectly, when the cart has multiple cuts.
- RDCatch: Events font color on unselected events seems to be hardcoded to black. Active / Next / Failed, etc events are less of a problem since the event background changes to some color. Interestingly, the upper section of the module, where the Decks, VUmeters, etc. looks perfect!
- RDAirplay: This issue may (not sure) affect on other modules, but it is in RDAirplay where it is evident, The Log / SoundPanel Buttons (The ones to switch the widget content) do lost their Coloring and 'pressed texture' features ... they look flat, all the same, so they lost their capability to tell the 'current status' of the widget. By comparison, in non-dark mode the buttons do nicelly paint in blue and look clearly active/non-active.

Best regards!

**Comment by ElvishArtisan** [comment]
How exactly are you testing this (platform, procedure, etc)? Just we're on the same page!

**Comment by alexolivan** [comment]
HI!

Here's what I'm doing:
Rivendell master (so qt4 , official, stable ... I'm still learning! :-)
Debian 10 Buster (Current Stable, although 11 Bullseye is on the corner).
I'm cnfiguring Dark desktop theme by selecting the default suplied GNOMEish 'Adwaita Dark' theme...so, my GTK preferences do point to 'Adwaita Dark'. Then, for my qt4 preferences, I set them to use the 'GTK+ style' (which, then, in turn, lead to Adwaita Dark)

Aside of that, I guess you know, in the absence of qt4 preferences defined, you can also point qt4 to use GTK+ (and that way 'Adwaita Dark') just by appendig -style=gtk+ to the commad line (works on most of rdxxxxx GUI modules... I recall rdlogmanager and rmlsend not liking it, but the rest they're happy with that)

I try to keep 'As neutral as possible' (if this is somewhat possible) I don't like to depend on GNOME, KDE, or whatever... so I don't install full dektop environment. Instead, I prefer very light and customizable setups... in a nutshell: I'm using Slim + openbox (then I use individual apps to get the ver basic GUI/desktop functuonalities ... for this matter, I'm including gnome-themes, the qt4 GUI preferences app , and the GTK prepferences app... I'm writing from memory!... I think they are lxappearance and qt4-qtconfig)

Sure, If you want a comprehensive list of packages, since I document all my labs and I have them recorded, I could give it here!
 
Best regards!

**Comment by ElvishArtisan** [comment]
Thanks. That was very helpful.

I'm not sure that Rivendell will ever play particularly well with desktop theming engines like gtk2; primarily because we already break the rules for theming various UI elements in numerous places, primarily through the use of color to indicate state. (See for example the start and soundpanel buttons in rdairplay(1). Thus, while I'm happy to accept PRs that improve compatibility with theming engines provided that they don't break the aforementioned state displays, I personally am not planning on making such compatibility a high priority.
