### ISSUE TITLE
RDCatch - RSS Upload SQL Error

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#685]
Hi!

Today I've been experimenting (master/qt4 branch)  with Uploading/RSS-Podcast stuff toghether with RDCatch (a very interesting feature!) ... My tasks do fail with an SQL error on syslog. here it is:

```
 Jul  8 13:14:02 debian rdcatchd: invalid SQL or failed DB connection[Unknown column 'SHELF_LIFE' in 'field list' QMYSQL: Unable to execute query]: insert into PODCASTS set FEED_ID=2,STATUS=2,ITEM_TITLE="Rivendell Podcast Test",ITEM_DESCRIPTION="",ITEM_CATEGORY="Music",ITEM_LINK="https://podcasts.alexolivan.com",AUDIO_FILENAME="192.168.1.10",AUDIO_LENGTH=62680724,AUDIO_TIME=3926543,SHELF_LIFE=0,EFFECTIVE_DATETIME=now(),ORIGIN_DATETIME=now()
```

- I've tried setting the RSS field 'Shelf life' to both unlimited (default value) and to some value , just in case, but the query is like failing due to a field problem.
- Using RDCastManager to post From Cart/Cut works indeed on the same cut, feed, etc...
- I've ensured thet audio export format matches the one defined on the feed (wondering how RDCatch manages eventual mismatched audio format selected in comparison with the one configured on the RSS Feed.... maybe selecting an RSS feed should disable Upload audio format form controls?) 

Maybe (probably) I'm missing something .... has any one experienced those SQL errors?

Best regards.

**Comment by ElvishArtisan** [comment]
This has all been thoroughly overhauled in the 'qt5' branch.

**Comment by alexolivan** [comment]
Thank you very much.... I took a look at qt5 commits and, man, there's a ton of stuff going on there...amazing job!

(Can't wait for the beta2 release!  :-D)
