### ISSUE TITLE
Bug: Time Differences Importing MP3 vs. WAV

### ISSUE THREAD

**Issue by TheOnlyAlPeterson** [ElvishArtisan/rivendell#69]
When importing a long monophonic WAV file (53:50), RDLibrary reports back the correct length.  But when importing a 128 kbps MP3 file of the identical audio, RDLibrary reports back 53:58.

Similar behavior has been noticed on smaller files as well, varying as much as 2-3 secs on a 15-minute file.

My MP3s were created on Cool Edit 2.1, using the built-in Fraunhofer codec last updated in 2003 on a guess.

**Comment by ElvishArtisan** [comment]
Post me a sample of two files exhibiting the behaviour please.

**Comment by ElvishArtisan** [comment]
Fixed in v2.15.3.
