### ISSUE TITLE
Write log message if LoadLog (LL) RML fails

### ISSUE THREAD

**Issue by druidlabs** [ElvishArtisan/rivendell#690]
I'd like a message to be written to the system log when a LL command fails.  Currently RDAirplay writes a message when the command is successful:

> rdairplay: loaded log 'StartOvernightChain' in Main Log

No message is issued if the requested log doesn't exist, which makes things like grep-ing the log difficult and can mislead inexperienced staff who won't realize a missing message in the log means the load failed.

**Comment by ElvishArtisan** [comment]
Sounds reasonable. Done in 314bbb09.

The message is of the 'unable to load log "foo", no such log', sent at ```LOG_WARNING``` priority.
