### ISSUE TITLE
Debian Buster RDCatch issue

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#691]
Hello Fred!
OS: Debian 10 Buster

I was successful compile code, and i was successful even make .deb packages <--- Thanks for that! 

There is an issue with RDCatch.
RDCatch v4.0.0beta2 

When you add MacroCart, the Start Time isn't showing at all, and in syslog there is a lot of messages like

Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
Aug  3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring

**Comment by ElvishArtisan** [comment]
The 'not valid for this DOW' messages can be safely ignored. They are for debugging purposes only --i.e. is issued with a priority of LOG_DEBUG-- and thus will not be visible to users using a the standard production setup.

**Comment by ElvishArtisan** [comment]
> When you add MacroCart, the Start Time isn't showing at all, and in syslog there is a lot of messages like
> Aug 3 13:18:45 debian rdcatchd: event 4 is not valid for this DOW, ignoring
> [...]

Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in c0f1f4d.
