### ISSUE TITLE
Add please code to configure.ac to recognize Raspbian OS correctly

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#692]
Fred, add please to configure.ac code for script can recognize the Raspbian OS for the python correct path.
And in Debian Buster and in Raspbian OS based on the Debian Buster there is no package mysql-server, now there is package called mariadb-server.

And in debian/control file also for package rivendell there is dependency like mysql-server what is wrong for the Debian and Raspbian.
May be we need dependency mysql-server | mariadb-server <--- this will be good for Ubuntu  and Debian.

#
# Determine Distro
#
AR_GET_DISTRO()
AC_SUBST(DISTRO,$ar_gcc_distro)
AC_MSG_NOTICE($ar_distro_id)
DISTRO_NAME="|                           Distribution Name ... Unknown |"
case "$ar_distro_id" in
     debian|raspbian)
       AC_MSG_NOTICE([Distro is Debian-ish])
       DISTRO_FAMILY="|                         Distribution Family ... Debian  |"
       DISTRO_IS_DEBIANISH=yes
       if test $ar_distro_id = "debian" ; then
         DISTRO_NAME="|                           Distribution Name ... Debian  |"
       fi
       if test $ar_distro_id = "raspbian" ; then
         DISTRO_NAME="|                         Distribution Name ... Raspbian  |"
       fi
       AC_SUBST(APACHE_PKG,"apache2")
       AC_SUBST(APACHE_CONFIG_DIR,"/etc/apache2/conf.d")
       AC_SUBST(USERMODE_PKG,"")
       AC_SUBST(MYSQL_PKG,"mariadb-server")
       AC_SUBST(QT_MYSQL_PKG,"libqt5sql5-mysql")
       AC_SUBST(DOC_PATH,"/usr/share/doc/rivendell")
       AC_SUBST(HAVE_USERMODE,"no")
       AC_SUBST(RDALSACONFIG_DESKTOP_FILE,"rivendell-rdalsaconfig-sudo.desktop")
       AC_SUBST(RDDBCONFIG_DESKTOP_FILE,"rivendell-rddbconfig-sudo.desktop")
     ;;

ubuntu)
       AC_MSG_NOTICE([Distro is Debian-ish])
       DISTRO_FAMILY="|                         Distribution Family ... Debian  |"
       DISTRO_IS_DEBIANISH=yes
       if test $ar_distro_id = "ubuntu" ; then
         DISTRO_NAME="|                           Distribution Name ... Ubuntu  |"
       fi
       AC_SUBST(APACHE_PKG,"apache2")
       AC_SUBST(APACHE_CONFIG_DIR,"/etc/apache2/conf.d")
       AC_SUBST(USERMODE_PKG,"")
       AC_SUBST(MYSQL_PKG,"mysql-server")
       AC_SUBST(QT_MYSQL_PKG,"libqt5sql5-mysql")
       AC_SUBST(DOC_PATH,"/usr/share/doc/rivendell")
       AC_SUBST(HAVE_USERMODE,"no")
       AC_SUBST(RDALSACONFIG_DESKTOP_FILE,"rivendell-rdalsaconfig-sudo.desktop")
       AC_SUBST(RDDBCONFIG_DESKTOP_FILE,"rivendell-rddbconfig-sudo.desktop")
     ;;

**Comment by ElvishArtisan** [comment]
What are the contents of '/etc/os-release' on Raspian?

**Comment by newdanceradio** [comment]
Please: 

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by ElvishArtisan** [comment]
Support added in f48fb2ef. Please test!

**Comment by newdanceradio** [comment]
Fred, tell me please, what about MYSQL_PKG for Debian and Raspbian
AC_SUBST(MYSQL_PKG,"mysql-client")

for Debian and Raspbian there is only mariadb-client package and there isn't mysql-client package.

**Comment by ElvishArtisan** [comment]
> for Debian and Raspbian there is only mariadb-client package and there isn't mysql-client package.

'Kay. I wasn't sure from your last if those were two alternative candidates or an outright replacement. Changed to 'mariadb-client' for Debian and Raspian in 381d15a.

**Comment by newdanceradio** [comment]
Yeap, now configure script recognized successfully Raspbian OS
Thanks!

**Comment by newdanceradio** [comment]
Fred, how about dependency in debian/control file
Now there is dependency for rivendell package mysql-server, may be reasonable to add mysql-server | mariadb-server ?

**Comment by alexolivan** [comment]
> Now there is dependency for rivendell package mysql-server, may be reasonable to add mysql-server | mariadb-server ?

Yep... although packages build fine, the mysql-client dependency is held as dependency upon installing the package. So, I guess in the mean time we would need to patch debian/control.

As another suggestion (don't know to which extent is applicable in Raspbian and/or Ubuntu) I would consider taking a look at meta/abstaract packages default-mysql-server and default-mysql-client.

I agree the server shouldn't be a dependency (although I understand it to be almost a must for an embedded system) but it would be wonderful if the default-mysql-client package exists in Ubuntu systems (I guess it does in Raspbian), because it would ease inter-compatibility

Cheers!

**Comment by ElvishArtisan** [comment]
> Yep... although packages build fine, the mysql-client dependency is held as dependency upon installing the package... This renders them unusable in Bullseye. So, I guess in the mean time we would need to patch debian/control.

Better would be to add a conditional to the build system to just 'do the right thing' depending on the distro detected. What values exactly do you need there for Bulleye?

> As another suggestion (don't know to which extent is applicable in Raspbian and/or Ubuntu) I would consider taking a look at meta/abstaract packages default-mysql-server and default-mysql-client.

Yes, from a distro perspective, this would be the real solution. Unfortunately, I don't think that there is any such.

**Comment by alexolivan** [comment]
Hi Fred!

In fact, mysql-client is absent both in Buster and Bullseye... it seems as Debian moved to MariaDB after Stretch things changed.
Currently, in Debian, my guess is that default-mysql-client could be the target.

Interestingly, as Ubuntu (and other Debian derivatives) are based on Debian base packages, Ubuntu got default-mysql-server and default-mysql-client as of Bionic (the rough equivalent of Buster) according to: [https://packages.ubuntu.com/bionic/default-mysql-client](https://packages.ubuntu.com/bionic/default-mysql-client)
 
I've not tested myself (got no Ubuntu on hand now) but I bet an  ``` apt-cache policy defaul-mysql-* ``` run on console could confirm this.

Best regards!

**Comment by alexolivan** [comment]
HI people!

Debianists we're very happy!!!! Yesterday we finally got a new Debian Release!!! Bullseye was officially set as Stable release (Yayyyy!!! i expected that for September :-).

While I'm gonna keep nightly-building qt5 branch Buster packages (now old stable) for a while, Bullseye is now (and will for the next 2 years approx :-) the main focus.

I will but soon clone and setup a new nightly-building qt5 branch Debian Bookworm (the new testing andd future release) VM out of the Bullseye VM, to generate packages, and report back on any issues found (in theory, but, at this point, most probably Bullseye and BookWork do not differ too much, so I expect no problems).
It might look premature but, In my experience, keeping up the testing release working, paves the way for future, smooth, painless, booooring (as Debian stable), transitions from release to release... not only for Debian, but for any debian-based distros.

Best regards!

**Comment by ElvishArtisan** [comment]
> In fact, mysql-client is absent both in Buster and Bullseye... it seems as Debian moved to MariaDB after Stretch things changed.
Currently, in Debian, my guess is that default-mysql-client could be the target.

Changed in 74c8851. Please test!

**Comment by alexolivan** [comment]
Hi. I have made I fresh clone of qt5 branch on my machine (Debian Bullseye)

```
On branch qt5
Your branch is up to date with 'origin/qt5'.

nothing to commit, working tree clean
```

ran autogen.sh and here's the resulting debian/control interesting part:

```
Package: rivendell
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}, **mysql-client**, libqt5sql5-mysql, apache2, curl, rsyslog, rivendell-pypad (= 4.0.0beta2-1)
Description: Radio Broadcast Automation System
 Rivendell is a complete radio broadcast automation solution, with
 facilities for the acquisition, management, scheduling and playout of
 audio content.  Modules for the production and management of podcast
 audio are also included.
```

As you see, mysql-client appears as a dependency...don't know if the changes on commit targetted to fix that.
Upon running configure, the file contents DID NOT change (this machina has no ASI hpi dev libraries installed...so configure results were not ideal:

```
configure: 
configure: "|---------------------------------------------------------|"
configure: "|         *** RIVENDELL CONFIGURATION SUMMARY ***         |"
configure: "|---------------------------------------------------------|"
configure: "| Platform Information:                                   |"
configure: "|                         Distribution Name ... Debian    |"
configure: "|                       Distribution Family ... Debian    |"
configure: "|                          Update I18N Data ... No        |"
configure: "|                                                         |"
configure: "| Configured Audio Drivers:                               |"
configure: "|  Advanced Linux Sound Architecture (ALSA) ... Yes       |"
configure: "|                          AudioScience HPI ... No        |"
configure: "|                 JACK Audio Connection Kit ... Yes       |"
configure: "|                                                         |"
configure: "| Audio Codecs:                                           |"
configure: "|            FLAC Encoding/Decoding Support ... Yes       |"
configure: "|                     MPEG Decoding Support ... Yes       |"
configure: "|             MPEG Layer 2 Encoding Support ... Yes       |"
configure: "|             MPEG Layer 3 Encoding Support ... Yes       |"
configure: "|       OggVorbis Encoding/Decoding Support ... Yes       |"
configure: "|                      M4A Decoding Support ... Yes       |"
configure: "|---------------------------------------------------------|"
configure: 
```

**Comment by ElvishArtisan** [comment]
'Kay, I finally went ahead and loaded up Bullseye in a VM and did a Rivendell build today. I've added a sub-section to 'DISTRO-SPECFIC NOTES' in ```INSTALL``` for it. I haven't actually tried running it, but the build looked pretty good (although all of the ugly deprecation warnings about using ```QString::sprint()``` are annoying).

The whole MySQL vs. MariaDB thing looks to be a hot mess, with multiple layers of virtual packages trying to satisfy various historical dependencies. Seeing as the long-term secular drift in the FOSS world seems to be towards MariaDB as well as in the interests of simplicity, I've gone ahead and set the DB package dependencies for _all_ Debian family distros to use MariaDB (The RedHat world has already been this way for some time). This is a change for Ubuntu, but 20.02 (Focal Fossa) does have packages for both, and I can't imagine wanting to run Rivendell v4.x on anything earlier than that.

You can find all of this stuff in a96c9c4f.

And, I guess I ought to clean up all of those ```QString``` warnings. Sigh. :weary:

**Comment by alexolivan** [comment]
> Seeing as the long-term secular drift in the FOSS world seems to be towards MariaDB as well as in the interests of simplicity, I've gone ahead and set the DB package dependencies for _all_ Debian family distros to use MariaDB

Hi Fred... although I'm a devoted FOSS fan (that's why I use Debian) and I'm happy with what I readed, I would like to point out, for the best interest of the project, that I've found that the MariaDB / rivendell4 combo segfaults RDCatch (I really, really  hope its my setup.... Today I will perform a new set of tries tweaking the config, but I think I've tried everything) which is in my opinion a key module. If I'm right (I hope I'm not!) this would break RDCatch for rivendell4 in Ubuntu too :-(

**Comment by ElvishArtisan** [comment]
Closing this issue, but continuing the hunt in #703.
