### ISSUE TITLE
Log generation take a long time in rd-4.0.0beta2

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#693]
Fred, i dont now why, but generating log in rd-4.0.0beta2 take a very long time.
I have a database for 2500 tracks and In version 3.6.1 log generation took about 2-5 minutes, but in 4.0.0beta2 log generation took about 30 minutes for the same database.
And in syslog there is a ton of messages like:

Aug  4 09:39:27 raspberrypi rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''NDR-04-08` && `LINK_ID`>=0 order by `LINK_ID` desc' at line 1 QMYSQL: Unable to execute query]: select `LINK_ID` from `LOG_LINES` where `LOG_NAME`='NDR-04-08` && `LINK_ID`>=0 order by `LINK_ID` desc
Aug  4 09:39:31 raspberrypi rdlogmanager: DB connection re-established
Aug  4 09:39:31 raspberrypi rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''NDR-04-08` && `LINK_ID`>=0 order by `LINK_ID` desc' at line 1 QMYSQL: Unable to execute query]: select `LINK_ID` from `LOG_LINES` where `LOG_NAME`='NDR-04-08` && `LINK_ID`>=0 order by `LINK_ID` desc
Aug  4 09:39:35 raspberrypi rdlogmanager: DB connection re-established

Also i would ask, when i'm run rddbmgr --check there is many messages like:

RDWaveFile::GetChunk() returned non-zero exit code 602 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 12 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 40 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 4 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 602 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 12 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 40 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 4 [Invalid argument]

What could be the problem ?

Thanks in advance.

**Comment by ElvishArtisan** [comment]
> Aug 4 09:39:27 raspberrypi rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''NDR-04-08&&LINK_ID>=0 order by LINK_IDdesc' at line 1 QMYSQL: Unable to execute query]: selectLINK_IDfromLOG_LINESwhereLOG_NAME='NDR-04-08 && LINK_ID>=0 order by LINK_ID desc
Aug 4 09:39:31 raspberrypi rdlogmanager: DB connection re-established
Aug 4 09:39:31 raspberrypi rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''NDR-04-08&&LINK_ID>=0 order by LINK_IDdesc' at line 1 QMYSQL: Unable to execute query]: selectLINK_IDfromLOG_LINESwhereLOG_NAME='NDR-04-08 && LINK_ID>=0 order by LINK_ID desc
Aug 4 09:39:35 raspberrypi rdlogmanager: DB connection re-established

Fixed in 52d58fb. Please test!

**Comment by ElvishArtisan** [comment]
> Also i would ask, when i'm run rddbmgr --check there is many messages like:
>
> RDWaveFile::GetChunk() returned non-zero exit code 602 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 12 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 40 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 4 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 602 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 12 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 40 [Invalid argument]
RDWaveFile::GetChunk() returned non-zero exit code 4 [Invalid argument]

Fixed in e5daddf.

**Comment by newdanceradio** [comment]
> > Aug 4 09:39:27 raspberrypi rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''NDR-04-08&&LINK_ID>=0 order by LINK_IDdesc' at line 1 QMYSQL: Unable to execute query]: selectLINK_IDfromLOG_LINESwhereLOG_NAME='NDR-04-08 && LINK_ID>=0 order by LINK_ID desc
> > Aug 4 09:39:31 raspberrypi rdlogmanager: DB connection re-established
> > Aug 4 09:39:31 raspberrypi rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''NDR-04-08&&LINK_ID>=0 order by LINK_IDdesc' at line 1 QMYSQL: Unable to execute query]: selectLINK_IDfromLOG_LINESwhereLOG_NAME='NDR-04-08 && LINK_ID>=0 order by LINK_ID desc
> > Aug 4 09:39:35 raspberrypi rdlogmanager: DB connection re-established
> 
> Fixed in [52d58fb](https://github.com/ElvishArtisan/rivendell/commit/52d58fbe297ce38a022d565a9929bcc94163afc8). Please test!

Yess, now error don't appears, in syslog everything seems fine.
Now Log is generated in 20 minutes.
I will try to generate Log on x86 machine, will see if there is the same behavior.
What else could cause slow log generation ?

**Comment by newdanceradio** [comment]
Oh, Fred, i found an issue why the Log generation took so much time.
I don't now why, but after upgrade from v.3.... to v4... in almost all scheduler codes there was 0 in Max in a row.
So, i was return all values back to 1 Max in a row and now Log is generating in 2 minutes!
