### ISSUE TITLE
RDDBConfig closes with segmentation fault

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#694]
When you try to create new database throw rddbconfig it closes with segmentation fault.
I was checked on Debian Buster X86-64 and Raspbian ARM, segmentation fault happens with both architectures ARM and X86-64

Here is a backtrace:

Thread 1 "rddbconfig" received signal SIGSEGV, Segmentation fault.
0xb67e8658 in RDCoreApplication::config() () from /lib/librd-4.0.0beta2.so
(gdb) bt
#0  0xb67e8658 in RDCoreApplication::config() () from /lib/librd-4.0.0beta2.so
#1  0xb68755b8 in RDFontEngine::RDFontEngine(QFont const&, RDConfig*) ()
   from /lib/librd-4.0.0beta2.so
#2  0xb6821a48 in RDDialog::RDDialog(QWidget*, QFlags<Qt::WindowType>) ()
   from /lib/librd-4.0.0beta2.so
#3  0x0001a694 in ?? ()
#4  0x00019908 in ?? ()
#5  0x0001e890 in ?? ()
#6  0xb4fe0244 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#7  0xb5a7b104 in QAbstractButton::clicked(bool) ()
   from /lib/arm-linux-gnueabihf/libQt5Widgets.so.5
#8  0xb5a7b340 in ?? () from /lib/arm-linux-gnueabihf/libQt5Widgets.so.5
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in ec13ee47, dc6b289 and a0f87af. Please test!

**Comment by newdanceradio** [comment]
Thanks, now it's working!
