### ISSUE TITLE
Assigning air date, daypart and day of week to a 𝐒𝐜𝐡𝐞𝐝𝐮𝐥𝐞𝐫𝐜𝐨𝐝𝐞

### ISSUE THREAD

**Issue by olvaar** [ElvishArtisan/rivendell#695]
Fred,

Would it be possible to add the airdate, daypart and day of week properties (like in rdlibrary - edit cart) to a schedulercode ?

So that if tagged by the code, the will be 'scheduled' in that period, daytime or day of week.

That would be a really nice feature.

I have been hoping on this for years. 

Maybe 4.00 is a nice opportunity to implement this.

Thanks 
Peter

**Comment by ElvishArtisan** [comment]
Interesting idea, but I it would cause massive complications for things like cart searches. A Schedule Code is very similar to a Rivendell Group: a basic tag that can be used to locate and select carts without regard to any other condition or state.

**Comment by olvaar** [comment]
Fred, 
I think you see it way bigger than I intended. 

I was thinking more :

Only During log generation : if the 'airdate, daypart or day of week'-condition is not met, then force 'max in row'-rule (for that schedulercode) to 0. otherwise if condition is met, leave as is.  

Thus the feature would not influence searching, selecting manually or any other rivendell functionality; only log generation. 

That would be sufficient, to be a good feature, for example for seasonal music (like xmas, summer,winter or day-themed songs (etc). 

I guess you saw it more of fully enabling/disabling of a schedulercode. That would indeed be a massive change.

Regards,
Peter
