### ISSUE TITLE
Something is wrong with DropBox in v4.0.0beta2

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#697]
First, when you choose normalization in dropbox, let's say -9 dBFS
in main window shows -900 dBFS

![Screenshot from 2021-08-05 18-14-24](https://user-images.githubusercontent.com/17381301/128377257-83041008-d8fe-4f79-8670-b27caadea059.png)

Second, when RDAirPlay is playing, and you change some thing in dropbox, the RDAirPlay is stop playing and freezes, after some time RDAirPlay closes, and when you trying to run RDAirPlay again - it doesn't start and appears window with Multiple instances not allowed!

In syslog we can see, that, when ripcd is sending notification about dropbox modification, then rivendell.service is killed. 

Aug  5 18:32:29 raspberrypi ripcd: sent notification: "NOTIFY DROPBOX MODIFY raspberrypi" to 239.192.255.72:20539
Aug  5 18:32:29 raspberrypi systemd[1]: rivendell.service: Main process exited, code=killed, status=11/SEGV
Aug  5 18:32:29 raspberrypi rdcatchd: rdcatchd exiting
Aug  5 18:32:30 raspberrypi ripcd: exiting normally
Aug  5 18:32:30 raspberrypi caed: cae exiting
Aug  5 18:32:30 raspberrypi rdadmin: received socket error 1
Aug  5 18:32:30 raspberrypi rdvairplayd: received socket error 1
Aug  5 18:32:30 raspberrypi rdairplay: received socket error 1
Aug  5 18:32:30 raspberrypi rdvairplayd: exiting
Aug  5 18:32:30 raspberrypi systemd[1]: rivendell.service: Failed with result 'signal'.
Aug  5 18:32:32 raspberrypi systemd[1]: rivendell.service: Service RestartSec=2s expired, scheduling restart.
Aug  5 18:32:32 raspberrypi systemd[1]: rivendell.service: Scheduled restart job, restart counter is at 1.
Aug  5 18:32:32 raspberrypi systemd[1]: Stopped Rivendell Radio Automation System.

**Comment by ElvishArtisan** [comment]
> First, when you choose normalization in dropbox, let's say -9 dBFS
in main window shows -900 dBFS

Fixed in a5c625d.

**Comment by ElvishArtisan** [comment]
> Second, when RDAirPlay is playing, and you change some thing in dropbox, the RDAirPlay is stop playing and freezes, after some time RDAirPlay closes, and when you trying to run RDAirPlay again - it doesn't start and appears window with Multiple instances not allowed!

Fixed in b2b5bf2. Please test!

**Comment by newdanceradio** [comment]
> 
> 
> > First, when you choose normalization in dropbox, let's say -9 dBFS
> > in main window shows -900 dBFS
> 
> Fixed in [a5c625d](https://github.com/ElvishArtisan/rivendell/commit/a5c625d1a7443d4b8a6c373c8c1bcbe4ba205eb4).

Confirm, the bug is fixed.

**Comment by newdanceradio** [comment]
> 
> 
> > Second, when RDAirPlay is playing, and you change some thing in dropbox, the RDAirPlay is stop playing and freezes, after some time RDAirPlay closes, and when you trying to run RDAirPlay again - it doesn't start and appears window with Multiple instances not allowed!
> 
> Fixed in [b2b5bf2](https://github.com/ElvishArtisan/rivendell/commit/b2b5bf27bf90a2315a8939a2074f72b9778caad4). Please test!

Confirm, the bug is fixed.

**Comment by newdanceradio** [comment]
Bugs that was described is fixed.
