### ISSUE TITLE
RN execute

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#700]
Hello Fred.

Could you please check is everything is OK with RN execute in version rd-4.0.0beta2 ?

Because, my setup of scripts and macro was worked fine in rd-3.6.2, but in rd-4.0.0beta2 RN commands don't work.
When i run macro, in syslog i can see that command is executed, but nothing happens.
When i run my scripts from shell, everything works fine.
I have double checked permissions, ownership and so on, but from macro i can't execute script.

In syslog i see that ripcd is executing script, but nothing happens.
Aug  9 19:44:04 raspberrypi ripcd: received rml: "RN /home/pi/rivendell-scripts/load_log.sh!" from 127.0.1.1
Aug  9 19:44:04 raspberrypi ripcd: received rml: "RN /home/pi/rivendell-scripts/load_log.sh!" from 127.0.1.1
Aug  9 19:44:04 raspberrypi ripcd: executing script "/home/pi/rivendell-scripts/load_log.sh" as rivendell:rivendell
Aug  9 19:44:04 raspberrypi ripcd: executing script "/home/pi/rivendell-scripts/load_log.sh" as rivendell:rivendell

Thanks in advance.

**Comment by ElvishArtisan** [comment]
All are possibilities. I'm currently in the midst of completing #689, but will be returning to this shortly.

**Comment by ElvishArtisan** [comment]
> But i should change RnRmlOwner and RnRmlGroup to user that i'm login in to the X session, in my case this is "pi" user.

Yes, you will need to have that set to match the perms needed to run your scripts.


> And one more, in every script that i launch throw RN, i'm added line
> export DISPLAY=:0.0
> and only after that, scripts start normally executing throw RN.

That tells us that at least one command that the script is attempting to open an X11 (GUI) connection. Generally, you want to avoid using such commands as (by definition) ```RN``` does not support GUIs.

**Comment by newdanceradio** [comment]
> That tells us that at least one command that the script is attempting to open an X11 (GUI) connection.

Hmm... but i don't have a command in scripts that is attempting to open X11 (GUI) connection.

For the example, i have script that loads in to the RDAirPlay log at midnight:

#!/bin/bash
DATE=$(date -d +1day +%d-%m)
/usr/bin/rmlsend LL\ 1\ NDR-$DATE\ -1\!

and this script doesn't work without line export DISPLAY=:0.0

This script without line export DISPLAY=:0.0 was worked in rd-3.

Another script, that shows weather in RDAirPlay:
#!/bin/bash
weather=$(/usr/bin/ansiweather -l riga -a false)
/usr/bin/rmlsend LB\ "$weather"\!

this script also don't work without export DISPLAY=:0.0

Another script, that generate log:
#!/bin/bash
/usr/bin/rdlogmanager -g -s Production

also don't work without export DISPLAY=:0.0

**Comment by newdanceradio** [comment]
So, commands 
/usr/bin/rmlsend
and
/usr/bin/rdlogmanager
need connection to Xserver
when trying to launch the above mentioned commands when user don't access to XServer shows the error:
qt.qpa.screen: QXcbConnection: Could not connect to display :0.0
Could not connect to any X display.

**Comment by ElvishArtisan** [comment]
Found the problem. The ```rmlsend(1)``` command was attempting to open an X11 even when invoked with arguments (which is supposed to force it into 'CLI-only' mode). Fixed in 1fb8578.

Please test!

**Comment by newdanceradio** [comment]
> Fixed in [1fb8578](https://github.com/ElvishArtisan/rivendell/commit/1fb8578e53ec2f60dc6e509669c2844cd7bcb393).

Yes, I confirm, now rmlsend is working as it should.

**Comment by newdanceradio** [comment]
rdlogmanager is the same problem, when running with arguments it attempting to open an X11

**Comment by newdanceradio** [comment]
> rdlogmanager is the same problem, when running with arguments it attempting to open an X11

I'm sorry Fred, but what about rdlogmanager ?
