### ISSUE TITLE
RDAdmin: Editing existing Dropboxes

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#702]
Whenever I edit a host Dropbox in RDAdmin, that IS NOT the last in the list, an UI/UX situation happens from there on: 
IF the last DropBox is edited, then it became a kind of 'copy' of the last edited one (this is clearly seen by repeating Dropbox IDs on the list... which leads me to think on a 'frontend like' error rather than an actual persistence/backend problem)

Eventually, when the bug triggers... you may manage to end with all the Dropboxes turning into clones of the edited one.

Upon quiting the Dropbox manager and re-entering it the list renders normally again.

**Comment by ElvishArtisan** [comment]
Confirmed here...

**Comment by ElvishArtisan** [comment]
> IF the last DropBox is edited, then it became a kind of 'copy' of the last edited one (this is clearly seen by repeating Dropbox IDs on the list... which leads me to think on a 'frontend like' error rather than an actual persistence/backend problem)

Yup. Some Qt Model Mayhem, to be precise.

Fixed in 8387805b. Please test!

**Comment by alexolivan** [comment]
Updated and the issue is gone.
Closing as solved
