### ISSUE TITLE
rdlogmanager is the same problem, when running with arguments it attempting to open an X11

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#704]
rdlogmanager is the same problem, when running with arguments it attempting to open an X11

_Originally posted by @newdanceradio in https://github.com/ElvishArtisan/rivendell/issues/700#issuecomment-899855889_

**Comment by ElvishArtisan** [comment]
Fixed in 13f2d5c. Please test!

**Comment by newdanceradio** [comment]
Confirm, now everything works !
Thanks Fred !
