### ISSUE TITLE
RDLibrary V4.0.0beta2 / Sort Carts by name, length...

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#705]
Hi

The ability to sort the carts by name, number, length... is not working. Nothing happend on clicking the column.

**Comment by alexolivan** [comment]
Same issue here (snapshot nightly-build 09-02-2021 on Debian Bullseye) .
I didn't recall about that feature from my 3.6 Tests. Today I have checked in a Rivendell 3.6 install and compared with 4.0, and yep... the feature is gone.

Nothing on stderr/stdout ... just as if the clicking doesn't trigger any event

**Comment by ElvishArtisan** [comment]
Confirmed here.

FWIW, those column-sorting features are 'magic' that is completely implemented by Qt; I've never had to do anything special to make it work. I wonder if there is some property that needs to be set to turn it back on?

**Comment by ElvishArtisan** [comment]
Fixed in acd80bc. Please test!

**Comment by alexolivan** [comment]
I would say it is fixed.... I see carts re-ordering upon clicking the top of a column.
