### ISSUE TITLE
RDLibrary - Edit Audio

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/rivendell#707]
If the file (track) length is short, we can't (zoom in) the wave in time scale, Time buttons isn't active.

![Screenshot from 2021-08-18 07-48-04](https://user-images.githubusercontent.com/17381301/129839026-a28b9e75-02c9-4569-bc63-091d01759f7a.png)

**Comment by ElvishArtisan** [comment]
This is not a bug, but rather an consequence of the granularity of the waveform depiction process. We use blocks of 1152 PCM frames for each, which means that expanding a wavefrom depiction to use less than that number of frames per pixel yields no additional detail.

(The weird 1152 frame number comes from the MPEG-1 spec, which defines that as the PCM frame payload for each MPEG frame.)
