### ISSUE TITLE
Database Error on DB upgrade or Check

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#708]
When importing and upgrading a Rivendell database (from v3.6.1) or running "rddbmgr --check" on an existing (and working) v4.0.0beta2 database, the following error is returned:

Checking schedule code rules...
DB connection re-established
invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 QMYSQL: Unable to execute query]: select `ID` from `RULE_LINES` where 
done.

Also seeing on the initial invocation of "rddbmgr --check":

rddbmgr --check
Checking DB/table attributes...
  Table "FEED_IMAGES" uses engine type InnoDB, should be MyISAM. Fix? (y/N) n
  Table "FEED_IMAGES" uses charset/collation latin1/latin1_swedish_ci, should be utf8mb4/utf8mb4_general_ci. Fix? (y/N) n
  Table "SUPERFEED_MAPS" uses engine type InnoDB, should be MyISAM. Fix? (y/N) n
  Table "SUPERFEED_MAPS" uses charset/collation latin1/latin1_swedish_ci, should be utf8mb4/utf8mb4_general_ci. Fix? (y/N) n
done.

Both issues are observed using both CentOS7 or Ubuntu as the OS environment.

**Comment by ElvishArtisan** [comment]
We will need a copy of the DB in question in order to analyze this. You can send a copy to us at 'support@paravelsystems.com'.

**Comment by ElvishArtisan** [comment]
Fixed in a559ec2 and 7220567. Please test!

**Comment by WMTH** [comment]
Verified, rddbmgr now functions correctly.
