### ISSUE TITLE
RDLibrary: non funcional scheduler Code dropdown?

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#709]
Hi.
After importing a bunch of tunes, having them some scheduler Codes, i feel as if them scheduler Code dropdown selector on top of the app os not working.
The group selector, but, does work for me.

I hace tested with the realtime filter option, but os not working yo me... Maybe I'm missing something... Has someone experienced this?

Regards

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 83c35bf. Please test!

**Comment by alexolivan** [comment]
Confirm fixed.
Closing, thanks.
