### ISSUE TITLE
build failure in Debian

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#710]
Hi... today I've notice my installed version was not updating, so I checked out and found a manual launch of building packages script failing, at least in Debian Bullseye.

I have to carefully re-check all the environment... I remember hiving this issue early building rivendell 3.X due to some math libs missing in header files or something similar (talking from memory). Here's the make error:

```
driver_alsa.cpp: In member function ‘virtual bool DriverAlsa::setInputVolume(int, int, int)’:
driver_alsa.cpp:1075:37: error: ‘pow’ was not declared in this scope
 1075 |     alsa_input_volume[card][stream]=pow(10.0,(double)level/2000.0);
      |                                     ^~~
driver_alsa.cpp: In member function ‘virtual bool DriverAlsa::setOutputVolume(int, int, int, int)’:
driver_alsa.cpp:1093:44: error: ‘pow’ was not declared in this scope
 1093 |     alsa_output_volume[card][port][stream]=pow(10.0,(double)level/2000.0);
      |                                            ^~~
driver_alsa.cpp: In member function ‘virtual bool DriverAlsa::getInputMeters(int, int, short int*)’:
driver_alsa.cpp:1217:34: error: ‘log10’ was not declared in this scope
 1217 |       levels[i]=(int16_t)(2000.0*log10(meter));
      |                                  ^~~~~
driver_alsa.cpp: In member function ‘virtual bool DriverAlsa::getOutputMeters(int, int, short int*)’:
driver_alsa.cpp:1241:34: error: ‘log10’ was not declared in this scope
 1241 |       levels[i]=(int16_t)(2000.0*log10(meter));
      |                                  ^~~~~
driver_alsa.cpp: In member function ‘virtual bool DriverAlsa::getStreamOutputMeters(int, int, short int*)’:
driver_alsa.cpp:1265:34: error: ‘log10’ was not declared in this scope
 1265 |       levels[i]=(int16_t)(2000.0*log10(meter));
      |                                  ^~~~~
driver_alsa.cpp: In member function ‘virtual bool DriverAlsa::setPassthroughLevel(int, int, int, int)’:
driver_alsa.cpp:1284:7: error: ‘pow’ was not declared in this scope
 1284 |       pow(10.0,(double)level/2000.0);
      |       ^~~
make[2]: *** [Makefile:530: driver_alsa.o] Error 1
make[2]: Leaving directory '/home/administrator/repos/rivendell/snapshots/qt5/rivendell/cae'
make[1]: *** [Makefile:541: all-recursive] Error 1
make[1]: Leaving directory '/home/administrator/repos/rivendell/snapshots/qt5/rivendell'
make: *** [debian/rules:9: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```

I have to check wether there was a code change or maybe its my environment. ./configure shows nice showing no problem.

Regards.

EDIT:
Checked the commits and saw a pair of commits with what seems to be an important code refactor, affecting header files (8888e4c and 6ed4643). The date was 18 and that was the day my nightly-builds stopped working... maybe that refactor got debian-environment needed libs for pow and log10 functions to work deleted... I'm wondering, if that's the case, whether same happens in the other refactored files.
I need to figure this out to keep up the testing and confirming bugfixes. I would but preffer to wait if someone is experiencing this, or whether this is, in fact, a problem due to code changes, before start messing with the currently nice and clean code with ugly patches and workarounds.

**Comment by edgeradio993fm** [comment]
Can confirm I have a similar error when compiling **driver_alsa.o** and **driver_jack.o** on Debian Buster.

**Comment by dklann** [comment]
Confirming the same build failure here on up-to-date Ubuntu Studio 20.04.3.

**Comment by alexolivan** [comment]
> Confirming the same build failure here on up-to-date Ubuntu Studio 20.04.3

This changes the picture quite a bit... if So, this is not a debian specific environment issue

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 7fe52159. Please test!

**Comment by dklann** [comment]
7fe5215 builds and runs here on Ubuntu Studio 20.04.3. Thanks for the fix Fred!

**Comment by alexolivan** [comment]
Confirm fixed for both Debian Buster and Bullseye
