### ISSUE TITLE
RDLibrary: UI filters ignored for new tracks ingesting from Dropboxes

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#712]
Hi again.

I think this is probably yet another UI pesky issue with qt4 -> qt5 migration: while you have RDLibrary opened, no matter which filters you have in form (or at least, haven't figured out any specific combination) newly imported carts will do 'leak' into the cart list.

I have discovered this by luck, as I put a bunch of tracks in Dropboxes and went away and I forget to close RDLibrary. Then I found RDLibrary list full with the new carts.
I have retried several times, with some filter combinations, and the behaviour seems consistent. Tracks do show in RDLibrary no matter artis, title, sched. code or wathever filter present.

Sure, the issue is just an annoyance...just close and re-open rdlibrary... but maybe it helps getting a trend, or a common part of code to keep an eye on other modules/forms accross rivendell, since overall, it feels as if the responsivennes or event-catch/reaction on the new qt5 forms requires some further tweak after the qt4 port.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 9cc917b. Please test!

**Comment by alexolivan** [comment]
Confirm fixed.
Thanks.
