### ISSUE TITLE
rmlsend not working when run from scripts or crontab.

### ISSUE THREAD

**Issue by caryhon139** [ElvishArtisan/rivendell#716]
I ported some of my 3.5 scripts to the 4.0 beta system and most of it works except rmlsend. I ran a bunch of tests using rmlsend and they don't seem to work anymore. ( rmlsend LB\ test! ) works from the command line but not from a bash script unlike 3.5 where it does work. The Op Guide uses the same sintax and, if followed, doesn't show how to fix it.

**Comment by caryhon139** [comment]
I ran a battery of tests with crontab. crontab -e, sudo crontab -e and nano /etc/crontab will not run the rmlsend command no matter what I do. However, if I run the command from my 3.5 system, using sudo crontaab -e, I can punch an rml command through without issue. Not sure why I can't cron script from the 4.0 system.

**Comment by alexolivan** [comment]
Are you using on the crontab the full path to rmlsend binary? ... A typical issue with crontab IS that comandos and dcripts run in a new environment... 

So, ensure yo use /usr/Bin/rmlsend (ir wathever full path os in your system) or use crontan to just call scrpits.
Within scripts, I use the 'which' command to initialize fullpath binaries (like rmlsend='which rmlsend') at the beginning of the script, so from there on $rmlsend points fullpath to the binary.

**Comment by caryhon139** [comment]
Yes. Using full path to /usr/bin/rmlsend in all the scripts.  Will play
with the"which" command today.

Thanks.

_ Cary _

**Comment by caryhon139** [comment]
I reduced my rml script to only one statement. An LB command /usr/bin/jacknet.sh which works from the command line. I used the straight path to the binary and then used the "which" command. Both worked correctly. Then I tried to run it from (crontab -e) and (sudo crontab -e). Both crashed. I've attached the /var/crash output from both in case the clue is buried in there.[](url

[rmlsendRD.txt](https://github.com/ElvishArtisan/rivendell/files/7071946/rmlsendRD.txt)
[rmlsendRoot.txt](https://github.com/ElvishArtisan/rivendell/files/7071947/rmlsendRoot.txt)

**Comment by ElvishArtisan** [comment]
Known problem in ```v4.0.0beta2```. Fixed in 1fb8578.

FYI, there were similar issues with rdlogmanager(1) that were fixed around that same time (16 August 2021).
