### ISSUE TITLE
RDLibrary: Wrong cut listing for scheduler code 'ALL' 

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#720]
I've noticed that, whenever the default scheduler code dropdown 'ALL' is selected, every CART, independently of wether it has only a single cut or not, appears to have 5, 6 cuts (this are not real database persisted entities, loos like a frontend issue).

Apparently, the cuts appear to be accounted as carts, since if the 'show only first 100 results' checkbox is ticked, I get only 16-18 carts listed (I have not counted them one by one, but my guess is that, the total sum of carts and 'ghost' cuts will hit 100).

I have also noticed after comparing RDLibrary 4.0 with a 3.6 install, that single-cut carts do appear always as multi-cut carts (they feature the + icon to expand the list entry and show the many cuts) in any circumstances... This, but, could very possibly be not a bug, but an intended feature instead... reporting just in case.

Best regards.

**Comment by ElvishArtisan** [comment]
Where exactly are you seeing this? Looking at both the 'Cuts' column in the rdlibrary(!) main screen as well as the 'Edit Cart' dialog, I am not seeing this.

**Comment by alexolivan** [comment]
Ok... mayde I'm going to try start using edited screenshots... not sure if it will work but far more descriptive for UI issues I think.

Here's my library. 886 Carts. ALL Grups Shown... SHEDULER CODE is ALL ... Only first 100 Matches unticked
![Screenshot at 2021-09-11 19-39-05](https://user-images.githubusercontent.com/1419896/132956633-2ed3e188-88ef-4825-8206-44d9ef00756f.png)
I see several cuts for every CART, althoug only one is on DB.

Now, ticking first 100 Matches only, displays from 16 to 18 carts, where each cart has many 'ghost' cuts. Sheduler Code filter is ALL
![Screenshot at 2021-09-11 19-41-09](https://user-images.githubusercontent.com/1419896/132956717-4ba5d5fa-b686-4e98-a092-9872fd4292ab.png)
I bet the sum of all ghost cuts and carts sum 100.

Upon seelcting any scheduler code, the behaviour normalizes... No 'ghost cuts' , 100 First matches look good.
![Screenshot at 2021-09-11 19-43-24](https://user-images.githubusercontent.com/1419896/132956764-4eabaf3a-a60a-4554-b767-65b9e930cbf8.png)
Notice but, that, unlike in 3.X , single-cut Carts do still feature the multi-cut expand + button

**Comment by ElvishArtisan** [comment]
_Very_ helpful. Thank you.

**Comment by ElvishArtisan** [comment]
Fixed in 604923d. Please test!

**Comment by alexolivan** [comment]
The issue, seems to have been almost completely mitigated by the fix. At least, the most annoying problem: 'ghostly/false cuts'
![Screenshot at 2021-09-13 11-01-00](https://user-images.githubusercontent.com/1419896/133055627-0340ba1f-4794-469a-9555-ee5373c86317.png)
Still, notice how cuts and carts are treated as same things: ticking 'show only first 100 Carts' do result in 98 shown (this happens becaise I have the three rivendell ads/jingles as cuts on a single cart :-P) 
This is unlike in 3.X, where 100 carts are 100 carts, regardless of the total number of cuts contained on those carts.
Also in 4.X, carts are always expandable, even if they contain only one cut.
I would suggest, if this is intentional, to update the UI labels and the Match counter, so 100 first matches, gives 100 results.

**Comment by ElvishArtisan** [comment]
> Still, notice how cuts and carts are treated as same things: ticking 'show only first 100 Carts' do result in 98 shown (this happens becaise I have the three rivendell ads/jingles as cuts on a single cart :-P)
This is unlike in 3.X, where 100 carts are 100 carts, regardless of the total number of cuts contained on those carts.
Also in 4.X, carts are always expandable, even if they contain only one cut.
I would suggest, if this is intentional, to update the UI labels and the Match counter, so 100 first matches, gives 100 results.

Fixed in 7bd18d2. We should now return 100 carts regardless of the number of cuts (assuming, of course, that there are actually that many that match the search criteria). Please test!

**Comment by alexolivan** [comment]
Confirm fixed.

Thanks.
