### ISSUE TITLE
Nautel RDS PyPad

### ISSUE THREAD

**Issue by HughStolmer** [ElvishArtisan/rivendell#722]
Hi Folks,
Has anyone been able to get the Nautel RDS working with the Nautel PyPad or the RD 4 Beta?
Here is what I have done using a Nautel VS300 on the latest Firmware:
-Tested Rivendell 4 PyPad UDP to another computer running Wireshark. It works.
-Set the Nautel PyPad config port to 7005 (Nautel's port in NOT changeable and must be 7005).
-Verified the Rivendell machine can ping the Nautel Transmitter's IP.
-Sent RDS text to the Nautel using Putty on a different Win 7 computer. The Nautel receives it and an FM tuner displays my text as RDS.
-Also, the Nautel requires a TEXT= to direct the string to the Radio Text. I am not sure if this is in the PyPad Code and just not visible in the config file. I tried including it, and not including it, and neither worked.
-Monitoring the network with Wireshark shows only a TCP response saying port not available or something, and it is from the Wireshark computer, not the Nautel or RD machine.

If someone has been able to get this to work, could you send or post a copy of your PyPad File? It would be much easier to change the fields of a working file than spend more time troubleshooting.
Thanks for any help,
-Hugh-

**Comment by HughStolmer** [comment]
Sorry I meant... with the Nautel PyPad ON the RD 4 Beta...
H

**Comment by ElvishArtisan** [comment]
> Sent RDS text to the Nautel using Putty on a different Win 7 computer. The Nautel receives it and an FM tuner displays my text as RDS.

Could you post the _exact_ string(s) that you sent, along with a description of the results? From that, it should be straightforward to arrive at a working PyPAD setup.

**Comment by HughStolmer** [comment]
Nautel actually has a procedure for this to test the RDS.
After setting up Putty to a Telnet session (negotiation in passive mode and checkbox for "Return key sends Telnet New Line instead of ^M") to the Transmitter's IP address and port 7005, then simply type:
TEXT=1234 ABCD 5678 EFGH

This text (1234 ABCD 5678 EFGH) appears 2 places: The front LCD panel of the transmitter (View Status menu I think) and on a tuned-in receiver with RDS capability as scrolling Radio Text.

PDF is attached.

Hugh
[ASCII over IP Test.pdf](https://github.com/ElvishArtisan/rivendell/files/7145535/ASCII.over.IP.Test.pdf)

**Comment by ElvishArtisan** [comment]
> PDF is attached.

Thank you. That's very helpful!

Question: can one send multiple lines in a single TCP session? For example, instead just sending:

```TEXT=1234 ABCD 5678 EFGH```

could one do:

```TEXT=1234 ABCD 5678 EFGH```
```DPS=5678 WXYZ 1234 STUV```

and update _both_ radiotext and the dynamic PS simultaneously in a single TCP session?

As currently written, the plug-in uses a seperate TCP session for each line, which is terribly inefficient from a TCP/IP pov. I'd much rather amalgamate everything into a single TCP session per PAD update.

**Comment by ElvishArtisan** [comment]
'Kay, the folks at Nautel have very kindly sent me a copy of the VS OPS manual. On page 2-69, it says:

> Use TCP port 7005. This is not user configurable. To use RDS over IP, the connection must be opened before each command.

So that appears to be that. One TCP session per command. :disappointed::

**Comment by ElvishArtisan** [comment]
Fixed in 1cc4b5b, with a number of other changes/enhancements; see the ```ChangeLog``` entry. This should now work after changing the the 'IpAddress=' directive in the sample configuration to the appropriate value.

Please test, especially as I don't have access to the actual hardware here.

**Comment by HughStolmer** [comment]
Hi,
Thank-you! I will try when I get a change to load the latest. I'm spread thin these days...
-Hugh-
