### ISSUE TITLE
Next-Stop Window: Incorrect when in 12-hour mode

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#726]
When playing a cart in RDAirplay using the default 24-hour mode, the next stop window displays correct information:

![Screenshot at 2021-09-13 17-30-51](https://user-images.githubusercontent.com/8458996/133165350-6bd7af15-c68d-4b4a-8a20-6414241ca95a.png)

If the time format is changed to 12-hour, the next stop window displays incorrect information:

![Screenshot at 2021-09-13 17-32-19](https://user-images.githubusercontent.com/8458996/133165494-f131be03-c2a3-4640-bf6f-2bfb90769cfa.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in f6d0e37. Please test!

**Comment by WMTH** [comment]
Tested and verified proper operation.

**Comment by WMTH** [comment]
Tested and verified proper operation.

**Comment by ElvishArtisan** [comment]
Thank you!
