### ISSUE TITLE
Cannot download qt5 branch

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#729]
Cannot download qt5 branch for test from Github;  Master branch will download on selection of any other branch.

**Comment by ElvishArtisan** [comment]
We've made no changes here. I just tried checking out a new tree using my usual procedure, which worked as expected (keyboard entry __bolded__):

*** snip snip ***
fredg@elastigirl:\~/testbuilds$ __git clone git@github.com:/ElvishArtisan/rivendell rivendell-qt5__
Cloning into 'rivendell-qt5'...
remote: Enumerating objects: 36030, done.
remote: Counting objects: 100% (5682/5682), done.
remote: Compressing objects: 100% (1647/1647), done.
remote: Total 36030 (delta 4479), reused 5175 (delta 4023), pack-reused 30348
Receiving objects: 100% (36030/36030), 34.98 MiB | 11.08 MiB/s, done.
Resolving deltas: 100% (29286/29286), done.
fredg@elastigirl:\~/testbuilds$ __cd rivendell-qt5/__
fredg@elastigirl:\~/testbuilds/rivendell-qt5$ __git checkout qt5__
fredg@elastigirl:\~/testbuilds/rivendell-qt5$ __git status__
On branch qt5
Your branch is up to date with 'origin/qt5'.

nothing to commit, working tree clean
*** snip snip ***

I seem to recall hearing in the last couple weeks that Github was about to start requiring 2FA setups for actual git(1) operations; meaning that users would no longer be able to use their primary account password for such operations. Perhaps that is what's going on? (I've used ssh(1) keys for Github for years now).

**Comment by WMTH** [comment]
I will use your procedure as I am certain that will work.  Whatever changed, occurred after 0900 CDT today as I pulled the qt5 branch at 0855 CDT without issue.

**Comment by WMTH** [comment]
Moved to the suggested methodology and was able to download and sync as needed.

**Comment by ElvishArtisan** [comment]
Thank you!
