### ISSUE TITLE
Rivendell 4.0 Beta 3 Install problem

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#737]
I am installed on Ubuntu Studio following using the install script. 
The upgrade to this newest Beta did not complete. System gives me multiple errors about broken packages. As part of the repair, the system removed Rivendell. Now when I try to re-run the install script I get the following  . . . 

The following packages have unmet dependencies:
 rivendell : Depends: mariadb-client but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Synchronizing state of autofs.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable autofs
/usr/share/ubuntu-rivendell-installer/installer_install_rivendell.sh: 171: rddbmgr: not found

Installation of Rivendell is complete.  Reboot now.

IMPORTANT: Be sure to see the FINAL DETAILS section in the instructions
           to ensure that your new Rivendell system is properly secured.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  ubuntu-rivendell-installer
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1,072 kB disk space will be freed.
(Reading database ... 593638 files and directories currently installed.)
Removing ubuntu-rivendell-installer (0.1.1-1) ...

Is this worth troubleshooting, or should I just hose the system and start over? I have nothing on this system that can't be lost, was just setup to test the beta.

**Comment by ElvishArtisan** [comment]
> Is this worth troubleshooting, or should I just hose the system and start over? I have nothing on this system that can't be lost, was just setup to test the beta.

Hold a bit. This is probably an incorrect dependency on the new packages. I will test a bit here.

**Comment by dklann** [comment]
I encountered this too.

Confirming successful installation of Beta 3 with `sudo apt remove mysql-common mysql-client-8.0 mysql-client-core-8.0 mysql-server-8.0 mysql-server-core-8.0`, and re-running the install script.

**Comment by ElvishArtisan** [comment]
Thank you for the report!
