### ISSUE TITLE
Rivendell 4.0 Beta 3 Rdairplay with integrated voicetracker (vy nice)

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#739]
To be sure, don't know when to use it.. Maybe to create as DJ VTs in a livesituation for the next hour...?!  

One problem. The waveform is not visible and has a black background. I've installed on a virt desktop on top of Ubuntu Studio..

**Comment by CWJR** [comment]
Voice tracker has always been in RD Log Edit.

**Comment by RudiOnTheAir** [comment]
Uh, that seems to be a question off resolution from sceen. On my privat 1240x1024 screen i can't see that button too. But on my jobs screen with 1900x1080 it is visible.. :) My Testsystem is running on a virt. KVM Server, so i just change the res to my needs.

![grafik](https://user-images.githubusercontent.com/47517341/137525083-ac30e0cb-2957-4655-863e-68a691489f53.png)

**Comment by alexolivan** [comment]
> What is that for a desktop inviroment?

Hi! Its no desktop environment... For application-specific systems (such as  a Rivendell system) I learnt to stick to bare window-manager (openbox) together with a set of companion apps/packages, so the system becomes a kinda single-purpose appliance (very little RAM and installation disk space footprint) easy to clone/distribute

![Screenshot at 2021-08-27 13-57-56](https://user-images.githubusercontent.com/1419896/137746005-2706d447-4380-4878-84b3-a6a50fa34d23.png)
4.x looks gorgeous!!! and is, by default far more friendly to dark themeing that 3.X was. 

![Screenshot at 2021-09-01 15-31-07](https://user-images.githubusercontent.com/1419896/137746302-bb5cee35-ca96-4777-9089-3b882db6ded0.png)
However, there are some issues with some modules, mainly RDAirplay and RDCartslots.

Best regards

**Comment by alexolivan** [comment]
> Pray be specific as to details!

Hi Fred!
I didn't wanted to further bother with minor issues like those ... my idea was to stick to beta-testing and report on core/bussiness-logic issues only (segfaults, qt, etc.. ) and report on dark-theme issues I found later, on a separate issue/thread.

I think it will help you keep things in order.
If you wish, I could start the issue/thread now, with some edited screenshot for specific issues, so they can be dealt later.

Thanks.
Regards.

**Comment by RudiOnTheAir** [comment]
> Interesting use case! So I take it that the USB interfaces are being operated in ALSA mode for Rivendell (seeing as the JACK > instance is using the `dummy` backend)? Or are you using multiple JACK instances?

On my server is running the virt rivendell server, holding the database and audiostore via nfs. And it plays 24/7 to a webstream via jackd and dummyinterface to liquidsoap streaming application. On my main system for live and vting i'm using jack too, with a USb interface. The 2nd client serving me jingles is using alsa without jack. The Jackd setup on my main system is needed because of having to play music direkt from disk with the same audiointerface. Thats why User=rd in rivendell.service, that i have to write in again after every update...;)

**Comment by alexolivan** [comment]
> There should someone create a XFCE Rivendell Theme.. ;)

I'm using a very specific set of packages (Debian packages ;-) that install, out of the box, every required piece of software and the companion GUI theme/desktop customization tools... to get the basic 'kinda desktop environment' I need. If needed, I could share them :-)

I just need to deal with a few config files for UI settings, for a few UI pieces: the application menu (just an xml file), the composite manager (compton), the system monitor widget (conky) and a few environment variables in /etc/environment... other than that, everything is setup through GUI tools, just like a regular desktop environment

Best regards.

**Comment by alexolivan** [comment]
Aha... I thought I shared earlier ot probably in the mailing list, my approach to this is similar, but achieved differently: What I do is to let Rivendell run as root, and, at the same time, neutralize JACKd users separation/compartimentation by means of JACKd's PROMISCUOUS MODE running feature.

In a nutshell: in my installs, there's a just a system wide jackd.service, that runs in promiscuous mode, where every jackd client, no matter from whoever launched it, can connect to, and share audio in/out to any other processes, regardless of their launching users... and that's it... Once jackd is a system resource/comodity... launching qjackctl does not require any jackd setup, it just detects system-wide jack and connects to it. Rivendell daemons, just connect to system-wide jack too.

Connectivity is then done either trough qjackctl connections bay, the patchbay, or wathever (I prefer to connect rivendell In/Outs to Ardour and use it as a virtual mixing table) ... Im planning to get a Zoom R16 DAW controller to physically control Rivendell:

![Screenshot at 2021-10-18 21-27-15](https://user-images.githubusercontent.com/1419896/137794370-5c669466-6e08-48e9-bb10-16f401c37a58.png)

For sharing audio between instances I use jacktrip.... it all gets inter connected transparently.

**Comment by ElvishArtisan** [comment]
Audio capture problems should be fixed by #759.
