### ISSUE TITLE
(qt5/beta4) Found Issues with dark themes

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#740]
Hi.
As comented earlier, Qt5/beta4 works far better than 3.X with dark themes... the result is truly eye candy to most people that sees my installs, they get really impressed, as almost everything integrates with themeing to perfection:
![Screenshot at 2021-08-27 13-57-56](https://user-images.githubusercontent.com/1419896/137760821-1c8083e8-88f3-43a9-92bf-0af8a09b577a.png)

However, the few issues found, are disrupting, and I feel they may be related to inherited code adaptations to enhance/allow dark themeing on 3.X (both in RDairplay and RDCartSlots) by hardcoding some styling:

![Screenshot at 2021-10-18 17-06-01](https://user-images.githubusercontent.com/1419896/137759236-0ad2d476-f29c-4d32-bbf7-1fdca3e5d160.png)

In RDAirplay, log widget background color seems to behave as hardcoded white... this tends to cause white background on white font issue. Same happens in RDCartSlots (Red circled)
Also, in RDAirplay, the button text font color seems to behave as hardcoded black, which is hard to read against dark theme background windows (blue circle)

Beyond those 'serious' issues, there's a 'minor' issue with light yellow background over white font color on the Cut Mark Editor:
![Screenshot at 2021-10-18 17-17-38](https://user-images.githubusercontent.com/1419896/137760597-5e1d446a-67f5-4ea2-b2d1-698b43e6a6df.png)

Incredible work...
Best regards!

**Comment by RudiOnTheAir** [comment]
Btw, as you may have seen on one of my screenshots. The **rd4-server-test** is using your debian 11 repo.. ;) With the same error. Can't stop after running record in rdlibrary cutplayer...
