### ISSUE TITLE
BUG : Previously "time modified" Audio will not play under "Timesqueeze"

### ISSUE THREAD

**Issue by validmirror** [ElvishArtisan/rivendell#75]
CentOS 6.7 (although was the same in 6.6) Rivendell 2.10.3int7

If a series of Carts have been marked in RDLibrary (enforce length), the audio will disappear when play attempt is made under new timesqueeze function, BUT the time will remain, creating a 15 second, [or whatever the length should be] dead air pause on the air for the duration of the scheduled cart.  This also appears to be a semi random event, likely depending on if the cart is being squeezed, or expanded, as all cuts on the cart are not affected, I'll attempt to determine which is happening, as RDAirplay does not indicate a failure/issue

**Comment by ElvishArtisan** [comment]
I've just posted fixes for several regressions in the old-style 'per event' timescaling (commit 3fc5ad0), and am not seeing this behaviour.  Please update and test again!

**Comment by ElvishArtisan** [comment]
Fixed in master.
