### ISSUE TITLE
Voicetrack record version 4

### ISSUE THREAD

**Issue by shootinggame82** [ElvishArtisan/rivendell#759]
Hi

Recording a voicetrack in RDLogEdit don't work at all.
It is possible to import voicetrack but not record.
![RDLogEdit](https://user-images.githubusercontent.com/24573240/142753947-61e02693-8e80-4b0e-ac96-80bd690b4762.png)

Also in RDAdmin when set the format to MPEG Layer 2 to 192 kbps/chan it always go back to 128 kbps in RDLogedit settings the next time i return.

![RDAdmin192](https://user-images.githubusercontent.com/24573240/142754034-d94fc046-ae61-4d3a-869a-b261eeb551d3.png)

![RDAdmin128](https://user-images.githubusercontent.com/24573240/142754038-658aee6b-8768-4b1d-8bbb-28a09db90a42.png)

I have tried in CentOS 7 and installed with the installation script. Also in Ubuntu Studio with the installation script and also compiled the latest source code.

**Comment by fpeyraud** [comment]
Hi. I can confirm this problem on Lubuntu 20.04 with version 4.0.0beta3 and reworked packages (no source modification except debian directory)

**Comment by RudiOnTheAir** [comment]
Can confirm this, too. Also no audiorecord on rdlibrary. Tested on Ubuntu Studio 20.04 install script. Jackd and Alsa...

**Comment by RudiOnTheAir** [comment]
After succesful getting jackd to work with user rd, i tried to make a record in rdlibrary. But after hitting the stop button, no audio is recorded, my jack connections are away...Had to restart rivendell.service!

See screenshot. Sorry for picture only, no c&p because of virt env. for now.

![image](https://user-images.githubusercontent.com/47517341/146909327-96ebc942-51ed-4c23-8038-54ec9851347d.png)

**Comment by RudiOnTheAir** [comment]
Tested again this morning with the latest packages for Debian11, Jackd dummy mode. But every time i try to record in rdlibrary, it look normal, the .wav file ist created and growing. But when i hit the stop button, CAED disappears.

The last lines created by sudo journalctl -f -u rivendell.service:

![image](https://user-images.githubusercontent.com/47517341/147459594-8fee48e4-a864-4a14-8c1b-35f09f1f1dd6.png)

**Comment by ElvishArtisan** [comment]
'Kay, I've just pushed a commit [884f327] that should fix the various issues with audio capture reported here. Please test!

**Comment by RudiOnTheAir** [comment]
Hi, and yes. Now CAED is no more crashing in my jackd / dummydevice setup. But, now i'm not able to see the Waveform after klick on Edit Markers. See pic...

![image](https://user-images.githubusercontent.com/47517341/147743261-7ed375c3-900b-43db-afe1-42e74c2c63ea.png)

**Comment by ElvishArtisan** [comment]
I pushed an additional commit [105b97] at Dec 29 09:30:42 2021 -0500 that fixes an additional problem found with capture under JACK.

If you are still experiencing the problem after applying that, please let us know the _exact_ audio parameters that you are attempting use --i.e. format, sample rate, bit rate and channel count.

**Comment by RudiOnTheAir** [comment]
OK, will do that. But have to wait für the next build from Alejandro Olivan Alvarez. Maybe tomorrow..?!

I'm using his "snapshot" repo -->

deb https://repo.alexolivan.com/debian bullseye/rivendell/snapshots main extras non-free

Thanks

**Comment by ElvishArtisan** [comment]
No worries! I greatly appreciate your testing feedback!

**Comment by alexolivan** [comment]
> OK, will do that. But have to wait für the next build from Alejandro Olivan Alvarez. Maybe tomorrow..?!

Hi... I'm a little bit offline this times, but I checked out and the repo is up to date at #105b97f:

```
root@debian:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  rivendell rivendell-dbgsym rivendell-importers rivendell-importers-dbgsym rivendell-pypad rivendell-select rivendell-select-dbgsym rivendell-webapi
  rivendell-webapi-dbgsym rivendell-webget rivendell-webget-dbgsym
11 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 166 MB of archives.
After this operation, 20.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-webget-dbgsym amd64 4.0.0beta3-1+git20211230-105b97f [387 kB]
Get:2 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-webget amd64 4.0.0beta3-1+git20211230-105b97f [265 kB]
Get:3 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-select-dbgsym amd64 4.0.0beta3-1+git20211230-105b97f [1,033 kB]
Get:4 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-select amd64 4.0.0beta3-1+git20211230-105b97f [289 kB]
Get:5 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-importers-dbgsym amd64 4.0.0beta3-1+git20211230-105b97f [778 kB]
Get:6 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-importers amd64 4.0.0beta3-1+git20211230-105b97f [298 kB]
Get:7 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-dbgsym amd64 4.0.0beta3-1+git20211230-105b97f [156 MB]
Get:8 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell amd64 4.0.0beta3-1+git20211230-105b97f [6,224 kB]                              
Get:9 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-pypad all 4.0.0beta3-1+git20211230-105b97f [267 kB]                            
Get:10 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-webapi-dbgsym amd64 4.0.0beta3-1+git20211230-105b97f [101 kB]                 
Get:11 https://repo.alexolivan.com/debian bullseye/rivendell/snapshots/main amd64 rivendell-webapi amd64 4.0.0beta3-1+git20211230-105b97f [272 kB]                        
Fetched 166 MB in 7s (25.1 MB/s)                                                                                                                                          
Reading changelogs... Done
```

Since I'm using dummy iface jackd on that VM , I'll try to record and report back!

**Comment by alexolivan** [comment]
OK... No mic, everything virtual'... so had to improvise a test by senfing glassplayer jacckd out (playing an internet streaming) into rivendell jackd record inputs to have some audio (didn't want to use a loop, but an external source)
This is THE FIRST time I've tried this ( I've never used any sort of record on RDLibrary) so I'm unsure I did the right procedure or have the right settings... anyways, audio was sensed (very compressed/processed input, but high quality)

![Screenshot at 2021-12-30 21-05-35](https://user-images.githubusercontent.com/1419896/147784992-d46ed8eb-0982-470c-90ab-fab238527173.png)

Recorded a while, then checked on the marks editor for the wavelenght, and also checked by playing the cut...

![Screenshot at 2021-12-30 21-06-22](https://user-images.githubusercontent.com/1419896/147785132-0e1bfed2-4ff9-4b47-b389-273130690e4e.png)

I've not tested this throughly, but, at first glance, it looks good...

**Comment by RudiOnTheAir** [comment]
Hmm, thanks for your work. But that changed nothing. I still get the Energy Export Failed message...

**Comment by ElvishArtisan** [comment]
> OK... No mic, everything virtual'... so had to improvise a test by senfing glassplayer jacckd out (playing an internet streaming) into rivendell jackd record inputs to have some audio (didn't want to use a loop, but an external source)
This is THE FIRST time I've tried this ( I've never used any sort of record on RDLibrary) so I'm unsure I did the right procedure or have the right settings... anyways, audio was sensed (very compressed/processed input, but high quality)

A trick I use in similar situations is to configure a log output in ```rdairplay(1)``` to use a different JACK port than ```rdlibrary(1)```, then load up a log and hit 'Start'. Just route the corresponding port to whereever you need it. No need for Internet at all.

**Comment by fpeyraud** [comment]
Hello
The record functionality seems OK now. I can record voicetracks like I used to do (Start - Record - Start - Save). Thanks :)
