### ISSUE TITLE
RDLogManager

### ISSUE THREAD

**Issue by shootinggame82** [ElvishArtisan/rivendell#760]
I Don't know if it should be like this or not (I am quite new to Rivendell)
Testing out version 4 and have 2 service created. One for one computer and the other for another computer.
We also have user with limit access and only one service and the user can create logs, we want them to use rdlogedit.
But if that user open up RDLogManager they can generate logs for both services.

![RDLogManager](https://user-images.githubusercontent.com/24573240/142763611-e8276511-380e-4c40-9a0c-a3cc0d4ca8b4.png)

The service called "Bosse" is a daily machine that run 24/7 and the machine that the others use has service "Studion".
Do i have to remove RDLogManager that from the menu, so they don't accidentality generate log for the "Bosse" service,  or is this some sort of bug ?

**Comment by ElvishArtisan** [comment]
The envisioned use case for rdlogmanager(1) is that a central authority (often referred to as the _traffic department_ in American English) have overall responsibility for generating logs. It is not possible to partition the rights to generate such on a per-service basis.
