### ISSUE TITLE
pypad_urlwrite.py cannot use https URLS

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#761]
Hello
As specified in [PyCURL documentation](http://pycurl.io/docs/latest/quickstart.html#working-with-https), in order to use https urls, the curl object options must be fed with a "certificate bundle", which can be provided by [certifi python package](https://pypi.org/project/certifi/). Nowadays, every website should (must?) be accessed through https, especially when credentials are provided through basic auth method.
Is it planned to support this usecase ?

**Comment by ElvishArtisan** [comment]
My understanding is that certifi is intended primarily for host environments such as IoT devices that do not provide an integrated CA bundle. Indeed, the various certifi packages for RHEL in EPEL do not include a CA collection at all, but merely export the system shared certificate trust collection instead.

Is this really a needed capability? What would a typical use case be?

**Comment by fpeyraud** [comment]
After a second reading of the PyCURL documentation (I should read the doc twice every time...) it appears that the package uses OS supplied certificate bundle. I made a test in a python3 interpreter which showed me it is working correctly. Sorry for the noise
The use case is to send the PAD data to a website through SSL/TLS
