### ISSUE TITLE
Beta-3 Server Client Configuration

### ISSUE THREAD

**Issue by caryhon139** [ElvishArtisan/rivendell#763]
Not sure if this is a big issue but I'm having and issue trying to connect a 4.0 client to the main Rivendell server which shares its snd library. I configured and debugged the server, set up during the install, but when I built the client, and used the appropriate settings during the install, I get as error message telling me It couldn't connect to the MySql database. The client is added to the hosts directory and I can see audio cuts in the local /var/snd folder but the error persists. NFS works as advertised.
Are there any instructions on how this is to be configured, or is it a bug?

**Comment by druidlabs** [comment]
Possibly access for the Rivendell database in the server is still
configured to allow access only from the server?  IIRC, that's the default
configuration when you install a standalone Riv using the install scripts.

This (somewhat out of date) wiki page has some information about setting up
client machines.
http://wiki.rivendellaudio.org/index.php/Remote_Client_Access

**Comment by caryhon139** [comment]
I would think that if the developers provided you with the option of Server
or Client systems then the server would be configured to allow remote
client access. At least that is what I believed when I saw the options list.

The wiki page setup worked well for 3.5 and previous. It doesn't seem to
work in the Beta 4 system. NFS is already set up and fstab contains the
appropriate drive settings for NFS connect. That part works. Just access to
the database is the issue.

_ Cary _

**Comment by caryhon139** [comment]
I rescanned the Wiki page and did some digging into it. I got it to work.
Most of it was good. The only step I took was to put in the bind=0.0.0.0
and that seemed to take as well.

All good now. no error.

Admins: Please close the ticket. Thanks.

_ Cary _
