### ISSUE TITLE
Rivendell 3: Sound Panel Meter Tags Do Not Match Output

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#767]
In Rivendell 3, Beta 3 the sound panel meter tags do not match the actual playout port.  It appears M1 and M3 tags are swapped on the sound panel.  That is if the assigned playout for the first playout is port 2, it will playout on port 2 (M3) however, the button indicates it is playing on port  0 (M1):

![Screenshot at 2021-12-12 09-42-27](https://user-images.githubusercontent.com/8458996/145719610-dbbd4494-df7a-4333-a4aa-f41f84fc1ff0.png)

Likewise, if the assigned playout port is 0 (M1), it will playout on port 0 (M1) but the tag on the button indicates the playout is on port 2 (M3).

![Screenshot at 2021-12-12 10-18-19](https://user-images.githubusercontent.com/8458996/145720336-e969cd43-cc1e-42a0-99b8-1fff5c701f29.png)

The Playout and indication for port 1 (M2) is functions as it should.

![Screenshot at 2021-12-12 09-42-50](https://user-images.githubusercontent.com/8458996/145720238-e53e699a-9d2e-4061-80a1-311cbb2956b1.png)

Configuration:

![Screenshot at 2021-12-12 09-44-14](https://user-images.githubusercontent.com/8458996/145720350-411e1cab-1e3f-445a-bcd9-16ff416c55a2.png)

![Screenshot at 2021-12-12 09-49-03](https://user-images.githubusercontent.com/8458996/145720357-65b2d654-c369-4f7b-a08e-54e52f244a60.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 0188da4. Please test!

**Comment by WMTH** [comment]
Built, tested, and confirmed corrected.

**Comment by ElvishArtisan** [comment]
Thank you!
