### ISSUE TITLE
Feature Request: RDLibrary, filter by more than one Sched. Code.

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#768]
Being a former DJ, and now enjoing the goods of a unified DB for audio management of Radio Automation Software, I'm wondering on how incredible would be being able to query the library for appropiate tracks matching multiple certain conditions:

I've created a series of sched codes that describe my music library has I have in my 'djish' mind... vocal, instrumental... trance, progressive, etc ... high, mid, low tempo... 90's, 00's, 10's... disco names, etc, etc.... Basically I've maped the many mental tags that, as a Dj, I had mentally to filter for suitable candidates for the next track to mix. But now, they're part of a DB!

So, Having RDLibrary open, is an incredible tool...since I can, for instance, look for techno tracks... for 90's tracks... and so on... and get all candidate carts, since, often we tend to recall the ones that we like more or played more and tend to forget some others that are good too.
The thing but is that I cannot combine those filter conditions. Only one condition at once, and you get a list.
It would be amazing if I could check on several sched codes on the dropdown (I know, I know ...that's easier said than done... it implies a full DB query rewrite :-( ) So I could add multiple filters...that would be awesome :-O.
That way, RDLibrary would become a perfect DJ assistant, since I could ask it something like: "OK, Rivendell, now give me for the next one all the tracks that played in Pacha, on the 90's, just Dance and House, and Mid tempo" ... and boom! It would list them... would be incredible.

An alternative or complementary approach, that I thing would be harder to implement and not necessarily more useful, would be to add an aditional column, on the cart list, named scheduler codes, that includes the string names of the scheduler codes of every cart (but my guess is that filling that column would require a very complex DB query with joins and maybe would hit performance) 

Best regards.

**Comment by CWJR** [comment]
As a corollary to this, for scheduling, I have long wished for a column that would duplicate the artist column, but could be changed to accommodate things like eliminating repeats of any of the Beatles who later recorded as solo artists.  Also, name changes like Ricky Nelson to Rick Nelson and Young Rascals to Rascals.  That added column would be the one the log generator uses for scheduling (and therefore separation) purposes.

We aim to have artist and title listed exactly as it appeared on the vinyl or CD release, but then, even slight differences in spelling allow repeats of artists or songs in the same day, which we do not want--especially artist repeats.

**Comment by ElvishArtisan** [comment]
> It would be amazing if I could check on several sched codes on the dropdown (I know, I know ...that's easier said than done... it implies a full DB query rewrite :-( ) So I could add multiple filters...that would be awesome :-O.
That way, RDLibrary would become a perfect DJ assistant, since I could ask it something like: "OK, Rivendell, now give me for the next one all the tracks that played in Pacha, on the 90's, just Dance and House, and Mid tempo" ... and boom! It would list them... would be incredible.

One could certainly make an argument that there ought to be at least the ability to filter on basis of one Group and up to two Scheduler Code values, primarily because the built-in music scheduler allows selection on the basis of up to those specific parameters. However, while allowing multiple selections in a single drop-down widget is technically possible under X11, the UX for it is ugly, kludgy and hence very rarely seen in actual code. And, AFAICT, it's not supported at all under macOS or Windows. What we could do is add a _second_ dropdown for scheduler codes, that would be enabled if the first were set to something other than 'ALL'.

**Comment by ElvishArtisan** [comment]
> As a corollary to this, for scheduling, I have long wished for a column that would duplicate the artist column, but could be changed to accommodate things like eliminating repeats of any of the Beatles who later recorded as solo artists. Also, name changes like Ricky Nelson to Rick Nelson and Young Rascals to Rascals. That added column would be the one the log generator uses for scheduling (and therefore separation) purposes.
>
> We aim to have artist and title listed exactly as it appeared on the vinyl or CD release, but then, even slight differences in spelling allow repeats of artists or songs in the same day, which we do not want--especially artist repeats.

The solution for conundrums like this is to establish what is known as a 'curated vocabulary' -- basically a list of all valid 'Artist' field values, from which users would be constrained to select. All of the major commercial music scheduler packages have this sort of capability, but it's really overkill for Rivendell, which is primarily focussed on the radio automation domain.

**Comment by alexolivan** [comment]
> the built-in music scheduler allows selection on the basis of up to those specific parameters

Didn't realized about that fact... I now understand your point of view, and makes very much sense: By adding a second selector, one could foresee, by looking at an RDLibrary filtered list, what would be the actual candidate carts that RDLogManager Clock Event will have to chose from for a given Event... very interesting! ... and also very useful as a DJ Companion :-D

Cheers

**Comment by ElvishArtisan** [comment]
Implemented in fbfc7e0.

**Comment by alexolivan** [comment]
Oh yeah! ... incredible!!!

Thanks, regards.
