### ISSUE TITLE
Hard start time with Make Next doesn't start if no previous event is running when timer expires

### ISSUE THREAD

**Issue by rmc47** [ElvishArtisan/rivendell#771]
To reproduce:
- Start from an empty log, with RDAirplay in automatic mode, but no events playing
- Add a cart
- Set a hard start time shortly after the current time
- Set `Action If Previous Event Still Playing` to `Make Next`
- Wait for the timer to elapse

I think I would expect the cart to start playing at its scheduled time - as it does if `Start immediately` or `Wait up to...` are chosen. The 2005-11-29 changelog entry seems to suggest this is the expected behaviour.

Instead, the event is made next, but not actually started.

I've not dug into it properly yet, but I wonder if the SetTransTimer() call at https://github.com/ElvishArtisan/rivendell/blob/master/lib/rdlogplay.cpp#L1407 fails to reconsider that event, because current_time has already ticked on past it?

I'm happy to have a go at a PR if you could confirm the intended behaviour.

**Comment by ElvishArtisan** [comment]
> The 2005-11-29 changelog entry seems to suggest this is the expected behaviour.

Agreed, that's a very misleading entry. I honestly have no idea why I wrote it that way.

The behavior you report is the intended behavior.
