### ISSUE TITLE
Building/packaging fails as of #8ae2c2b

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#772]
Hi.

My last nightly build (Debian Bookworm/testing) has failed. I did a full clean, and tried manually, with the following error:

cp apis/rivwebpyapi/PKG-INFO debian/python3-rivwebpyapi/usr/lib/python3/dist-packages/rivwebpyapi-4.0.0b3.egg-info/
cp: cannot stat 'apis/rivwebpyapi/PKG-INFO': No such file or directory
make: *** [debian/rules:91: binary] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess

looks like some of the latest pyhton api commits broke something.

**Comment by dklann** [comment]
Here too. First seen in commit 8ae2c2b on branch _qt5_.

**Comment by alexolivan** [comment]
Yep... Also bullseye and Buster are not bulding anymore. Definitely feels some pesky packaging bug hidden around.

**Comment by ElvishArtisan** [comment]
Some new Python dependencies added for building DEB packages. See the 'OPTIONAL PREREQUISITES' section in 'INSTALL'.

**Comment by dklann** [comment]
Confirmed successful compile on Ubuntu Studio 20.04 after installing optional dependencies (Python modules _build_ and _twine_). Also had to `apt install python3-venv` in addition to those dependencies.

**Comment by ElvishArtisan** [comment]
Thanks!

> Also had to apt install python3-venv in addition to those dependencies.

Interesting. That is techinically a dependency of the other two packages. ```apt(1)``` should have added it automatically.

**Comment by alexolivan** [comment]
So its all about deps... 
Installed twine, python3-build and python3-venv on Bullseye, and packaging resumed to work. I expect Bookwork to be the same.
OTOH Buster lacks python3-build (I bet python3-venc too), and twine seems to be far older than the one on Bullseye, so it seems I would probably have to drop support for Buster.

Cheers!

**Comment by RudiOnTheAir** [comment]
How about building a flatpack version?

**Comment by ElvishArtisan** [comment]
> How about building a flatpack version?

Not possible unfortunately, due to a number of fundamental limitations --e.g. the sandbox environment only supports PulseAudio.

**Comment by RudiOnTheAir** [comment]
Ah, nice to know.

Thanks...


Am Montag, Dezember 27, 2021 16:37 CET, schrieb Fred Gleason ***@***.***>:
 
 
How about building a flatpack version?
Not possible unfortunately, due to a number of fundamental limitations --e.g. the sandbox environment only supports PulseAudio.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>

-- 
MfG
Wolf-Rüdiger Schwoon
https://blog.schwoon.info
https://drk-loppersum.de

**Comment by dklann** [comment]
Not to "beat a dead horse" with this issue, but I wonder if flatpak will be viable in the near future. Flatpak on current Fedora supports pipewire and pipewire includes "drop-in" compatibility with JACK. Just "holiday dreaming" here... :)

**Comment by ElvishArtisan** [comment]
Audio API support is just the tip of the iceburg. Flatpack's packaging model seems to make an assumption that each project but a  a single entry point (typically, a desktop binary). Rivendell is considerably more complex than that, with a dozen-ish entry points, a set of service daemons and an IPC framework to tie it all together.

**Comment by dklann** [comment]
Ah, right!  I've been skeptical of Flatpaks for just this reason. I **guess** an adventurous soul _could_ put each Rivendell GUI app inside a Flatpak container, but that seems way too "fun". Docker might possibly be a better "container" choice, but I am even more wary of Docker. And anyway, we're way off topic for this closed issue.... :)

**Comment by ElvishArtisan** [comment]
At a minimum, it would need a custom Flatpack runtime, something that the FreeDesktop people [strongly discourage](https://docs.flatpak.org/en/latest/dependencies.html#runtimes).

So yes, it's basically a non-starter.
