### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by andrubemis** [ElvishArtisan/rivendell#773]
This is tiny, I know, but if I try to sign in to RDAdmin (RD 4 beta 3) using a non-admin user, I get the following textbox: "This account has insufficient priviledges for this operation."

"Privileges" is misspelled (or misspelt, depending upon where you live). That is all :)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
> This is tiny, I know, 

No bug too small! Thank you for the report.

Fixed in edc226f.
