### ISSUE TITLE
RDAdmin 4.0.0beta3 Manage Groups List Ordering

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#777]
The list of Groups in RDAdmin->Manage Groups was "sort-able" in previous versions of Rivendell. Now, clicking on the various column headings does not change the order of the Groups in the list. I looked at the code in _rdadmin/list_groups.cpp_ (in branch _master_) and was unable to learn how the list is sorted. Someone more familiar with GUI coding might have an easier time...

Thanks!

**Comment by ElvishArtisan** [comment]
In Qt4 and earlier, list sorting was something that one got "for free" --i.e. the Qt GUI classes implemented it automatically. Starting with Qt5 that's no longer the case; each list that requires sorting needs its underlying model to have a custom sorting algorithm implemented in code. Currently, the only model to have such in v4.x is ```RDLibraryModel```. I agree that sorting would be handy in ```RDGroupListModel``` as well (especially for doing things like figuring out cart number ranges).

**Comment by ElvishArtisan** [comment]
Implemented in bcb22cc. Please test!

**Comment by dklann** [comment]
> Implemented in [bcb22cc](https://github.com/ElvishArtisan/rivendell/commit/bcb22cc706e1537e05d103f09fdd1c387f058da8). Please test!

Confirmed working on three instances of the latest commit.

I'll make an attempt at looking at your `RDLibraryModel` and `RDGroupsListModel` and do similar for other models where it would be helpful to sort on different columns.

Thanks much Fred!
