### ISSUE TITLE
SQL Error in 4.0.0beta3

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#778]
In RDLogEdit: ticking the "Show Only Recent Logs" checkbox results in the SQL error:
```
invalid SQL or failed DB connection[Undeclared variable: 14order QMYSQL: Unable to execute query]: select `NAME`,`DESCRIPTION`,`SERVICE`,`START_DATE`,`END_DATE`,`ORIGIN_USER`,`ORIGIN_DATETIME`,`COMPLETED_TRACKS`,`SCHEDULED_TRACKS`,`MUSIC_LINKS`,`MUSIC_LINKED`,`TRAFFIC_LINKS`,`TRAFFIC_LINKED`,`LINK_DATETIME`,`MODIFIED_DATETIME`,`AUTO_REFRESH` from LOGS where (`TYPE`=0)&&(`LOG_EXISTS`='Y') &&((`SERVICE`='Production')||(`SERVICE`='napa'))order by `LOGS`.`ORIGIN_DATETIME` desc limit 14order by `NAME`
```
Notice the 
```
order by `NAME`
```
tacked on to the end of the query. I thought this might be from a missing <Space> character, but studying the code leads me to believe it is something more sinister.

I do not know C++ nor Qt well enough to further troubleshoot this. I get lost looking for the definition of the function (method?) `filterChanged()`.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in bd2fee5. Please test!

**Comment by ElvishArtisan** [comment]
> I get lost looking for the definition of the function (method?) ```filterChanged()```.

```filterChanged()``` is actually a 'faux' method, meaning that it is basically a figment of C++'s imagination. It's what Qt referrs to as a __signal__; that is, an abstract "port" that can be wired to one or more __slots__ (which are actual methods, with a special attribute defined). It's a powerful enabler of code modularity in Qt. You can find detailed info at https://doc.qt.io/qt-5/signalsandslots.html.

**Comment by ElvishArtisan** [comment]
Thank you!
