### ISSUE TITLE
EX and MT Macros seems not working (beta4)

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#780]
Hi!

After checking latest Operations and Implementation guide (I've never attempted to use EX before), the syntax of EX seems clear to me: this macro will trigger the execution of a MACRO Cart passing its cart number as argument.
So, I dare to open an issue, since I have 3 macro carts that do actually work when called from RDLibrary, and do also work when used in logs on logmachines (I've been unable to test them in RDCatch in Debian), so I can assert they are fine, however, when trying to run them through EX on an rmlsend call on CLI or the GUI RMLSend module, the carts are not executed.

I can see in syslog that ripcd aknowledges receipt of the RML command, so I can assume it (EX) is queued for its processing/execution, however, nothing happens afterwards, so I feel the issue is actually the EX Macro itself. 

EDIT:
Added MT Macro to the issue since, commands such as:
```
rmlsend --to-host=127.0.0.1 MT\ 1\ 10000\ 050008!
```
Are also not executing the cart.

UPDATE:
After rebooting the VM to apply configuration changes on it, I immediatly experienced EX macro working... I have to further investigate what state changes are to this behaviour to happen, but, although probably unrelated, this makes me wonder wether it has something in common with rdcatchd crashing after rdcatch issues any order to it.

Best regards.

**Comment by ElvishArtisan** [comment]
```rdcatchd(8)``` dying will absolutely take operation of the ```Execute Cart``` [```EX```] RML with it. _Anything_ that causes ```rdcatchd(8)``` to crash is a major Rivendell bug by definition.   RML problems are just collateral damage.

**Comment by alexolivan** [comment]
Understood... since rdcatchd crashing is a known issue, this one has no sense... closing!
