### ISSUE TITLE
Dropbox repeat scheduler code in cart

### ISSUE THREAD

**Issue by kpsq973** [ElvishArtisan/rivendell#783]
Rivendell 3.6.2
If you add a scheduler code in the dropbox 

In some cases it adds that sched_code every time it ingest a new file.

So if you open a cart and look at the scheduler code for example 
the scheduler code “rock” Will be repeated a lot of times.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 5afcd7e. Please test!
