### ISSUE TITLE
RDCatch Recording: nothing in cut after apparent successful recording

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#785]
Hi.

I've been playing with rdcatch, trying to do some recordings.
My setup is a VM with just Jackd, so only card 0, wich is jack.
I have setup card 0 as a switch device (just to allow for routing as I learnt from RD 3.X)

I have setup a recording event in RDCatch.
I've selected card 0 / port 0
Format is mpeg layer 2 / bitrate 128kb
Switcher Host to NONE

This doesn't work, and following line appears in syslog:

```
Mar  9 11:45:00 debian caed: invalid twolame parameters, card=0, stream=0, chans=2, samprate=44100  bitrate=0

```
Bitrate=0 caught my attention... is that right?

I've managed to make it to do something by seting the switcher host to the host itself, then choosing the jackd card switcher...but it seems to trigger a sound loop/feed-back at the input with lots of noise.

No recording to file anywaus whatsoever

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by alexolivan** [comment]
I've noticed that tonight's package builds would include a pair of commits related to RDCatch problems, one of them including this...so I've checked this by re-scheduling a recording.
The result was successful.
I've tested with and without autotrim/normalize options, just in case, and no problems (only mpeg2 codec tested)

I'm not sure whether should I close this issue, since may be other commits related to all this queued to be pushed and tested... (I will open another, separated issue, related to yet another one-shot issue regarding recordings in rdcatch, as I thing those are totally unrelated)

**Comment by ElvishArtisan** [comment]
This specific issue should be fixed by c22a040. That said, in the course of fixing this, I uncovered a bunch of problems lurking in the RDCatch subsystem. Stay tuned for more fixes!

**Comment by alexolivan** [comment]
OK... so, I think I better close this particular one, so the issues list gets cleaner.

Thanks!

**Comment by alexolivan** [comment]
Hi Fred... sure.
I'll also paste a screenshot of the RDAdmin->Host->RDCatch section so config can be seen.

![Screenshot at 2022-05-24 18-24-42](https://user-images.githubusercontent.com/1419896/170086086-697d8ff4-62f7-41ed-aaf8-9845669c8d13.png)

![Screenshot at 2022-05-24 18-26-13](https://user-images.githubusercontent.com/1419896/170086145-a231cae4-2da4-4e80-9a7e-18c093609d05.png)

What's most surprising is that actual data ends into the temp file... it very much seems as it fails at the very last step

**Comment by alexolivan** [comment]
Hi again... I've done some further testing

Here's an screenshot of RDCatch event scrolled right for details of event being shown (Nice feature I didn't notice!!! ... I however notice the trim field is showing -4000dB instead of -40.00dB, and also I see there's no column for the normalization field) regarding codec, channels, bitrate, etc

![Screenshot at 2022-05-25 09-57-12](https://user-images.githubusercontent.com/1419896/170214543-3fc0c8ea-46f5-4bb1-9a09-b04aac26112b.png)

Early results seem to point at a problem with NORMALIZATION.
If normalization is disabled, recordings do get imported to cart/cut successfully, either with or without the autotrim checkbox.
I have not tried changing normalization level (just in case) and I have it at -8dB... will test wether it does matter

**Comment by ElvishArtisan** [comment]
Still unable to goose it here.

Could you configure your Syslog setup to record DEBUG level messages and then send me the output during the entire course of the event? That should flag exactly where this is going off the rails.

**Comment by alexolivan** [comment]
HI Fred... I'm trying to get DEBUG messages from rivendell, but I'm failing to do so.

So far, Debian default rsyslog install config seems to come with debug messages already intercepted and routed towards /var/log/debug:

```
#
# Some "catch-all" log files.
#
*.=debug;\
	auth,authpriv.none;\
	mail.none		-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail.none
```

But the contents of /var/log/debug upon a failed Record/export look very familiar and not useful for debug:

```
May 27 09:50:00 debian ripcd: added new connection 13337
May 27 09:50:06 debian rdcatchd: deleted file "/var/snd/rdcatchd-record-215.wav"
May 27 09:50:06 debian ripcd: sent notification: "NOTIFY CART MODIFY 61001" to 239.192.255.72:20539
May 27 09:50:11 debian rdcatchd: closed connection 1
```

Also, I took a look at /etc/rsyslog.d/10-rivendell.conf , uncommented the line as suggested:
LOCAL7.DEBUG	/var/log/rivendell/debug 
Then restarted rsyslog prior to repeat the bugged export... However, nothing ever goes into /var/log/rivendell/debug

In fact, It is but very extrange (I think we've talked about this earlier) that, enabled or not, debug and operations files, along with their rotation files, are present under /var/log/rivendell, with absolutely no content which is kinda counter-intuitive.

```
root@debian:~# ls -l /var/log/rivendell
total 0
-rw-r----- 1 root root 0 May 27 00:00 debug
-rw-r----- 1 root root 0 Apr 27 00:00 debug-20220427
-rw-r----- 1 root root 0 Apr 28 00:00 debug-20220428
-rw-r----- 1 root root 0 Apr 29 00:00 debug-20220429
-rw-r----- 1 root root 0 Apr 30 00:00 debug-20220430
-rw-r----- 1 root root 0 May  1 00:00 debug-20220501
-rw-r----- 1 root root 0 May  2 11:08 debug-20220502
-rw-r----- 1 root root 0 May  3 09:40 debug-20220503
...
-rw-r----- 1 root root 0 May 27 00:00 operations
-rw-r----- 1 root root 0 Apr 27 00:00 operations-20220427
-rw-r----- 1 root root 0 Apr 28 00:00 operations-20220428
-rw-r----- 1 root root 0 Apr 29 00:00 operations-20220429
-rw-r----- 1 root root 0 Apr 30 00:00 operations-20220430
-rw-r----- 1 root root 0 May  1 00:00 operations-20220501
-rw-r----- 1 root root 0 May  2 11:08 operations-20220502
-rw-r----- 1 root root 0 May  3 09:40 operations-20220503
...
```

I Feel that Rivendell isn't happy with Debian logging environment... as if it is not catching events or something.
I've not dealt a lot with rsyslog, since it works out-of-the-box for most installs, but I'm gonna investigate further to see if I grasp something.

**Comment by ElvishArtisan** [comment]
Should be fixed in current 'qt5' branch. Please test!

**Comment by alexolivan** [comment]
Hi fred.
Tested again, and the bug is somewhere hidden there: I've scheduled right now a short recording, with the only difference of having 'normaliation' enabled:

![Screenshot at 2022-09-07 20-51-58](https://user-images.githubusercontent.com/1419896/188955995-9e55fe6a-e658-4e51-b20b-985c629ee35a.png)

During this August holidays I've been pushing my mockup VM quite a bit... I've had a ton of fun setting it up kinda close to a real radio (I've even named it :-P), and I've been theese weeks testing a whole setup of automated recordings of certain parts of the grid, together with their automatic upload and publishing on a podcast feed... so far, it works perfect! recordings are done and upload and it is working for weeks, super stable (as far as I've managed to test)... but still, the normalize checkbox must be kept untiked, otherwise, the temp wav audio record never gets to the target cut.

**Comment by ElvishArtisan** [comment]
'Kay, thanks for testing! I'll pound on it a bit more here.

**Comment by ElvishArtisan** [comment]
'Kay, I've been testing this heavily on Linux Mint 21 (basically, Ubuntu Jammy with XFCE), using a JACK-based setup. It's been rock solid. I'm not sure where to go from here. Any chance that I could get access to your instance and see this in realtime?

**Comment by ElvishArtisan** [comment]
> I'm thinking about which of the settings has priority. My bet RDLibrary settings do override conflicting settings at RDCatch event.

The other way around, actually; the settings in 'RDLibrary' are the defaults, which can then be modified on a per-event basis.

The screenshots are very helpful. Any chance you could post the one for RDAdmin->ManageHosts->[hostname]->RDCatch as well?

**Comment by ElvishArtisan** [comment]
> The screenshots are very helpful. Any chance you could post the one for RDAdmin->ManageHosts->[hostname]->RDCatch as well?

No worries; I see you have already! (Time for coffee...)

**Comment by alexolivan** [comment]
I'm closing this one... I feel we may get into this in the future (after the Magick feed image issues) as I feel that all this could be simply a matter of media libraries on Debian Bullseye being more recent that the ones in CentOS (specially for those using deb-multimedia packages).
I wouldn't be surprise it may appear on Ubuntu 22.04 or future releases.

It is just a matter of being on alert and recall on this, provide eventual future problems or issue reports on blank recordings.
In the mean time, there's no point on having this opened

Thank you for your presence.
