### ISSUE TITLE
Log Operations Fail 

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#787]
Following the changes of March 10 (previous builds function correctly), the log operations of RDAirplay do not function properly.  

1. If a cart is playing and a log selected, the new log overwrites the playing cart however, the cart is still playing and the playout information of that cart (time played and time bar - wrong scale) appear in the first cart of the newly playing log. The time remaining is subtracted from the total time of the overwriting cart.
2. When the original cart ends, the system paused until start on the first cart slot is selected, the cart from the newly selected log plays from the incorrect time remaining, not the start of that cart.
3. If the log is unloaded, the original cart continues to play but cannot be seen in the cart stack.
4. If the log is unloaded, new carts cannot be added to the stack for playout.

A video is attached illustrating some of the issues.

https://user-images.githubusercontent.com/8458996/159180066-7c06d9eb-2383-42c7-b26d-3e6404a893ed.mp4

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 2fbc968, 612f6a7 and 1c653b8. Please test.

**Comment by WMTH** [comment]
Tested and confirmed proper operation.
