### ISSUE TITLE
[BUG] 4.0.0beta3 delay when clicking on direct buttons in rdAirPlay

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#788]
Hi,
I've noticed a  ~1s delay between click on the direct buttons (left part of RdAirPlay) and music playout. This delay does not exist when the same cart is triggered from the sound panel. Looking closer in the logs, caed seems to be triggered with delay using direct buttons.

Configuration : Ubuntu 20.04, Jack2, intel core i3, 4GB RAM, SSD

**Comment by RudiOnTheAir** [comment]
> Hi, I've noticed a ~1s delay between click on the direct buttons (left part of RdAirPlay) and music playout. This delay does not exist when the same cart is triggered from the sound panel. Looking closer in the logs, caed seems to be triggered with delay using direct buttons.
> 
> Configuration : Ubuntu 20.04, Jack2, intel core i3, 4GB RAM, SSD

Ack. My testsystem is running Debian11. Same delay. 1 to 3 seconds... But only! when the cart is added manual by using the ADD button or moving from panel.

**Comment by ElvishArtisan** [comment]
I'm unable to reproduce the problem here. However, I've a hunch that it was caused by the same set of changes that caused #787 and #789 (since fixed). Could you please retest?

**Comment by RudiOnTheAir** [comment]
To be honest. I'm not sure.

It looks like it depends on what you've done after fresh start of rdairplay.

1. Run rdairplay - Add 20min track via ADD button > delay

2. Run rdairplay - Load log and play some songs. > no delay.

2b. Unload prev. loaded log - Add 20min track via ADD button >  no delay

Could you reproduce now??


Am Dienstag, März 29, 2022 19:51 CEST, schrieb Fred Gleason ***@***.***>:
 
 
I'm unable to reproduce the problem here. However, I've a hunch that it was caused by the same set of changes that caused #787 and #789 (since fixed). Could you please retest?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

-- 
MfG
Wolf-Rüdiger Schwoon
https://blog.schwoon.info
https://drk-loppersum.de

**Comment by ElvishArtisan** [comment]
Nope.  :(

Are you in a position to build Rivendell from the Git sources, or are you just tracking the changes in each beta release?

**Comment by RudiOnTheAir** [comment]
Every time i build from git to test the changes for my new virtual RD4 setup...  

git clone -b qt5 https://github.com/ElvishArtisan/rivendell.git
...

**Comment by ElvishArtisan** [comment]
> Every time i build from git to test the changes for my new virtual RD4 setup...
>
> git clone -b qt5 https://github.com/ElvishArtisan/rivendell.git

Thanks.
So, you should have all of the recent changes. I still cannot reproduce this here. Is it still occurring on your setup after you pull in the most recent changes?

**Comment by RudiOnTheAir** [comment]
The last time i had build was 26th of march. I can do it again...

**Comment by ElvishArtisan** [comment]
The most recent relevant commits [1c653b8, 612f6a7, 2fbc968] were on 25 March 2022, so that should have been a good test.

I take it that you're still seeing the problem there?

**Comment by fpeyraud** [comment]
Hi
I've built the HEAD of qt5 branch yesterday (working on clean Ubuntu packaging) and cannot reproduce the delay either. It looks OK here too (Rivendell, + JACK in group scoped promiscuous mode). Thanks a lot !

**Comment by RudiOnTheAir** [comment]
Yes, i have done my above descibed error test again. And yes, now it works as it should.

Tnx

**Comment by ElvishArtisan** [comment]
Cool. Thank you everyone who reported and tested this very elusive issue!

**Comment by dzkahn** [comment]
I am experiencing this problem on 4.0.0.0rc0. I open RDairplay. Add cart to main player. Press start and sometimes there is a very pronounced delay. It continues to delay if I add a cart and play it again. Panel buttons play without delay. If I close Rdairplay and open it again, and play a cart it will work normally without delay. It can take several closes and opens of RdAirPlay to have the bug appear. On the other had, It can take several closes and opens of RdAirPlay to have RdAirPlay not to have the delay and work normally
