### ISSUE TITLE
rdclilogedit in Version 4.0.0beta3 Requires GUI

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#790]
When run on the command line, rdclilogedit(1) crashes if the shell environment variable DISPLAY is unset. I would like to be able to use this command in scripts with no DISPLAY set (i.e., headless).

[This stackoverflow question](https://stackoverflow.com/questions/17979185/qt-5-1-qapplication-without-display-qxcbconnection-could-not-connect-to-displ) suggests that setting (and exporting) the shell environment variable QT_QPA_PLATFORM to `offscreen` is one way to handle this. The other way is to invoke the command with the option `-platform offscreen`. Is specifying _platform_ as _offscreen_ (either as an environment variable or as a command line argument) the way this will be handled from now on?

Thoughts?

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 427a964. Please test!

**Comment by dklann** [comment]
I suspected QtCoreApplication() would be a reasonable fix, but I don't know enough to have been certain of it.

Confirmed working here.

Thanks!
