### ISSUE TITLE
Rivendell 4.0.0beta3 db version 355 - Rdairplay cannot play - "RDCae lost bytes"

### ISSUE THREAD

**Issue by radiocafero** [ElvishArtisan/rivendell#796]
When crash:

Apr 12 16:15:30 rivecnts caed: UnloadPlayback - Card: 1  Stream: 1  Handle: 141
Apr 12 16:19:16 rivecnts caed: LoadPlayback  Card: 1  Stream: 1  Name: /var/snd/010127_001.wav  Handle: 143
Apr 12 16:19:16 rivecnts rdairplay: log engine: started audio cart: Line: 9  Cart: 10127  Cut: 1 Pos: 0  Card: 1  Stream: 1  Port: 0
Apr 12 16:19:16 rivecnts caed: PlaybackPosition - Card: 1  Stream: 1  Pos: 552  Handle: 143
Apr 12 16:19:16 rivecnts caed: Play - Card: 1  Stream: 1  Handle: 143  Length: 269844  Speed: 100000  Pitch: 0
Apr 12 16:19:16 rivecnts pypad_icecast2.py[2197]: Updating live.radiocafe.ro: song=SADE - BY YOUR SIDE
Apr 12 16:19:19 rivecnts rdairplay: log engine: finished event: Line: 8  Cart: 10117  Cut: 1 Card: 1  Stream: 0  Port: 0
Apr 12 16:19:19 rivecnts caed: StopPlayback - Card: 1  Stream: 0  Handle: 142
Apr 12 16:19:19 rivecnts caed: UnloadPlayback - Card: 1  Stream: 0  Handle: 142
Apr 12 16:23:42 rivecnts rdairplay: RDCae lost 18 bytes when sending "LP  1 060105_001!"
Apr 12 16:45:56 rivecnts rdservice: ran local maintenance routines
Apr 12 16:45:56 rivecnts rdservice: ran system-wide maintenance routines

After restart rdairplay:

pr 12 20:00:04 rivecnts rdservice: ran local maintenance routines
Apr 12 20:48:06 rivecnts rdservice: ran local maintenance routines
Apr 12 20:48:06 rivecnts rdservice: ran system-wide maintenance routines
Apr 12 21:37:12 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 1!"
Apr 12 21:37:12 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 1!"
Apr 12 21:37:12 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 1!"
Apr 12 21:37:12 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 1!"
Apr 12 21:37:12 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 1!"
Apr 12 21:37:12 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 1!"
Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 0!"
Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 0!"
Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 0!"
Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 0!"
Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 6 bytes when sending "TS 0!"
Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 12 bytes when sending "ME 30001 0!"
Apr 12 21:37:24 rivecnts rdairplay: log machine 1 mode set to AUTO
Apr 12 21:37:24 rivecnts rdairplay: log machine 2 mode set to AUTO
Apr 12 21:37:24 rivecnts rdairplay: log machine 3 mode set to AUTO
Apr 12 21:37:24 rivecnts rdairplay: RDAirPlay started
Apr 12 21:37:25 rivecnts rdairplay: user changed to 'user'
Apr 12 21:37:31 rivecnts ripcd: received rml: "LL 1 Prod-0411!" from ::ffff:127.0.0.1
Apr 12 21:37:34 rivecnts rdairplay: loaded log 'Prod-0411' in Main Log
Apr 12 21:37:35 rivecnts ripcd: received rml: "MN 1 10!" from ::ffff:127.0.0.1
Apr 12 21:37:42 rivecnts rdairplay: RDCae lost 18 bytes when sending "LP  1 010140_001!"

When try to play something:

Apr 12 21:37:24 rivecnts rdairplay: RDCae lost 12 bytes when sending "ME 30001 0!"
Apr 12 21:37:24 rivecnts rdairplay: log machine 1 mode set to AUTO
Apr 12 21:37:24 rivecnts rdairplay: log machine 2 mode set to AUTO
Apr 12 21:37:24 rivecnts rdairplay: log machine 3 mode set to AUTO
Apr 12 21:37:24 rivecnts rdairplay: RDAirPlay started
Apr 12 21:37:25 rivecnts rdairplay: user changed to 'user'
Apr 12 21:37:31 rivecnts ripcd: received rml: "LL 1 Prod-0411!" from ::ffff:127.0.0.1
Apr 12 21:37:34 rivecnts rdairplay: loaded log 'Prod-0411' in Main Log
Apr 12 21:37:35 rivecnts ripcd: received rml: "MN 1 10!" from ::ffff:127.0.0.1
Apr 12 21:37:42 rivecnts rdairplay: RDCae lost 18 bytes when sending "LP  1 010140_001!"

**Comment by radiocafero** [comment]
4.0.0beta3, DB vers. 355. Centos 7.9 2009 (Core). VPS server on CONTABO Company.
Play on Jack Audio with Stereotool and Liquidsoap. 
After restart rivendell service, back to normal.
The uptime play was over 3 months or more.
Nothing is happening here. It just generate log and playing continuously.

**Comment by ElvishArtisan** [comment]
> 4.0.0beta3, DB vers. 355. Centos 7.9 2009 (Core). VPS server on CONTABO Company.

Thanks.

Sounds like it's time to roll another release. Chances are excellent that this has been swatted already in GitHub.
