### ISSUE TITLE
feature : Change Branding logo in RdAirPlay

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#797]
Hello
In qt5 branch, since the size of the rdairplay window can change, the branding logo is now static. It used to be embedded in the skin image which doesn't make sense anymore. On the other hand, the user logo can be changed.
I would find useful to be able to change the branding logo also so that I can put the radio station logo on the branding place and a host specific logo in the user-logo space.

**Comment by ElvishArtisan** [comment]
The 'branding bug' (to use the technical term) is intended to be a space where the software packager (as opposed to end user) can claim a bit of credit. It certainly can be changed at build time --just modify the 'icons/bug-138x60.xpm' file before building the software-- but is intentionally not exposed in the runtime user configuration. As you mention, the end user does get a generous amount of space for branding of their own. (Which reminds me: we really do need to replace that 'User Logo' placeholder image with something a bit snappier.)
