### ISSUE TITLE
RD V4 latest beta - pypad_icecast2.py - ModuleNotFoundError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#800]
Hi

Do i miss something on my debian11 testsystem, running the latest QT5 V4 Beta..

Thanks in advance...

`Traceback (most recent call last):
  File "/usr/lib/rivendell/pypad/pypad_icecast2.py", line 31, in <module>
    from rivendellaudio import pypad
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 24, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/rivendell/pypad/pypad_icecast2.py", line 33, in <module>
    import pypad  # Rivendell v3.x style
ModuleNotFoundError: No module named 'pypad'
`

**Comment by ElvishArtisan** [comment]
As per the 'INSTALL' file, that plug-in requires the PyMySQL module. That should be provided by the ' python3-mysqldb' package.

**Comment by RudiOnTheAir** [comment]
Uups. Sorry. And yes.
Thats the package name also on Debian 11.

Fixed
