### ISSUE TITLE
BUG : Default group when editing multiple carts

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#802]
Hi
On qt5 branch (at least), when editing multiple carts at the same time, for changing scheduler codes or artist or whatever, the GROUP menu defaults to the first group item on the system, which may change groups for all the carts if one does not notice it.
I change a whole bunch of carts from MUSIC to BEDS group before I noticed it.
There should be a "no change" or empty item by default, or, at least, the menu should default to the group of the first cart selected for edition.

**Comment by ElvishArtisan** [comment]
Unable to reproduce the problem here. Can you give me a step-by-step procedure to goose it?

**Comment by fpeyraud** [comment]
- Install a fresh and minimal ubuntu 22.04
- Install mariadb-server and rivendell (from rivendell-fr packages)
- create a dropbox importing in MUSIC group
- import ~10 songs via the dropbox
- Open rdlibrary and see all the songs correctly stored in the MUSIC group
![image](https://user-images.githubusercontent.com/87763/166259238-b53a123b-9c6e-4ef7-9381-9728bb2080d9.png)

- select a bunch of the freshly imported carts and click EDIT button
- The mass cart edit window shows the BEDS group selected by default
![image](https://user-images.githubusercontent.com/87763/166259403-59feefa8-e022-4223-a4c1-3c05c58d9582.png)
- clicking OK, the selected carts are transferred to the BEDS group
![image](https://user-images.githubusercontent.com/87763/166259621-df6c0d89-c927-4927-9168-69c89a32987b.png)

In my opinion, there should be an empty option in the GROUP menu, selected by default, which does not alter the groups of selected carts. This would be coherent with the other fields which are left empty to keep cart information unchanged.
Currently, only the existing GROUPS are listed in the menu
![image](https://user-images.githubusercontent.com/87763/166259956-291e56dc-5237-4b3d-a9c7-daa56d73e391.png)

**Comment by ElvishArtisan** [comment]
> Install mariadb-server and rivendell (from rivendell-fr packages)

Ah, so you're running v4.0.0beta3. Looks like this issue has already been corrected in the GitHub qt5 branch.

**Comment by fpeyraud** [comment]
No, I did not change the version number, but it's actually the commit 29a5a26a

**Comment by ElvishArtisan** [comment]
So you did not install packages from rivendell-fr?

**Comment by fpeyraud** [comment]
yes, but from the special qt5 repo :

`deb [arch=amd64] https://apt.rivendell-fr.org/ jammy qt5`

**Comment by ElvishArtisan** [comment]
Ok, I've tweaked the UX a bit in the 'Edit Cart' dialog to make multi-cart editing a bit more discoverable. Instead of showing a blank entry by default, the __Group:__ and __Usage:__ dropdowns will now display '[unchanged]'. This also fixes the problem where it was formerly impossible to re-select the blank entry once a specific value had been selected in each dropdown.

Implemented in 0a633f27. Please test!

**Comment by fpeyraud** [comment]
Hello
Thanks a lot. I've tested and it's OK !
There may be some more UX tuning to do on the cart mass editing window, but this will be for another issue !
