### ISSUE TITLE
BUG rdairplay : buttons overlapping log

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#803]
On qt5 branch
When Main Log widget is selected and the window width is more than 1410 pixels wide (on a full HD screen), the log operation buttons overlap the log item listview
![image](https://user-images.githubusercontent.com/87763/166238827-c7942327-8300-4a5f-b0e3-60864483808e.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 89244593. Please test!

**Comment by fpeyraud** [comment]
Hi
No more overlap, but just a small change in space between buttons and list. I presume that it's due to fixed sizing and positioning in the code instead of using QVboxLayouts. Not blocking. Maybe a future improvement.
Thanks for the fix :)
