### ISSUE TITLE
RDAirplay/LogMachines: Log going muted very often.

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#806]
Hi... Probably not the right place to post this (I'm thinking on the mailing list...but I'm not sure it is operational and I'm also able here to share screenshots). Hope I can close this quick... now to the point:

I think I'm completelly misunderstanding the point on Markers (still!) , since as setup them on more and more and tracks, the more evident is that MainLog gets muted to 0 (sometimes it also ducks for some unknow reason in the middle of a playback...but that's another history)

So... I'm analyzing occurences of this, take screenshots of the affected tracks markers, and share here.

So here's the tail of a track, where (as I understand them) I setup a fede-down before the segue point, since I want a longer/smoother fade down of the track. I check No Fade on segue out mark because the segue start point is just on the last splash... so I don't see the need to fading down 'twice'

![Screenshot at 2022-05-05 17-51-18](https://user-images.githubusercontent.com/1419896/166964023-3efe90a0-b678-4ee0-a67e-cfc21362943d.png)

And here the start of the next one (This is how I'm editing most of the tracks): I have a fade Up mark that intends to bring up the track while on the first bar, then I got a bar of plain base before marking the Talk starting point:

![Screenshot at 2022-05-05 17-52-10](https://user-images.githubusercontent.com/1419896/166964925-9e6c81ef-9ddf-44a5-8da7-76f1a53c483a.png)

Expected result is that first beat of the new track silently starts over the last beat (splash/crash) of the fading-down ending previous track, then the volume gets up and reaches fully up on the end of first bar...
Actual result is that the ending track does as espected, with MainLog eventually getting silent as next start goes up... but level never recovers... The track is playing on RDAirplay, but vumeters are down as MainLog level is stuck at 0. I need to manually send an RML command to set level to 0.

Why is that happening? What Am I doing wrong?

Thank you in advance.
Best regards.

**Comment by alexolivan** [comment]
I'm starting to think something may be wrong here.

I observed a whole track playing while Main Log machine was muted (as it often happens)...I let it play all along, and watch what will happen as the next track is reached and segued, since it has a fade up mark after the start mark:

![Screenshot at 2022-05-10 10-59-33](https://user-images.githubusercontent.com/1419896/167591597-afaead11-de2e-4375-ae52-36480883ae5c.png)

But the MainLog kept faded down...as if fade up marks do not work effectively fadding up, but effectively set the level down at the start, leading silence.

I have to observer the behaviour without fade up marks after a 'mutted status', and see if it recovers...

**Comment by alexolivan** [comment]
Nice! How quick! ... I was worried thinking that the database data would have been written in the wrong fields and all the work in RDlibrary was at stake... but being the problem in the log machine I'm somehow relief.

Sure this ugly bug will be crushed soon or later... although probably easier said than done.

Cheers!

**Comment by ElvishArtisan** [comment]
>  I was worried thinking that the database data would have been written in the wrong fields and all the work in RDlibrary was at stake... but being the problem in the log machine I'm somehow relief.

Unfortunately, the reality is precisely the opposite --i.e. the log machines are working properly; rather, the marker editor was transposing the fields during during load and save operations. :(

**Comment by alexolivan** [comment]
> Unfortunately, the reality is precisely the opposite --i.e. the log machines are working properly; rather, the marker editor was transposing the fields during during load and save operations. :(

Ouch! That hurted :-P ... I think this time maybe justified to backup the DB first, and then try to 'flip' the fields with some kind of SQL script... scary stuff, but could be interesting and should work!

Will test as soon as I can apply updates to the test VM!

**Comment by alexolivan** [comment]
Hi.

It took me somehow long time to backup everything and re-install rivendell so I could get up-to date in packaged install.
I also was in need to test the SQL scrit I mentioned earlier to 'swap' markers on the existing database.

I've been listening my radio again for a while, and it seems its working beatifully! yayyyyyyy :-D

I'm closing this now, but will keep listening for I while to check how it goes along with GTS pips, fake ads, etc... (well, the full feat  test I've being doing) to ensure this big ugly bug is dead :-)

Thank you!
Cheers
