### ISSUE TITLE
RDLOGEDIT/VOICETRACKER bigger size kills marker position

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#810]
Hi

On my Debian11 Setup (latest qt5) a strange gui problem, depending on the size of the VT... I made a screen recording simple with my cellphone to show.

https://cloud.schwoon.net/index.php/s/spaLGNFowYp86pY

**Comment by ElvishArtisan** [comment]
Fixed in c7e8a92. Please test!

**Comment by RudiOnTheAir** [comment]
Yes. Seems OK now. That was very quick. Many thanks...

**Comment by RudiOnTheAir** [comment]
Reopen that issue...
It is better, but not perfect. The marker are walking, but not very fast...

**Comment by RudiOnTheAir** [comment]
The seque marker are moving too...

**Comment by RudiOnTheAir** [comment]
Hi

Are there already considerations how to change the inaccuracy of the waveform in the Voictracker?

Thanks and a nice weekend!

**Comment by ElvishArtisan** [comment]
'Kay, finally got a chance to come back to this. Should be fixed in 9a10bba. Please test!

**Comment by RudiOnTheAir** [comment]
Yesssss.. That looks much better. The next days i will make more tests, but i seems that there is no more shifting around.
One Question. The vertical green line marks the play position?? One my system i notice a small delay from what i see and what i hear. I seems like the left edge of the waceform window is the playposition. And sometimes the green line disappears.. More can i report later this week...

Thanks for fixing!

**Comment by ElvishArtisan** [comment]
> The vertical green line marks the play position?? 

Yes.

> One my system i notice a small delay from what i see and what i hear. I seems like the left edge of the waceform window is the playposition. And sometimes the green line disappears.. More can i report later this week...

What type of audio setup are you using (ALSA, JACK, HPI)? Also, what audio parameters (format, samplerate, bitrate, etc)?

Thanks for testing!

**Comment by RudiOnTheAir** [comment]
> What type of audio setup are you using (ALSA, JACK, HPI)? Also, what audio parameters (format, samplerate, bitrate, etc)?
Jackd, pcm, 44.1 khz
I have seen the lag on my audio workstation. Server and Client running on local 1Gb/s Switch. NFS storage.
 
> Thanks for testing!
Thanks for your work!

**Comment by RudiOnTheAir** [comment]
Hi
After a long time, due to family needs, I found time to test the RC. As it looks, the display in the voice tracker works. Except for the thing with the delayed display of the waveform. What u see is not what u hear... ;)

I tested another feature that would save me a lot of time. Rendering a log. Since I work a lot with ramptalks, i.e. push the following track under the voicetrack, it now always happens that the voicetrack fades out after the start of the following track instead of continuing to run at full volume. You can then no longer hear the moderation to the end. Goofy on a ramp talk. ;)
RDairplay is doing it right with the same log...

Any idea? 

Thanks and a nice weekend.

**Comment by CWJR** [comment]
Known problem with rendering.  Solution is to change all voice-tracks 
to "no fade on segue".  I have suggested that the default for all new
files should be "no fade on segue", not the other way around (which is
what it is).  In our operation, everything is a "segue" transition, and
it is very rare that we want a fade on any segue.
--Chuck

**Comment by RudiOnTheAir** [comment]
Hi

This would require finding all the voicetracks of a log (in rdlogedit) and manually changing the no fade switch there.?
I would have to look up the cards by number because I have a lot of old logs whose voicetracks haven't been erased yet.

Maybe it would make the most sense if you had a choice per group in rdadmin how to deal with the fades.??

--
Rüdiger

**Comment by CWJR** [comment]
Right!  Which renders the whole Render option pretty useless.  There does not seem to be much commitment to fixing this.  The only time I have used Render was when we had a whole weekend special broadcast that was a 100% voice-tracked remote due to Covid restrictions.  I had to import all the VT's from contributors manually, so it was easier to click 'no fade' at the time of import, but in ordinary voice-tracking, that is a different story.

--Chuck

**Comment by RudiOnTheAir** [comment]
Hi

During the production of the last voicetracked show, I noticed that it makes a difference whether I listen to the voicetrack in rdlogedit/voicetracker or then play the finished log in rdairplay. This is partly imprecise and shifted, since it only fits if you leave suitable gaps.

Is there anything left to do before the release of V4? Version 3 was never accurate to the millisecond either, but that didn't matter much.

Thank you for all your work.

**Comment by ElvishArtisan** [comment]
> Is there anything left to do before the release of V4?

Test it on "real world" systems. That's actually been going on for some time, but that testing is now scaling up to larger setups. It was a test on a system with around 40 Rivendell instances on a single server that uncovered some scalability issues with the RDCatch subsystem, which has gone through some significant refactoring as a result. When it finally passes that benchmark, we should be close to ready for a production release.

> Version 3 was never accurate to the millisecond either, but that didn't matter much.

No automation system running on a general-purpose --i.e. non-hard-realtime -- OS will give you that kind of precision. The goal with Rivendell is more modest; namely, to make any latency jitter imperceptible to the human ear. If you're noticing it though, I'd call that a problem.

**Comment by ElvishArtisan** [comment]
> I tested another feature that would save me a lot of time. Rendering a log. Since I work a lot with ramptalks, i.e. push the following track under the voicetrack, it now always happens that the voicetrack fades out after the start of the following track instead of continuing to run at full volume. You can then no longer hear the moderation to the end. Goofy on a ramp talk. ;)
RDairplay is doing it right with the same log...

Fixed in 9bae0c8. Please test!

**Comment by ElvishArtisan** [comment]
> Which renders the whole Render option pretty useless. There does not seem to be much commitment to fixing this.

The title of this issue is "RDLOGEDIT/VOICETRACKER bigger size kills marker position". That issue was fixed in c7e8a92 on 25 May 2022, the day after it was reported. While that's certainly a quicker turnaround than most issues reported here, the moral of the story is: if you find a new anomaly, please open a new issue rather than hiding it within another, effectively unrelated one. The chances of the new problem being noticed and addressed in a timely manner will go up significantly.

Thank you both for your detailed bug reports. They are appreciated here!

**Comment by RudiOnTheAir** [comment]
Hi,
Made some render tests, and it works as expected. Then I close this issue. Thanks for ur work...!

For my  inaccuracy problem i will possibly open a new issue... ;)
