### ISSUE TITLE
Rivendell 4 Beta Reports Fail to be Generated

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#811]
## Problem Description ##
With Rivendel 4.0.0beta3 running on Ubuntu Studio 20.04, create a report ("technical playout" in this case), use rdlogmanager in GUI mode or command line mode to generate the report.
## Expected Behavior ##
A report gets generated.
## Actual Behavior ##
The report file is generated.  Sometimes a complete report _is_ generated. Other times the report file contains only the header text. When it fails to generate a complete report the command displays (in the terminal window from which rdlogmanager was launched) many messages like this:
```
invalid SQL or failed DB connection[Data too long for column 'SERVICE_NAME' at row 1 QMYSQL: Unable to execute query]: insert into `ELR_LINES` set `SERVICE_NAME`='MIX-3620061',...
```
## Analysis ##
It appears as if process IDs can be longer than 6 digits (on Ubuntu Studio 20.04 anyway), making the length of the string being inserted into column SERVICE_NAME longer than 10 characters (the length defined in the database schema).

The simple fix is to enlarge the size of SERVICE_NAME in the schema. Is that the right fix for this?

**Comment by ElvishArtisan** [comment]
> It appears as if process IDs can be longer than 6 digits (on Ubuntu Studio 20.04 anyway), making the length of the string being inserted into column SERVICE_NAME longer than 10 characters (the length defined in the database schema).

Sounds like a reasonable diagnosis.

> The simple fix is to enlarge the size of SERVICE_NAME in the schema. Is that the right fix for this?

I'd be reluctant to go that route, seeing as ```ELR_LINES``` is currently quite near the maximum supported row size for InnoDB tables. (Remember, we're using the utf8mb4 character set, which means that each character of a VARCHAR column can consume up to 4 bytes). A better approach might be to steal a couple of characters from the 'MIX-' prefix. Perhaps use 'MX' instead? This would allow up to eight-digit long PIDs.

**Comment by ElvishArtisan** [comment]
'Kay, I've just changed the 'MIX-' prefix to 'MX' and committed it as 8febf1d. According to [this discussion at StackExchange](https://unix.stackexchange.com/questions/231719/why-is-the-maximum-pid-in-a-64-bit-linux-system-222), Linux PIDs currently max out at 4000000, so that should provide sufficient room along with an order-of-magnitude cushion for future increases.

Please test!

**Comment by dklann** [comment]
Confirmed working here. This seems a reasonable solution. I'd say this is fixed for another generation or so ...
