### ISSUE TITLE
RDAirplay: Wrong cut shown on MainLog widget (top three slots)

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#813]
Hi!

Not sure wheter it worked differently in RDv3, or if it is the intended way to work but, since I've been splitting some of my carts into two 'dayparted' cuts (a longer, 'Original/Club Mix' that can be aired at night, and a shorter, 'Radio Edit' one, meant to be aired during daytime) I'm noticing that in RDAirplay, the first top three 'slots' of the MainLog widget do show the Cut that is being played and (As I suppose, maybe I'm wrong) the cuts that are going to be played for the next two carts.

Well... the issue is that, no matter what, the first cut (in my carts de original/log cut named 'Club Mix') is always presented as the one going to be aired, regardless of being on a time that should present 'Radio Edit' as the next cuts to be played:

![Screenshot at 2022-05-30 11-23-57](https://user-images.githubusercontent.com/1419896/170971393-fbe8433c-1ea0-4b3a-b296-1619a1555e80.png)

However, the actual daypart/airing playout works perfect!!! ... I mean, regardless of what is presented on the widget, no 'Club Mix' cut is aired at wrong time :-) . Instead, as the cart reaches playout time, the cut information is updated to 'Radio Edit', along with play time lenght, etc,  as the shorter cut is correctly aired

![Screenshot at 2022-05-30 11-27-27](https://user-images.githubusercontent.com/1419896/170971670-950b44c5-8860-4df5-99e9-0e609ad28894.png)

This behaviour, however, feels to me like counter-intuitive... I would expect either no cut information (if it is not possible to dertermine with certainty which cut is going to be aired), or the the cut information corresponding to the one that's going to be aired (according to cut airing rules and current time).

Cheers!

**Comment by ElvishArtisan** [comment]
> This behaviour, however, feels to me like counter-intuitive... I would expect either no cut information (if it is not possible to dertermine with certainty which cut is going to be aired), or the the cut information corresponding to the one that's going to be aired (according to cut airing rules and current time).

I think this is a very sensible suggestion. There's been code in Rivendell for years that attempts to predict what the next cut to play will be for a given cart, but it's very fraught process that (as you've observed) can easily go wrong. Better policy would be to just not attempt it at all!

**Comment by ElvishArtisan** [comment]
Implemented in cd8ee0c Please test!

**Comment by alexolivan** [comment]
Tested and confirmed!... closing
Thanks.
