### ISSUE TITLE
RDLibrary 'Unable to create destination file'

### ISSUE THREAD

**Issue by RubenGepkens** [ElvishArtisan/rivendell#814]
Hello,

I tried installing Rivendell v4.0.0beta3 on Ubuntu 20.04 LTS and 22.04 LTS but on both versions I am unable to import audio files. During importing with RDLibrary I receive the following message: "Import Error: Unable to create destination file".

The error occurs when adding or editing a cart. I am also unable to delete a cart and get the message: "RDLibrary: Unable to delete audio!". I tried to import different formats (WAV, FLAC, MP3) but that does not work. When launching RDLibrary as superuser I still get this error.

I was able to at least partially import audio using `rdimport` using the command line. This way a cart was added but no audio was imported (the card is coloured red).

During installation the 1 kHz test tone was generated without a problem. This file can be seen in `/var/snd/` and can be played normally in RDAirplay / RDLibrary.

The `/var/snd` folder has the following permissions, owner and group:
`drwxrwxr-x  2 radio rivendell 4,0K mei 30 17:34 snd`

The `/etc/rd.conf` is configured as follows:
```
[Identity]
; These entries are used to define the system user and group that will
; own the audio files.
AudioOwner=radio
AudioGroup=rivendell
```

The `radio` is my username for the system and is part of the following groups:
```
radio@radio-virtual-machine:~$ groups radio
radio : radio adm cdrom sudo audio dip plugdev lpadmin lxd sambashare rivendell
radio@radio-virtual-machine:~$ groups rivendell
rivendell : rivendell
```

I am not sure what I should do next. Please let me know if more information is required.

Kind regards.

**Comment by ElvishArtisan** [comment]
> [Identity]
> ; These entries are used to define the system user and group that will
> ; own the audio files.
> AudioOwner=radio
> AudioGroup=rivendell

> The radio is my username for the system and is part of the following groups:

The user/group specified in the ```[Identity]``` section should be dedicated system account, _not_ a personal account used for logging in. I'd suggest starting over again with a new 'stock' install.

**Comment by andrubemis** [comment]
I've been having the same problem importing from a dropbox. Here's what I'm getting from the system journal:

```
Nov 01 21:07:02 rd-MacBookAir rdimport[10874]: Importing file "SONG.wav" [Imported from SONG.wav] to cart 011139 ...
Nov 01 21:07:03 rd-MacBookAir ripcd[9907]: added new connection 73
Nov 01 21:07:03 rd-MacBookAir rdxport.cgi[11070]: processing RDXPORT_COMMAND_IMPORT
Nov 01 21:07:11 rd-MacBookAir rdxport.cgi[11070]: Unable to create destination file 'import.cpp' line 279
Nov 01 21:07:11 rd-MacBookAir rdimport[10874]: Audio Converter Error: Unable to create destination file, skipping /home/rd/music_import/SONG.wav...
Nov 01 21:07:11 rd-MacBookAir ripcd[9907]: added new connection 74
Nov 01 21:07:11 rd-MacBookAir rdxport.cgi[11073]: processing RDXPORT_COMMAND_DELETEAUDIO
Nov 01 21:07:11 rd-MacBookAir rdxport.cgi[11073]: unlink(/var/snd/011139_001.wav): Success
Nov 01 21:07:11 rd-MacBookAir ripcd[9907]: sent notification: "NOTIFY CART MODIFY 11139" to 239.192.255.72:20539
```
