### ISSUE TITLE
ALSA Config

### ISSUE THREAD

**Issue by jnk19** [ElvishArtisan/rivendell#816]
Hi guys,

I want to change the bit depth on the sound card I have. I have put on asoundrc after the rate 48000 (which Rivendell has auto make the config) format S24_3LE but still open it as S32_LE. Is there any config that can be done on Rivendell to set the the output bit depth?

Some help would be appreciated.

Regards.

**Comment by ElvishArtisan** [comment]
> I want to change the bit depth on the sound card I have. I have put on asoundrc after the rate 48000 (which Rivendell has auto make the config) format S24_3LE but still open it as S32_LE. Is there any config that can be done on Rivendell to set the the output bit depth?

Rivendell's ALSA driver natively supports S16_LE and S32_LE only. Curious: why exactly is S23_3LE required?

**Comment by jnk19** [comment]
Hi,

I was testing an AES67 driver which requires S24_3LE to be working correct. After all I leave it on S32_LE without any issues but I wondering if can be supported to S24_3LE.

Regards.

**Comment by ElvishArtisan** [comment]
> I was testing an AES67 driver which requires S24_3LE to be working correct. After all I leave it on S32_LE without any issues but I wondering if can be supported to S24_3LE.

Probably, but I lack a device for actually testing such a setup. FWIW, S32_LE, S24_LE and S24_3LE all effectively end up being PCM24 from Rivendell's POV; the differences being in how the audio frames are aligned within the data buffers. If S32_LE is working satisfactorily, I'd be inclined to just leave things as they are.

**Comment by jnk19** [comment]
Yes it is working correct with S32_LE no issues so far. You can give a check also with this driver:

https://github.com/bondagit/aes67-linux-daemon

It is working correct so far ^^ with Rivendell no problems at all.

Regards.

**Comment by ElvishArtisan** [comment]
Thank you for the link; will definitely check that out!
