### ISSUE TITLE
[BUG] RdAirPlay : Log does not restart after unclean shutdown

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#817]
Hello
I'm testing qt5 branch (commit [8e9be75](https://github.com/ElvishArtisan/rivendell/commit/8e9be755f6f5fc74d2ad5c4cb71fbf3f28ef3f36) ) on Ubuntu 22.04 (rivendell-fr.org packages) and I'm facing an issue : 
When aRdAirPlay is in Automatic mode and a log is playing (a real log generated by rdlogmanager, not a manually baked log), and I perform a hard reboot, the computer restarts and all the setup come back to life (caed launched, jack present, database and apache ready, session un and running, rdairplay launched automatically by session autostart), the last log is reloaded, but not started, even if the checkbox is checked in rdadmin>Manage Hosts>RdAirPlay>Restart log after unclean shutdown

![image](https://user-images.githubusercontent.com/87763/180210422-2c71851f-4f80-4615-b38d-cbc9d9ab7d2c.png)

I think it should restart automatically.
I feel like it is quite critical for stable production release.

Thanks by advance for your feedback

**Comment by ElvishArtisan** [comment]
> I perform a hard reboot,

By 'hard reboot', do you mean something like just hitting the hardware reset button or yanking out the power cord, or simply powering the system completely down and then restarting?

**Comment by fpeyraud** [comment]
Hello. I really mean a hard reboot like hitting reset button or unplugging
the power cord. A really dirty unclean shutdown.

Le mar. 13 sept. 2022 à 19:14, Fred Gleason ***@***.***> a
écrit :

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 73ab30c. Please test!

**Comment by fpeyraud** [comment]
Tested and fixed. Thanks !
