### ISSUE TITLE
Zip Download is "Not Available on Server"

### ISSUE THREAD

**Issue by philhulett** [ElvishArtisan/rivendell#822]
The Zip download of 3.4.1 is not available on the server. Can't download.  Targa is available. 
Using Chrome browser, Windows 10.

**Comment by ElvishArtisan** [comment]
We quit making ZIP downloads quite some time ago -- back around when v3.0 was released IIRC (2018-ish).

**Comment by ElvishArtisan** [comment]
Site has been refactored and the ZIP download link removed.
