### ISSUE TITLE
RD400b3 possible rdairplay bug

### ISSUE THREAD

**Issue by zotz** [ElvishArtisan/rivendell#824]
The ability to cue a cart while adding in rdairplay seems to not work for me. I can cue existing cards in log. Both seem to work as I expect in my 3.5.0 instance of rdairplay.

I am attaching pics to help explain.
![riv350_airplaycue01](https://user-images.githubusercontent.com/614926/191841384-8fd58486-6285-4954-89b8-ff169361407a.png)
![riv350airplaycue02](https://user-images.githubusercontent.com/614926/191841393-fefcb02c-9593-4fdf-8a66-0e4da6ccfea7.png)
![riv400b3airplaycue01](https://user-images.githubusercontent.com/614926/191841415-58b73934-301c-4a5d-804c-9482eaa7ed28.png)

![riv400b3airplaycue02](https://user-images.githubusercontent.com/614926/191841432-c8181591-a885-4115-b2b0-84950d4dd0a6.png)

all the best,

drew

**Comment by ElvishArtisan** [comment]
Is this v3.x or v4.x?

**Comment by zotz** [comment]
The pics are from 3.x and 4.x for comparison. The problem is with 4.x

**Comment by ElvishArtisan** [comment]
Thanks.

Fixed in 8ac9554 and 09b3d4c.
