### ISSUE TITLE
RDLibrary: Duplicate entries while managing carts

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#825]
Hi.
I found a situation where duplicate cart entries (same cart number) may appear in RDLibrary.
No back-end issues, as always, seems to be yet another qt5 pesky bug.

![Screenshot at 2022-09-08 17-11-32](https://user-images.githubusercontent.com/1419896/192095296-d6c3f09b-993c-4959-8f0d-51cdbc14424b.png)

I wanted to create a new macro cart out of an existing one (I don't know wether does a shortcut for that exist) so I started to work back and forth editing a new cart while copying from the existing one... then, I got that the new cart had like 'vanished', and rather, two duplicates for the other one were shown.
Closing RDLibrary and opening again showed both carts OK, since the new one was persisted the very moment I closed it to go to the existing one.

Cheers.

**Comment by ElvishArtisan** [comment]
Confirmed here. I have been seeing this occasionally too for a past few months, but have never been able to reliably reproduce it. Any hint would be welcomed!

**Comment by ElvishArtisan** [comment]
Fixed in d4a1879. Please test!

**Comment by alexolivan** [comment]
Unable to reproduce.
It wasn't usual to see that issue though... so I'm not sure whether I've tried hard enough to trigger it back again.
I've tried opening several macro carts and doing stuff with them for a while, and it all went well, so I will close this as fixed.

Thank you.
Cheers.
