### ISSUE TITLE
Question about languages

### ISSUE THREAD

**Issue by lbracci** [ElvishArtisan/rivendell#826]
Probably this is a stuped question, but I can't get Rivendell 4 beta to show another language, other than english. I've tried in Ubuntu 20.04 and Ubuntu 22.04 from a terminal window, running the RD applications with the "lang" environment variable set ("lang=ES rdairplay" , "export lang=ES", "lang=es" in lowercase too, etc.), but it didn't work. 

Any suggestions?

**Comment by ElvishArtisan** [comment]
Something like `export LANG=es_ES.UTF-8' should work, but it doesn't here either.

**Comment by ElvishArtisan** [comment]
Fixed in fef674a. You'll also need to ensure that you have the translation files for Qt5 installed; available in the 'qt5-qttranslations' package on RHEL-ish or the 'qttranslations5-l10n' package on Ubuntu-ish systems.

Please test!
