### ISSUE TITLE
RDCatch: Silent mp3 files Uploaded to RSS feeds 

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#827]
Hi.

Today, while coding a simple webapp to play my RSS episodes, I've realized that all MP3s are completelly silent.
Files are there, full weight and length, but all their contents is silence.
Source Cart/Cut recordings are OK (no normalization :-P), I can listen to them on RDLibrary.

Thinking on a normalization problem I did tests:
- RDAdmin -> ManageFeeds: Repost . That didn't make any difference.
- RDAdmin -> ManageFeeds, edit the feed and turn normalization OFF , then, from RDCast Manager y manually created an episode out of the cart/cut --> It worked!
- RDAdmin -> ManageFeeds, edit the feed, put normalization back ON, then from RDCast Manager, create episode from cart/cut -- it also worked!

So, apparently, episodes created manually from RDCast Manager from Cart/Cut, do work (including the normalization setting :-)
However, every single episode that has been uploaded automatically from an RDCatch event schedule, ends up in plain silence.

I've downloaded mp3 files to check them localy, both silent ones and good ones, looking for some difference, but they all look good from an encoding perspective, so, there seems to be no problem regarding the encoding part/settings but the content itself.

I've disabled normalization anyways on all feeds in RDAdmin -> ManagFeeds, just in case that trips the wire during an RDCatch Upload event. As new recordings will be uploaded as episodes, I'll see if that makes any difference.

Cheers!

**Comment by ElvishArtisan** [comment]
Unable to reproduce here. Everything works (manual/automatic, with/without normalization).

Could you post screenshots of:
- The feed configuration from ```rdadmin(1)```
- The upload event dialog from ```rdcatch(1)```

**Comment by alexolivan** [comment]
OK. Tonight there's a weekly recording scheduled. The longest one... its a 5h recording (really puting the thing up to the test :-). And this morning, the corresponding automatic upload to Feed triggered. So far so good.
Early on, let me point out that it has been a partial success... For the first time, I got a non-silent episode!
The only change I'm aware of, is that yesterday I disabled normalization in the Feed configuration. 
Now, that context is set, let me answer questions

> Could you post screenshots of:
> 
> * The feed configuration from `rdadmin(1)`

![Screenshot at 2022-09-30 10-05-42](https://user-images.githubusercontent.com/1419896/193223017-57512c9f-4f58-4727-baf0-c2dfc4fe0457.png)

> * The upload event dialog from `rdcatch(1)`

![Screenshot at 2022-09-30 10-07-23](https://user-images.githubusercontent.com/1419896/193223044-7dfefd3a-dbe8-457d-af58-3b21ee47e6c4.png)

Aditionally, here's the preceding recording envent details on rdcatch:

![Screenshot at 2022-09-30 10-09-40](https://user-images.githubusercontent.com/1419896/193223434-bcbbcda9-2afd-48e4-bcd6-e58893a395b2.png)

**Comment by ElvishArtisan** [comment]
> While previous episodes do seem to show the feed title, this one has an strange 'rdcatch=upload....' string.

Confirmed here, and fixed in c9fcf7b.

However, I've still not been able to reproduce your 'silent mp3' problem.

Thank you for the screenshots!

**Comment by alexolivan** [comment]
> Confirmed here, and fixed in [c9fcf7b](https://github.com/ElvishArtisan/rivendell/commit/c9fcf7b51b7bd6e718ba5848207ce1d6c8b75d43).

After upgrading to rc0 The title issue has been fixed! :-)

**Comment by alexolivan** [comment]
After upgrading to rc0, the two recordings of this night do appear two times, kind as if duplicated:

![Screenshot at 2022-10-08 16-38-36](https://user-images.githubusercontent.com/1419896/194713795-e464ce97-a5d5-4ed0-8d90-820cb918974c.png)

However, only the first of the episodes appears to actually have an asociated mp3 file uploaded, while the second one has an URL on the RSS/XML that points to a non-existant mp3 file (I can see 404 errors on console):
 
![Screenshot at 2022-10-08 16-38-10](https://user-images.githubusercontent.com/1419896/194714065-1ebc5c07-55d6-413f-99d3-3ab1014b71e8.png)

As a side note, the first recording on both shows have recorded successfully regarding sound (no normalization) quality, integrity / lenght.
Looks to me as if the RDCatch Upload event has triggered twice somehow... RDcatch module shows only one event, I don't think DB duplicated entries. This entries have been in RDcatch/DB setup for months already.
Tonight, more recordings are comming... I'll keep reporting.

**Comment by alexolivan** [comment]
Neither the feed uploads of saturday-sunday sessions nor sunday evening ones have been duplicated.
Sound is OK. Title is OK.

I'm gonna close this issue.
- For sound, I dare to assert it is just normalization in RDCatch. Nothing to do with Podcasting/Feeds part.
- If duplicated recordings de appear in the future (I feel I'll see them sometime in the future) I'll open a separate issue. Again I would bet being some kind of strange RDCatch behaviour.
- For uploaded sound shorter than recorded one, I'll eventually open too a separate issue (no clue on what could cause this)

Thank you very much.
Cheers.
