### ISSUE TITLE
RDLogEdit should not allow a log to be voice-tracked from more than one instance at a time

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#83]
The voice-tracker algorithm in Rivendell only allows for a given log to be voice-tracked by one user at a time; multiple users will wind up overwriting each other's changes.  There should be a warning when a user attempts to open a log in the voice-tracker that is already being voice-tracked elsewhere.

**Comment by AaronJowitt** [comment]
With another automation system, we have the flexibility to have multiple instances voice tracking the same log.  For example, one announcer is in the StationC log for 15Sep voice tracking the 10am-2pm shift, while in another studio another announcer is in the StationC log for 15Sep voice tracking the 2pm-6pm shift.  Different shift, same log, works perfectly.  Desirable RD have this same flexibility.

**Comment by ElvishArtisan** [comment]
Fixed in v2.19.0.
