### ISSUE TITLE
RSS Feeds: invalid image URLs when no image is configured.

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#830]
Hi.

I've arranged a complex (again, trying to test as deep as my abilities allow me) set of feeds. One superfeed, and several other feeds.
So far, so good... But I have not dealt with images, icons, at all...  so, all I see in RDCastManager are 'defalt' icons all around.

So, I'm not sure whether the default image/icon should have been uploaded to the podcast server... if so, they're missing.

Now, digging on the RSS XML while parsing, I've realized that URL for the images do appear on the XML, however, they booth look strange, and useless, since there're no actual images uploaded.

Here's the kind of URL serrors I'm seeing on the RSS/XML (I checked the XML doing a console.log) 

![Screenshot at 2022-09-30 13-11-04](https://user-images.githubusercontent.com/1419896/193257948-032e620e-d02d-445c-b50e-a7c32d62c1a3.png)

I need some time to get some fancy images and populate the Feeds configuration more realistically...maybe once images are in place it all works. However, I would expect image URLs being either empty, or pointing to a default/placehold image (some .jpeg, .png, etc) but that's why I wonder wether the default RD icon should have been uploaded. 

Cheers!

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
While it would theoretically be possible to use the Rivendell RDCastManager logo as a default image, the logic involved in doing so would be intricate and finicky; plus I cannot imagine any actual production user not providing their own custom artwork. Thus, I've changed things so the relevant tag fields now get an empty value. N.B. this will cause certain schemas --e.g. iTunes-- to fail validation!

Applied in 882b77e. Please test!

**Comment by alexolivan** [comment]
OK!

Closing.
Thank you!
