### ISSUE TITLE
RD400rc0: When playing an item from RDAirplay, an error on console is thrown and the file doesn't play.

### ISSUE THREAD

**Issue by djmasa1** [ElvishArtisan/rivendell#831]
I've tried this several times and I can repeat it each time that i've tested so far. When playing 999999 (TEST) from RDAirPlay, I receive the following console error below and the item never plays:
Error from console: 

`invalid SQL or failed DB connection[Column 'EVENT_DATETIME' cannot be null QMYSQL: Unable to execute query]: insert into `ELR_LINES` set `SERVICE_NAME`='Production',`LENGTH`=0,`LOG_NAME`='SAMPLE',`LOG_ID`=1,`CART_NUMBER`=999999,`STATION_NAME`='test1',`EVENT_DATETIME`=NULL,`EVENT_TYPE`=3,`EVENT_SOURCE`=0,`EXT_START_TIME`=NULL,`EXT_LENGTH`=-1,`EXT_DATA`='',`EXT_EVENT_ID`='',`EXT_ANNC_TYPE`='',`PLAY_SOURCE`=1,`CUT_NUMBER`=1,`EXT_CART_NAME`='',`TITLE`='Test Tone',`ARTIST`='Rivendell Radio Automation',`SCHEDULED_TIME`=NULL,`ISRC`='',`PUBLISHER`='',`COMPOSER`='',`USAGE_CODE`=0,`START_SOURCE`=1,`ONAIR_FLAG`='N',`ALBUM`='',`LABEL`='',`USER_DEFINED`='',`CONDUCTOR`='',`SONG_ID`='',`DESCRIPTION`='1 kHz at Reference Level [-16 dBFS]',`OUTCUE`='[tone]',`ISCI`=''
`

This is a brand new system brought up to test out 4.0.0rc0. The system is Ubuntu Linux 22.04 running as a VM under VirtualBox. I attempted this multiple times. I also ran rddbconfig and even tried re-creating the database. There were no problems or errors brought up when creating the database. When it created the database, it automatically asked to upgrade it to the required database version. That went okay, also.  I made sure the rivendell database user had all permissions on the database, so it doesn't seem like a permissions issue as far as I can tell.

I'm testing with JACK. The rd.conf file is pretty much untouched except for the required database username/password/database changes. the JACK setup is from the same setup on the wiki.

**Comment by djmasa1** [comment]
It seems like this occurs if the file is missing. Chalk this up to not paying enough attention. Still shouldn't it just say the source file wasn't found?

**Comment by ElvishArtisan** [comment]
Doesn't sound right. While a missing file in the audio store will definitely keep play-out from happening, it shouldn't throw a SQL error. Was this system built using the standard installer?

**Comment by djmasa1** [comment]
It was compile from source un Ubuntu 22.04. There probably was some compiler warnings that flew by, but there were no errors on the build. I had everything linked and all the options were selected to be included in the build except for HPI support because we don't use any of that hardware, so it was really necessary. Everything else was per the build development released in the apt repository on Jellyfish Jammy repos at the time. I don't know if it's related, but I also noticed some errors being thrown during an rdimport session also, but I wasn't quick enough to figure out which files they were as I was doing a mass import from a directory. In the future, I'll pay closer attention to which files it was. The problem originally reported as above was the actual test file with the tone was missing, and that error was thrown in it's place, and of course nothing played because it simply wasn't there.

**Comment by ElvishArtisan** [comment]
> It was compile from source un Ubuntu 22.04. There probably was some compiler warnings that flew by, but there were no errors on the build.

You will definitely see compiler warnings on Jammy Jellyfish, mostly deprecation warnings from Qt5. Unfixable at a the moment due to the need to maintain backwards compatibility with Qt 5.9. Once CentOS 7 goes EoL (30 June 2024), we'll finally be able to clean these up.

**Comment by ElvishArtisan** [comment]
> I had everything linked and all the options were selected to be included in the build except for HPI support because we don't use any of that hardware, so it wasn't really necessary. Everything else was per the build development released in the apt repository on Jellyfish Jammy repos at the time. I don't know if it's related, but I also noticed some errors being thrown during an rdimport session also, but I wasn't quick enough to figure out which files they were as I was doing a mass import from a directory.

I suspect that there's something amiss with your runtime environment. When I set up a machine for source builds, I typically begin by doing a standard install using the online installer, then go back and remove the Rivendell packages and add the necessary development packages. That way, I know I've got the "standard" run-time setup. (Which is not to say that there cannot be a problem with that setup, but it takes a lot of the possible "oops, forgot to set up MySQL | Apache | desktop | &lt;whatever&gt;" problems off the table).

**Comment by ElvishArtisan** [comment]
Closing this for now. Feel free to reopen if this recurs.
