### ISSUE TITLE
RDCatch: Cant schedule recording event

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#834]
Hi.

While editing events in RDCatch, I've found that events are kinda 'locked' regarding their Active Days checkboxes setup.
Switching an event from one day to another, by changing checked switchboxes results in an error stating that an event with there parameters already exist.
Early tests seems to show that while I can add more checkboxes, the problem seems removing them (where moving one check from one checkbox to another implies a remoing somehow).

A very visual situation happens where you can't simply remove an event Active Day... Here, an event scheduled every Monday and Friday...
![Screenshot at 2022-10-14 20-27-02](https://user-images.githubusercontent.com/1419896/195916845-c36158e1-f0c5-47f4-ab92-1518029df92b.png)

Can't be changed to be just monday:
![Screenshot at 2022-10-14 20-25-17](https://user-images.githubusercontent.com/1419896/195916332-b85b7a0e-9d70-48c2-85dc-4b01e889b888.png)

My guess this is simply some kind of qt5/frontend validation issue

Cheers.

EDIT 1:

Further testing shows that the problem seems to be Monday 00:00.
I've tried creating other events, and editing them and there's no problem... however, whenever I taget Monday on the first clock, I got the issue

EDIT 2:
Turns out that I can actually schedule the event, as long as the start time seconds value does not matches other events (different week days). So, as other day events are on second :22 , I can persist either in second :21 or :23 , but is :22 value what triggers the error:

![Screenshot at 2022-10-14 20-57-42](https://user-images.githubusercontent.com/1419896/195921472-1b67938d-6eab-47b7-a9b8-bb0f91a1adb1.png)

![Screenshot at 2022-10-14 20-58-04](https://user-images.githubusercontent.com/1419896/195921498-06ed1abe-7650-4847-ab54-f35e9d6f3b7e.png)

**Comment by ElvishArtisan** [comment]
Unable to reproduce the problem here. Any chance that you could post a 'click-by-click' for reproducing it? (Preferably, starting with creating new record event(s) from scratch).

**Comment by alexolivan** [comment]
I'm unable to figure a cause for this, but the issue is there.

I'm sure this is Front-End related, though, because I've been struggling to find an explanation for this looking directly at the DB table.

I'm on it on my spare time... I think there must be a reason why in some circumstances, the frontend mis-identifies two events to be the same, while they're not.

**Comment by ElvishArtisan** [comment]
Found it! Fencepost error in the validation code.

Fixed in 63841a4. Please test!

**Comment by alexolivan** [comment]
You got it! ... it's fixed. closing, Thank you!
