### ISSUE TITLE
PyPAD scripts have no effect

### ISSUE THREAD

**Issue by expertup** [ElvishArtisan/rivendell#837]
I have installed Rivendell on CentOS 7 by this tutorial: http://static.paravelsystems.com/rivendell-install-rd3/rivendell-install-rhel7.html

I have two songs in library for test.
![image](https://user-images.githubusercontent.com/1708687/199333525-243975e5-7c5a-4da7-b285-cfd501c63e20.png)

In PyPAD instances are 2 scripts:
1. stadnard pypad_filewrite.py script
2. remaked pypad_urlwrite.py script (I added other ftp lib for suport tsl mode) 
![image](https://user-images.githubusercontent.com/1708687/199333909-453350d9-877c-4b54-8cf4-4a405fb1b77e.png)
![image](https://user-images.githubusercontent.com/1708687/199334190-6aafd697-b07b-4753-9371-0c34fb71e9b3.png)

But, when I play songs in RDAirPlay as if no script was executing. This means that the song title is not saved to the text file. I checked the FTP script in console itself (its separate part) works fine, bun not form Rivendell.
![image](https://user-images.githubusercontent.com/1708687/199334959-63b85ea9-4edc-4f67-9d89-44d64523352b.png)

What could be the reason why the scripts "do not work"? I asked the people for whom I am carrying out the order - they had no idea.
I don't have Rivendell connected to any audio server, could that be the reason? Overall, the title of the song must be saved in an FTP file, because there is no other option.

**Comment by jmpalmito** [comment]
did you select any group in the "group selection" section ?

**Comment by expertup** [comment]
> did you select any group in the "group selection" section ?

Do You think about group in import song? Default is "BEDS" and I imported song under this gorup. This You can see on 1st screen.

**Comment by jmpalmito** [comment]
I meant in the pypads configuration:  there is a section where you can choose (or not) the groups allowed. perhaps is the beds group not allowed

**Comment by expertup** [comment]
> I meant in the pypads configuration: there is a section where you can choose (or not) the groups allowed. perhaps is the beds group not allowed

Ok, I found this! In group must check "Transmit now & Next data".

It is probably mentioned somewhere in the documentation :-)

But thank you very much for pointing.

![VirtualBoxVM_9KH6llZqlR](https://user-images.githubusercontent.com/1708687/199592003-05f1c82e-7cbf-4047-aa38-489e749b71d8.png)
