### ISSUE TITLE
RD4.0.0rc0-1:  CAE segfault

### ISSUE THREAD

**Issue by brettpatram** [ElvishArtisan/rivendell#838]
Observed was a hang in the rdairplay application on my test system. rd4.0.0rc0-1 running on Ubuntu Studio/ Jammy 22.04

Log snippet of systemd journal right before segfault:

```Nov 03 22:08:08 rdserv1 caed[39073]: StopPlayback - Card: 3  Stream: 1  Handle: 88
Nov 03 22:08:08 rdserv1 rdairplay[45334]: log engine: finished event: Line: 487  Cart: 11265  Cut: 1 Card: 3  Stream: 1  Port: 0
Nov 03 22:08:08 rdserv1 caed[39073]: UnloadPlayback - Card: 3  Stream: 1  Handle: 88
Nov 03 22:08:08 rdserv1 kernel: show_signal_msg: 4 callbacks suppressed
Nov 03 22:08:08 rdserv1 kernel: caed[39087]: segfault at 55e01b340747 ip 00007f8073e21b35 sp 00007f8066625a10 error 4 in librd-4.0.0rc0.so[7f8073b4b000+3db000]
Nov 03 22:08:08 rdserv1 kernel: Code: 48 23 50 20 48 89 50 10 5b 4c 89 e0 5d 41 5c 41 5d 41 5e c3 90 48 8b 40 10 4c 89 e2 4c 89 ef 48 01 c6 e8 0e 0d d4 ff 48 8b 03 <48> 8b 50 10 4c 01 e2 48 89 50 10 48 8b 50 10 48 23 50 20>
Nov 03 22:08:08 rdserv1 systemd[1]: Started crash report submission.
Nov 03 22:08:08 rdserv1 whoopsie[352568]: [22:08:08] Using lock path: /var/lock/whoopsie/lock
Nov 03 22:08:08 rdserv1 systemd[1]: whoopsie.service: Deactivated successfully.
Nov 03 22:08:11 rdserv1 systemd[1]: Started crash report submission.
Nov 03 22:08:11 rdserv1 whoopsie[352583]: [22:08:11] Using lock path: /var/lock/whoopsie/lock
Nov 03 22:08:11 rdserv1 systemd[1]: whoops
[_usr_sbin_caed.0.crash.gz](https://github.com/ElvishArtisan/rivendell/files/9935339/_usr_sbin_caed.0.crash.gz)
ie.service: Deactivated successfully.
Nov 03 22:08:11 rdserv1 mariadbd[835]: 2022-11-03 22:08:11 701 [Warning] Aborted connection 701 to db: 'Rivendell' user: 'rduser' host: 'localhost' (Got an error reading communication packets)
Nov 03 22:08:49 rdserv1 rdairplay[45334]: RDCae lost 18 bytes when sending "LP  2 011629_001!"
```

Crash dump
[_usr_sbin_caed.0.crash.gz](https://github.com/ElvishArtisan/rivendell/files/9935344/_usr_sbin_caed.0.crash.gz)

A restart of Rivendell service got system back into an operational state again

Since this involves audio engine I will note that Rivendell is configured to use the alsa loopback driver for playback . 
Because of this, I must take advantage of the subdevices exposed to achieve multiple stereo playbacks.  asound.conf is manually edited so that the rd.n devices aliases address the subdevices of the same card, device.

**Comment by ElvishArtisan** [comment]
Sounds like a decidedly non-standard setup. I'm curious: what requirement drove the need for this?

**Comment by brettpatram** [comment]
> Sounds like a decidedly non-standard setup. I'm curious: what requirement drove the need for this?

The use of the alsa loopback driver is to pass stable/low latency audio samples from CAE into several gstreamer app stacks acting as consumers. These app stacks do various jobs such as payload audio into RTP to send to network, and vice versa for receiving back from the network. While jack can satisfy the same things (and more) like alsa loop, there is a performance and resource efficiency realized utilizing Alsa as the "transport" mechanism to other userspace apps

**Comment by ElvishArtisan** [comment]
Fair enough. However, it's going to be difficult to troubleshoot this because of the number of moving parts involved. At a mimimum, we going to need backtraces from any crashes. Those should be available in '/var/crash'.

**Comment by brettpatram** [comment]
I will need to figure out why nothing was written to /var/crash on my system.  However I was not run into another segfault for past 15 days.  Closing due to lack of needed data to investigate further
