### ISSUE TITLE
Strange behaviour RML DP command (potential bug ??)

### ISSUE THREAD

**Issue by jmpalmito** [ElvishArtisan/rivendell#839]
Hi,
V4.0
In opsguide  : 

> "14.8.35. Play Slot [DP]
> [...]
> Play the cart currently loaded in the slot slot. The slot must be in Cart Deck mode. This command will be ignored if the slot is unloaded or already playing. "
> 

If I use this RML command when the cartslot is already playing, it launches a second time the slot from the beginning without stopping the first one, the slot is playing twice. I can stop both with the stop RML command (DS). But when I use the DP command again, I can hear the previous mix again (same song playing twice) + the new one that i've just launch (the slot is playing 3 times the same song). This can only be stopped by exiting RDcartslots.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 7066ebf. Please test!
