### ISSUE TITLE
RDLibrary in branch qt5, Copying Cuts Fails

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#843]
Where: all commits to branch qt5
What: Copying Cuts in RDLibrary fails
Why: typo in lib/rdcut.cpp, line 991
```"where `CUT_NAME`='"+cutName()+"i";```
should be
```"where `CUT_NAME`='"+cutName()+"'";```

I would create a pull request, but I'm lazy and will let you fix it @ElvishArtisan!

**Comment by ElvishArtisan** [comment]
Yup, that's definitely a 'Fred wasn't paying attention' bug.

**Comment by ElvishArtisan** [comment]
Fixed in 497ccd4. Please test!

**Comment by dklann** [comment]
Yes, belated confirmation that this is now working. Thanks!
