### ISSUE TITLE
Icecast PyPad Now/Next in v4.0.0rc0 includes all groups regardless of explicit inclusions

### ISSUE THREAD

**Issue by WLGW-Ops** [ElvishArtisan/rivendell#845]
Greetings!

I've encountered a potential issue during tests of v4.0.0rc0 that appears to prevent Icecast2 PyPad from excluding groups not explicitly listed in NowGroups/NextGroups. I have a specific group (Stingers) that I would like to exclude from metadata transmission. Screenshots attached for reference (really enjoy the scalable RDAirplay GUI btw).

Best Regards,
Brian
WLGW Operations

![Screenshot from 2022-11-27 06-16-17](https://user-images.githubusercontent.com/119166967/204135281-4a0571bb-d21b-428e-9789-a73a52b766fe.png)

![Screenshot from 2022-11-27 06-14-21](https://user-images.githubusercontent.com/119166967/204135276-41ef7742-ba27-41af-b730-55350e9bb53d.png)
![Screenshot from 2022-11-27 06-15-26](https://user-images.githubusercontent.com/119166967/204135279-041b6725-e1c6-4d9c-bfba-a0d03198995c.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Ok, I see what is going on here. You've specified a set a groups in the ```[NextGroups]``` section, which will trigger a PAD update if a cart belonging to any of those groups is the "next" to play, _even if the "now" playing cart doesn't belong to one of the listed groups_.

To fix this, use a ```[NextGroups]``` section like this:
```
[NextGroups]
Group1=NOSUCHGROUP
```
A group named "NOSUCHGROUP" can _never_ occur, so the effect will be to turn off forwarding for "next" events entirely.

**Comment by WLGW-Ops** [comment]
Awesome, I'll test this and confirm from my end.

**Comment by WLGW-Ops** [comment]
The suggested change works as expected. Thank you much!
