### ISSUE TITLE
Deleted Cart Cached in RDAirplay (V4.0.0rc0int2 on Version 22.04.1 LTS Jammy Jellyfish)

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#846]
If a recently played cart is deleted prior to restarting RDAirplay, the cart will be presented in the RDAirplay Select Cart applet with the original cart data.  If that deleted cart is selected for play it will load in RDAirplay however, with an error in the cart box indicating [CART NOT FOUND].  

To Reproduce, create a test cart in RDLibrary, save it, and then select for play in RDAirplay.  Once the cart has finished playing (or has been stopped  and deleted in RDAirplay) delete in RDLibrary, then select for play in RDAirplay.

If RDAirplay is closed and re-opened, this behavior will not occur. That is, the deleted cart will not re-appear.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in a157602. Please test!

**Comment by WMTH** [comment]
Ran a few tests following compilation of the code and found that the reported issue has be eradicated.
