### ISSUE TITLE
RDLibrary CD Rip issues in v4.0.0rc3 (Ubuntu 22.04.1 LTS Jammy Jellyfish) - Confirming #847

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#848]
Also seeing "CD Text Reader Process Failed [Call to /usr/bin/cdda2wav failed]" messages when opening the "RIP CD" function in RDLibrary.  This is still occurring in the rc3 build of this morning.

**Comment by ElvishArtisan** [comment]
Sounds like you're missing icedax(1). Available in most distros by installing a package of the same name. See the ```INSTALL``` file.

(And yes I agree, that's a horribly non-intuitive name). :)

**Comment by WMTH** [comment]
Installed icedax, and tested; indeed the problem is solved.
