### ISSUE TITLE
RHEL 9 install script points to 8rd4 repo

### ISSUE THREAD

**Issue by WLGW-Ops** [ElvishArtisan/rivendell#853]
Not sure if RHEL 9 is an active development branch or not, but noticed the install_rivendell.sh points to 8rd4 repos as indicated per the attached.

![Screenshot from 2022-12-28 12-16-49](https://user-images.githubusercontent.com/119166967/209855590-e4a61226-806a-428e-94cd-06ad3b25d11b.png)

Best Regards,
Brian
WLGW Operations

**Comment by ElvishArtisan** [comment]
On Dec 28, 2022, at 13:23, WLGW-Ops ***@***.***> wrote:
> Not sure if RHEL 9 is an active development branch or not, but noticed the install_rivendell.sh points to 8rd4 repos as indicated per the attached.
> 
It’s no longer active (see the announcement for v4.0.0rc1). That whole installer is about to go away. It was a nice try at least…

Cheers!


|---------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |             Chief Developer             |
|                           |             Paravel Systems             |
|---------------------------------------------------------------------|
| Impossible, adj.:                                                   |
|  (1) I wouldn't like it and when it happens I won't approve; (2) I  |
|  can't be bothered; (3) God can't be bothered. Meaning (3) may      |
|  perhaps be valid but the others are 101% whaledreck.               |
|                                                                     |
|                                              -- Chad C. Mulligan    |
|                                              "The Hipcrime Vocab"   |
|---------------------------------------------------------------------|

**Comment by WLGW-Ops** [comment]
Gotcha, good to know.
