### ISSUE TITLE
v4.0.0rc1 RHEL 8 install package conflict w/ rivendell-opsguide

### ISSUE THREAD

**Issue by WLGW-Ops** [ElvishArtisan/rivendell#854]
Greetings,

I'm receiving a _rivendell-opsguide_ package conflict between **rivendell-4.0.0rc1-1.x86_64** and **rivendell-4.0.0rc1-1.x86_64** during installation. Removing rivendell-opsguide from line 148 of /usr/share/rhel-rivendell-installer/installer_install_rivendell.sh allowed the installation to proceed on the subsequent attempt.

![Screenshot from 2022-12-28 17-19-46](https://user-images.githubusercontent.com/119166967/209884402-02148e36-655a-4e2b-949a-28ed887f3c18.png)

![Screenshot from 2022-12-28 17-48-58](https://user-images.githubusercontent.com/119166967/209886469-999842a4-d0ce-452c-8bee-884a387b3438.png)

**Comment by WLGW-Ops** [comment]
Quick follow-up here...

@ElvishArtisan  - Any chance to review and/or confirm the above? Is this just a matter of the RHEL 8 packages not being finalized or is something else going on? If I'm flawed in testing the RPM package install, let me know and I'll proceed with source for further testing....

Best Regards,
Brian

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed and synced to the online installer instance. Please test!

**Comment by WLGW-Ops** [comment]
Thanks Fred, I’ll test this evening and confirm.

**Comment by WLGW-Ops** [comment]
Confirmed - issue with package conflict is resolved. I'm encountering a new issue with ASI card detection that didn't previously exist; not sure if that would be relevant to any package changes or not? I'm continuing to investigate on my end in case it's a hardware / OS config problem.

**Comment by ElvishArtisan** [comment]
What model card are you using? The driver that the v4.x installers use is the current one from AudioScience, meaning that cards that have been end-of-lifed by ASI likely won't be detected.

**Comment by WLGW-Ops** [comment]
I'm using an ASI5211 (obsolete...old production room workstation).

I was able to get it working, however in doing so I observed some missing directories:

- /usr/src/asihpi-4.20.35
- /var/lib/dkms/asihpi

I copied the missing dirs and symlinks over from another sandbox and everything worked as expected. Thoughts?

Best Regards,
Brian

**Comment by ElvishArtisan** [comment]
Unable to reproduce this here.

> I copied the missing dirs and symlinks over from another sandbox and everything worked as expected. Thoughts?

So what was the provenance of these files on the other sandbox?

**Comment by WLGW-Ops** [comment]
I figured out the delta between my two test environments: The problem instance had a version mismatch between the kernel and kernel-headers packages. Someone (aka me) failed to update packages on the host prior to Rivendell installation. I was able to reproduce the non-issue on subsequent OS reloads. No problems encountered with the Rivendell installer itself.

Cheers,
Brian

**Comment by ElvishArtisan** [comment]
Cool. Thank you.
