### ISSUE TITLE
Possible bug or question regarding NowGroups/NextGroups

### ISSUE THREAD

**Issue by djmasa1** [ElvishArtisan/rivendell#857]
I'm using the pypad_glasscoder.py script. It doesn't seem to be processing the NowGroups and NextGroups section of the configuration. I just read about how to put this feature in v4.x's opsguide.. It's sending ALL updates regardless of the configuration being set. When setting the configuration, does the services have to be restarted or can it just take the configuration update on the fly? As a troubleshooting step, I shutdown the RDAirplay instance, shutdown glasscommander,  and restarted the Rivendell services. After that, I brought up RDAirplay manually and then brought up glasscommander.

The configuration for the host's pypad entry has this config:

UpdateUrl=http://10.10.10.2:1
MasterLog=Yes
Aux1Log=No
Aux2Log=No
VLog101=No
..
VLog120=No

[NowGroups]
Group1=MUSIC
Group2=SHOW
Group3=TRAFFIC

[NextGroups]
Group1=MUSIC

[Line1]
Key=StreamTitle
Value=%a - %t

**Comment by WLGW-Ops** [comment]
I ran into the same thing a while back. Fred advised to use "_Group1=NOSUCHGROUP_" in your next group since this group name cannot exist by design. Link below for more details.

https://github.com/ElvishArtisan/rivendell/issues/845

**Comment by djmasa1** [comment]
Interesting. I tried it with Group1=NOSUCHGROUP in the [NextGroups] section and the updates ceased on the [NowPlaying] area also, leaving Now Playing titles sent out via Glasscoder stale. After changing it back to what I had before, the updates still weren't processing. There are no errors that I can see in the syslog. I'm afraid I'm at a loss to explain what's happening.

**Comment by djmasa1** [comment]
So, troubleshooting a little further, because something was bugging me about it, I copied the config inside the instance area into a flat file and manually ran the pypad script as the rd user with:
/usr/lib/rivendell/pypad/paypad_glasscoder.py localhost 34289 py_glasscoder_test.cfg

The result is as I would have expected it to work with the system, the PyPAD script is running and updating with the now and next sections as expected. I even decided to keep the Group1=NOSUCHGROUP in on this config to see what happens. The result is what I would have expected given @WLGW-Ops 's comment from the earlier issue. So, I guess the confusion now is why is it through the error above and why does it say it's crashing?

**Comment by djmasa1** [comment]
To futher troubleshoot this, I terminated my manual running of pypad_glasscoder.py. I decided to update the instance config on a whim. I re-ordered the configuration file so that it has the [NowGroups] and [NextGroups] sections are defined before the [Glasscoder] section. I saved it. The PyPAD instance was saved without any errors and started to immediately run as expected. So I guess the lesson here is that the configuration order is important and it didn't like those being defined after the [GlassCoder] section for some reason.

**Comment by WLGW-Ops** [comment]
Glad to hear you were able to dig in and figure out what all was going on. I was out of town so missed the above until this evening. Any issues in the past day?

Best Regards,
Brian
WLGW Operations

**Comment by ElvishArtisan** [comment]
I think we have something squirrely going on in ```rdpadengined(8)```. I seen it deadlock a couple of times here as well, but haven't been able to reliably reproduce it.

**Comment by ElvishArtisan** [comment]
'Kay, I pounded on this a bit today and found/fixed a couple of ```rdpadengined(8)``` issues in 2f295cc. I think we're good now, but as always, please test if you're able!

**Comment by djmasa1** [comment]
Hi Fred,
Thanks always for your hard work on this. I'll try to test it out this weekend and see what happens and report back.

**Comment by djmasa1** [comment]
I have been able to confirm that this is indeed fixed as of 2f295cc.
