### ISSUE TITLE
v4.0.0rc1 no panel button animation on button press

### ISSUE THREAD

**Issue by dzkahn** [ElvishArtisan/rivendell#858]
On v4.0.0rc1, if a macro is assigned to a panel button, there is no animation when the button is press. Older versions had animation giving feedback the button was pressed, with the current behavior, the button could be pressed multiple times since there is no visual feedback.

**Comment by ElvishArtisan** [comment]
This is completely a function of the window manager|desktop|theme being used; Rivendell itself has no control over such styling details. I would suggest using [Linux Mint XFCE Edition](https://linuxmint.com/edition.php?id=304), an Ubuntu derivative that provides a nice, lightweight desktop with proper button animation,

**Comment by dzkahn** [comment]
If using Ubuntu 22.04, installing this package, gives button animation to the panel. 
sudo apt install qt5-style-plugins

**Comment by ElvishArtisan** [comment]
> If using Ubuntu 22.04, installing this package, gives button animation to the panel.
sudo apt install qt5-style-plugins

Good to know! Added a dependency for this to the DEB package in 6bfd69fd, so (as of next version release) this will get pulled in automatically.
