### ISSUE TITLE
v4.0.0rc1 Ubuntu installer does not add user to audio group

### ISSUE THREAD

**Issue by dzkahn** [ElvishArtisan/rivendell#859]
v4.0.0rc1 Ubuntu installer does not add the user "rd" to the "audio" group. This causes jack promiscuous mode not to work, since rivendell.service has environment=JACK_PROMISCOUS_SERVER=audio

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 0ca7cf4 and synched to the [Paravel-Ubuntu-22.04-Test](https://software.paravelsystems.com/ubuntu/dists/jammy/main/) repo. Please test!

**Comment by willvincent** [comment]
Confirm, rd user is correctly added to audio group now.

**Comment by ElvishArtisan** [comment]
Thank you.
