### ISSUE TITLE
rdairplay - Crashes when missing audio file is encountered

### ISSUE THREAD

**Issue by tcbeaton** [ElvishArtisan/rivendell#86]
We have experienced rare instances where a voice track file is not physically present in "/var/snd", but it is listed with cart number in the log. When this cart attempts to play, rdairplay crashes by freezing. No audio is played back from this moment forward until rdairplay is restarted.

The potential cause of the missing files *may* be related to the issue of multiple simultaneous voice tracking sessions on the same log - see issue #83.

**Comment by edglazer** [comment]
We've seen this too. To reproduce the problem:
1. Open an existing log
2. Insert voice track 
3. Start recording voice track
4. Cancel voice track
5. Use X to close window
This should include a cart in the log, referencing a file that doesn't exist in /var/snd which causes rdairplay to crash.

**Comment by ElvishArtisan** [comment]
Fixed in Github-stable.
