### ISSUE TITLE
I can't compile, where can I get the binaries?

### ISSUE THREAD

**Issue by daprose-dotcom** [ElvishArtisan/rivendell#864]
I can't compile the source code on windows, not enough nor precise instructions anywhere. Where can I obtain the binaries/execute for Windows?

**Comment by ElvishArtisan** [comment]
What exactly are you attempting to build? Rivendell itself is an unabashedly Linux-based system; there is no Windows support.

That said, there is support for building the C library for Rivendell's WebAPI on Windows, which enables things like accessing the Rivendell cart library and log subsystems. You can find build instructions for that in the 'INSTALL-WINDOWS` file at the top of the Rivendell source tree.
