### ISSUE TITLE
Rdimport is not importing artist info

### ISSUE THREAD

**Issue by workino** [ElvishArtisan/rivendell#866]
Hello,
this evening i found a problem importing a bulk of flac file in rivendell.
The artist tag is not imported correctly ( not imported at all :) )

is it my problem or is the rdimport?

Tag in the file:
- FLAC, 162.40 seconds, 44100 Hz (audio/flac)
title=Kings & Queens
album=Kings & Queens
albumartist=Ava Max
artist=Ava Max
copyright=2020
tracknumber=1
tracktotal=1
discnumber=1
disctotal=1
genre=
date=2020-06-30
isrc=USAT21906943
lyrics=
BPM=130.146

![image](https://user-images.githubusercontent.com/2070098/213886930-fc12a4c2-6018-4081-bb1a-b55cc412accf.png)

Rivendell version 4.0 rc1

Do i need to compile from github?

**Comment by ElvishArtisan** [comment]
Mostly, it's a matter of FLAC (along with the various Ogg encodings) not having a standard metadata schema. Hence, people tend to make them up on the fly, which results in a bunch of _ad hoc_ and incompatible schemas. Rivendell doesn't even attempt to recognize any of them.
