### ISSUE TITLE
RDLogEdit / Voicetracker crash when clicking on the  end of log "line"

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#867]
As described above. See the mouse cursor.. With left click, happens when not exactly  hit the line, rdlogedit and the VT crashes...

OS Debian 11, v4.0.0rc1int0

![image](https://user-images.githubusercontent.com/47517341/215277334-694566c6-211c-4796-9a76-be33a7600a87.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in d380a62. Please test!
