### ISSUE TITLE
V4.0.0Beta3int3 / Bug when edit an event in RDlogmanager and save as

### ISSUE THREAD

**Issue by jmpalmito** [ElvishArtisan/rivendell#869]
Hi,
ubuntu 22.04 V4.0.0Beta3int3
In Rdlogmanager, Edit an event that already exists 
Drag& drop a CART in pre-import area
"Save As"  with a new name
The name of the windows change to the new name : are we editing the old or the newly created event at this moment ? confusing...
When you push "Ok" to close the editing event  and Open the new Event Created : the Pre-import CART area is empty
When you push "cancel" to avoid modifying the previous cart, the pre-import CART is present in the previous event
Not sure to be extremely clear
Hope you can reproduce it
JM

**Comment by ElvishArtisan** [comment]
> "Save As" with a new name
> The name of the windows change to the new name : are we editing the old or the newly created event at this moment ? confusing...

The new one, as indicated by the changed event name on the titlebar. Similar to what happens in most (all?) office automation type applications.

**Comment by ElvishArtisan** [comment]
Fixed in 4369249. Please test!
