### ISSUE TITLE
rdairplay - Log entries should be re-playable

### ISSUE THREAD

**Issue by tcbeaton** [ElvishArtisan/rivendell#87]
When using Rivendell in live mode, there are times such as EAS breaks, when it would be advantageous to be able to re-play or restart a log item which has already begun. For example, if an EAS alert breaks in at the beginning of a song, or if the current log item is stopped, the operator/jock should be able to reselect the item and play it again.

**Comment by ElvishArtisan** [comment]
On Nov 12, 2015, at 11:45 24, tcbeaton <notifications@github.com> wrote:

> When using Rivendell in live mode, there are times such as EAS breaks, when it would be advantageous to be able to re-play or restart a log item which has already begun. For example, if an EAS alert breaks in at the beginning of a song, or if the current log item is stopped, the operator/jock should be able to reselect the item and play it again.

It is already possible to ‘pause’ an event and then resume it, while also (optionally) recueing it to a different resume point.  To enable this feature, go into RDAdmin->ManageHosts->[hostname]->RDAirPlay and check the ‘Enable Paused Events’ box in the ‘Miscellaneous Settings’ section.

Cheers!
 

|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by saschaludwig** [comment]
It's also possible to "COPY" the played event from the log into the first position.
There is a slight problem with 'pause':
When a cart is played on Main Log Output 1 and was paused and then unpaused, it then is beeing played on Main Log Output 2 and vice versa every time you unpause it.
That's really annoying if you just adjusted the volume of the corresponding channel.

Would it be possible to tie them to the channel the cart had been started on?
