### ISSUE TITLE
Bitrate in RDLogedit settings

### ISSUE THREAD

**Issue by olsson82** [ElvishArtisan/rivendell#870]
It's not possible to change bitrate settings to 192 kpbs in RDLogedit settings.
Each time you come back it's set to 128 kbps.

Tested on Debian 11 (and 12)  from source.

![Skärmbild från 2023-02-18 06-12-17](https://user-images.githubusercontent.com/122672087/219842821-9253cc13-04ff-4abd-acb2-650f8c8e10a7.png)

**Comment by ltyndale** [comment]
I can confirm that this happens with the latest V4 (QT5 branch) source code, compiled on Ubuntu 18.04.

**Comment by ElvishArtisan** [comment]
Confirmed here on qt5.

**Comment by ElvishArtisan** [comment]
Fixed in 6570921. Please test!

**Comment by olsson82** [comment]
> 

I can confirm that it's working now. Compiled from qt5 source today.
