### ISSUE TITLE
Rivendell 4.0.0 rc2 -- Cannot access MySQL from remote RD nodes

### ISSUE THREAD

**Issue by BeDazzleMe** [ElvishArtisan/rivendell#872]
I've installed RD 4.0.0 rc2 on Oracle Linux 8 today.
DB on it's own VM, installation went fine, rebooted and needed to add bind-address=0.0.0.0 for mariadb to listen for remote SQL connections, then was able to restore a RD 3.6.6 DB all OK.
On DB machine I can run RD apps and everything looks normal.

From another node, also on Oracle Linux 8, installation went fine no issues, however on reboot it cannot talk to the DB server via MySQL.

I can telnet there fine. /etc/rd.conf is fine. Everything I start rivendell services on the remote node it complains with the following:

Mar  1 18:54:05 au-gc-rd4-edit-01 systemd[1]: Stopped Rivendell Radio Automation System.
Mar  1 18:54:05 au-gc-rd4-edit-01 systemd[1]: Started Rivendell Radio Automation System.
Mar  1 18:54:05 au-gc-rd4-edit-01 systemd[1]: rivendell.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar  1 18:54:05 au-gc-rd4-edit-01 systemd[1]: rivendell.service: Failed with result 'exit-code'.
Mar  1 18:54:07 au-gc-rd4-edit-01 systemd[1]: rivendell.service: Service RestartSec=2s expired, scheduling restart.
Mar  1 18:54:07 au-gc-rd4-edit-01 systemd[1]: rivendell.service: Scheduled restart job, restart counter is at 68.
Mar  1 18:54:07 au-gc-rd4-edit-01 systemd[1]: Stopped Rivendell Radio Automation System.

This message repeats until I stop rivendell services.

I can access MySQL from MySQL Workbench fine. I've checked perms on rduser - all fine. Reset password, allowed access from %.

Other than this issue, the installation and config went suprisingly well and I am looking forward to testing.

Darren.

**Comment by ElvishArtisan** [comment]
First thing I'd check is the DB account credentials in the ```[mySQL]``` section of /etc/rd.conf'. The installer was recently changed to generate a random password instead of the old (and insecure) 'readme'. You may need to update the value on the client system to match the one used by the installer (just look in the '/etc/rd.conf' file on that system).

**Comment by BeDazzleMe** [comment]
> First thing I'd check is the DB account credentials in the `[mySQL]` section of /etc/rd.conf'. The installer was recently changed to generate a random password instead of the old (and insecure) 'readme'. You may need to update the value on the client system to match the one used by the installer (just look in the '/etc/rd.conf' file on that system).

Yes that is the first thing I checked as I noticed on the ubuntu install it sometimes does not set the credentials in rd.conf.

[mySQL]
; The connection parameters for the MySQL server.
;
Hostname=172.25.5.160
Loginname=rduser
Password=letmein
Database=Rivendell
