### ISSUE TITLE
PyPAD not send anything to Shoutcast Server

### ISSUE THREAD

**Issue by PeWe79** [ElvishArtisan/rivendell#873]
HI, I'm running with Rivendell v3.6.7. PyPAD not working / not send anything to streaming server Shourcast. But PyPAD status was Ok (green light) and no error log there. Try to restart Rivendell service but help.

**Comment by ElvishArtisan** [comment]
Please let us know:

1) The version and host environment of Shoutcast in use --e.g. "v1.9.8 on Windows 10.
2) You PyPAD configuration (with credentials suitable redacted).
