### ISSUE TITLE
rdviarplayd fails to start missing Spanish translation file

### ISSUE THREAD

**Issue by dzkahn** [ElvishArtisan/rivendell#875]
I am running rivendell v4.0.0rc2, I didn't have this problem on rc1. On startup rdviarplayd fails to start. When trying from the terminal I get the following error. 
![rdvairplayd](https://user-images.githubusercontent.com/62032501/223218914-cd1ae065-fdc1-4f0a-aaa0-d00c007d612a.png)

**Comment by ElvishArtisan** [comment]
Confirmed here.
