### ISSUE TITLE
System loses Rivendell logged in user after modifying rdcatch in rdadmin

### ISSUE THREAD

**Issue by ltyndale** [ElvishArtisan/rivendell#877]
I am not sure if this is just my setup, but I've now seen it on Ubuntu and a Raspberry PI, compiled from source.

Version: The QT5 / Rivendell 4 release Candidate

After making a change in rdadmin --> Manage Hosts --> Rdcatch, then launching any other Rivendell module (rdcatch, rdlibrary, rdairplay, anything) there is no longer a logged in user, on the title bar the Rivendell Logged In User shows up as blank, with no access to anything.  The first time I ran into this I launched rdlibrary and it showed me an empty library.  Initially I thought it had killed my database, but then I discovered it was logging out the logged in user and leaving no user logged in.

Trying to log the user back in with rdlogin (or trying to log any other Rivendell user in) does not work either.  The only way to recover from this is to restart the Rivendell services.

This only seems to happen when going into rdadmin --> Manage Hosts --> rdcatch.  Every other combination I've tried editing things in rdadmin does not result in this behaviour.  Also this only appears in the V4, I checked a V3.6.7 install I have and it does not exhibit this behaviour.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in a6b4105. Please test!

**Comment by ltyndale** [comment]
Issue appears to be fixed.
