### ISSUE TITLE
[Qt5 branch] RDcatch : can't délete items 

### ISSUE THREAD

**Issue by jmpalmito** [ElvishArtisan/rivendell#879]
Hi, 
tested on  ubuntu xfce 22.04 Rivendell V4.0.0beta3int3
impossible to delete items in RDcatch. The only way to achieve this is to check 'make oneshot'.
++
JM

**Comment by ElvishArtisan** [comment]
Please update to v4.0.0rc2 and try again. If you used the online script for the initial install, you should be able to do that by running the following two command:

```sudo apt update```
```sudo apt upgrade```

and then reboot.
