### ISSUE TITLE
rdlibrary - Option to have cuts within a cart play sequentially vs. randomized and weighted

### ISSUE THREAD

**Issue by tcbeaton** [ElvishArtisan/rivendell#88]
If a cart consists of five cuts, instead of having them play in a randomized order, based on day parts, we need the option to have them play in order. If possible, the ability for the carts to be day parted would still be useful to remove some carts from the sequential rotation based on time.

**Comment by ElvishArtisan** [comment]
Feature implemented in v2.12.0.
