### ISSUE TITLE
Rivendell 4 RDLogManager Horizontal Scrollbar "Jump"

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#884]
## Summary ##

In all recent versions of Rivendell 4.0.0, some (_not all_) horizontal window scrollbars behave unexpectedly when one clicks inside the window. This doesn't seem like a show-stopper, but it confuses users.

For example, I noticed that between RC releases (not sure exactly which), this effect was fixed for the full-log panel in RDAirPlay. It used to jump horizontally, but now does not. In fact, while filing this report, I can't see this effect in any other Rivendell app that shows a horizontal scrollbar... Maybe RDLogManager Edit Clocks is the last one...

## Steps to reproduce ##

Example in this [Screencast](https://github.com/ElvishArtisan/rivendell/assets/727293/c66883e7-fc36-43b7-8167-21b106a48d2e)

(In words):
* launch RDLogManager
* click `Edit Clocks`
* choose a clock to edit
* click on any line in the event list and watch the horizontal scrollbar jump to the right while the window pane jumps to the left

This seems like an artifact of moving to QT5 and I have no idea how to start looking deeper at the problem.

**Comment by ElvishArtisan** [comment]
> This seems like an artifact of moving to QT5 and I have no idea how to start looking deeper at the problem.

That's been my conclusion as well. It's bugged me for a long time, but I've not found any way to address it either. The behavior appears to be 'baked in' to Qt5.

**Comment by dklann** [comment]
Thanks for your comment Fred. I have no doubt you've dug deeply into this. I wonder if it's similar to "column sorting" (something that used to be built in to QT3, and with QT5 one must provide one's own sort method to enable sortable columns). Maybe there's something in [this](https://doc.qt.io/qt-5/qabstractscrollarea.html#horizontalScrollBarPolicy-prop) that's related?

**Comment by ElvishArtisan** [comment]
Ok, I see what is going on here. When the user selects a cell in a model view (by clicking on it), the Qt code automatically attempts to scroll to the position where as much as the cell's content as possible becomes visible. That makes sense where each cell can be individually selected (```QAbstractItemView::SelectionBehavior=SelectItems```), but not where a click selects an entire row (```QAbstractItemView::SelectionBehavior=SelectRows```), where no horizontal auto-scrolling should occur at all; the visual intent being to operate on the entire row without regard to the column boundaries.

However, while this really is a Qt bug, it's prevelance in certain places also strongly implies that we're not providing enough horizontal real estate in those places to allow the data to be displayed optimally.

**Comment by dklann** [comment]
Ah! I see what you mean. Good call! Clicking in a row where the column is fully visible does **not** cause the horizontal jump. Seems like just a "documentation issue" to me. :)

With wider displays readily available, and the changes to RDAirPlay (window resizing), might it make sense to modify the Edit Clock window in RDLogManager making it slightly larger, or resizable?

Thanks!

**Comment by dklann** [comment]
b548473 changes look good here! Thanks!

**Comment by dklann** [comment]
Not sure whether this is related to this issue...

Running commit cabbfe1a, I see that when editing a clock, the "pie" does not appear in the right-hand panel of the Edit Clock window until one clicks on an event line.

I didn't notice this (one way or the other) when testing commit b548473.

![image](https://github.com/ElvishArtisan/rivendell/assets/727293/f0093007-cab1-45e6-a98e-e91481c27c9e)

**Comment by dklann** [comment]
I'll keep this thread going here instead of starting a new issue...

Commit cabbfe1a introduces a resizable Edit Event window. In that window, the right-hand edge of the contents is cut off. This is on an up-to-date Linux Mint 21.1 running in a virtual machine. Resizing the window so that it is wider does not reveal the contents at the right-hand edge.

![image](https://github.com/ElvishArtisan/rivendell/assets/727293/aa4112d0-521b-4372-b578-8cf7b0c3e98f)

**Comment by ElvishArtisan** [comment]
> Running commit https://github.com/ElvishArtisan/rivendell/commit/cabbfe1a1eaa9149d440316958d3f0227f4ec617, I see that when editing a clock, the "pie" does not appear in the right-hand panel of the Edit Clock window until one clicks on an event line.

Just a difference in behavior. For consistency sake, we should probably should put the blank circle back for when no event is selected.

**Comment by ElvishArtisan** [comment]
> Commit https://github.com/ElvishArtisan/rivendell/commit/cabbfe1a1eaa9149d440316958d3f0227f4ec617 introduces a resizable Edit Event window. In that window, the right-hand edge of the contents is cut off. This is on an up-to-date Linux Mint 21.1 running in a virtual machine. Resizing the window so that it is wider does not reveal the contents at the right-hand edge.

Thanks for the feedback. That window is still very much a WIP.

**Comment by dklann** [comment]
> > Running commit [cabbfe1](https://github.com/ElvishArtisan/rivendell/commit/cabbfe1a1eaa9149d440316958d3f0227f4ec617), I see that when editing a clock, the "pie" does not appear in the right-hand panel of the Edit Clock window until one clicks on an event line.
> 
> Just a difference in behavior. For consistency sake, we should probably should put the blank circle back for when no event is selected.

Understood. I concur that showing the pie circle would reduce existing users' confusion...
