### ISSUE TITLE
4.0 installed on Ubuntu 22.04.2 LTS desktop can't import mp3

### ISSUE THREAD

**Issue by lotussutol** [ElvishArtisan/rivendell#886]
4.0 installed on Ubuntu 22.04.2 LTS desktop can't import mp3. I have tried the bulk import and single import. Both fail.
Also, when I import .wav files no meta data is brought in.

**Comment by ElvishArtisan** [comment]
Please let us know...
1. The precise version of Rivendell in question (visible in the title bar of any main Rivendell window).
2. The provenance of the installation --e.g. was this installed using the [online installer](https://software.paravelsystems.com/howtos/ubuntu/jammy/)? If not, is this an installation from source, or were packages used?
3. The specific steps needed to duplicate the problem (pray be specific as to details).

**Comment by lotussutol** [comment]
Rivendell v4.0.0rc3

I followed the instructions on this page to the letter.
https://www.rivendellaudio.com/howtos/ubuntu/jammy/

Specific steps are I put MP3 in a folder. I navigated to that folder in terminal and did this
sudo rdimport --verbose --normalization-level=-10 --add-scheduler-code=ALL --autotrim-level=-30 --segue-level=-15 MUSIC *.mp3 2> errorlog.txt

Or, I can go into RDLibrary and click add and then import and pick an mp3 and it errors out.
I can get a wave or flac to import this way.

**Comment by ElvishArtisan** [comment]
Thanks.

Sounds like you're missing the MPEG decoder library. As a check, opena terminal and do ```dpkg --list | grep libmad```. You should get back something like:

ii  libmad0:amd64                              0.15.1b-10ubuntu1
                       amd64        MPEG audio decoder library
