### ISSUE TITLE
Build broken in Debian (Bullseye and Bookworm).

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#888]
Hi.

Today I've found that my automated build scripts are failing to build snapshots.
On Debian Bullseye, I found the building bails out complaining about rdvairplayd.cpp like this:

`rdvairplayd.cpp: In constructor ‘MainObject::MainObject(QObject*)’:
rdvairplayd.cpp:70:49: error: no matching function for call to ‘RDCoreApplication::RDCoreApplication(const char [12], const char [12], bool, const char [11], MainObject*)’
   70 |       "rdvairplayd",false,RDVAIRPLAYD_USAGE,this));
      | 
`

Cheers.

**Comment by ElvishArtisan** [comment]
Confirmed present under Linux Mint 21 as well.

**Comment by ElvishArtisan** [comment]
Fixed in 1cd8f5e2. Please test!
