### ISSUE TITLE
Rdairplay  will not adjust screen size //rdlogedit add vt bug

### ISSUE THREAD

**Issue by rogerdavis198** [ElvishArtisan/rivendell#891]
Rdairplay will not resize to * so I can not use it ?? rdlibrary works at this size with no problem
*Width=1356
*Height=665
currently I can not see half the buttons or load any logs ??
.....................
rdlogedit 
add vt, all 3 three blocks go grey in voice tracker and you have to click on on the last track down then back on Vt to get the waveforms back which is a pain when you are trying to vt shows .

thanks

**Comment by rogerdavis198** [comment]
rocky 8

**Comment by ElvishArtisan** [comment]
> Rdairplay will not resize to * so I can not use it ?? rdlibrary works at this size with no problem
> *Width=1356
> *Height=665
> currently I can not see half the buttons or load any logs ??

Your display is too small. The minimum required resolution for Rivendell v4.x is 1680x1050, as per the HARDWARE REQUIREMENTS section in the [INSTALL](https://github.com/ElvishArtisan/rivendell) file.

**Comment by ElvishArtisan** [comment]
> rdlogedit
> add vt, all 3 three blocks go grey in voice tracker and you have to click on on the last track down then back on Vt to get the waveforms back which is a pain when you are trying to vt shows .

Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in b78e402. Please test.
