### ISSUE TITLE
RDLogmanager - Clock pie is white when first opening

### ISSUE THREAD

**Issue by jburtner** [ElvishArtisan/rivendell#894]
Just wanted to leave a note that in RD 4.0.2 the clock pie is all white when fist opening a clock - until an event item is selected. Then it shows all of the pie slices accurately...

Thx,
jb

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 2f0b8fd. Please test!

**Comment by jburtner** [comment]
Thank you Fred! I'm not set up to build yet so will test next release.
