### ISSUE TITLE
Bug: Problem with umlauts

### ISSUE THREAD

**Issue by prometoys** [ElvishArtisan/rivendell#9]
Hi,

we can use umlauts in the Carts and search in rdlibrary for carts with an umlaut (e.g. term "fünf" finds the artist 'Fünf Sterne Deluxe'). But we can't use search terms with umlauts in the search fields rdlogedit and rdlogmanager. 

(Rivendell 2.8, Debian Wheezy, Tryphon-debs)

**Comment by ElvishArtisan** [comment]
Fixed in v3.x.
