### ISSUE TITLE
voice tracker - Remove extra information after song title

### ISSUE THREAD

**Issue by tcbeaton** [ElvishArtisan/rivendell#91]
We are experiencing an intermittent display of additional information following the song title in voice tracker. The extra info is not always displayed, and so far I have not been able to reproduce steps to either show or hide the info reliably. See attached screen capture.

![image](https://cloud.githubusercontent.com/assets/8934460/11125047/cb469814-8935-11e5-8a89-5139deae54b8.png)

**Comment by ElvishArtisan** [comment]
Resolved in v2.16.0.
