### ISSUE TITLE
RDAirplay crash issue (repeatable - non-emergency)

### ISSUE THREAD

**Issue by KRVS-Engineering** [ElvishArtisan/rivendell#914]
One of my students discovered that if you are recording a voice track in RDAirplay and you accidently hit the unload log button, it will crash RDAirplay.

v4.1.0 regular build.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 5d3931f. Please test!

**Comment by KRVS-Engineering** [comment]
Similar if not same issue.  I tried twice reloading the form page each time:

[a208bf9e] /index.php/Special:RequestAccount MWException from line 291 of /var/www/wiki.rivendellaudio.org/includes/mail/UserMailer.php: PEAR mail package is not installed
Backtrace:
#0 /var/www/wiki.rivendellaudio.org/includes/User.php(4279): UserMailer::send(MailAddress, MailAddress, string, string, array)
#1 /var/www/wiki.rivendellaudio.org/extensions/ConfirmAccount/backend/ConfirmAccount.class.php(121): User->sendMail(string, string)
#2 /var/www/wiki.rivendellaudio.org/extensions/ConfirmAccount/business/AccountRequestSubmission.php(245): ConfirmAccount::sendConfirmationMail(User, string, string, string)
#3 /var/www/wiki.rivendellaudio.org/extensions/ConfirmAccount/frontend/specialpages/actions/RequestAccount_body.php(315): AccountRequestSubmission->submit(RequestContext)
#4 /var/www/wiki.rivendellaudio.org/extensions/ConfirmAccount/frontend/specialpages/actions/RequestAccount_body.php(80): RequestAccountPage->doSubmit()
#5 /var/www/wiki.rivendellaudio.org/includes/specialpage/SpecialPage.php(384): RequestAccountPage->execute(NULL)
#6 /var/www/wiki.rivendellaudio.org/includes/specialpage/SpecialPageFactory.php(553): SpecialPage->run(NULL)
#7 /var/www/wiki.rivendellaudio.org/includes/MediaWiki.php(281): SpecialPageFactory::executePath(Title, RequestContext)
#8 /var/www/wiki.rivendellaudio.org/includes/MediaWiki.php(714): MediaWiki->performRequest()
#9 /var/www/wiki.rivendellaudio.org/includes/MediaWiki.php(508): MediaWiki->main()
#10 /var/www/wiki.rivendellaudio.org/index.php(41): MediaWiki->run()
#11 {main}

**Comment by ElvishArtisan** [comment]
'Kay, so this looks like a wiki problem?
