### ISSUE TITLE
RDlogManager issue

### ISSUE THREAD

**Issue by Zutterart** [ElvishArtisan/rivendell#915]
Since v4.1.0 i notice that the RDlogmanager - generator does not accept newly created scheduler codes. 
Everything looks right: in the Event the service is added (enabled) to the list.

**Comment by ElvishArtisan** [comment]
Not clear exactly what 'accept' means here. Could you please provide a detailed step-by-step procedure for goosing the issue?

**Comment by Zutterart** [comment]
![Uploading Event.png…]()
1. i made a new 'Scheduler Code', via RDAdmin - Scheduler Codes (example: 'Soft rock')
2. i made a new 'Log Event', via RDLogManager - Edit Events, based on the new scheduler code
3. i added the new log event in a log clock (in 'scheduler rules', i set the max in a row on 1, and in the 'services list' is the service enabled)
4. after generating a new log, via RDLogManager, i do not see a song from the new scheduler code.

**Comment by ElvishArtisan** [comment]
Thanks. That goosed it.

The actual cause is the space in the schedule code. As a short-term work-around, just don't use spaces in schedule codes and you should be good.

**Comment by ElvishArtisan** [comment]
Fixed in ef7084a0 and 9691126. Please test!

**Comment by Zutterart** [comment]
OK... closing this :-)

Cheers!
