### ISSUE TITLE
BUG RDAirPlay Voice Tracker permissions

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#918]
v4.1.0: When logged in with a user with the 'Voicetrack Logs' permission **removed** under Production Rights, the Voice Tracker is correctly greyed out within RDLogEdit. However, the Voice Tracker within RDAirPlay is fully functional for the logged-in user. Please could the correct permissions be applied in RDAirPlay so that we can restrict the use of the Voice Tracker?

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 906bd14. Please test!

**Comment by vizubeat** [comment]
Thanks @ElvishArtisan. I would love to test, but I'm afraid I don't know how, as I've not built from source before, only used 
the Paravel packages. But I've read the changes in the commit and understand what's been changed, if that counts for anything! Can't wait for a new production release :-)

**Comment by vizubeat** [comment]
Tested, works perfectly in 4.1.2 🥳 -- thank you!
