### ISSUE TITLE
Cannot sucessfully compile release 4.1.1

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#924]
Compilation of release 4.1.1 build fails at:

make[1]: Entering directory '/home/rd/dev/rivendell-4.1.1/cae'
  CXX      driver_hpi.o
driver_hpi.cpp: In member function ‘virtual int DriverHpi::inputPortQuantity(int) const’:
driver_hpi.cpp:96:10: error: ‘d_sound_card’ was not declared in this scope
   96 |   return d_sound_card->getCardInputPorts(card);
      |          ^~~~~~~~~~~~
driver_hpi.cpp: In member function ‘virtual int DriverHpi::outputPortQuantity(int) const’:
driver_hpi.cpp:102:10: error: ‘d_sound_card’ was not declared in this scope
  102 |   return d_sound_card->getCardOutputPorts(card);
      |          ^~~~~~~~~~~~
make[1]: *** [Makefile:541: driver_hpi.o] Error 1
make[1]: Leaving directory '/home/rd/dev/rivendell-4.1.1/cae'
make: *** [Makefile:552: all-recursive] Error 1

This  is seen when compiling in both the current CentOS7 and Ubuntu Jammy environments.

**Comment by ElvishArtisan** [comment]
What version of hpklinux are you using?

**Comment by fpeyraud** [comment]
Confirmed here.
I had to enclose the line in `#ifdef HPI ... #endif` like the other functions

**Comment by WMTH** [comment]
Version 4.20.39-1

**Comment by ElvishArtisan** [comment]
@fpeyraud Ah, I see. You're building without HPI support. Yup, that's a bug!

**Comment by ElvishArtisan** [comment]
@WMTH But I don't see how you could be goosing this if you're building with HPI support. What does your Rivendell Configuration Summary say after running './configure'? You should have a line in the 'Configured Audio Drivers' section like: 'AudioScience HPI ... Yes'.

**Comment by WMTH** [comment]
It reports 'AudioScience HPI ... No'.  We don’t have any AudioScience cards installed.  Up until this release, this has not posed a problem.  I did try adding ‘—disable-hpi’ in the configuration options but that had no impact.

**Comment by ElvishArtisan** [comment]
@WMTH Sounds like you're missing the 'hpklinux-dev' package. Adding that and re-running 'configure' should allow the build to proceed. Or, you could make the changes suggested by @fpeyraud. Or, just wait. I plan to cut a release with this fixed later today.

**Comment by WMTH** [comment]
I am performing a test build now with the addition of the hpklinux-dev package added.

**Comment by ElvishArtisan** [comment]
Fixed in e6f6aaa. Please test!

**Comment by ElvishArtisan** [comment]
@WMTH 
> I am performing a test build now with the addition of the hpklinux-dev package added.

Thanks. If you could also test the fix I just committed (with the hpklinux-dev package removed), that'd be great. Then I can push a new release.

**Comment by WMTH** [comment]
Both builds in progress now.

**Comment by WMTH** [comment]
Both the build with the  <https://github.com/ElvishArtisan/rivendell/commit/e6f6aaade008f4fdb52ecae20a07be632fd52702> e6f6aaa commit without the hpklinux-dev package and the original 4.1.1 build with the hpklinux-dev package compiled successfully.

**Comment by ElvishArtisan** [comment]
Cool. Thank you!
