### ISSUE TITLE
Log Auto Refresh Fails with Appended Log

### ISSUE THREAD

**Issue by glenndrives** [ElvishArtisan/rivendell#926]
This is for V3.6.6, but wait, I'll have one for 4.1.2 too.

When appending a log to one currently running in RDAirPlay the Auto Refresh does not work for the appended log. It does, however, still work for the log that was already loaded.

The appended log is loaded with an RML command in a shell script:

    #!/bin/bash
    
    NOWDATE=$(date` +%y%m%d)
    rmlsend AL\ 1\ WHRV-MD$NOWDATE\!
    
    exit 0

**Comment by ElvishArtisan** [comment]
Duplicate. See #927.
