### ISSUE TITLE
Log Auto Refresh Fails with Appended Log v4.1.2

### ISSUE THREAD

**Issue by glenndrives** [ElvishArtisan/rivendell#927]
This is for v4.1.2

When appending a log to one currently running in RDAirPlay the Auto Refresh does not work for the appended log. It does, however, still work for the log that was already loaded.

This was tested on v4.1.2 after finding the issue on 3.6.6.

Testing was done with two logs and using the following at the command line: rmlsend AL\ 1\ alt-md\!

**Comment by ElvishArtisan** [comment]
The content of the appended log, once it has been appended, has been effectively copied from its original source to the destination log. It's just the same as if the content had been copy-pasted from the original log into the destination one. Hence, changes to the original log after the append operation will not show up in the destination log. This is the intended behavior.

If changes need to be made to the appended log after the append operation (voicetracks, etc), they will have to be done on the destination log.

**Comment by glenndrives** [comment]
Will work on work flow.
Cheers!
