### ISSUE TITLE
AL RML only adds the first item in the appended log v4.1.2

### ISSUE THREAD

**Issue by glenndrives** [ElvishArtisan/rivendell#928]
When appending a log to one currently in RDAirPlay the AL RML command only appends the first item in the appended log.

Before appending alt-md log:
![image](https://github.com/ElvishArtisan/rivendell/assets/6921104/1abd02a5-e2cf-423a-b0b9-b38b4c842b7d)

After sending the rmlsend AL\ 1\ alt-md\! command:
![image](https://github.com/ElvishArtisan/rivendell/assets/6921104/de2f2c24-4800-4bce-9480-696903dde6f2)

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 83efb5e. Please test!
