### ISSUE TITLE
4.1.2: RDAirPlay window is slightly too wide

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#930]
We have a 1280x1024 touch screen which is still perfect for our needs, but unfortunately the minimum width of RDAirPlay is too wide to comfortably fit on this 4:3 screen. 

See below:

![rd](https://github.com/ElvishArtisan/rivendell/assets/93675293/b5d7dfc6-e810-49f6-ad9c-89104546265e)

As funny as it is to see `Rivendel Automatio`, please could the minimum width of the window be reduced ever to slightly to ensure compatibility with non-widescreen displays? This also means that we lose the right hand scrollbar of the Main Log view, when left-aligning the window. If we right-align the window we see the scrollbar again, but lose part of the Mode and Cart Start buttons on the Main Log.

Additionally, not sure if this is related, but there appears to be a strange ~1px rendering or positioning problem on the left hand side of the RDAirPlay window, which isn't present on the right hand side (screenshot above):

![rd2](https://github.com/ElvishArtisan/rivendell/assets/93675293/5c3295f7-f8b7-4fd5-b9fb-37c7a5dd29e9)

Appreciate these are small details, but a fix would really help useability!

Thank you.

**Comment by ElvishArtisan** [comment]
> As funny as it is to see Rivendel Automatio, please could the minimum width of the window be reduced ever to slightly to ensure compatibility with non-widescreen displays? This also means that we lose the right hand scrollbar of the Main Log view, when left-aligning the window. If we right-align the window we see the scrollbar again, but lose part of the Mode and Cart Start buttons on the Main Log.

This sounds reasonable, especially seeing as 1280x1024 is a VESA standard resolution.

> Additionally, not sure if this is related, but there appears to be a strange ~1px rendering or positioning problem on the left hand side of the RDAirPlay window, which isn't present on the right hand side (screenshot above):

Interesting. I'm not seeing this on my setup here (CentOS 7 XFCE). I'm wondering if this could be a window manager artifact? What is your desktop environment? Does this change if you reposition or resize the window?

**Comment by ElvishArtisan** [comment]
> We have a 1280x1024 touch screen which is still perfect for our needs, but unfortunately the minimum width of RDAirPlay is too wide to comfortably fit on this 4:3 screen.
> [..]
>  please could the minimum width of the window be reduced ever to slightly to ensure compatibility with non-widescreen displays?

Done, in 6071fd7. Please test!

**Comment by vizubeat** [comment]
Thanks @ElvishArtisan! To the point about the strange ~1px artefact, this was seen on a standard fresh Ubuntu Jammy installation with Rivendell 4.1.2 following the Paravel appliance guide - I believe the default DE is GNOME?

**Comment by vizubeat** [comment]
Thanks @ElvishArtisan this looks great on the Sound Panel and Main Log windows.

But there is now an issue of 'overflow' on the Voice Tracker - perhaps the meters could be made smaller to fit in the tracks and remaining time labels at 1280x1024? See below.

![rdvt](https://github.com/ElvishArtisan/rivendell/assets/93675293/4dc06669-3456-4814-982a-fdc5b2c6e838)

**Comment by ElvishArtisan** [comment]
Fixed in b3b7676. Please test!
