### ISSUE TITLE
Typo in cae/Makefile.am

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#935]
Git commit f06f3d14 appears to be missing the header file _play\_session.h_. On further investigation, it turns out that it's simply a "stray" underscore in cae/Makefile.am.

I'll submit a pull request if you'd like, but it seems like a pretty easy fix: replace _play\_session.h_ with _playsession.h_.

**Comment by ElvishArtisan** [comment]
Sure 'nuff. Fixed in 7e45309. Please test!

**Comment by dklann** [comment]
Confirming that the build works here as expected in commit 7e45309.

**Comment by ElvishArtisan** [comment]
Thanks!
