### ISSUE TITLE
RDLibrary 4.1.2 SIGSEGV on Ripping CD

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#937]
- **What**: Segmentation violation in rdlibrary when ripping a CD. Rivendell version 4.1.2 installed on Linux Mint 21.1 (Vera)
- **Steps to Reproduce**
  - launch RDLibrary
  - insert CD into on-board CD drive
  - touch _Rip CD_ button
  - select cuts to rip
  - touch _Rip Disc_ button
  - crash

See the stack trace as reported by coredumpctl(1) [here](https://pastebin.com/WJzuRf7Q).

**Comment by ElvishArtisan** [comment]
Unable to reproduce here. Unfortunately, not terribly surprising given how many operational variables are involved in CD ripping (CDDB vs. MusicBrainz vs. CDText vs. ISRC detection). I greatly appreciate the stack trace, but without source code line numbers it's not terribly useful. Any chance that you could install the debuginfo package (which provides line number info for the debugger) and then re-run this? Also, a screenshot of the 'Rip Disk' dialog before touching the 'Rip Disk' button would be helpful as it would allow us to see what metadata sources (MusicBrainz, CDText, etc) were in play.

**Comment by dklann** [comment]
Unfortunately, this is on a machine that is remote to me and I do not have access to the CD drive, nor regular access to the people at the station.

I'm closing this issue due to lack of information.
