### ISSUE TITLE
BUG 4.1.3 Press of space bar to start main log doesn't work after changing operating mode

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#939]
Also noted in other v4.x versions, but still there in v4.1.3:

After clicking the Operating Mode button to change mode, the focus of the space bar seems to stay attached to that button - i.e. the space bar can be used to change Operating Mode after it has been clicked, but not start the Main Log machine. This is shown with a dotted line around the Operating Mode button after it has been clicked.

User has to click into the Main Log area to 'release' focus from the Operating Mode button to send spacebar input back to the 'start main log' function.

This is problematic for users that are using multiple operating modes whilst also wanting to start the main log from the space bar.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in f76691b. Please test!
