### ISSUE TITLE
Rdlibrary 4.1.3 does not sort cart reports

### ISSUE THREAD

**Issue by paulk-2** [ElvishArtisan/rivendell#945]
Rdlibrary reports are no longer sorted.  GUI shows sorted by cart, but report shows unsorted (they were sorted in 3.x).

might be related to issue 940, but listed separately since that one referred to cuts and not carts.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 43761e9. Please test!
