### ISSUE TITLE
RDAirPlay doesn't show new groups added with RDAdmin until you restart it (bug?)

### ISSUE THREAD

**Issue by lbracci** [ElvishArtisan/rivendell#948]
Hi,

In previuos versions of Rivendell, if you have RDAirPlay opened and you add a new group in RDAdmin, when you click "ADD" in RDAirPlay to add a new cart to the log, the new group is visible in the list of groups. But in Rivendell 4.1.3, RDAirPlay doesn't show the new group, and the carts in that group can't be added; you must close and reopen RDAirPlay to see the new group.

Steps to reproduce:

- Open RDAirPlay, press ADD. The window to select a cart will appear.
- Close the "Select Cart" window, but leave RDAirPlay opened.
- Open RDAdmin. Create a new group, visible to all users.
- Return to RDAirPlay. Press ADD again.
- Check the list of groups in the Select Cart window: The new group will not be shown. 

Thank you.

**Comment by ElvishArtisan** [comment]
Not a bug, but the way it has been (for quite awhile at least).
