### ISSUE TITLE
CAE non-existent sessions

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#949]
Running Rivendell 4.1.3int1 (commit 15f550b9) on Linux Mint 21.3. This is a virtual machine on which previous versions of Rivendell 4 worked as expected.

When attempting to play a log in RDAirPlay, the VU meters do not move, no sound is produced, and the countdown and count-up timers do not move. But Cuts transition from one to the next as if they are playing.

The system journal contains the following messages:

> Mar 14 16:12:10 u2204ram rdairplay[4543]: loaded log '240314' in Main Log
> Mar 14 16:12:10 u2204ram ripcd[4494]: received rml: "MN 1 0!" from ::ffff:127.0.0.1
> Mar 14 16:12:15 u2204ram caed[4493]: attempted to operate non-existent session, serial: 1
> Mar 14 16:12:15 u2204ram caed[4493]: attempted to unload non-existent session, serial: 1
> Mar 14 16:12:15 u2204ram caed[4493]: attempted to operate non-existent session, serial: 1
> Mar 14 16:12:15 u2204ram caed[4493]: attempted to operate non-existent session, serial: 1
> Mar 14 16:12:15 u2204ram caed[4493]: attempted to play non-existent session, serial:1
> Mar 14 16:12:15 u2204ram rdairplay[4543]: log engine: started audio cart: Line: 0  Cart: 60001  Cut: 1 Pos: 0  Serial: 1  Card: 1  Port: 0

I looked briefly at _cae/cae.cpp_ and _cae/playsession.cpp_, but I'm unable to discern what a "non-existent" session is.

Any pointers on what to look for in troubleshooting this?

Thanks!

**Comment by ElvishArtisan** [comment]
Two possible spots in the source code that this could have come from: line 692 or line 743 of 'cae/cae.cpp'. Both of those sections deal with manipulating the virtual mixer built into CAE.

**Comment by ElvishArtisan** [comment]
Combining this with #951.
