### ISSUE TITLE
support request: trouble resolving installation dependencies

### ISSUE THREAD

**Issue by ryanrain** [ElvishArtisan/rivendell#95]
good morning all!
here are the steps i've taken, hopefully this can be reproduced!
- i'm running ubuntu 15.04
- i download rivendell-2.11.0.tar.gz and untar it.
- i open the terminal, cd into the folder, and run ./configure
- it runs a bunch of checks which all seem fine, until...
```
checking how to hardcode library paths into programs... immediate
Fixing libtool for -rpath problems.
./configure: line 15384: libtool: No such file or directory
mv: cannot stat 'libtool-2': No such file or directory
chmod: cannot access 'libtool': No such file or directory
checking for X... no
checking for Qt... no
configure: error: *** Qt toolkit not found, unable to continue ***
```
i've tried downloading QT from qt.io, and Ubuntu UI Toolkit Gallery from the operating system's installer, neither of which have worked... any ideas? thanks in advance!
-ryan

**Comment by waynemerricks** [comment]
Hi,

Isn't libtool part of the build-essentials package? I'm almost certain its in the same bunch as automake and the like.  Either way, if you really need a source install then you'll need to jump through some QT3 shaped hoops.  I wrote this a long time ago for Debian 6 (2013) but it mostly still applies to recent Ubuntu.  Some of the package names might have changed though.

http://rivendell.tryphon.org/wiki/Debian_6_Install_Rivendell_2.1.1_from_Source

You will get stuck when it comes to QT3, you'll have to get old source for that and install that manually too.

So here is the easier way, add the Utopic repo to your apt sources.list:

http://debian.tryphon.eu

sudo apt-get update
sudo apt-get install rivendell-server
sudo apt-get install rivendell

You might have issues with mysql not installing before dpkg tries to use it.  In that case install mysql-server and rerun: dpkg-reconfigure rivendell rivendell-server.

It takes less than 10 minutes to install Riv if you use the repo.

**Comment by ryanrain** [comment]
thanks wayne! you guessed exactly right, i have absolutely no need to install from source, but jsut didn't find info to install from the repo on http://rivendellaudio.org/rivendell/download.shtml

i've followed your instructions. i already had mysql on my system (i make websites by day...) so no problems there.

the install process appears to have completed, but unfortunately, now upon opening any of the new applications (such as RDAdmin etc.) i get a message saying "Unable to start Rivendell System Daemons!". any thoughts on how to troubleshoot that one? thanks again!

**Comment by waynemerricks** [comment]
There is usually only 3 things that stop the daemons running.
- It can't connect to the database
- /var/run/rivendell doesn't exist so it can't create pid files
- your sound card is in use by pulse audio and causing weirdness

Try running caed from a terminal, you usually get much better error messages there.

**Comment by Pollito001** [comment]
configure: error: *** Qt toolkit not found, unable to continue *** on archlinux help.
