### ISSUE TITLE
RDLibrary No Longer Allows Partial Numeric Cart Search

### ISSUE THREAD

**Issue by WLGW-Ops** [ElvishArtisan/rivendell#952]
**System Config:**
Oracle Enterprise 8
Rivendell v4.1.3
DB Version 3.71

**Summary:**
As of v4.1.3, RDLibrary no longer allows search by partial cart number; search displays a given cart ONLY when the complete cart number is entered. Alpha text still works as expected.

**Examples:**
Search for partial cart number - no carts displayed
Search for exact cart number - cart displayed
Search for partial artist or title name - carts displayed

**Attempted Fixes:**
System reboot
Re-execute DB update and reboot

Screen shots attached for reference.

![Screenshot from 2024-03-21 09-04-42](https://github.com/ElvishArtisan/rivendell/assets/119166967/3806bd86-7d1b-414d-b7c3-910f84103bfb)
![Screenshot from 2024-03-21 09-05-27](https://github.com/ElvishArtisan/rivendell/assets/119166967/6fd0193f-bbf4-4b0d-a323-7f73762757a5)
![Screenshot from 2024-03-21 09-05-57](https://github.com/ElvishArtisan/rivendell/assets/119166967/7338276b-561d-4106-8658-1cf90f0145ce)
![Screenshot from 2024-03-21 09-06-29](https://github.com/ElvishArtisan/rivendell/assets/119166967/0bedb1c2-d80d-4b76-b226-9dc95c486692)

Best Regards,
Brian
WLGW Operations

**Comment by WLGW-Ops** [comment]
This issue still persists in v4.2.0

**Comment by WLGW-Ops** [comment]
This issue persists in v4.2.1

@ElvishArtisan - There weren't issues with cart # search prior to 4.1.3. Has there been a change whereby this is now expected behavior?

Best Regards,
Brian

**Comment by ElvishArtisan** [comment]
Yes, this is the expected exhavior. The changes were introduced in v4.1.3, and documented in Appendix I of the Operations Guide. See: https://opsguide.rivendellaudio.org/html/appendix.library_searches.html.

**Comment by WLGW-Ops** [comment]
Good to know, this changes our workflow a bit as staff was used to entering a partial cart number for quick display during live operation.
