### ISSUE TITLE
V4 RDLibrary crashs after deleting an  new added empty cut

### ISSUE THREAD

**Issue by jmpalmito** [ElvishArtisan/rivendell#953]
Hi all !
1. edit a CART with multiple CUTs
2. Delete one of this CUT, but not the last one
3. ADD a new CUT. It replaces the previous deleted one
4. Delete this new specific CUT
5. RDlibray crashs with this message: 
_ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 571
Aborted (core dumped)_

There is no problem when the last CUT of the range is deleted

Can you reproduce it ?
Regards
JM

**Comment by WLGW-Ops** [comment]
Reproducible on my end. I executed from a terminal and saw "invalid or failed DB connection" errors prior to the crash. The final message received was consistent with @jmpalmito's results. Screen shot attached.

**System Config:**
Oracle Enterprise 8
Rivendell v4.1.3
DB Version 3.71

![Screenshot from 2024-03-22 07-22-09](https://github.com/ElvishArtisan/rivendell/assets/119166967/5d5caf29-b73d-4472-bdc6-6518ff3dffe6)

Best Regards,
Brian 
WLGW Operations

**Comment by WLGW-Ops** [comment]
@jmpalmito - can you test issue #952?

**Comment by WLGW-Ops** [comment]
This issue still exists in v4.2.0

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 29a2317. Please test!
