### ISSUE TITLE
Version 4.2.0 Pypad behavior

### ISSUE THREAD

**Issue by ctecamp** [ElvishArtisan/rivendell#955]
Greetings we have several pypad scripts that run for each song.

Urlwrite
File write
UDP send 
TuneIn

Since updating to 4.2.0 on Ubuntu 
File write doesn't work at all from the get go and the others crash after a command in the log for the display label.

These is just what I've been able to ascertain so far.

**Comment by ctecamp** [comment]
Pypad scripts go red after a macro carts.
Error log for scripts are blank.

**Comment by ctecamp** [comment]
In my logs pypad scripts crash after macro cart with "LC color string!" RML.

**Comment by ctecamp** [comment]
Apparently macros as mentioned before putting a stop main log crashes it as well

**Comment by ctecamp** [comment]
Every single pypad script throws this error.
File "/use/lib/python3/dist-packages/rivendellaudio/pypad.py", line 961. in start jdata=json.loads(msg)

**Comment by ctecamp** [comment]
Filewrite also doesn't work in 4.1.3

**Comment by ElvishArtisan** [comment]
Should be fixed in v4.2.1. Please test!

**Comment by RudiOnTheAir** [comment]
Uhm, no.
I'm using filewrite for the mp3 encoder Butt. >> Version 4.2.1 Db 374
```
Traceback (most recent call last):
  File "/usr/lib/rivendell/pypad/pypad_filewrite.py", line 59, in <module>
    rcvr.start(sys.argv[1],int(sys.argv[2]))
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 963, in start
    jdata=json.loads(msg)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 50 column 2 (char 1396)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_rivendell_pypad_pypad_filewrite.py.151.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/rivendell/pypad/pypad_filewrite.py", line 59, in <module>
    rcvr.start(sys.argv[1],int(sys.argv[2]))
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 963, in start
    jdata=json.loads(msg)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 50 column 2 (char 1396)
```

**Comment by ElvishArtisan** [comment]
> Traceback (most recent call last):
  File "/usr/lib/rivendell/pypad/pypad_filewrite.py", line 59, in <module>
    rcvr.start(sys.argv[1],int(sys.argv[2]))
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 963, in start
    jdata=json.loads(msg)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 50 column 2 (char 1396)

Hmm. That's looking a lot like a corrupt string from the database.

I've just added some code in fe58694 that should assist in running this down. After applying that update, add ```KillPypadAfterJsonError=Yes``` to the ```[Debugging]``` section of your '/etc/rd.conf' file and restart the 'rivendell' service. The next time you hit one of these, you should get a useful error message in the 'Error Log' dialog for the respective PyPAD script.

**Comment by RudiOnTheAir** [comment]
Thank you for this opportunity. I have three systems in production, but all are from the repo and not self-compiled. Strange that it worked for a long time without any problems. I assume it would be time-consuming to build a test Debian package...?

**Comment by ElvishArtisan** [comment]
Debian is not one of my 'officially supported' distros, though I do know folks who run Rivendell on it.

**Comment by RudiOnTheAir** [comment]
Uupps. I mean Ubuntu/Mint LTS. Thats nearly the same...;)

rd@rd4-server:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.2
Release:	21.2
Codename:	victoria

**Comment by ElvishArtisan** [comment]
Ah. That's an easy one. Give me a bit...

**Comment by ElvishArtisan** [comment]
Packages available at: http://static.paravelsystems.com/rivendell/4.2.1int0-1/jammy/

**Comment by RudiOnTheAir** [comment]
That means. At TOH i switch to another system, make a snapshot from running system and install via dpkg -i rivendell* all packages?

**Comment by ElvishArtisan** [comment]
I'd install only the ones that are already there. Unless you're doing something 'unusual', that's probably the 'rivendell' and 'rivendell-opsguide' packages.

**Comment by RudiOnTheAir** [comment]
Yes, that are exactly my installed packages.
Installed them, added the line in rd.conf and system is up and running. No wait and see.

Thanks for ur support...

**Comment by ctecamp** [comment]
Greetings Fred,

Just FYI, after loading 4.2.1 some things are working others still crashing.

Have found that when some of the scripts crash they crash all of them. Ie
bring pypad down completely.

Running them one at a time here to try and see which are working without
issues and which ones are burning down the house.

Tim Camp
WZEW-FM

**Comment by ElvishArtisan** [comment]
@ctecamp: thank you for the update. If you could post backtraces of any crashes (from the Error Log in the PyPAD dialog), that would be very helpful.

**Comment by RudiOnTheAir** [comment]
Where is my pasted errorlog gone??? Here i paste it again..
```
pypad_filewrite.py[3186]: error parsing JSON: "{
    "padUpdate": {
        "dateTime": "2024-04-27T05:35:59+-2:00",
        "hostName": "rd4-server",
        "log": {
            "name": "Prod-0427"
        },
        "machine": 1,
        "mode": "Automatic",
        "next": {
            "agency": "",
            "album": "",
            "artist": "R. Kelly",
            "cartNumber": 901293,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-90SLOW",
            "isci": "",
            "isrc": "",
            "label": "",
            "length": 320222,
            "lineId": 144,
            "lineNumber": 145,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": null,
            "title": "I Believe I Can Fly",
            "userDefined": "",
            "year": null
        },
        "now": null,
        "onairFlag": false,
        "service": {
            "description": "Default Audio Service",
            "programCode": ""
        },
        "shortHostName": "rd4-server"
    }
}{
    "padUpdate": {
        "dateTime": "2024-04-27T05:35:59+-2:00",
        "hostName": "rd4-server",
        "log": {
            "name": "Prod-0427"
        },
        "machine": 1,
        "mode": "Automatic",
        "next": {
            "agency": "",
            "album": "1984",
            "artist": "Nik Kershaw",
            "cartNumber": 900182,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-80-MID",
            "isci": "",
            "isrc": "",
            "label": "NR",
            "length": 269500,
            "lineId": 145,
            "lineNumber": 146,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-27T05:41:19+-2:00",
            "title": "Wouldn`t It Be Good",
            "userDefined": "",
            "year": null
        },
        "now": {
            "agency": "",
            "album": "",
            "artist": "R. Kelly",
            "cartNumber": 901293,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-90SLOW",
            "isci": "",
            "isrc": "",
            "label": "",
            "length": 320222,
            "lineId": 144,
            "lineNumber": 145,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-27T05:35:59+-2:00",
            "title": "I Believe I Can Fly",
            "userDefined": "",
            "year": null
        },
        "onairFlag": false,
        "service": {
            "description": "Default Audio Service",
            "programCode": ""
        },
        "shortHostName": "rd4-server"
    }
}

"
```

**Comment by RudiOnTheAir** [comment]
..and the next one after restart:
```
pypad_filewrite.py[18544]: error parsing JSON: "{
    "padUpdate": {
        "dateTime": "2024-04-28T14:40:03+-2:00",
        "hostName": "rd4-server",
        "log": {
            "name": "Prod-0428"
        },
        "machine": 1,
        "mode": "Automatic",
        "next": {
            "agency": "",
            "album": "1983",
            "artist": "Eurythmics",
            "cartNumber": 900154,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-80-MID",
            "isci": "",
            "isrc": "",
            "label": "NR",
            "length": 219154,
            "lineId": 338,
            "lineNumber": 339,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-28T14:40:06+-2:00",
            "title": "Love Is A Stranger",
            "userDefined": "",
            "year": null
        },
        "now": {
            "agency": "",
            "album": "1984",
            "artist": "The Cars",
            "cartNumber": 900611,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-80SLOW",
            "isci": "",
            "isrc": "",
            "label": "NR",
            "length": 230779,
            "lineId": 335,
            "lineNumber": 336,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-28T14:36:16+-2:00",
            "title": "Drive",
            "userDefined": "",
            "year": null
        },
        "onairFlag": false,
        "service": {
            "description": "Default Audio Service",
            "programCode": ""
        },
        "shortHostName": "rd4-server"
    }
}{
    "padUpdate": {
        "dateTime": "2024-04-28T14:40:03+-2:00",
        "hostName": "rd4-server",
        "log": {
            "name": "Prod-0428"
        },
        "machine": 1,
        "mode": "Automatic",
        "next": {
            "agency": "",
            "album": "1983",
            "artist": "Eurythmics",
            "cartNumber": 900154,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-80-MID",
            "isci": "",
            "isrc": "",
            "label": "NR",
            "length": 219154,
            "lineId": 338,
            "lineNumber": 339,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-28T14:40:04+-2:00",
            "title": "Love Is A Stranger",
            "userDefined": "",
            "year": null
        },
        "now": {
            "agency": "",
            "album": "",
            "artist": "START_AD_BREAK",
            "cartNumber": 101,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "Werbung",
            "isci": "",
            "isrc": "",
            "label": "",
            "length": 1123,
            "lineId": 337,
            "lineNumber": 338,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-28T14:40:03+-2:00",
            "title": "START_AD_BREAK",
            "userDefined": "",
            "year": 2019
        },
        "onairFlag": false,
        "service": {
            "description": "Default Audio Service",
            "programCode": ""
        },
        "shortHostName": "rd4-server"
    }
}

"
```

**Comment by RudiOnTheAir** [comment]
Btw. The Filewriter has some hours ago stoppt the updating, but showed green though...

**Comment by ctecamp** [comment]
URLWRITE SCRIPT ERROR

Traceback (most recent call last):

File "/usr/lib/rivendell/pypad/pypad_commotion.py", line 63, in <module>

rcvr.start(sys.argv[1],int(sys.argv[2]))

File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 961, in
start

jdata=json.loads(msg)

File "/usr/lib/python3.10/json/__init__.py", line 346, in loads

return _default_decoder.decode(s)

File "/usr/lib/python3.10/json/decoder.py", line 340, in decode

raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 81 column 2 (char 2271)

Error in sys.excepthook:

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in
apport_excepthook

with os.fdopen(os.open(pr_filename,

FileNotFoundError: [Errno 2] No such file or directory:
'/var/crash/_usr_lib_rivendell_pypad_pypad_commotion.py.151.crash'


Original exception was:

Traceback (most recent call last):

File "/usr/lib/rivendell/pypad/pypad_commotion.py", line 63, in <module>

rcvr.start(sys.argv[1],int(sys.argv[2]))

File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 961, in
start

jdata=json.loads(msg)

File "/usr/lib/python3.10/json/__init__.py", line 346, in loads

return _default_decoder.decode(s)

File "/usr/lib/python3.10/json/decoder.py", line 340, in decode

raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 81 column 2 (char 2271)


FILEWRITE ERROR


Traceback (most recent call last):

File "/usr/lib/rivendell/pypad/pypad_filewrite.py", line 59, in <module>

rcvr.start(sys.argv[1],int(sys.argv[2]))

File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 963, in
start

jdata=json.loads(msg)

File "/usr/lib/python3.10/json/__init__.py", line 346, in loads

return _default_decoder.decode(s)

File "/usr/lib/python3.10/json/decoder.py", line 340, in decode

raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 81 column 2 (char 2289)

Error in sys.excepthook:

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in
apport_excepthook

with os.fdopen(os.open(pr_filename,

FileNotFoundError: [Errno 2] No such file or directory:
'/var/crash/_usr_lib_rivendell_pypad_pypad_filewrite.py.1000.crash'


Original exception was:

Traceback (most recent call last):

File "/usr/lib/rivendell/pypad/pypad_filewrite.py", line 59, in <module>

rcvr.start(sys.argv[1],int(sys.argv[2]))

File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 963, in
start

jdata=json.loads(msg)

File "/usr/lib/python3.10/json/__init__.py", line 346, in loads

return _default_decoder.decode(s)

File "/usr/lib/python3.10/json/decoder.py", line 340, in decode

raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 81 column 2 (char 2289)

**Comment by ctecamp** [comment]
Caveat to my previous email.
Another machine running the same scripts has had no errors and is
running fine.
The difference is,  the error free machine has no macros in the logs it is
running.

The machine that is failing has macros in AUX log 2 which seem to be
responsible for crashing all the pypad scripts regardless of which log
they are assigned to.

Really curious, and it looks like the macros are causing some extra data
that is showing up in the trace log error statement.


Tim Camp
WZEW-FM

**Comment by ElvishArtisan** [comment]
@RudiOnTheAir and @ctecamp: thank you. Very helpful information.

I hope to have another interrim build for you to test shortly...

**Comment by ElvishArtisan** [comment]
Fixed in f8dfc52. I've also cut an interrim release and built a set of DEB packages, available at http://static.paravelsystems.com/rivendell/4.2.1int1-1/. Please test!

**Comment by ctecamp** [comment]
Will do.

**Comment by ctecamp** [comment]
👍👍👍

**Comment by RudiOnTheAir** [comment]
Great, testing the next hours.. Will report

Up and running for test

**Comment by RudiOnTheAir** [comment]
OK, seems to work. No problems seen with your latest test package.. Great job.

I'm asuming you'll build a new version, so i can go back to my production os and run an update the next days?

**Comment by ElvishArtisan** [comment]
Yes. Expect that in the next couple days. Thank you all for your assistance in running this issue down!
