### ISSUE TITLE
RD v4.2.0 pypad_icecast2.py crashes

### ISSUE THREAD

**Issue by starrbuck68** [ElvishArtisan/rivendell#956]
Running Rivendell version 4.2.0 on Ubuntu 22.04 LTS and getting pypad_icecast2.py crashes occasionally. I can't see anything wrong with the song data.  Crash file attached below.

[apr23-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt](https://github.com/ElvishArtisan/rivendell/files/15081218/apr23-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt)

**Comment by ElvishArtisan** [comment]
Chances are excellent that this is fixed in ed481ec. Please test!

**Comment by starrbuck68** [comment]
> Chances are excellent that this is fixed in [ed481ec](https://github.com/ElvishArtisan/rivendell/commit/ed481ec3f1fa252c9a72dfda631e7bfddde8cfad). Please test!

Great news! I am using the apt package version so I think I would have to test in the next release.

**Comment by starrbuck68** [comment]
Installed 4.2.1 today so I will let you know if this happens again. Thank you so much.

**Comment by starrbuck68** [comment]
Crashed again similarly:

[apr24-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt](https://github.com/ElvishArtisan/rivendell/files/15103686/apr24-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt)

**Comment by RudiOnTheAir** [comment]
At my first test with the filewriter it crashed also. Said it has no rights to access to the 777 file... Then i changed the name to force a restart and voila. It seems to work.. The file has to be owned by pypad??

`rd@rd4-server:~$ ls -la /tmp/filewrite.txt
-rwxrwxrwx 1 rd rd 0 Apr 25 09:02 /tmp/filewrite.txt
`

`
rd@rd4-server:~$ ls -la /tmp/filewriter.txt
-rw-r--r-- 1 pypad pypad 38 Apr 25 09:09 /tmp/filewriter.txt
`

**Comment by ElvishArtisan** [comment]
On Apr 25, 2024, at 3:17 AM, RudiOnTheAir ***@***.***> wrote:
> At my first test with the filewriter it crashed also. Said it has no rights to access to the 777 file... Then i changed the name to force a restart and voila. It seems to work.. The file has to owned by pypad??
> 
Scripts are executed by the user:group specified in the ‘PypadOwner=‘ and ‘PypadGroup=‘ directives in the ‘[Identity]’ section of rd.conf(5). On a stock Rivendell Installer setup, those are indeed ‘pypad’:’pypad’.

Cheers!


|---------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |             Chief Developer             |
|                           |             Paravel Systems             |
|---------------------------------------------------------------------|
|         A room without books is like a body without a soul.         |
|                                                                     |
|                                                         -- Cicero   |
|---------------------------------------------------------------------|

**Comment by starrbuck68** [comment]
Still failing similarly:

[apr26-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt](https://github.com/ElvishArtisan/rivendell/files/15137124/apr26-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt)

[apr27-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt](https://github.com/ElvishArtisan/rivendell/files/15137125/apr27-_usr_lib_rivendell_pypad_pypad_icecast2.py.151.crash.txt)

**Comment by RudiOnTheAir** [comment]
OK, here we go...
```
pypad_filewrite.py[3186]: error parsing JSON: "{
    "padUpdate": {
        "dateTime": "2024-04-27T05:35:59+-2:00",
        "hostName": "rd4-server",
        "log": {
            "name": "Prod-0427"
        },
        "machine": 1,
        "mode": "Automatic",
        "next": {
            "agency": "",
            "album": "",
            "artist": "R. Kelly",
            "cartNumber": 901293,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-90SLOW",
            "isci": "",
            "isrc": "",
            "label": "",
            "length": 320222,
            "lineId": 144,
            "lineNumber": 145,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": null,
            "title": "I Believe I Can Fly",
            "userDefined": "",
            "year": null
        },
        "now": null,
        "onairFlag": false,
        "service": {
            "description": "Default Audio Service",
            "programCode": ""
        },
        "shortHostName": "rd4-server"
    }
}{
    "padUpdate": {
        "dateTime": "2024-04-27T05:35:59+-2:00",
        "hostName": "rd4-server",
        "log": {
            "name": "Prod-0427"
        },
        "machine": 1,
        "mode": "Automatic",
        "next": {
            "agency": "",
            "album": "1984",
            "artist": "Nik Kershaw",
            "cartNumber": 900182,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-80-MID",
            "isci": "",
            "isrc": "",
            "label": "NR",
            "length": 269500,
            "lineId": 145,
            "lineNumber": 146,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-27T05:41:19+-2:00",
            "title": "Wouldn`t It Be Good",
            "userDefined": "",
            "year": null
        },
        "now": {
            "agency": "",
            "album": "",
            "artist": "R. Kelly",
            "cartNumber": 901293,
            "cartType": "Audio",
            "client": "",
            "composer": "",
            "conductor": "",
            "cutNumber": 1,
            "description": "Cut 001",
            "eventType": "Audio",
            "externalAnncType": "",
            "externalData": "",
            "externalEventId": "",
            "groupName": "ROT-90SLOW",
            "isci": "",
            "isrc": "",
            "label": "",
            "length": 320222,
            "lineId": 144,
            "lineNumber": 145,
            "outcue": "",
            "publisher": "",
            "recordingMbId": "",
            "releaseMbId": "",
            "songId": "",
            "startDateTime": "2024-04-27T05:35:59+-2:00",
            "title": "I Believe I Can Fly",
            "userDefined": "",
            "year": null
        },
        "onairFlag": false,
        "service": {
            "description": "Default Audio Service",
            "programCode": ""
        },
        "shortHostName": "rd4-server"
    }
}

"
```

**Comment by ElvishArtisan** [comment]
Combining this with #955.
