### ISSUE TITLE
4.2.2: Bug? RML DB does nothing

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#959]
Executing RML `DB /home/rd/database.sql!` appears to do nothing. I've checked the changelog and it doesn't look like this RML has been removed, but can you verify?

**Comment by ElvishArtisan** [comment]
Removed, as of v3.x. You can find the ChangeLog entry on 2018-08-13.

**Comment by vizubeat** [comment]
Apologies, I need new glasses. Thanks for the reply!
