### ISSUE TITLE
4.2.2 Permissions: User can edit cut markers with no production rights

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#961]
I'm logged in as a user that has no Production Rights selected in RDAdmin, but this user can still add/modify/remove markers on cuts. It cannot delete cuts, but modifying markers could be considered just as destructive. Could the ability to edit markers be removed when 'modify carts' is not selected, and/or a new toggle added to make this optional?

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 1519123. Please test!

**Comment by vizubeat** [comment]
Thanks Fred - again I need to build another test setup as the other one is being used for testing, but this looks great. Thanks for everything :-)

**Comment by ElvishArtisan** [comment]
Remember: hypervisors are your friend! :)

**Comment by vizubeat** [comment]
I cannot compile from source. Just know that I'm trying to help in testing :-) 

<img width="649" alt="Screenshot 2024-05-12 at 18 25 33" src="https://github.com/ElvishArtisan/rivendell/assets/93675293/cf0a72ae-3ac4-4eb6-aa2d-714938a0c257">

...that must be a me thing, but I've read and understand the changes in 1519123 and it looks great - thank you!

**Comment by dklann** [comment]
Confirmed working as expected (commit 8b0dbf57) with a Rivendell user having no "Production" permissions -- no ability to set markers in cuts.
