### ISSUE TITLE
4.2.2: Bug? Sound panel buttons do not turn yellow when adding a cart with certain permissions

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#964]
When logged in as a user that has the `Configure system panels` permission, and when adding carts from the cart picker, the sound panel buttons change yellow to indicate where a cart might be placed - both system panel buttons and user panel buttons change yellow.

However, when logged in as a user that does not have the `Configure system panels` permission, the user sound panel buttons do not change yellow after selecting a cart. That user can still actually add the chosen cart to a user panel (and correctly cannot add a cart to a system panel), but having the buttons **_not_** turn yellow is confusing behaviour. 

Please could user panel buttons turn yellow when the `Configure system panels` option is not selected? Many thanks.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 1908a55. Please test!

**Comment by vizubeat** [comment]
Thank you - I need to spin up a 'test test' rig, as I'm doing a bunch of testing with the 'test' rig! Will do though!

**Comment by vizubeat** [comment]
I cannot compile from source. Just know that I'm trying to help in testing :-) 

<img width="649" alt="Screenshot 2024-05-12 at 18 25 33" src="https://github.com/ElvishArtisan/rivendell/assets/93675293/cf0a72ae-3ac4-4eb6-aa2d-714938a0c257">

...that must be a me thing, but I've read and understand the changes in 1908a55 and it looks great - thank you!

**Comment by ElvishArtisan** [comment]
Try adding:
``` export DOCBOOK_STYLESHEETS=/usr/share/xml/docbook/stylesheet/docbook-xsl-ns```
to '~/.bashrc', then open a new terminal and do a fresh build from there.

**Comment by vizubeat** [comment]
Hi @ElvishArtisan thanks for the tip. I did that and found the exact same results even though `echo $DOCBOOK_STYLESHEETS` returns the correct string/path. Any suggestions? @dklann was able to verify the other changes, maybe he could verify that this issue #964 has been resolved? I'd still love to be able to compile for myself, I did once before 🤷

![Screenshot_1](https://github.com/ElvishArtisan/rivendell/assets/93675293/2c6cbafc-7677-4c8a-91dd-cecdd37996f4)

**Comment by dklann** [comment]
Confirmed working here as of commit 8b0dbf5.

When logged in as a Rivendell user with permission "Configure System Panels" **un**selected, and using the RDAirPlay "ADD" button to add a cart to a System Panel, the panel buttons do not turn yellow and RDAirPlay will not let me choose them as a "destination" for the selected cart.

When switching to a User Panel, the panel buttons turn yellow and I can place the chosen cart in any of those button positions. And, _bonus_, I can then play the cart if it is an audio cart! :)

**Comment by vizubeat** [comment]
Thanks @dklann much appreciated :-)

Now to work out why I can't compile from source myself! :-(

**Comment by xiaoying-kylin** [comment]
Hello, I’m encountering the same issue. Could you please share how you resolved it?
