### ISSUE TITLE
4.2.2 Bug? Waveform does not display on longer cuts when zoomed in

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#966]
I am aware of #950 but this seems slightly different.

When viewing the markers of some longer cuts - for example this hour-long pre-record, the waveform is chopped off towards the end. 

This is the view at the end of the file at full zoom in:

![zoom_full_in](https://github.com/ElvishArtisan/rivendell/assets/93675293/d66fe149-c815-4f3f-af65-e9465f3060b0)

And this is the view at 2 levels down/out from full in:

![soom_2_out_from_full](https://github.com/ElvishArtisan/rivendell/assets/93675293/e69536a1-0b22-45da-8ade-8ccdccd92c5e)

The audio is definitely there though, here's the cursor and meters playing past the end of the visible waveform:

![zoom_playing](https://github.com/ElvishArtisan/rivendell/assets/93675293/946ee88e-b5fe-4b4a-ba3e-8b3028a11028)

This makes it tricky to set markers accurately as you can't see the waveform. Can anything be done?

**Comment by ElvishArtisan** [comment]
Known problem. It is the same as #950.
