### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by xotakfr** [ElvishArtisan/rivendell#967]
Hey everyone, currently attempting an installation of Rivendell server but the installation script doesn't seem to find some packages and is having some issues creating the rd user.I have attached the install log.
[log.txt](https://github.com/ElvishArtisan/rivendell/files/15362770/log.txt)

Edit : Happens on Noble and Jammy

**Comment by ElvishArtisan** [comment]
> 2024-05-18 12:26:26 (16.7 MB/s) - ‘/etc/apt/sources.list.d/Paravel-Ubuntu-24.04-Repo.list’ saved [66/66]
>
> Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
> Hit:2 https://software.paravelsystems.com/ubuntu/dists/noble/main  InRelease
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
>The following NEW packages will be installed:
>  ubuntu-rivendell-installer
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 142 kB of archives.
> After this operation, 178 kB of additional disk space will be used.
> Get:1 https://software.paravelsystems.com/ubuntu/dists/noble/main  ubuntu-rivendell-installer 0.1.2noble-1 [142 kB]
> Fetched 142 kB in 1s (155 kB/s)
> Selecting previously unselected package ubuntu-rivendell-installer.
> (Reading database ... 13176 files and directories currently installed.)
> Preparing to unpack .../ubuntu-rivendell-installer_0.1.2noble-1_all.deb ...
> Unpacking ubuntu-rivendell-installer (0.1.2noble-1) ...
> Setting up ubuntu-rivendell-installer (0.1.2noble-1) ...
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Package traceroute is not available, but is referred to by another package.

Looks like Ubuntu's package repo was having some sort of problem -- perhaps offline or undergoing some sort of maintenance. Judging from the timestamps, I'd say you're somewhere in Europe? I'd say wait twenty-four hours, then give this another try.

**Comment by xotakfr** [comment]
Yeah Europe it is. I'll try again tomorrow. I'm also trying to install a Ubuntu VM to see it it'll fix the problem since I was trying to run the server off a systemd container

Edit : At least I don't thing they're down since I used deboostrap successfully few minutes prior running install script

**Comment by xotakfr** [comment]
Okay, after a bit of digging around, I found out that the universe repository isn't enabled by default in environements created by debootstrap. Since I now know this, I will attempt a reinstallation.

**Comment by ElvishArtisan** [comment]
Interesting approach. If you do get this working, please consider sharing some of your notes here (or even better, add a page for it on the the Rivendell Wiki (https://wiki.rivendellaudio.org).
