### ISSUE TITLE
Ubuntu 24.04 - Filewrite.py - AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#975]
Hi

I'm beginning to make the change to the next platform an like to run (x)ubuntu 24.04. All is workung so far, but the filewriter plugin not.
I'm getting the same error when using the icecast2.py.

What i am missing...? Tnx...

Btw, the database is a restored one from the running ubuntu22.04. The filewrite plugin is added new. (Deleted the existing)

`Traceback (most recent call last):
  File "/usr/lib/rivendell/pypad/pypad_filewrite.py", line 54, in <module>
    rcvr.setConfigFile(sys.argv[3])
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 875, in setConfigFile
    db=self.__openDb()
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 826, in __openDb
    creds=self.__getDbCredentials()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rivendellaudio/pypad.py", line 821, in __getDbCredentials
    config.readfp(open('/etc/rd.conf'))
    ^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
`

**Comment by RudiOnTheAir** [comment]
Could be the reason for this the newer python3 version 3.12, running on ubuntu 24.04.??

**Comment by ElvishArtisan** [comment]
Tracking this issue at #979.

**Comment by ElvishArtisan** [comment]
Fixed in #979.
