### ISSUE TITLE
PyPAD Filewrite Fails on Ubuntu 24.04

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#976]
@glenndrives 
Thanks. 
That works now. And i think that in the next release it should be fixed.. But there is no problem to copy back the file then..

_Originally posted by @RudiOnTheAir in https://github.com/ElvishArtisan/rivendell/issues/823#issuecomment-2264997906_

**Comment by dklann** [comment]
See [this] (https://github.com/ElvishArtisan/rivendell/issues/823#issuecomment-2263722157) for the proposed fix.

**Comment by dklann** [comment]
Also referenced in https://github.com/ElvishArtisan/rivendell/issues/975

**Comment by ElvishArtisan** [comment]
It's a more fundamental issue than just PyPAD Filewrite. See #979.

**Comment by ElvishArtisan** [comment]
Fixed in #979.
