### ISSUE TITLE
Cannot Successfully Compile V4.3.0int6

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#989]
When compiling V4.3.0int6 the following error is encountered:

CXX      hpiplayout_test.o
In file included from ../rdhpi/rdhpiplaystream.h:35,
                 from hpiplayout_test.h:29,
                 from hpiplayout_test.cpp:26:
../rdhpi/rdhpisoundcard.h:34:10: fatal error: asihpi/hpi.h: No such file or directory
   34 | #include <asihpi/hpi.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:992: hpiplayout_test.o] Error 1
make[1]: Leaving directory '/home/rd/dev/rivendell-4.3.0int6/tests'
make: *** [Makefile:553: all-recursive] Error 1

The indicated file is indeed missing.

**Comment by ElvishArtisan** [comment]
On Oct 25, 2024, at 12:12 PM, Gary Horn ***@***.***> wrote:
> When compiling V4.3.0int6 the following error is encountered:
> 
> CXX hpiplayout_test.o
> In file included from ../rdhpi/rdhpiplaystream.h:35,
> from hpiplayout_test.h:29,
> from hpiplayout_test.cpp:26:
> ../rdhpi/rdhpisoundcard.h:34:10: fatal error: asihpi/hpi.h: No such file or directory
> 34 | #include <asihpi/hpi.h>
> | ^~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:992: hpiplayout_test.o] Error 1
> make[1]: Leaving directory '/home/rd/dev/rivendell-4.3.0int6/tests'
> make: *** [Makefile:553: all-recursive] Error 1
> 
> The indicated file is indeed missing.
> 

What version of the AudioScience driver are you using? You can get that on Ubuntu by doing:

	dpkg --list | grep hpklinux-dev

Or on a RedHat set up with:

	rpm -q hpklinux-devel

Cheers!


|---------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |             Chief Developer             |
|                           |             Paravel Systems             |
|---------------------------------------------------------------------|
|         A room without books is like a body without a soul.         |
|                                                                     |
|                                                         -- Cicero   |
|---------------------------------------------------------------------|

**Comment by WMTH** [comment]
Until now, I have not installed the AudioScience driver as we don’t use those cards and have been successfully compiling until the introduction of 4.3.0int6.  As I review the Changelog, I do see the addition of ‘hpiplayout_test’ that is likely to be the cause.  I will install a hpklinux driver and try to compile again.

**Comment by WMTH** [comment]
After the installation of :

hpiinfo_2.0.1-1_amd64.deb 
hpklinux-dev_4.20.43-1_amd64.deb
hpklinux_4.20.43-1_amd64.deb

The result:

make[1]: Entering directory '/home/rd/dev/rivendell-4.3.0int6/tests'
  CXXLD    hpiplayout_test
/usr/bin/ld: hpiplayout_test.o: in function `MainObject::MainObject(QObject*)':
/home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:72:(.text+0x490): undefined reference to `RDHPISoundCard::RDHPISoundCard(RDConfig*, QObject*)'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:74:(.text+0x4c9): undefined reference to `RDHPIPlayStream::RDHPIPlayStream(RDHPISoundCard*, QObject*)'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:83:(.text+0x63b): undefined reference to `RDHPIPlayStream::setCard(int)'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:84:(.text+0x66b): undefined reference to `RDHPIPlayStream::openWave(QString)'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:89:(.text+0x6a1): undefined reference to `RDHPIPlayStream::getStream() const'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:89:(.text+0x6ac): undefined reference to `RDHPIPlayStream::getCard() const'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:91:(.text+0x6d0): undefined reference to `RDHPIPlayStream::getStream() const'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:91:(.text+0x6e4): undefined reference to `RDHPISoundCard::setOutputVolume(int, int, int, int)'
/usr/bin/ld: /home/rd/dev/rivendell-4.3.0int6/tests/hpiplayout_test.cpp:92:(.text+0x6ed): undefined reference to `RDHPIPlayStream::play()'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:839: hpiplayout_test] Error 1
make[1]: Leaving directory '/home/rd/dev/rivendell-4.3.0int6/tests'
make: *** [Makefile:553: all-recursive] Error 1

**Comment by WMTH** [comment]
Last compile issue solved by excluding '--disable-hpi' from the configuration options.
