### ISSUE TITLE
Broken Links in the Online Ops Guide

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#991]
Not sure if this belongs here, but at least this is a way to track it. Please redirect as appropriate!

The online copy of the Rivendell Operations and Administration Guide currently has some broken links in (at least) the Rivendell Macros appendix. See, for instance, https://opsguide.rivendellaudio.org/html/sect.rml.jack_port_names.html and https://opsguide.rivendellaudio.org/html/sect.rml.log_machines.html

Steps to reproduce:

- visit [this page](https://opsguide.rivendellaudio.org/html/chapter.rml.html)
- click on [14.7 JACK Port Names](https://opsguide.rivendellaudio.org/html/sect.rml.jack_port_names.html)
- see the "404" message

Thanks!

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 266ea14. Please test.

This should be visible at https://opsguide.rivendellaudio.org as well.

**Comment by dklann** [comment]
Confirmed fixed. I forgot that **_all_** the documentation (including for the online manual) is in the the repo! Thanks Fred!
